### ISSUE TITLE
Announcement of correctionform.txt

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#1]
The https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/correctionform.txt file in this repository gives an accurate, public view of the correction submissions, and their status.  The plan is to keep this file in sync with the Sanskrit Lexicon Correction Form (Responses), which is where user Correction Form submissions go.

As time goes by, the plan is to have similar information about the corrections that get applied to the dictionaries by various processes outside the correction form venu.

**Comment by gasyoun** [comment]
A volunteers wanted link from different pages of Cologne here would make the start. People would start asking. Making another project for to-be one person does not looks a good way to spend my holiday time. :mahjong:

**Comment by drdhaval2785** [comment]
Now we have sanskrit-lexicon.github.io up and running.
@gasyoun will have to design web page. Best HTML and CSS guy around.
By the way - announcement of correctionforms has lived its life.
Closing it.
