### ISSUE TITLE
Hiatus

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#10]
While checking errors in PWK, I came across titO.
It would be a great thing if the list of hiatus provided by Marcis can be checked in all dictionaries to see whether the hiatus is lost by transliteration script.
If it is lost - restore it

**Comment by gasyoun** [comment]
> no way for the usual HK to represent an a-u or a-i hiatus.

I wonder if it was ever documented by Peter Scharf.

**Comment by Andhrabharati** [comment]
Wiki says thus-

### Harvard-Kyoto > Conversion to Devanagari
Sanskrit text encoded in the Harvard-Kyoto convention can be unambiguously converted to Devanāgarī, with two exceptions: Harvard-Kyoto does not distinguish अइ (a followed by i, in separate syllables, i.e. in hiatus) from ऐ (the diphthong ai) or अउ (a followed by u) from औ (the diphthong au). However such a vowel hiatus extremely rarely would occur inside words. Such a hiatus most often occurs in sandhi between two words (e.g. a sandhi of a word ending in 'aH' and one beginning with 'i' or 'u'). _Since in such a situation a text transliterated in Harvard-Kyoto would introduce a space between the 'a' and 'i' (or 'a' and 'u') no ambiguity would result._ 
`-------------------`
Probably an underscore could also be used; or now that we have unicode, this is the simplest solution-

> If two English characters are making one Devanagari vowel (ex: ai, ou), then, ZWJ or ZWNJ character can be used to separate them into different vowels.
> 
> Example:
> iMDiyainfo = इंडियैन्फ़ो
> iMDiya^info = इंडिय‍इन्फ़ो
> iMDiya^^info = इंडिय‌इन्फ़ो

**Comment by Andhrabharati** [comment]
Anyways, no point in reviving these almost "dead" trans-coding schemes; unicode is becoming **the defacto** quite faster now.

**Comment by Andhrabharati** [comment]
```
    no way for the usual HK to represent an a-u or a-i hiatus.

I wonder if it was ever documented by Peter Scharf.
```

Do not know if Peter Scharf has mentioned about this anywhere (wrt HK notation); but Thomas Malten sure has done so, way back in 1997!!

Look at this-

![image](https://user-images.githubusercontent.com/75209130/110946364-c7fac200-8364-11eb-9ff1-057ef71a1bb0.png)


Incidentally, @funderburkjim also cited to have used thus (2014) at the top of this particular page-

https://github.com/sanskrit-lexicon/CORRECTIONS/issues/10#issuecomment-61421396
