### ISSUE TITLE
Documenting methods for processing faultfinder errors

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#100]
Recently, the method to process the errors (presently faultfinder method, later on extensible to any method) has been changed and more or less fixed now. It uses the suspect word list found by faultfinder method and gives suggestions based on fuzzy logic.
It is time to document it for future reference and use.

1. METHOD TO DEVELOP fuzzyalpha.txt and fuzzyalpha.html
@funderburkjim will have to write this.

2. Download [fuzzyalpha.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/VEI/vei-fuzzyalpha.txt) and [fuzzyalpha.html](http://funderburkjim.github.io/fuzzywork/vei-fuzzyalpha.html). 
3. Make a copy of fuzzyalpha.txt and rename it to fuzzybeta.txt (where we will make changes).
4. Open fuzzybeta.txt and fuzzyalpha.html side by side.
5. Ctrl+Click on the image links of fuzzyalpha.html to open the images in separate tab.
6. Verify whether the headword is correct or not.
7. If the headword is correct, write NO CHANGE in fuzzybeta.txt e.g. `008 aSvatTva ->   NO CHANGE`
8. If the headword is incorrect, correct it. The format of correction is `wrong word -> correct word : notes` e.g. `017 kanzya -> kOzya : The print u is inverted to n.`
9. Once the errors are corrected, save fuzzybeta.txt.
10. Upload [fuzzybeta.txt](https://github.com/drdhaval2785/SanskritSpellCheck/blob/master/fuzzyalpha/vei-fuzzybeta.txt) to github and post its link to [github issue](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/98#issuecomment-94237327) where we are tracking errors of particular dictionary.
11. Make necessary change in the name of dictionary in the code e.g. `$dict = "vei";` and run [github_issues_post.php](https://github.com/drdhaval2785/SanskritSpellCheck/blob/master/fuzzyalpha/github_issues_post.php).
12. This separates fuzzybeta.txt in two parts depicting [change.txt](https://github.com/drdhaval2785/SanskritSpellCheck/blob/master/fuzzyalpha/vei_change.txt) and [nochange.txt](https://github.com/drdhaval2785/SanskritSpellCheck/blob/master/fuzzyalpha/vei_nochange.txt).
13. Copy paste the output of change file into one issue of github titled `corrections` and no change file to `NO CHANGE`. e.g. https://github.com/sanskrit-lexicon/CORRECTIONS/issues/98#issuecomment-94237727 and https://github.com/sanskrit-lexicon/CORRECTIONS/issues/98#issuecomment-94237762 respectively.

14. Integrating the fuzzybeta.txt correction file into database of Cologne.
@funderburkjim will have to write this section

**Comment by gasyoun** [comment]
Was not aware of https://github.com/drdhaval2785/SanskritSpellCheck/blob/master/fuzzyalpha/github_issues_post.php

**Comment by funderburkjim** [comment]
In response to the request, [here](https://github.com/funderburkjim/fuzzyalpha-example) is a self-contained example of constructing the pui-fuzzyalpha.txt and .html.

**Comment by drdhaval2785** [comment]
Now point 14 only pending.
Good to see the magic behind the files come online on repository

**Comment by gasyoun** [comment]
@funderburkjim impressive. If I'l ever meet Python, I'll test all of it.

**Comment by drdhaval2785** [comment]
@gasyoun I met the python and it works as Jim suggested.
And as Jim said, the last step is very slow. 
Good that Jim documented it, otherwise I would have aborted the program.

@funderburkjim 
For the next remaining dictionary, I will try to construct these files myself, so that I come to know whether I understood the instructions properly or not.

**Comment by funderburkjim** [comment]
@drdhaval2785  Re : for next dictionary ...  

Good idea.  HOWEVER:  The program fuzzyalpha.py requires some slight adjustments for each dictionary.
 I've put a revised version and an adjusted readme.txt file into an 'extension-notes' folder of the 
fuzzyalpha-example directory.  You may want to use this when you try another dictionary.

I've already constructed the fuzzyalpha materials for the remaining specialized dictionaries locally, 
and am waiting for appropriate time to upload to these Corrections issues for you and/or @Shalu411 or me to work on.

**Comment by gasyoun** [comment]
@drdhaval2785 do you understand which are left, which are the non-specialized ones?

**Comment by drdhaval2785** [comment]
I guess this issue has lived its life. Let's put it to sleep.
