### ISSUE TITLE
PGN corrections drawn from faultfinder suggestions

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#103]
6 cases were found by faultfinder for the headwords of PGN (Personal and Geographical Names in the Gupta Inscriptions)

These comprise headwords of  PGN that

* occur only in PGN
* have spelling patterns that 
  * don't occur among the MW headwords (as detected from faultfinder),
  * are not of the 'rxx' variety.

I've put pgn-fuzzyalpha.txt [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/PGN/pgn-fuzzyalpha.txt)  and pgn-fuzzyalpha.html as active html page [here](http://funderburkjim.github.io/fuzzywork/pgn-fuzzyalpha.html).

The instructions are as per [issue 100](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/100).

@Shalu411  This would be a good one for you to do.  It is a short list and won't take much time.  And, it will give you the opportunity to get the technical details worked out.

Basically, you are going to 'complete' the pgn-fuzzyalpha.txt file,  using the links in pgn-fuzzyalpha.html (mostly the page links) to help you see what's going on.  To 'complete' the .txt file,  first download it (right click on link above to pgn-fuzzalpha.txt, and 'save as' to a local file).  Then change this local copy and, when you're done, upload somewhere in the cloud (Dropbox is fine) and mention the link to upload location in a comment in this issue.  I'll grab your corrected file, and do the installation on the Cologne server.

As to the format expected in your corrected pgn-fuzzyalpha.txt,  see Dhaval's instructions;  you might also 
want to look at Dhaval's completed file [vei-fuzzyalpha-completed.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/VEI/vei-fuzzyalpha-completed.txt).

Lots of little details, but not too hard once you've done it once or twice. :sunglasses:

**Comment by gasyoun** [comment]
@funderburkjim it's time I understand as well. Now I do not. :tangerine: 

Why some are in () only?
`001 samudragupwa -> (samudragupta)`

Why some () are empty?
`003 SukkraSarmman -> Suklakarmman ()`

Should we have such a big fuzzy distance or just one letter a time would do? Possible correction are taken from different dictionaries or the same?
`004 KAdpAra -> (KAYjAra,KAdira,KApara,KArkAra)`

**Comment by funderburkjim** [comment]
@gasyoun 
`Why some are in () only?`  All suggestions, whether in parens or no,  are words in some dictionary that are 
   within a certain edit distance of the word in question (samudragupwa in case 001 of pgn-fuzzyalpha.txt).
   samudragupta is a word in some dictionary which has a close spelling to samudragupwa,  so 
   sumdragupta qualifies as a suggestion.   NOW  imagine we have a list of all suggestions *based on edit
   distance* criterion.   This list is further analyzed into two sublists, based on the preceding and succeeding
   headword  (in case 001 of PGN,  the preceding headword is candragupta, and the following headword is
   also candragupta -  unusual they are the same.)   If a given suggestion is alphabetically between the
   preceeding and following headword, then that suggestion goes in non-parenthesized list;  if the suggestion
   fails to be alphabetically between, then that suggestion goes in the parenthesized list.  

`Why some () are empty?`    There are no suggestions that are NOT in alphabetical order.  E.g., in case 003
   there is just one suggestion Suklakarmman  and it is alphabetically between ruzwaSarmman and 
   suSarmman,  so Suklakarmman   was put outside (), and there was no other suggestion that could go in
   ()

`Should we have such a big fuzzy distance?`   There is no easy answer to this question.  The edit-distance
  maximum edit distance parameter used in the PGN fuzzyalpha.py program was 6.   This generates some
  false positives (bad suggestions).    I don't know if there is a 'best' edit distance threshold.

**Comment by funderburkjim** [comment]
There is two other details of the suggestion generation that is incorporated in fuzzyalpha.py.  
 Suppose that the fuzzy distance parameter is set to 6.   And suppose our base word is X (like samudragupwa 
 is case 001 of PGN).  Our initial pool of candidates for suggestions, Y, is all 300,000+ words in sanhw1.txt.
 
* An accepted suggestion Y must have the same first letter as X  (e.g., Y must start with 's')
* Once we have the set S of all words Y which have the same first letter as X and whose edit distance from
   X is <=6,  then this suggestion list is further reduced to include only those Y in S which have the minimum
   edit distance from X.   To elaborate:  Suppose the edit distances from X happen to be 3 for some Y in S,
   4 for some other Y in S, and 6 for other Y in S.   Then the FINAL suggestion list will only include those 
   Y with edit distance of 3.

The first condition was chosen to provide some computational efficiency.

The second condition was chosen as a way to prune the list of suggestions (so that list would not be too long).

These choices could be debated,  but, for our purposes in generating correction suggestions they seem to 
be plausible.

**Comment by drdhaval2785** [comment]
I worked with two dictionary suggestions, and the suggestions are very
useful overall. Lets keep them as they are.
Yhe parenthesis mystery also bothered me. Thanks for clarification.

**Comment by gasyoun** [comment]
@funderburkjim 
1) `words in some dictionary` why not link to it? why not add info where it comes from? That can help in the decision making. Knowing the background helps at least me.
2) ` suggestion is alphabetically between the preceeding and following headword, then that suggestion goes in non-parenthesized list` I hope Dhaval got it because I hardly.
3) `edit-distance maximum edit distance parameter used in the PGN fuzzyalpha.py program was 6` - can we recreate the files with 5,4,3,2,1? 1 seems to give fine results, see https://github.com/sanskrit-lexicon/CORRECTIONS/issues/45#issuecomment-92873646
4) `all 300,000+ words in sanhw1.txt` -> all 430k. Feel the difference between 300 and 430k.
5) `same first letter as X` - what about the a+X, an+X (in the beginning of the word) variations, should not we include them as well? Maybe PD dirt can be cleaned because of it?

**Comment by funderburkjim** [comment]
@gasyoun Re 5). PD

I've generated pd-fuzzyalpha , 1158 cases.  Review of a random selection of these makes me think that
 THERE ARE ALMOST NO ERRORS.   Rather,  I suspect these cases are simply due to the great number
of compound words in PD that do not appear in MW.  Take `agnicEtanya` as an example.  Both `agni` and
`cEtanya` are words appearing in MW, but the compound word does not appear, and the `icE` sequence
appearing in this compound does not appear in any MW word.

I think a different approach should be used to examine this PD faultfinder list.  The reason is that 1158 cases
is, practically speaking, a large list to check manually against scans.

One different approach would be for
one of our Sanskrit experts simply to read each word in the list and judge whether the word is *obviously* a
correct Sanskrit word (I suspect this will be true in 90% of the cases), or whether the word needs further
examination.  Then, the words marked for further examination can be examined 'manually' by comparison
to the scanned images.

Another possible approach would be to write a program to identify  the words which are (like agnicEtanya)
compounds of MW headwords.  Here's how the program could work. The program could successively try
all 2-fold partitions of the word, for instance 
a+gnicEtanya, ag + nicEtanya, agn+icEtanya, agni+cEtanya, agnic+Etanya  ... agnicEtany + a
and, for a given partition, check if both components are MW headwords.  If so, the given word would be
marked as OK.   The remaining words (those not marked as OK) would need further review, either by
Sanskrit experts, or manually by comparison to scan.
Note: This mechanical partition is simple-minded, that's why it would be a good first thing to try. One weakness of the mechanical partition approach is that it does not take into account sandhi that can occur
in compounds when combining nominal stems.  For instance, the word `akzIRendu` occurs among the 
1158 PD cases.  This is likely a compound of akzIRa and indu, (both MW stems) but this fact would not
be found by the mechanical partition approach.

**Comment by gasyoun** [comment]
@funderburkjim the non-appearance of `agnicEtanya` in MW is understood. PD initial goal was to list all the possible combinations, MW wanted to keep the bricks separately so he has only `agni` and `cEtanya`. At the end of the day PD failed and the dictionary will be never finished. As a part of the initial goal in Pune I plan to print the total index of all the 430k wordforms found in Sanskrit dictionaries to see if it has any practical usage.
1k+ cases is a list too big indeed, just to test.
`One different approach` does not makes sense - it would bring as to the Bronze Age (pre-2014). It would make sense only if @drdhaval2785 would create a sister to his sandhi generator and analyze the words and mark the ones which are fishy at least from the phonetics standpoint. 
`Another possible approach` seems to be more promising. The fact is such a program is already written and used at http://sanskrit.inria.fr/MW/90.html#ciraprasuutaa In 2013 Gérard Huet wrote: `I know how to split arbitrary compounds. So the lexicalized entries do not matter that much, except for looking up their definitions, of course.`
It's too bad Huet's code is closed, he said it took them 6 months to make the `mechanical partition is simple-minded` process with Pawan Goyal a little more smarter. The sandhi part is rather stupid in Huet's splitting of samasas as well, actually. This is where @drdhaval2785 or @mbykov code could come handy.

**Comment by funderburkjim** [comment]
These few cases have been examined.

Two were changed:
------------------------------------------------------------------------
001 candragupta
001 samudragupwa ->  samudragupta : print error
001 candragupta
001 headword <a target='_PGNword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=samudragupwa'>samudragupwa</a> ---  page <a target='_PGNpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/servepdf.php?page=021'>021</a>

------------------------------------------------------------------------
005 KAdpAra
005 kowwvarza -> kowivarza: typo (kowivarza,kowIvarza)
005 kfmilA
005 headword <a target='_PGNword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=kowwvarza'>kowwvarza</a> ---  page <a target='_PGNpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/servepdf.php?page=216'>216</a>

**Comment by funderburkjim** [comment]
The other 4 were marked as no change:

------------------------------------------------------------------------
002 svayamBudeva
002 cCandaka ->  NO CHANGE:   candaka is mentioned as alter
002 DftipAla
002 headword <a target='_PGNword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=cCandaka'>cCandaka</a> ---  page <a target='_PGNpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/servepdf.php?page=056'>056</a>

------------------------------------------------------------------------
003 ruzwaSarmman
003 SukkraSarmman -> NO CHANGE  : (possibly 'kk' is print error for 'k')
003 suSarmman
003 headword <a target='_PGNword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=SukkraSarmman'>SukkraSarmman</a> ---  page <a target='_PGNpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/servepdf.php?page=077'>077</a>

------------------------------------------------------------------------
004 gayA
004 KAdpAra -> NO CHANGE  :
004 kowwvarza
004 headword <a target='_PGNword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=KAdpAra'>KAdpAra</a> ---  page <a target='_PGNpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/servepdf.php?page=215'>215</a>

------------------------------------------------------------------------
006 paYcanagarI
006 nOyoga ->  NO CHANGE: (niyoga)
006 cUqAmaRi
006 headword <a target='_PGNword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=nOyoga'>nOyoga</a> ---  page <a target='_PGNpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webtc/servepdf.php?page=235'>235</a>
