### ISSUE TITLE
Method to take backup of github issues

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#105]
@funderburkjim and @gasyoun 
We will need to take some kind of backup of all the work which have been done as issues in these github repositories.
Otherwise one fine morning we will be without any record of how and what we did.
Jim may have a look around Github API and come out with a way forward.

**Comment by gasyoun** [comment]
@drdhaval2785 the more we need it, because of as Github is at Rackspace https://github.com/blog/493-github-is-moving-to-rackspace that means
Dallas-Fort Worth (DFW)
Chicago (ORD)
Northern Virginia (IAD)
London (LON)
Sydney (SYD)
Hong Kong (HKG)
that if a giant wave will come the data centers might be in trouble (Dallas-Fort Worth - the rest are seaside and at high risk). And after there will be electricity issue in Northern Virginia and Chicago. So I suggest there should be several people who have it not only in Dropbox (hosted in Ireland), but locally on hard drive and even DVD once per 6 months. I propose we finish it by mid-November, when I'm waiting a major earthquake in California.

**Comment by funderburkjim** [comment]
I agree that it would be good to have a back up of the Github issues.  This question came up several months ago and at that time I found no good way to do it.

**Comment by gasyoun** [comment]
@funderburkjim what about https://github.com/github/backup-utils ?

**Comment by drdhaval2785** [comment]
I fiddled around with Github API.
git bash command passed was as below:
![capture](https://cloud.githubusercontent.com/assets/5755132/7511478/b2dc98b2-f4c2-11e4-9715-9a7a6e3af4fc.PNG)

This outputs all the comments to the specific issue (I have chosen the present issue only).

The output is as below:
![capture](https://cloud.githubusercontent.com/assets/5755132/7511497/d5d8ffc2-f4c2-11e4-85cf-d2faf5c94183.PNG)
![capture](https://cloud.githubusercontent.com/assets/5755132/7511509/e6c3fa58-f4c2-11e4-89ae-ecc48be28303.PNG)
![capture](https://cloud.githubusercontent.com/assets/5755132/7511516/f8790b8a-f4c2-11e4-9303-721eace936c5.PNG)

So, there is a chance that by Github API we may get what we want.

Please note that the first member of the discussion (which Github calls 'issue') is not fetched by this manner.
It is fetched by the following command.
![capture](https://cloud.githubusercontent.com/assets/5755132/7511549/37830380-f4c3-11e4-988b-34c7d5f21936.PNG)

Out of all the junk that is shown, the part we are interested is 'body'
![capture](https://cloud.githubusercontent.com/assets/5755132/7511559/519d0716-f4c3-11e4-869b-f20a3883dfa0.PNG)

**Comment by drdhaval2785** [comment]
Thanks to http://stackoverflow.com/questions/2304372/how-do-you-copy-and-paste-into-git-bash, I learnt how to copy paste from the git bash prompt.

The following is the result
```

dell user@DELL ~
$ curl https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issues/105/com
ments
[
  {
    "url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issues/com
ments/98969463",
    "html_url": "https://github.com/sanskrit-lexicon/CORRECTIONS/issues/105#issu
ecomment-98969463",
    "issue_url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issu
es/105",
    "id": 98969463,
    "user": {
      "login": "gasyoun",
      "id": 80761,
      "avatar_url": "https://avatars.githubusercontent.com/u/80761?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gasyoun",
      "html_url": "https://github.com/gasyoun",
      "followers_url": "https://api.github.com/users/gasyoun/followers",
      "following_url": "https://api.github.com/users/gasyoun/following{/other_us
er}",
      "gists_url": "https://api.github.com/users/gasyoun/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gasyoun/starred{/owner}{/repo
}",
      "subscriptions_url": "https://api.github.com/users/gasyoun/subscriptions",

      "organizations_url": "https://api.github.com/users/gasyoun/orgs",
      "repos_url": "https://api.github.com/users/gasyoun/repos",
      "events_url": "https://api.github.com/users/gasyoun/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gasyoun/received_even
ts",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-05-05T06:41:44Z",
    "updated_at": "2015-05-05T06:41:44Z",
    "body": "@drdhaval2785 the more we need it, because of as Github is at Racks
pace https://github.com/blog/493-github-is-moving-to-rackspace that means\r\nDal
las-Fort Worth (DFW)\r\nChicago (ORD)\r\nNorthern Virginia (IAD)\r\nLondon (LON)
\r\nSydney (SYD)\r\nHong Kong (HKG)\r\nthat if a giant wave will come the data c
enters might be in trouble (Dallas-Fort Worth - the rest are seaside and at high
 risk). And after there will be electricity issue in Northern Virginia and Chica
go. So I suggest there should be several people who have it not only in Dropbox
(hosted in Ireland), but locally on hard drive and even DVD once per 6 months. I
 propose we finish it by mid-November, when I'm waiting a major earthquake in Ca
lifornia."
  },
  {
    "url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issues/com
ments/99199852",
    "html_url": "https://github.com/sanskrit-lexicon/CORRECTIONS/issues/105#issu
ecomment-99199852",
    "issue_url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issu
es/105",
    "id": 99199852,
    "user": {
      "login": "funderburkjim",
      "id": 6393033,
      "avatar_url": "https://avatars.githubusercontent.com/u/6393033?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/funderburkjim",
      "html_url": "https://github.com/funderburkjim",
      "followers_url": "https://api.github.com/users/funderburkjim/followers",
      "following_url": "https://api.github.com/users/funderburkjim/following{/ot
her_user}",
      "gists_url": "https://api.github.com/users/funderburkjim/gists{/gist_id}",

      "starred_url": "https://api.github.com/users/funderburkjim/starred{/owner}
{/repo}",
      "subscriptions_url": "https://api.github.com/users/funderburkjim/subscript
ions",
      "organizations_url": "https://api.github.com/users/funderburkjim/orgs",
      "repos_url": "https://api.github.com/users/funderburkjim/repos",
      "events_url": "https://api.github.com/users/funderburkjim/events{/privacy}
",
      "received_events_url": "https://api.github.com/users/funderburkjim/receive
d_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-05-05T19:41:43Z",
    "updated_at": "2015-05-05T19:41:43Z",
    "body": "I agree that it would be good to have a back up of the Github issue
s.  This question came up several months ago and at that time I found no good wa
y to do it."
  },
  {
    "url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issues/com
ments/99606568",
    "html_url": "https://github.com/sanskrit-lexicon/CORRECTIONS/issues/105#issu
ecomment-99606568",
    "issue_url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issu
es/105",
    "id": 99606568,
    "user": {
      "login": "gasyoun",
      "id": 80761,
      "avatar_url": "https://avatars.githubusercontent.com/u/80761?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gasyoun",
      "html_url": "https://github.com/gasyoun",
      "followers_url": "https://api.github.com/users/gasyoun/followers",
      "following_url": "https://api.github.com/users/gasyoun/following{/other_us
er}",
      "gists_url": "https://api.github.com/users/gasyoun/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gasyoun/starred{/owner}{/repo
}",
      "subscriptions_url": "https://api.github.com/users/gasyoun/subscriptions",

      "organizations_url": "https://api.github.com/users/gasyoun/orgs",
      "repos_url": "https://api.github.com/users/gasyoun/repos",
      "events_url": "https://api.github.com/users/gasyoun/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gasyoun/received_even
ts",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-05-06T20:54:24Z",
    "updated_at": "2015-05-06T20:54:24Z",
    "body": "@funderburkjim what about https://github.com/github/backup-utils ?"

  }
]

dell user@DELL ~
$ curl https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issues/105
{
  "url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issues/105",

  "labels_url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issue
s/105/labels{/name}",
  "comments_url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/iss
ues/105/comments",
  "events_url": "https://api.github.com/repos/sanskrit-lexicon/CORRECTIONS/issue
s/105/events",
  "html_url": "https://github.com/sanskrit-lexicon/CORRECTIONS/issues/105",
  "id": 70883955,
  "number": 105,
  "title": "Method to take backup of github issues",
  "user": {
    "login": "drdhaval2785",
    "id": 5755132,
    "avatar_url": "https://avatars.githubusercontent.com/u/5755132?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/drdhaval2785",
    "html_url": "https://github.com/drdhaval2785",
    "followers_url": "https://api.github.com/users/drdhaval2785/followers",
    "following_url": "https://api.github.com/users/drdhaval2785/following{/other
_user}",
    "gists_url": "https://api.github.com/users/drdhaval2785/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/drdhaval2785/starred{/owner}{/r
epo}",
    "subscriptions_url": "https://api.github.com/users/drdhaval2785/subscription
s",
    "organizations_url": "https://api.github.com/users/drdhaval2785/orgs",
    "repos_url": "https://api.github.com/users/drdhaval2785/repos",
    "events_url": "https://api.github.com/users/drdhaval2785/events{/privacy}",
    "received_events_url": "https://api.github.com/users/drdhaval2785/received_e
vents",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "milestone": null,
  "comments": 3,
  "created_at": "2015-04-25T09:29:08Z",
  "updated_at": "2015-05-06T20:54:24Z",
  "closed_at": null,
  "body": "@funderburkjim and @gasyoun \r\nWe will need to take some kind of bac
kup of all the work which have been done as issues in these github repositories.
\r\nOtherwise one fine morning we will be without any record of how and what we
did.\r\nJim may have a look around Github API and come out with a way forward.",

  "closed_by": null
}

dell user@DELL ~
$

dell user@DELL ~
$
```

**Comment by gasyoun** [comment]
@drdhaval2785 and you can do it in batch for every issue?

**Comment by drdhaval2785** [comment]
Not at all. I am worst when it comes to terminals. Let Jim throw some light.

**Comment by funderburkjim** [comment]
The methods you show work most of the time. 
But, there is the annoying feature of 'pagination' which has to be dealt with.
For instance, try this url (either via curl or via a browser):
```
https://api.github.com/repos/sanskrit-lexicon/GreekInSanskrit/issues/4/comments
```
You'll see that exactly the first 30 comments are returned (there are more than 30 comments in this issue).
I'm sure there is a way (in a program) to check for this, and to retrieve all of the records, but at the
moment I'm not sure of the details.

**Comment by drdhaval2785** [comment]
@gasyoun and @funderburkjim 
Made my first shell script.
It is really easy to do this issue backup.
https://github.com/drdhaval2785/github_issue_backup is the repository.
https://github.com/drdhaval2785/github_issue_backup/blob/master/github_issue_backup.sh is the shell script doing the magic.
https://github.com/drdhaval2785/github_issue_backup/tree/master/sanskrit-lexicon/CORRECTIONS is where I have backed up issues and comments till 107 of CORRECTIONS repository as it stood on 8_5_2015

**Comment by gasyoun** [comment]
@drdhaval2785 looks good enough, let's go for the rest. .txt files are good enough if everything else will be lost.

**Comment by funderburkjim** [comment]
@drdhaval2785  How did you solve the pagination problem for issue comments when an issue has more than 30 comments ?

**Comment by drdhaval2785** [comment]
page=1&per_page=10000 in the argument
I.e. it gives page 1 and page 1 has 10000 entries (instead of usual 30)

**Comment by funderburkjim** [comment]
@drdhaval2785   Just confirmed your page=1&per_page=10000  parameters work as advertised.

Terrific -  that seems to completely bypass the pagination problem.

I've put a Python version [here](https://github.com/funderburkjim/testing/tree/master/GithubIssueBackup).
The example backs up the GreekInSanskrit issues.
The main difference is that only the 'body' elements are output.

I think your curl-based script is fine.  If, for some purpose, you wanted to have just the 'body' elements,
you could write a PHP program to read your output files, interpret the JSON, and write out just the body
elements to some file.

Are you going to commit to periodically backing up the issues for all the sanskrit-lexicon repositories?

If so, we  could all clone that repository when you do an update,  so there will be distributed copies in case
Gasyoun's GitHub disaster scenario should come to pass.

A possible enhancement would be to download the images (dictionary excerpts) that appear with many of
the comments.   I'm not sure this would be worth the trouble, but wanted to mention.

**Comment by gasyoun** [comment]
Images would not hurt, but not critical.

**Comment by drdhaval2785** [comment]
Right now i m on work to interpret json and output in HTML in just the same
environment as Github has. This includes handling github flavored markup
and getting github stylesheet.
Raw HTML version having title, author and body is ready. Garnishing it
further

**Comment by gasyoun** [comment]
Raw HTML to be seen where?

**Comment by drdhaval2785** [comment]
Raw HTML to be seen at http://drdhaval2785.github.io/github_issue_backup/sanskrit-lexicon/CORRECTIONS/html/1.html
The issues https://github.com/drdhaval2785/github_issue_backup/issues need to be tackled.
Half tackled.

The major issue is non-consistent use of Markup.
e.g. At some places we have `[]()` pattern to show links and at some places `<a href` methodology.
If I treat one, the other is deranged.
Therefore, right now links are not being displayed well.

The feel is like github issues display.
Note your issues at https://github.com/drdhaval2785/github_issue_backup/issues

**Comment by funderburkjim** [comment]
@drdhaval2785  Your html display is pretty, nice and easy to read.   Especially nice to see the
commentor and date sections.

I'm not bothered by the few places where the github markup conventions are not exactly like github does it.

If you are interested in making your conversion of github markdown to html more exact, it might be that existing programs to do this would help.  

A search on `github markup render php`  gave some leads that, on first blush anyway, look promising; notably [php-markdown](https://github.com/michelf/php-markdown)

**Comment by drdhaval2785** [comment]
I used https://github.com/erusev/parsedown for parsing GFM and https://github.com/syntaxhighlighter/syntaxhighlighter to syntax highlight.

**Comment by drdhaval2785** [comment]
The final product is https://github.com/drdhaval2785/github_issue_backup/

The backup of sanskrit-lexicon/CORRECTIONS repository of 8th May 2015 is https://www.dropbox.com/s/lny7df4xy0ox7lt/sanskrit-lexicon_8_may_2015.zip?dl=0

**Comment by gasyoun** [comment]
Backup downloaded, thanks. Let's finalize the backup solution or you'll be gone with the winds.

**Comment by drdhaval2785** [comment]
So what remains to be finalized ?
Tool is ready.
If we want to store it somewhere, @funderburkjim is the most knowledgeable about such stuff.

The next best thing which @funderburkjim can do is - 'Prepare a cron script that backs up the issue at every week'. I am not at all conversant with crons.

The took is a commandline one, so cron would not be difficult for Jim I guess.

**Comment by drdhaval2785** [comment]
For ease of work,
I have created https://github.com/drdhaval2785/github_issue_backup/blob/master/cronjob.sh
Clicking on this script would take backup of upto 150 issues of sanskrit-lexicon/CORRECTIONS repo (right now there are 116 odd).

Cronning remains to be done by @funderburkjim

**Comment by gasyoun** [comment]
Cron is easy, just a matter of one line of code.

**Comment by funderburkjim** [comment]
I also don't know about cron jobs.   
*  I don't know how to start one  (maybe @gasyoun can show syntax?)
* I'm not sure whether I have the ability at Cologne to do cron jobs.

In any case,  I want to get Dhaval's code working locally, and then to add all the repositories.
Even if cron is not practical,  it should be possible to just run an extended 'cronjob.sh' script locally, on 
system schedule.
(or, maybe a cron job can be set up under Windows?  Marcis, do you know how?)

The backed up comments (output of cronjob.sh) can then be uploaded to 
* another non-Github repository  (maybe BitBucket)
* OR, in the S3 sanskrit-lexicon storage area that has been set up.

Comments?

**Comment by gasyoun** [comment]
Crons run only under Unix, never Windows. BitBucket and S3 are all US-based. It should be spread around the globe. When the giant wave will come, half of US will be underwater, so S3 will have downtime bigger than uptime, so it will not help.

**Comment by funderburkjim** [comment]
Have done a backup of sanskrit-lexicon, using form
```
sh github_issue_backup.sh  sanskrit-lexicon -a -a testejf1 -l
```

'testejf1' was just the name of output folder.  In it is folder 'sanskrit-lexicon', which has the backup.
The backup (uncompressed) is about 25MB and the process took about 10 minutes.

The last '-l' argument was used to suppress copying of the 6.4MB Emoji images for each repository.

As far as I can tell, the html/images  directory in each repository backup does NOT have all the 
embedded comment images.  However, the html displays properly display the Github images.  

This is a very easy process which Dhaval has developed, and seems good.

  To provide the multi-continent safety that paranoid Gasyoun suggests,  
@drdhaval2785 @gasyoun and I can each periodically do a backup and store locally.  Then 3 of the
continents will be provisioned.

@drdhaval2785  I used all the introductory material you provided, which was good to get me up to speed.
However, it took several tries to get the exact form of the above command.   The readme might need a little
more attention at this point.

Also, I notice that you have authentication codes in the script.   While these worked fine,  I'm a bit concerned
that you might be leaving yourself open to security issues -- Not sure if this is so, but thought it should be
mentioned.

Thanks for setting this up.

**Comment by funderburkjim** [comment]
@drdhaval2785   I tried to run this at Cologne, and ran into a couple of issues.  I'll mention these in the
Issues of https://github.com/drdhaval2785/github_issue_backup/.

**Comment by drdhaval2785** [comment]
@funderburkjim 
After correction of code, the image files (which were missed earlier) increased the size of backup to 80 MB.
The execution took around 1 hr 34 mins.

Started at 2015-05-31_20-14-49
Ended at 2015-05-31_21-48-15

I have a local copy of 31-5-2015 in my system for paranoid @gasyoun .

**Comment by drdhaval2785** [comment]
`cronjob_sanskrit_lexicon.sh` is the oneclick solution.
Click this file and sleep for 2 hours.
The output should be ready in e:/backuptrial folder.
If you need some other output, change that destination in the .sh file.

**Comment by gasyoun** [comment]
@drdhaval2785 when the wave will come, you'll remember my words for sure.

**Comment by drdhaval2785** [comment]
I will remember you, provided both of us survive.
