### ISSUE TITLE
PD headwords with different Devanagari and IAST spellings

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#108]
There is a certain duplication of headword spelling that is present in PD.  
For nearly every headword,  the headword is given in two forms, Devanagari and IAST.
![image](https://cloud.githubusercontent.com/assets/6393033/7557131/c8fd1ae2-f759-11e4-8f3f-b207cd0ca586.png)

In the Cologne digitization, these two forms were coded in different ways.  The Devanagari was coded in
HK (which we have by now changed to SLP1), and the IAST was coded with the 'Anglicized Sanskrit' method
which represents IAST diacritics with numbers following the letter.
Here is how the digitizations look for the three headwords of the above image:
```
<P>.{#aMhohan#}¦ (am3ho-han)
<P>.{#aMhohi#}¦ (am3hohi) 
<P>.{#aMhi#}¦ (am3h-ri)
```

Now further imagine converting the IAST to SLP1 -  we expect to get THE SAME SPELLING as the coding of 
the Devanagari form of the headword.

This is the case with the first one (we ignore the '-' in `am3ho-han` and use the fact that 'm3' is a
representation of anusvAra).   Similarly, when the IAST of the second example is converted to SLP1, we
get the same spelling as the SLP1 coding of Devanagari.

But look at the third example -  Here, the SLP1 transcoding of the IAST is `aMhri`, which differs from the
SLP1 coding `aMhi` of the Devanagari ---  something is wrong.  Brief examination (say of the scan) for this
case shows that the `aMhi` spelling is wrong.

Now a relatively simple program was used to carry out this analysis for all headwords.
The analysis results in about 1500 (out of 107,620 headwords) cases where the Devanagari and IAST 
spellings are inconsistent.  

I think this list deserves further examination, as it will likely uncover many spelling errors - either in the
Devanagari coding or in the IAST coding.

After the corrections under issue 106, there are 1427 cases where the Devanagari and IAST 
spellings are inconsistent.  A first presentation of these is in file
[pd_deva_ne_iast.txt](https://gist.github.com/funderburkjim/8b4d16edde01075be131).

Note1: the first 4 cases can be ignored - the difference is due to IAST ambiguity in handling the hiatus 'ai'.
Note2: 4756 systematic IAST/DEVA differences ignored.  

Because 1427 is a large number of cases, we need to develop some ways to expedite the analysis of these 
cases.  
Based on examination of 80 of the cases in connection with issue#106,  I expect most of the
errors to be in the coding of Devanagari, and most of these are due to typographical errors.  However, a 
small percentage (5% ?) will likely be due to errors in the text.  And a similarly small percentage will be errors in the printed IAST.

**Comment by gasyoun** [comment]
Excellent analysis. `1500 (out of 107,620 headwords) cases where the Devanagari and IAST 
spellings are inconsistent` is not a small number indeed. It took us a few months to handle a similar number in Vachaspatyam doubles. The only thing I ask for - if you make SLP1 file, make .py script that adds or replaces SLP1 to Devanagari so one can actually work with the file, otherwise it's valuable information but hard to use for those who are shy to code or use converters for such files.

**Comment by funderburkjim** [comment]
Here are correction records (in an extended standard-form) for the first 40 cases:
```
pd:aicadeva,15:Ecadeva:n: hiatus
pd:aiculA,16:EculA:n: hiatus
pd:aibuka,17:Ebuka:n: hiatus
pd:aivuli,18:Evuli:n: hiatus
pd:aMsapArSvAmitApa,533:aMsapArSvABitApa:p:  aBitApa = burning pain
pd:aMsaBitti,553:am3sa-bhitti1:am3sa-bhitti:t:
pd:aMhi,664:aMhri:t:
pd:aMhryagra,688:aMhryagra:t:
pd:aMsamadaBaYjana,703:akaMsamadaBaYjana:t:
pd:akaTayitavya,789:a-kathayitvya:a-kathayitavya:p:
pd:akarmAMSa,1183:a-karmam3s4a:a-karma1m3s4a:p:
pd:akalpitAvidyA,1313:akalpita1vidva1:akalpita1vidya1:p:
pd:akalyARaPala,1341:akalya1n2an2a-phala:akalya1n2a-phala:t:
pd:akARqA,1486:a1ka1n2d2a1:aka1n2d2a1:p:
pd:akAraRatvatas,1660:aka1ran2at2va-tas:aka1ran2atva-tas:p:
pd:akAraRadvizwa,1665:akara1n2a-dvis2t2a:aka1ran2a-dvis2t2a:p:
pd:akArapUrvaka,1733:akarapu1rva-ka:aka1rapu1rva-ka:p:
pd:akAryakAraRaBAva,1883:a-ka1ryaka1rn2abha1va:a-ka1ryaka1ran2abha1va:p:
pd:akAryanirbanDitA,1922:aka1ryani1rbandhi-ta1:aka1ryanirbandhi-ta1:p:
pd:akAryapratizeDa,1933:aka1rya-prat2is2edha:aka1rya-pratis2edha:p:
pd:akAryArTatva,1983:a1ka1rya1rtha-tva:aka1rya1rtha-tva:p:
pd:akAlanIhAravfzwi,2057:aka1la-ni1ha1ravr2s2ti:aka1la-ni1ha1ravr2s2t2i:p:
pd:akAlapratikANkzaRatA,2073:a1ka1lapratika1n3ks2an2a-ta1:aka1lapratika1n3ks2an2a-ta1:p:
pd:akAlaharaRam,2161:a-ka1laharan2am3:a-ka1laharan2am:p:
pd:akAlopakAnta,2193:akAlopakrAnta:t:
pd:akIrtidveza,2314:akirti-dves2a:aki1rti-dves2a:p:
pd:aNkukumAlepana,2357:akuNkumAlepana:p:
pd:akuwitvA,2364:a-kutitva1:a-kut2itva1:p:
pd:akuwilAtman,2374:akutila1tman:akut2ila1tman:t:
pd:akuRWavarcas,2403:akun2t2ha-vareas:akun2t2ha-varcas:t:
pd:akulaja,2520:akulaja~akulaja:n:  Two derivations akula-ja or a-kulaja
pd:akuhakArTa,2601:akuhakArTa~akuhakArTa:n: two derivations
pd:akftadArasaMgraha,2753:akr2ta-da1rasa1n3graha:akr2ta-da1rasan3graha:t: also note M in devanagari, N in IAST
pd:akftapadaSabdam,2782:akr2ta-pada1s4abdam:akr2ta-padas4abdam:t:
pd:akftaSayanakiya,2906:akftaSayanakriya:t:
pd:akftAputra,3016:akr2ta-putra:akr2ta1-putra:t:
pd:akftArcana,3034:akr2ta1cana:akr2ta1rcana:t:
pd:akfSASva,3252:aks4a1s4va:akr2s4a1s4va:p:
pd:akxptakramatva,3312:akxptakramatva:t:
pd:akriyAvizwa,3619:a-kriya1vis2ta:a-kriya1vis2t2a:p:
```
6 are no change
20 are print changes.  18 of these were errors in the printed IAST, 2 in the printed Devanagari 
14 are typos (errors in digitization).   6 of these were in Devanagari, 8 in IAST.

The extension to the standard form is exemplified by

pd:akftArcana,3034:**akr2ta1cana:akr2ta1rcana**:t:

This means that the spelling `akr2ta1cana` is to be changed to `akr2ta1rcana`  [insert an 'r']
for the headword with key1=akftArcana, L = 3034, in the pd dictionary; and that it is a typo (OCR error, error in digitization).

**Comment by funderburkjim** [comment]
Here is a sample of what I am working with:
```
* TODOx Case 0040: akriyAvizwa [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=pd&page=1-0146b][page 1-0146b]]
;pd:akriyAvizwa,3619:akriyAvizta:n:
pd:akriyAvizwa,3619:a-kriya1vis2ta:a-kriya1vis2t2a:p:
;  <P>.{#akriyAvizwa#}¦ (a-kriya1vis2ta) {%adj.%} not being associated with an action
;  <>{#nAkriyAvizwAnAM smArakatvasaMBavaH#} Bha1t2t2Di1. ii. 201. 1 ({%on%} v. 5. 11)
;
* TODO Case 0041: akrItayajamAna [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=pd&page=1-0146b][page 1-0146b]]
;pd:akrItayajamAna,3633:akrItayajamARa:n:
;pd:akrItayajamAna,3633:akri1ta-yajama1n2a:akri1ta-yajama1n2a:n:
;  <P>.{#akrItayajamAna#}¦ (akri1ta-yajama1n2a) {%m.%} a sacrificer who cannot be
;  <>hired {#akrItayajamAnasya BakzasattvAcca#} Nya1yMa1Vi. 498. 15 ({%on%} x. 2. 9) [Page1-147a+ 64]
;
```

This is optimized for Emacs org-mode usage (an outlining mode), and looks more useful when viewed within the Emacs editor:
![image](https://cloud.githubusercontent.com/assets/6393033/13409618/ce62aa52-df01-11e5-8e53-9539ef8734fe.png)

The work is fairly efficient with this format.  

An intermediate familiarity with Sanskrit is probably required to make the decision whether the
error is with the Devanagari or IAST.  

If anyone wants to work on some of these, let me know.  I could tailor the above to show 
Devanagari and IAST, rather than the current SLP1 and AS (Anglicized Sanskrit) coding used in the
pd.txt file (as shown above).

**Comment by funderburkjim** [comment]
These changes have now been made and installed.

Of all the cases examined, there were about 1280 changes made, and 132 cases where no change
was required.

Here is another tabulation of the cases, based on (a) whether the change was to the Devanagari or to the IAST, and (b) whether the change was judged to be a typist error ('t') or an error in the printing ('p'):

DEVA-p 95
DEVA-t 390
IAST-p 418
IAST-t 386

The file [hwchk_iast1.org (raw)](https://raw.githubusercontent.com/sanskrit-lexicon/CORRECTIONS/master/dictionaries/PD/issue-108/hwchk_iast1.org)  is the edited working document for these changes, and would be a good starting place for any reviewing that others may
wish to do.   [Note: In this 'raw' view, the links are not active].

**Comment by gasyoun** [comment]
Amazing how many non-t errors are there.
