### ISSUE TITLE
MCI corrections drawn from faultfinder suggestions

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#110]
Only 13 correction candidates for MCI (Mahabharata Cultural Index) dictionary were identified by faultfinder.
Corrections were made to 6 of these:
<hr>
001 fzaBa
001 exaka -> elaka:  Digitization is 'l2'. Possibly should be 'eLaka', though
   no other dictionary has 'eLaka'
   ekaka, ejaka, ewaka, eqaka, eRaka, etaka, eraka, elaka (ezaka)
001 elapatra
001 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=exaka'>exaka</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=007'>007-a+ 39</a>

<hr>
005 vasUnAM
005 vAyavyAswra -> vAyavyAstra : print error, or stray dot below t in print()
005 vAyuvarza
005 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=vAyavyAswra'>vAyavyAswra</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=138'>138-a+ 40</a>

<hr>
007 kiNkIRikASrama
007 kimjapya -> kiMjapya:  (kiYjapya,kiMjapya)
007 kiMdatta
007 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=kimjapya'>kimjapya</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=311'>311-a+ 38</a>

<hr>
008 trigaNga
008 tridlvA -> tridivA () : print error
008 trivizwapa
008 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=tridlvA'>tridlvA</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=360'>360-a+ 38</a>

<hr>
010 yamunAtIrTa
010 yamnnAdvIpa -> yamunAdvIpa (): print error
010 yayAtipatana
010 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=yamnnAdvIpa'>yamnnAdvIpa</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=430'>430-a+ 38</a>

<hr>
013 SUrasena
013 Sfngin -> SfNgin : IAST missing dot over 'n'  SfMgin, SfNgin ()
013 SEneya
013 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=Sfngin'>Sfngin</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=891'>891-b+ 39</a>

<hr>

**Comment by funderburkjim** [comment]
The 7 with no changes are:

002 niSAkara
002 nizwyUnaka -> NO CHANGE: nizwAnaka ()
002 nizWUrika
002 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=nizwyUnaka'>nizwyUnaka</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=034'>034-b+ 37</a>

<hr>
003 vAmana
003 vAmyO -> NO CHANGE: ('O' is dual form)  vAmya ()
003 vAyutanaya
003 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=vAmyO'>vAmyO</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=052'>052-a+ 38</a>

<hr>
004 SArdUlI
004 SAlipIRqa -> NO CHANGE: MW has SAlipiRqa ()
004 SiKin
004 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=SAlipIRqa'>SAlipIRqa</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=061'>061-a+ 36</a>

<hr>
006 kAzWavant
006 kiNkIRikASrama -> NO CHANGE: MW has kiNkiRikASrama ()
006 kimjapya
006 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=kiNkIRikASrama'>kiNkIRikASrama</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=311'>311-a+ 38</a>

<hr>
009 mfgaDUma
009 medraTA -> NO CHANGE: medram ()
009 meDAtiTi
009 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=medraTA'>medraTA</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=417'>417-b+ 38</a>

<hr>
011 sinDUttama
011 sinDos ->  NO CHANGE: Inflected form of sinDu (siglos,sidDas,sidDis,sinDa,sinDi,sinDu,sinDuH)
011 sItA
011 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sinDos'>sinDos</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=479'>479-b+ 38</a>

<hr>
012 rudrasya
012 rEByASrama ->  NO CHANGE: (rAjASrama,rAmASrama)
012 romA
012 headword <a target='_MCIword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=rEByASrama'>rEByASrama</a> ---  page <a target='_MCIpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/MCIScan/2014/web/webtc/servepdf.php?page=558'>558-b+ 40</a>

<hr>

**Comment by gasyoun** [comment]
Closed?

**Comment by funderburkjim** [comment]
Working documents are:
* [mci-fuzzyalpha.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/MCI/faultfinder/mci-fuzzyalpha.txt)
* [mci-fuzzyalpha.html](http://funderburkjim.github.io/fuzzywork/mci-fuzzyalpha.html)
