### ISSUE TITLE
KRM Corrections drawn from faultfinder suggestions

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#112]
I went through the exercise of generating faultfinder candidates for the 'headwords' of the grammar text KRM (Kṛdantarūpamālā).  120 cases resulted (out of about 2000 headwords).

The headwords are roots, in a DAtupAWa form. (Since MW does not present roots in this form, the
comparison is probably not too useful. A comparison with, say, Wilson, or  mADavIya DAtupAWa might be
more relevant.)

I've glanced at the list, and think that there are no corrections to be made.

For the reference of others who may wish to examine the list, here are the two work documents:
* [krm-fuzzyalpha.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/KRM/krm-fuzzyalpha.txt)
* [krm-fuzzyalpha.html](http://funderburkjim.github.io/fuzzywork/krm-fuzzyalpha.html)

**Comment by gasyoun** [comment]
Yeah, a dhatupatha round is a different issue. One that I'm interested in and hope @Shalu411 as well.

**Comment by Shalu411** [comment]
Namaste
Sure, I am.
