### ISSUE TITLE
kowISvaramAhAtmya in PW

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#115]
In working with ACC,  I happened to notice kowISvaramAhAtmya in PW.  According to the scan of PW, this
should be spelled kow**e**SvaramAhAtmya , as it is in ACC.
However, when making the change to PW just now, I noticed that the change from 'I' to 'e' would put the
word out of alphabetical order in PW.  Also, I realized I could not explain the compound 'koweSvara' , although
the explanation of 'kowISvara' as 'kowi + ISvara' is easy.

So, now I'm wondering if the printed form kow**e**SvaramAhAtmya  in PW is itself wrong.

Here's the scan of PW:
![image](https://cloud.githubusercontent.com/assets/6393033/7668445/acacf922-fc07-11e4-8f6c-4c234cecd061.png)

Can any of our Sanskrit experts clarify the situation?

**Comment by Shalu411** [comment]
Namaste
कोटृ (kotf)) >> कोट्ट (kowwa). 
It means fort. Solved. :)
Festung (German) = Fortress

Apte-SE- कोट्टः [L=11554] [p= 0425-c] 	[कुट्ट्-घञ् निº गुणः] A fort, castle.

SKD- कोट्टः [L=8978] [p= 2-202] 	कोट्टः, पुं, (कुट्ट्यन्ते शत्रवोऽत्र । कुट्ट छेदे + घञ् । निपातनात् गुणः ।) दुर्गपुरम् । इति लिङ्गादि-संग्रहे अमरः ॥

**Comment by gasyoun** [comment]
@funderburkjim issue closed?

**Comment by funderburkjim** [comment]
@Shalu411   OK.  I misread कोट्ट   Thanks for explaining.

Could you explain etymology of koweSvaramAhAtmya  ?

**Comment by drdhaval2785** [comment]
koweSvara is a pilgrim center in Gujarat.
It may be a work explaining its religious importance.

https://en.wikipedia.org/wiki/Koteshwar,_Kutch

**Comment by funderburkjim** [comment]
@drdhaval2785   Thanks for derivation idea, and link.
