### ISSUE TITLE
A repository to store headword files

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#116]
@funderburkjim 
Just to keep track of how the files like sanhw1.txt or mw1.txt changed over time, wouldn't it be nice if we can place them in a github repo and update periodically (via some of your pythons)?
This way we can track the change over time too.

**Comment by funderburkjim** [comment]
The sanhw1.txt file is in this Corrections repository, and has been for a while.

What else were you thinking of?  Not sure what 'mw1.txt' is.

**Comment by gasyoun** [comment]
It's there since long time https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/sanhw1/sanhw1.txt

**Comment by drdhaval2785** [comment]
@funderburkjim and @gasyoun 
I know for long that this sanhw1.txt lives in CORRECTIONS repository.
What I wanted to tell is that a random user should be able to locate all up to date SLP1 headword files of different dictionaries of Colone at one place, so that he can use it for his purpose.

**Comment by drdhaval2785** [comment]
Not on high priority.
If need be, we can scrape headwords for different dictionaries from sanhw1.txt

**Comment by funderburkjim** [comment]
@drdhaval2785  Ok.  We can revisit this idea if and when the need arises.
