### ISSUE TITLE
sArisTAKA in MW

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#12]
<key2>sArisTA-KA~</key2> seems to have an issue, because it generates | ! | and only one of it's kind:
`#sāristhā-khā!#` for `sArisTAKA`

![saristha](https://cloud.githubusercontent.com/assets/80761/4617555/3384911e-5300-11e4-9705-d245aa76e479.PNG)

Discovored by https://github.com/drdhaval2785/SanskritSorting/issues/16

**Comment by drdhaval2785** [comment]
@funderburkjim
Too difficult?
We have tackled so many corrections.
This is only a single word.

**Comment by drdhaval2785** [comment]
@funderburkjim
Too difficult?
We have tackled so many corrections.
This is only a single word.

**Comment by gasyoun** [comment]
@drdhaval2785 single word long forgotten that will dive out the next time I compile my updated edition of reverse dictionary. By end of 2015 I hope I'll send it to the printer. If Jim will be nice :ice_cream:

**Comment by funderburkjim** [comment]
I've changed one thing in the display of MW, so now key2 for sArisTAKA displays with the candra-bindu.
Here's the comment and change made to the disp.php program (in webtc directory of the display for MW):
```
 /* Mar 23, 2015.  Normally in MW, ~ is used as a 'space' character,
    this is a holdover from a coding convention in Malten's Monier.all.
    However, in the current SLP1, ~ is used to indicate candra-bindu.
    This appears in key2 for one word (key1=sArisTAKA, key2=sArisTA-KA~);
    As far as is known, this is the only use of ~ in Sanskrit-SLP1 in 
    mw.xml.  Thus, we change this global replacement in all of $line,
    to deal just with the $body.
 $line = preg_replace('/~/',' ',$line);
 */
 if (preg_match('|^(.*)(<body>.*</body>)(.*)$|',$line,$matches)){
  $head = $matches[1];
  $body = $matches[2];
  $tail = $matches[3];
  $body = preg_replace('/~/',' ',$body);
  $line = $head . $body . $tail;
 }
```

**Comment by funderburkjim** [comment]
re '~' in PWG:
in pwg.xml, a '~' occurs in 577 records.
Most of these occur in forms VOWEL+M+~ , and these would be candidates for changing to VOWEL+~.
  I want to confirm with Peter whether M~ is redundant in SLP1, and if so will make the change.
As is common, when the other cases are examined,  it's like turning over a rock in the woods -- various
obscure creatures crawl out!
For instance, there are a few cases where ~ has been used for an mdash = &mdash;  (long dash). One
of these occurs under headword anapAya, and in anapAya one sees &lt;NV&gt; -  what the heck is that?  There
are 21 cases of &lt;NV&gt;  Based on the anapAya example, and a vague memory of a comment from Thomas, I think &lt;NV&gt;xxx&lt;/NV&gt; is from a source of 'corrigendum' material that Thomas started to insert but then didn't finish; the last one in pwg.txt is 
```
<H1>000{antaHpArSvya}1{antaHpArSvya/}¦ (von {#antar + pArSva#}) •adj.
<NV>{%an den Seiten befindlich%} st.</NV> = {#antaHparSavya#} ¯{¤VS. 39, 9.¤}
```
If so, perhaps these NV sections (which at least in case anapAya are definitely not in the body of the print) should also be removed.

There is actually an email comment from Thomas of Dec 15, 2011, as follows:
```
tag <NV> (N=Nachträge=addtions V=Verbesserungen=corrections) is a first feeble attempt to integrate the very extensive additions and corrections added by Boehtlingk himself to pwg. I think they can be deleted, because there are now better ways to handle these additions (similarly to the Halle and Schmidt complex, I think)
```
So, Thomas would be in favor of removing these. Maybe I should go ahead and delete these, and put 
the old versions as an NV.txt file under PWG in Corrections repository.

**Comment by gasyoun** [comment]
You must have been an inspector or detective before we met. disp.php is great, but for my .indd file I'll use .xml, so it does not solves a thing actually. As per `whether M~ is redundant in SLP1, and if so will make the change.` - Peter has to agree or change his documentation. `'corrigendum' material that Thomas started to insert but then didn't finish` is where it gets interesting. `(which at least in case anapAya are definitely not in the body of the print) should also be removed` - if not removed at least marked as such that are not in the print. So nobody would have to solve the puzzle without any clues. What is `Halle` complex in Thomas' email is interesting, no idea. Removing these does not sounds a good idea as well - it's at least a start, even if abandoned. The only issue is to have a list of such abandoned starts.

**Comment by funderburkjim** [comment]
For our information, here is my email question to Peter regarding M~, and his response:
```
Peter -
 In PWG, there are 577 records of pwg.xml in which the current coding of Devanagari in SLP1 includes a ~.
 In almost all of these, the form is VOWEL+M+~.   Is the form M~ redundant in SLP1, i.e., should all of these
 cases be changed to VOWEL+~ ?
 Incidentally, why is candra-bindu used at all - does it represent a different pronunciation than M? Why is it
 absent from the usual listing of the Devanagari alphabet?
```

```
Dear Jim,
"M~" is not meaningful in SLP1.  'M' indicates anusvAra; '~' indicates nasalization which does not apply to anusvAra since anusvAra is already a nasal sound.
I believe the endoding "M~" is a relic of Thomas' original encoding which distinguished bindu from candra bindu.  In SKD at least, bindu was encoded as M and candrabindu as MM.  We should check whether "M~" represents candrabindu as MM did in SKD.
Now the use of bindu and candrabindu in Devanagari Vedic texts varies so it is not clear what the phonetic significance is without some further investigation.  When it occurs above a vowel or semivowel y, l, or v, candra bindu represents nasalization of the vowel or semivowel.  If candrabindu occurs with a virama (or avagraha) below it, it indicates an anusvAra.  Many texts use bindu for an anusvAra that is susceptible to being replaced by a stop homorganic with the following stop, e.g. vanaM gacCati could become by sandhi vanaN gacCati, but contrast this with a 'true' anusvAra, which only occurs before spirants (S, z, s, h) and r, e.g. vanaM sarati, vanaM rocate.  If the use of M~ is consistent according to the above contexts, it may be possible to accurately transcode the 'M~' to either 'M' or '~' depending upon that context.
```

**Comment by funderburkjim** [comment]
I think that 'M~' in pwg.txt always occurs due to my conversion of Thomas's  MM which he used to
represent candra-bindu in his version of HK transliteration.

According to Peter's reply, the transformation of candra-bindu MM to M~ is incorrect and, MM should be
changed to ~.  Unless anyone can see a reason otherwise,  I'll make that change. to PWG.

I think Peter's long 3rd paragraph has no direct bearing on such a change.   Although I found the comment 
on 'true' anusvAra interesting, as provides an explanation of why, for instance, saMsAra is so spelled, rather
than being spelled as samsAra.

**Comment by gasyoun** [comment]
~ does not makes much sense, but let it be - it's better than that inconsistency what we have now. If I were to choose between `transcode the 'M~' to either 'M' or '~'` I would go for 'M'. Or do we use M for the anusvara and should not add a second meaning?

**Comment by funderburkjim** [comment]
@gasyoun 'Halle complex'  :  A group at Halle University worked with Thomas (and me)  in 2010/11 to 'add' some other texts (sort of like Schmidt) which in some sense supplement  Boehtlingk.  
For an example see http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/halleSample2/disp/index.php,
and enter kfzRa.
This data is not public, as far as I know; 
if you wanted to get this you would need to contact members of the project at
Halle.  I can email Thomas for a contact for Halle if you wish to pursue this.

**Comment by funderburkjim** [comment]
@gasyoun  re ~ and M.  I think the answer has to do with finer points of SLP1.  To have pwg Devanagari coded in conformance with SLP1,  we should use ~ for candrabindu, and M for anusvAra.  That's my understanding.

**Comment by gasyoun** [comment]
@funderburkjim let it be as you say. not found: kfzRa - so sure I would want to send an email to Halle. In 2006 I even received scans of books from Halle, so there is a strong old school of Indology scholars.

**Comment by funderburkjim** [comment]
@gasyoun Be sure to change to SLP1, then look up word 'kfzRa'.

**Comment by funderburkjim** [comment]
Re M~.  I went ahead and changed the M~ to ~.  This was done by a change to the hk_slp1.xml transcoder
file in convertwork directory; so the change is visibile in pwg_orig_utf8_slp1.txt.  Also had to slightly adjust some of the subsequent manualByLine##_slp1.txt input files so that subsequent updates would work.

@drdhaval2785  I think it is safe to close this issue now, and am doing so.

**Comment by funderburkjim** [comment]
Also Removed the &lt;NV&gt; cases (21) in PWG.
The old data is in [removenv_all.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/PWG/removenv_all.txt).

**Comment by drdhaval2785** [comment]
Great. Conclusively ended the thread. Happy.

**Comment by funderburkjim** [comment]
Made the same correction of MM (HK) -> ~ (SLP1) for dictionaries PWG (already mentioned), and
SKD, AP, AP90, PW, VCP.  Not currently aware of other dictionaries requiring back-correction.

**Comment by gasyoun** [comment]
MM is more self evident, but it's good to have a uniform standard. If Peter says ~, so be it. Thanks, Jim.
