### ISSUE TITLE
Interesting Correction submission

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#120]
In processing recent submissions to the Correction Form, Here was one, entered under Yates dictionary:

वाल्मीकि: संस्कृतस्य आदिकविरिति मन्यते। 
तेन हि रामायणं नाम विश्वप्रसिद्धा कृतिः रचिता। 
सः संस्कृतस्य आदिकविः आसीत् | 
अस्य रचनासु वेदोत्तर-कालीन-संस्कृतस्य प्रवाहः, माधुर्यं च वर्तते।

As best as I can determine this is a praising of Valmiki.

**Comment by Shalu411** [comment]
Namaste
Yes it is, indeed not just about praising but importance of Valmiki.
I do not know what context it was put up in correction form-  but here is the translation.

वाल्मीकि: संस्कृतस्य आदिकविरिति मन्यते।
Valmiki is considered as first poet of Samskrt. 
तेन हि रामायणं नाम विश्वप्रसिद्धा कृतिः रचिता।
The world-famous work, Ramayana, is composed by him, indeed.
सः संस्कृतस्य आदिकविः आसीत् |
He is the first poet of Samskrt. 
अस्य रचनासु वेदोत्तर-कालीन-संस्कृतस्य प्रवाहः, माधुर्यं च वर्तते।
In his poetry, there is the post-Vedic flow and sweetness of Samskrt.

---
My comment- :)
And if we all agree that "Samskrt is the oldest language in the world", then Valmiki happens to be the first poet of all languages in the world.

**Comment by gasyoun** [comment]
Samskrt is not the oldest language of the world, but one with the biggest literature and that should be enough. Thank you again @Shalu411 for such a precise translation, wish there would be more.
