### ISSUE TITLE
Change in cfr_adj.py

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#122]
In a discussion regarding the previous 'bring up to date' commit, @gasyoun raised the question of why the 'history' of the commit showed changes in corrections that were done many months ago.  See
[here](https://github.com/sanskrit-lexicon/CORRECTIONS/commit/fc22b56d5f8bf83ae75b98275be08799c1ef00c9) for that discussion.

@gasyoun suggested I should make a correction to cfr_adj.py to counter the poor Google policy of inserting new Correction form changes into the middle of the history.  I think I've now done that.

The [correctionform.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/correctionform.txt) and similar files for each dictionary are
now based on a sort of the date-time field.  You'll see this in correctionform.txt by noting that the
case number order (as shown) and the date are now consistent.   If things work as expected, then
as new correction form submissions are added,  the revised correctionform.txt files should only
vary based on the new correction form submissions.  

We'll have to keep an eye on this for the next few times correctionform.txt is regenerated to be sure
that the program change is indeed functioning as advertised.

**Comment by gasyoun** [comment]
Let's see. I give you my thanks.

**Comment by drdhaval2785** [comment]
I saw a curious thing while seeing github for windows.
The correction numbers got decreased by one.
I am not sure whether @funderburkjim wanted to point to this or is it something irrelavent.

![capture](https://cloud.githubusercontent.com/assets/5755132/11530560/9aac509a-991b-11e5-8db4-05b1b3235efb.png)

**Comment by funderburkjim** [comment]
My memory tells me that someone, using the correction form submission process, entered an 'empty' or otherwise completely unusable correction;  and that I deleted it.   This would account for what you observed.  

 It should be possible to 'go back in time' in cfr.tsv to see this but at a first glance, I don't see how, now on Dec. 2 after several intervening rounds of commits, to go back to that Nov 26/27 period.  If you discover how to go back in time,  you might write a description of how to do that.

**Comment by drdhaval2785** [comment]
1. You open cfr.tsv in github
2. You click on 'History'

![capture](https://cloud.githubusercontent.com/assets/5755132/11552519/9418d72c-99ab-11e5-97eb-ed617597c17c.png)

3. You go to the concerned time period and check the alterations.


![capture](https://cloud.githubusercontent.com/assets/5755132/11552540/d0f15f16-99ab-11e5-8053-a9aad8dff5c1.png)

**Comment by drdhaval2785** [comment]
I guess you meant the following change in https://github.com/sanskrit-lexicon/CORRECTIONS/commit/2d839bfc99aebbf2dc6a89730715b24dcaf904dd

![capture](https://cloud.githubusercontent.com/assets/5755132/11552572/1ffd4156-99ac-11e5-9d10-01ef95381fb1.png)

In this case, we can close this issue. There is no abnormal behaviour by your change in script.

**Comment by funderburkjim** [comment]
@drdhaval2785  Good explanation.  My error was in trying to access this feature in the GUI for the local repository, rather than looking at the github.com repository.

The deleted line was -11/18/2015 16:40:08  PW ..., as you surmised.
