### ISSUE TITLE
correction to sort order in correctionform.txt

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#123]
Due to a 'bug' (feature) of the Google [correction form response sheet](https://docs.google.com/spreadsheets/d/1xwxkgCw1hLPTWPh27YURHkR0pcbNpYDCcUeR_NAEiWw/edit#gid=0),  new corrections submitted by users are inserted into rows in the middle of the spreadsheet, rather than at the end of the spreadsheet.

The program [cfr_adj.py](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/cfr_adj.py) generates the correctionform.txt files of this repository (both for all dictionaries, and for each dictionary separately).  The original version of this program did not take into account the 'bug'.  This led to difficulty in using the Git history for the correctionform files.

At @gasyoun's urging,  back on July 18, 2015 I made a change to cfr_adj.py to sort the corrections by
the date-time field of the spreadsheet.   This was not done properly, and today I realized this and made a correction so the sorting will be done properly.

The purpose of this 'issue' is just to mention the above.  I'll close it when the accuracy of the process has been verified.

**Comment by gasyoun** [comment]
5000 corrections in this form alone since 2014. Or is everything there? I guess no, there would have been evern more. It's good that you documen even documenting and I give you my thanks. Three months are left for me to prepare my reverese word index, so I'll be back soon active again.

**Comment by funderburkjim** [comment]
I think this issue has been solved adequately.
