### ISSUE TITLE
PW headwords ending in anusvAra

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#124]
In looking at the 'itrans' list of words ([reference](https://github.com/sanskrit-lexicon/GreekInSanskrit/issues/17)), it was noticed that some PW headwords erroneously end in 
anusvAra (= slp1 'M').

This issue examines all such cases; there are only 19 cases to examine.

**Comment by funderburkjim** [comment]
case = 1 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=atideSyaM'>atideSyaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=1021'>1021-3</a> 
linenum = 3643

```
<H1>100{atideSyaM}1{atideSyaM}¦ •Adj. {%zu übertragen , auszudehnen auf%} ¯NJA7JAM.7,2,1. ‹Davon› •Nom.abstr. #{°tva} •n. ‹S. 7.› PW1792
```

**Comment by funderburkjim** [comment]
case = 2 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=aByaNgaM'>aByaNgaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=1092'>1092-1</a> 
linenum = 15792

```
<H1>100{aByaNgaM}1{aByaNgaM}¦ •m. ²1) {%Salbung , Bestreichung mit fetten Stoffen%} ¯SPR.7711. ²2) {%Salbe.%} PW7854
```

**Comment by funderburkjim** [comment]
case = 3 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=alaktaM'>alaktaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=1116'>1116-2</a> 
linenum = 19957

```
<H1>100{alaktaM}1{alaktaM}¦ •m. {%rother Lack%} , ‹namentlich› {%der in Wasser aufgelöste.%} #{°rasa} •m. ‹dass.› ¯BHA7VAPR.1,76. ƒPage1.116-3ƒ PW9887
```

**Comment by funderburkjim** [comment]
case = 4 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=AgAmikaM'>AgAmikaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=1161'>1161-3</a> 
linenum = 27593

```
<H1>100{AgAmikaM}1{AgAmikaM}¦ •Adj. (•f. #{A}) {%auf die Zukunft bezüglich.%} PW13651
```

**Comment by funderburkjim** [comment]
case = 5 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=ekAdaSakapAlaM'>ekAdaSakapAlaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=1270'>1270-1</a> 
linenum = 44861

```
<H1>100{ekAdaSakapAlaM}1{e/kAdaSakapAlaM}¦ •Adj. {%auf eilf Schüsseln vertheilt.%} PW22062
```

**Comment by funderburkjim** [comment]
case = 6 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=etaddevatyaM'>etaddevatyaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=1272'>1272-1</a> 
linenum = 45202

```
<H1>100{etaddevatyaM}1{etaddevatyaM}¦ •Adj. {%diese zur Gottheit habend%} ¯C2AT.BR.8,3,3,6. PW22230
```

**Comment by funderburkjim** [comment]
case = 7 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=krandaM'>krandaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=2111'>2111-1</a> 
linenum = 64545

```
<H1>100{krandaM}1{kra/ndaM}¦ •m. ²1) {%Gewieher.%} ²2) {%Geschrei , Ruf.%} PW31694
```

**Comment by funderburkjim** [comment]
case = 8 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=grahItavyaM'>grahItavyaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=2192'>2192-2</a> 
linenum = 76749

```
<H1>100{grahItavyaM}1{grahItavyaM}¦ ²1) •Adj. ³a) {%für sich zu nehmen , zu empfangen.%} ³b) {%zu schöpfen%} ‹(eine Flüssigkeit).› ²2) •n. {%das Empfangensollen.%} PW37429
```

**Comment by funderburkjim** [comment]
case = 9 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=cetavyaM'>cetavyaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=2236'>2236-3</a> 
linenum = 83443

```
<H1>100{cetavyaM}1{cetavyaM}¦ •Adj. ²1) {%zu schichten , neben einander zu legen.%} ²2) {%einzusammeln.%} PW40596
```

**Comment by funderburkjim** [comment]
case = 10 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=CandasyaM'>CandasyaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=2242'>2242-1</a> 
linenum = 84182

```
<H1>108{CandasyaM}1{CandasyaM}¦ ‹(› #{Candasi/a}) ²1) •Adj. {%in Liedform sich bewegend , dem Lied angemessen , das L. betreffend%} ‹u.s.w.› ²2) •f. #{A^} ‹Bez.› {%bestimmter Backsteine.%} PW40934
```

**Comment by funderburkjim** [comment]
case = 11 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=janitavyaM'>janitavyaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=2251'>2251-3</a> 
linenum = 85540

```
<H1>100{janitavyaM}1{janitavyaM}¦ •Adj. {%was geboren werden ~ , was entstehen soll.%} PW41572
```

**Comment by funderburkjim** [comment]
case = 12 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=jyotizyaM'>jyotizyaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=2279'>2279-1</a> 
linenum = 89732

```
<H1>100{jyotizyaM}1{jyotizyaM}¦ •Adj. {%unter Beleuchtung befindlich%} ¯TS.6,4,2,2 ; ‹vgl.› •Comm. ¯1,554,8.fgg. PW43591
```

**Comment by funderburkjim** [comment]
case = 13 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=tAmravaRaM'>tAmravaRaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=3023'>3023-1</a> 
linenum = 93509

```
<H1>100{tAmravaRaM}1{tAmravaRaM}^1¦ ²1) •Adj. {%dunkelroth%} ¯TAITT.A7R.1,12,4.¯Chr.64,23. ²2) •m. ³a) {%*eine best. Grasart.%} ³b) ‹N.pr.› ¹a) ‹eines Sohnes des †Kr2shn2a› ¯VP.^2.¨2,129. ¹b) ‹eines Theiles von †Bha7rata †Varsha› ¯VP.2,3,6. ²3) •*f. #{A} {%die chinesische Rose.%} ²4) •*f. #{I} {%Sesamblüthe.%} PW45345
```

**Comment by funderburkjim** [comment]
case = 14 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=pratyanIkaBAvaM'>pratyanIkaBAvaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=4152'>4152-1</a> 
linenum = 148310

```
<H1>100{pratyanIkaBAvaM}1{pratyanIkaBAvaM}¦ •m. {%das Gegentheilsein%} •Comm. ‹zu› ¯NJA7JAS.1,1,42.2,2,2. PW71935
```

**Comment by funderburkjim** [comment]
case = 15 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=mahAdamBaM'>mahAdamBaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=5044'>5044-2</a> 
linenum = 173956

```
<H1>100{mahAdamBaM}1{mahAdamBaM}¦ •Adj. {%grossen Betrug übend%} (†C2iva) PW84381
```

**Comment by funderburkjim** [comment]
case = 16 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=SitivAraM'>SitivAraM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=6232'>6232-3</a> 
linenum = 232196

```
<H1>100{SitivAraM}1{SitivA/raM}¦ ²1) •Adj. {%weissschweifig.%} ²2) •*m. {%®Marsilea_quadrifolia.%} PW112231
```

**Comment by funderburkjim** [comment]
case = 17 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=saMskftatvaM'>saMskftatvaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=7009'>7009-3</a> 
linenum = 242100

```
<H1>100{saMskftatvaM}1{saMskftatvaM}¦ •n. {%das Zugerichtetsein%} ‹u.s.w.› ¯G4AIM.3,4,33. PW117008
```

**Comment by funderburkjim** [comment]
case = 18 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=saMhatahastaM'>saMhatahastaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=7011'>7011-1</a> 
linenum = 242290

```
<H1>100{saMhatahastaM}1{saMhatahastaM}¦ •Adj. •Du. {%sich gegenseitig an der Hand fassend%} •Comm. ‹zu› ¯GOBH.2,2,1. •Nom.abstr. #{°tva} •n. ¯ebend. ƒPage7.011-2ƒ PW117103
```

**Comment by funderburkjim** [comment]
case = 19 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=subanDanaM'>subanDanaM</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=7155'>7155-3</a> 
linenum = 262524

```
<H1>100{subanDanaM}1{subanDanaM}¦ •n. {%ein festes Band.%} #{°vimocana} •Adj. ‹als Beiw. †C2iva's.› PW126996
```

**Comment by gasyoun** [comment]
Every case needs to be examined?

**Comment by funderburkjim** [comment]
Every case examined, and the corrections shown are now implemented.
 Note: (The headowrd links in the cases above are broken, since they use the old spellings).
