### ISSUE TITLE
MW key2 corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#125]
First, I've invited Github user Zaaf2 (Zilton) to the 'researchers' team of Sanskrit Lexicon.

Zilton has submitted many corrections to the dictionaries, mainly MW.  He mentioned in an email that he is new to the Github kind of network, so we'll have to help him get up to speed on that.

If you read this note Zilton,  Welcome! Add a comment so we'll know you are there.

I've been reviewing some former work, which takes https://github.com/funderburkjim/MWlexnorm to the next step.   Namely, to parse the declension information from MW records, in such a way as to
make explicit the declineable stems.   This forms a basis for generating declension tables based on the information from MW.  I'll detail this step more in the MWlexnorm repository.  But in this issue, I'm raising questions that arise in a few cases.

**Comment by funderburkjim** [comment]
case 1: feminine of AyuHpati  
[scan](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=148)

(H3) आयुः-पति [p= 148] : mf(इनी)n. presiding over longevity ĀpṠr.  (cf. आयुष्पति.) [L=25875]

**The question is: is the feminine stem AyuHpatinI   (as the scan shows) or is it AyuHpatnI ?**

There is a similar word Ayuzpati  (on the [next page](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=149) of the scan), whose feminine
stem is AyuzpatnI.

(H3) आयुष्-पति [p= 149] : mf(त्नी)n. ruling over long life AV.  [L=25903]

There are several other 'patnI' ending words.   I don't see under 'pati' that the feminine form is
'patnI', but suspect that it is.

**Comment by funderburkjim** [comment]
case 2:  antaHstomaBAgam  [scan](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=1312)

H3) अन्तः-स्तोम-भागम् [p= 1312] : mfn. within the bricks called स्तोम-भागा, ṠBr.  [L=8039.12]

This appears to be an error in the print.  I think the headword should not have the final 'm',
i.e., should be `antaHstomaBAga`.

**Comment by funderburkjim** [comment]
case 3: ASiraduG  [scan](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=158)

(H3) ASira-duG [p= 158] : mfn. milking for a mixture with soma ĀṡvṠr.  [L=27709]

**Should this be ASiraduGa  (with an 'a')?**  In which case 'ASiraduG' would be considered a factual error.

Using [this multidictionary lookup](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/hwnorm/hwnorm1.php),  only MW has ASiraduG, and no dictionary has
either ASiraduGa   or ASiraduh.

**Comment by funderburkjim** [comment]
case 4: lolat [scan](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=905)

(H2) लोलत् [p= 905] : mf(अन्ति)n. moving to and fro, rolling &c (cf. √ लुल्). [L=183105]

Is the feminine for is an error in the print?  I think it should be 'antI', so `lolantI' for the f. form,
as this is a present participle.

**Comment by zaaf2** [comment]
Hi Jim, 

Those are very interesting observations. 

As far as I can see, they are typographical errors. 

Case 3 almost certainly is: no Sanskrit word by itself can end in घ् . It would require a reduction to another consonant.

Case 1 seems also to be an error. The fem. of पति is पत्नी (MacDonell, A Sanskrit Grammar for Students, §99).

Case 2 deserves more consideration. The error could be in the information “mfn” even if it is improbable. One must see how the word is used in the context. I was unable to find the passage. Perhaps it is used there as an adverb (“ind.”), in which case  अन्तः-स्तोम-भागम् would be justified.

Case 4 is a very good catch! Yes, it seems to be an error. I found no exception to the rules for the formation of the fem. of present parasmaispada participles that would justify the form लोलन्ति. 

A beginner’s question: Will the eventual corrections of those errors be incorporated to the digital edition? In this case, wouldn’t it be a good idea to preserve both readings, adding at the same time some distinctive mark?

**Comment by zaaf2** [comment]
Hi Jim, 

Those are very interesting observations. 

As far as I can see, they are typographical errors. 

Case 3 almost certainly is: no Sanskrit word by itself can end in घ् . It would require a reduction to another consonant.

Case 1 seems also to be an error. The fem. of पति is पत्नी (MacDonell, A Sanskrit Grammar for Students, §99).

Case 2 deserves more consideration. Even if it is improbable, the error could be in the information “mfn”. One must see how the word is used in the context. I was unable to find the passage. Perhaps it is used there as an adverb (“ind.”), in which case  अन्तः-स्तोम-भागम् would be justified.

Case 4 is a very good catch! Yes, it seems to be an error. I found no exception to the rules for the formation of the fem. of present participles that would justify the form लोलन्ति. 

A beginner’s question: Will the eventual corrections of those errors be incorporated to the digital edition? In this case, wouldn’t it be a good idea to preserve both readings, adding at the same time some distinctive mark?

Thank you for the invitation. 
It is good to be here.

**Comment by funderburkjim** [comment]
@zaaf2  Thanks for comments.  I think I'll go ahead with the changes as suggested, since you provide a confirmation.

Re `wouldn’t it be a good idea to preserve both readings?`  It would be a good idea, but there is 
technically no provision for this in the way the dictionaries (MW in this case) are set up.  However, in cases like these where we are on purpose deviating from the print edition,  there is `for MW` a file (corrections_factual.txt) which contains such cases.   Currently, this file is in the MWS repository of the sanskrit-lexicon project here at GitHub; here is current version of [corrections_factual.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/corrections-factual.txt).  

So, when these changes get fully incorporated into the digital edition, part of the incorporation process will be to update corrections-factual.txt.

**Comment by zaaf2** [comment]
As I went through the file corrections_factual.txt I found the observation I once made about पर (case 100). But this is not a factual error. It is a scanning error; and, as I observe, it is still there. In the printed edition the n. begins at line 116030.1 [remotest distance MBh.] and goes without interruption until line 116038 [existence (regarded as the common property of all things) W.]. There is no change of gender in between. This means that the neuter applies to the entire interval. 
In the digital edition however the entries from L=116031 to L=116034 appear wrongly as f., when they are n.

**Comment by gasyoun** [comment]
Greetings, @zaaf2 it's good to see you around.

**Comment by funderburkjim** [comment]
Case 5 Dartf  (Note: this is slp1 spelling)  [scan](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=510)

(H2) धर्तृ॑ [p= 510] : m. bearer, supporter RV.  AV.  [L=99897]
m. &c (f. °तॄ॑ VS.  TS. ) [L=99898]

The scan clearly shows feminine ending in 'F' (long vocalic 'r') (which MW version of IAST spells as
 `t-<r-dot><i-macron-accent>`.  However I think the dot under the r is wrong, and that the
feminine is **`t-r-<i-macron-accent>`**.   The reasons are
* trI  is common for ending of feminine stem for nominals ending in vocalic r ('f' in slp1)
* in MW72, the feminine shows as trI.

**Comment by funderburkjim** [comment]
@zaaf2  Regarding `no Sanskrit word by itself can end in घ् `:

* Would you remind me of the letters in which Sanskrit words may end ?
* In doing an advanced search for MW headwords ending in 'G', the only non-verb is ASiraduG - this observation further justifies the conclusion that the spelling should have been ASiraduGa.

**Comment by zaaf2** [comment]
I was wrong. The rule applies to words in a sentence before a pause, but not to how they appear in the dictionary. It would be true if the words were given in the nominative. For example: सरघ् f., nom. sg.: सरट्, राघ् m., nom.: राक् 

“The rules of Sandhi are only applicable after the final consonant of a word has been reduced to one of the eight allowable (actually occurring) consonants at the end of a word in pausā, viz: क् ट् त् प् ङ् न् म् and ः (Visarga)” (MacDonnell 27)

But I think this rule still applies to detect an error in आशिरदुघ्, because when the last consonant of a word is not one of the above, the MW dictionary points to its nominative case (always, generally?). I think also that the exceptions apply to verbal roots when used as a noun (राघ्) or to compounds ending in verbal roots, as सरघ् seems to be (< स-√रघ् ?). As for आशिरदुघ् , there is no verbal root दुघ् (‘to milk’ is दुह्), while दुघ means: “mfn. milking, yielding (ifc.)”, exactly what is required here ("milking for a mixture with सोम").

But all these are mere conjectures. I think it does not help at all. --- Conclusion - I am uncertain too.

**Comment by funderburkjim** [comment]
@zaaf2 re 'G' -- Thanks, your explanation helps clarify.  I think I'll leave this one unchanged, for now.  Maybe @drdhaval2785 or @Shalu411  (who know Sanskrit much better than do I) may provide further insight.

**Comment by funderburkjim** [comment]
case 6 harimIqe  [scan](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=1290)

" I praise hari " (or °qe-stotra) n. N. of a hymn.

* I added harimIqe-stotra, n. as a headword
* The placement of the gender 'n.' suggests that the headword 'harimIqe' can be declined.  However, it seems to me to be a verb phrase  (Iqe is present tense 1s of Iq).  From this 
I reason that it should not be declined.  Also, I am not sure how to decline a word ending in 'e' as
a n. (or m. or f., for that matter).   Thus I am changing the markup of harimIqe so that it will not
be recognized as declineable.
This decision can be reversed, if experts provide arguments requiring it.

**Comment by zaaf2** [comment]
Cases 5 and 6: I can only agree with your observations.

**Comment by Shalu411** [comment]
Namaste
I apologize for silence so long. 
[For the benefit of next ones whoever would check- I insert the snip here for each case-]
Case-1 - पतिनी > पत्नी  
Confirm. पतिनी to be found nowhere I searched.
![ayuspatini](https://cloud.githubusercontent.com/assets/6392207/10103940/7693c59e-63c4-11e5-9663-897aa92e0498.JPG)

Case 2 ..--भागम् > --भाग
@funderburkjim is right. 
It should be either without "m" in the end, or without "mfn" - Either way it seems fine.
![stomabhaga](https://cloud.githubusercontent.com/assets/6392207/10104130/7ffdf95a-63c5-11e5-87f0-9159ba13cc6b.JPG)


Case 3 - दुघ् > दुघ 
Apte gives this- दुघ a. (At the end of comp). Milking, yielding, granting, as in कामदुघ
दुघ् is altogether missing in 2 dictionaries I checked. Do not think any such word exists. There can only be दुघ। 
दुघ¦ त्रि० दाग्धि--दुह--क हस्य घः ।
![asiradugh](https://cloud.githubusercontent.com/assets/6392207/10104212/09eb753e-63c6-11e5-9a96-9befa58dd3de.JPG)

```I am still uncertain that we should change ASiraduG headword to ASiraduGa.```
It can happily be changed. I am sure because of its meaning (=milking).

Case 4 लोलन्ती - is right. (ati) > (antI)
@funderburkjim is right. 

Case 5 धर्तृ (is in fact base form of धर्ता) has its feminine form as धर्त्री.. So may be dot below "r" (ृ) was mistake. "-trI" would make sense instead. Again @funderburkjim is right.
![dhartr](https://cloud.githubusercontent.com/assets/6392207/10106110/64a4694a-63d0-11e5-9ac6-4e234dd6cc0a.JPG)

Case 6
हरिमीडे-स्तोत्रम् happens to be here- Just googled the name-
 http://sanskritdocuments.org/doc_vishhnu/harimIDestotra.html?lang=en
Again @funderburkjim is right. The argument is quite true. हरिमीडे-स्तोत्र can be a base word- but not just हरिमीडे.
![harimide](https://cloud.githubusercontent.com/assets/6392207/10106519/d3fa4222-63d2-11e5-989c-224fa2e13cf7.JPG)

Hope this helps. Will try to be in touch. 
Namaste

**Comment by funderburkjim** [comment]
Case  7: bahuvelam [scan](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=1331)

mfn. oftentimes, Pañcad. 

Case 8: antaHstomaBAgam [scan](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=1312)

mfn. within the bricks called stoma-BAgA, ṠBr. 

In both of these cases, I think  'mfn' should be changed to 'ind'.   Both of these occur within the
supplement part of the dictionary.  The senses of each is adverbial, and both are marked as adverbs in PW, which is the only other of the Cologne dictionaries in which they appear.  I speculate that they were added to the supplement of MW by copying from PW, and that the copyist erroneously put the mfn (Adjective) designation.   Both changes will be mentioned in the factual corrections file.

**Comment by gasyoun** [comment]
Your speculations are correct.

**Comment by funderburkjim** [comment]
@gasyoun  Thanks for confirm.

@Shalu411 Thanks for looking at them.  Based on your confirmation, I'll add the 'a' to ASiraduG to 
make it ASiraduGa -- this is the one that @zaaf2  and I were uncertain about.

**Comment by funderburkjim** [comment]
Case 8: sAhebrAm

m. N. of the author of the kASmIra-rAja-vaMSa (died before 1883) Cat. 

![image](https://cloud.githubusercontent.com/assets/6393033/10114992/272fc908-63c9-11e5-8575-8cf9dda56436.png)

I am going to mark this with the tag `<loan/>` --- the only impact of this is as a warning that 
constructing a declension table for this is not appropriate.   The reason is that I think it is actually
a Hindi word.   This [link](http://koausa.org/Personality/SahebRamKaul.html) seems to have information about this 19th century figure  (@gasyoun Note the reference to a work by Buhler).

Incidentally, there is only one (other) word in MW marked as `<loan/>`: sArisTAKA, again a proper name.

**Comment by funderburkjim** [comment]
@zaaf2  Regarding the errors under `para`.  I agree with you, and am glad you looked at the corrections_factual.txt file.  This looks like I was just confused.  At the present time, here is where 
there need to be changes:

f. N. of a river MBh.  VP.  (v.l. पारा, वेणा, वेण्णा) [L=116029]    OK
f. of a goddess (cf. s.v.) [L=116030]  OOK 
(H1B) प॑र : n. remotest distance MBh.  [L=116030.1]  OK

```
(H1B) प॑रा : f. highest point or degree ib. [L=116031]   WRONG.  Should be para, n.
f. final beatitude L.  (also -तरम् and परात् पर-तरम्) [L=116032]   WRONG.  Should be para, n.
f. the number 10 ,000 ,000 ,000 (as the full age of ब्रह्मा) VP.  [L=116033]   WRONG.  Should be para, n.
f. N. of partic. सामन्s Kāṭh.  [L=116034]   WRONG.  Should be para, n.
```

(H1B) प॑र : n. any chief matter or paramount object (ifc. [f(आ).] having as the chief object, given up to, occupied with, engrossed in, intent upon, resting on, consisting of, serving for, synonymous with &c MBh.  Kāv.  &c ) [L=116035]   OK

I'm making the changes to L= 116031, 2, 3, 4 now,  and will also remove the comment from the corrections_factual.txt file, since the underlying problem is in the nature of a typo, not a problem with the print edition.

**Comment by Shalu411** [comment]
Welcome @funderburkjim . Fine. 
Regarding case 7 and 8, what you plan to do is OK. 
I think issues settled here? Or should I look into that "corrections_factual.txt file," too? Please let me know.

**Comment by gasyoun** [comment]
Bühler indeed. I'm reprinting a book of his in October. There should be at least some 50 words marked as `loan` in MW, but that is another story. @Shalu411 can we mark it as a Hindi word? Looking into that "corrections_factual.txt" file too would make you lost for a few weeks, so I guess no need.

**Comment by Shalu411** [comment]
@gasyoun 
``` can we mark it as a Hindi word?``` 
You mean sAhebrAm.. right? But if the book he authored belongs to Samskrt literature, he has every right to stay in Samskrt Dictionary by Samskrt status. If we mark it Hindi, is there any special purpose that will be served, instead of marking it as <loan/> as @funderburkjim proposes?

**Comment by gasyoun** [comment]
Samskrtam dictionaries contain many loanwords. We need to mark them right. They will remain there. It's not just @funderburkjim proposes - Huet, or @drdhaval2785 if they will continue to play with generation of grammar, they'll find in useful one day as well.

**Comment by funderburkjim** [comment]
@Shalu411   No need to look into that corrections_factual file,  unless just for fun :smile:

**Comment by funderburkjim** [comment]
Am marking 'humAuM'  (Emperor Humayun) as `<loan/>`  (Probably from Persian).

Regarding marking sahebrAm as Hindi (instead of the more generic `<loan/>`):   I think I'll stick to 
`<loan/>` for now.  A more refined markup would require more discernment than I have now.  

@gasyoun  '50+ loan words in MW':  Interesting.  I have no idea how to identify, except just when
we stumble over one.  If we had them all, it might be the subject of an interesting research article.

**Comment by gasyoun** [comment]
`<loan/>` is enough.

**Comment by funderburkjim** [comment]
The corrections have been made to MW.

Also, [corrections-factual.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/corrections-factual.txt) has been updated.

**Comment by gasyoun** [comment]
Some of the quoted instanced are Vedic and not Sanskrit. Hope @Shalu411 is right, but I'll keep an eye on them. Otherwise closed.

**Comment by Shalu411** [comment]
``` No need to look into that corrections_factual file, unless just for fun :smile:```
Namaste
Sure. OK. Then I will not. Thanks. :)
