### ISSUE TITLE
o_vs_O - diff highlight, columns expanded

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#135]
@funderburkjim and @zaaf2 ,

As per request of @gasyoun - 
I have done these two changes and uploaded the file to drdhaval2785@github.io/o_vs_O/output1 folder.
1. Difference in the SLP1 format of both the words are highlighted. 
2. The word columns are longer now, and the link columns are shorter to stop word curtailments.
![capture](https://cloud.githubusercontent.com/assets/5755132/10863304/b66171c6-7fee-11e5-9bf4-d399c486a32c.png)

P.S. - Earlier the link columns were shorter only, but someone asked to elongate them so that they can click the dictionaries far away. But as we have decided that we would be concentrating on only the 'highest probability' ones, the columns would have not many dictionaries to click. So, rolling back to the good old one.

**Comment by gasyoun** [comment]
First of all let me thank you. It's well done, as usual and quick. More than that - on time.
1. highlighting sample, par_Avah_	pa_RavaH_
