### ISSUE TITLE
`o` vs `O` Corrections in PWG, Part 2

### ISSUE THREAD

**Issue by zaaf2** [sanskrit-lexicon/CORRECTIONS#137]
#130 continued. 
Checking the divergences detected by the o_vs_O method of highest probability (one dictionary in first word and more dictionaries in second word), as applied to PWG, at the file http://drdhaval2785.github.io/o_vs_O/output1/PWG.html.

**Comment by zaaf2** [comment]
`103.` रराठ्य → रराट्य
OCR error.
![image](https://cloud.githubusercontent.com/assets/14730665/10916892/a29063e6-823c-11e5-8383-ed3155bfe3a4.png)
 
MW: 
रराट [p= 868] : n. = ललाट, the forehead, brow
रराटी : f. id. BhP.  [L=175290]

`104.` राजशूक ― राजशुक MW,PW,SHS,WIL,YAT
Typographical error in the PWG printed edition. Only शुक gives the appropriate sense.
PW `*राजशुक [L=93533] [p= 5181-1]	 m.  eine Papageienart mit rothen Streifen an Hals und Flügeln  Râǵan.19,113.`
PWG: `शुक [L=100072] [p= 7-0235] … — a) Papagei`
MW: 
`राज-शुक [p= 874] : m. a kind of parrot (with red stripes on the neck and wings) L.  [L=176675]`
`शुक [p= 1079] : m. (prob. fr. √1. शुच्, and orig. " the bright one ") a parrot RV.  &c [L=218749]`
`शूक [p= 1085] : mn. (g. अर्धर्चा*दि ; derivation doubtful) the awn of grain; mn. a bristle, spicule, spike (esp. the bristle or sharp hair of insects &c ) W.  [L=220137]`
`शूका : f. scruple, doubt L. (…) f. the sting of an insect (cf. above ) , anything that stings or causes pain Suṡr.  Car.  [L=220145]; (…)`

`105.` वाङ्घ् ― वङ्घ् (→वाङ्क्ष्)
OCR error, different words, change to वाङ्क्ष्
![image](https://cloud.githubusercontent.com/assets/14730665/10916901/ae9c2cd8-823c-11e5-9765-5b6f8365ef58.png)
 
PWG: वाङ्घ् [L=89427] [p= 6-0886]	वाङ्क्षति (काङ्क्षायाम्)  Dhâtup. 17, 17.  — Vgl. काङ्क्ष् und वाञ्छ्.
MW: 
वङ्घ् cl.1 A1. वङ्घते, to go; to set out; to move swiftly; to blame or censure Dhātup.  iv, 36.
वाङ्क्ष् [p= 936] : (connected with √ वाञ्च्क् cf. काङ्क्ष्) cl.1 P. वाङ्क्षति, to wish, desire, long for Dhātup.  xvii, 17. [L=189801]

`106.` वार्वरक ― वर्वरक
No change. Different, connected words. A variant of बार्बरक
PWG: वार्वरक [L=90415] [p= 6-0951], (बार्बरक)  adj.  von वर्वर (बर्बर) gaṇa धूमादि zu  P. 4, 2, 127.
MW:
वर्वरक [p= 926] : m. (more correct बर्ब्°) N. of a man Mudr.  [L=187836]
बार्बरक [p= 728] : mfn. (fr. बर्बर) g. धूमा*दि. [L=144434]

**Comment by gasyoun** [comment]
No change words will be included in No change list. I guess it's time we start to collect them in a new TXT file, what do you say @drdhaval2785 ?

**Comment by drdhaval2785** [comment]
Ask @funderburkjim. In earlier exercises where I was an active member for
correction finding, we mentioned the OK lists at the end of issues. Jim may
have stored or may retrieve from Github issues. It would be a good method
to note OK words at the end of the issues handled so far.
we can keep them in whitelist and not display them in next dictionaries

**Comment by zaaf2** [comment]
`107.` शक्राग्नी ― शक्राग्नि
No change. The form with -ī is the correct dual of m. words in -i. The form with -ĭ is mentioned “im comp.”
![image](https://cloud.githubusercontent.com/assets/14730665/10946497/4b2c21a6-8301-11e5-91af-f760c0618f16.png)
शक्राग्नि [p= 1045] : m. du. इन्द्र and अग्नि (lords of the नक्षत्र विशाखा) VarBṛS.  [L=211134]

`108.` शरिका ― शणिका 
No change. Different words.
PWG: शरिका [L=98150] [p= 7-0097]	 f.  N. eines Palastes  Schiefner, Lebensb. 305 (75).
MW: शणिका [p= 1048] : f. Crotolaria of various species L.  [L=211796]

`109` शुनकचञ्चूका ― शुनकचञ्चुका SKD,VCP
Insufficient elements to reach a conclusion. 
It is the name of a plant. Both PWG and SKD are referring to the same source. According to PW, it is a manuscript:
![image](https://cloud.githubusercontent.com/assets/14730665/10946506/5736f2a0-8301-11e5-9809-d43583fc997c.png)
चञ्चु f. and चञ्चू f. are variants in the sense “a beak, bill” (MW).
PWG शुनकचञ्चूका [L=100357] [p= 7-0258]	 f.  ein best. Strauch, = क्षुद्रचञ्चु  Râǵan. im Çkdr.
SKD शुनकचञ्चुका, स्त्री, (शुनकस्य चञ्चरिव । इवार्थे कन् ।) क्षुद्रचञ्चुक्षुपः । इति राजनिर्घण्टः ॥
MW: 
* क्षुद्र-चञ्चु [p= 330] : f. " having small points ", N. of a plant L.  [L=59926]
* चञ्चु (…) m. the castor-oil plant L.; (…) m. the plant गो-नाडीक (or नाडीच) L.; (…) m. the plant क्षुद्रचञ्चु; f. a beak, bill VarBṛS.  Pañcat.  Hit.  [L=70802]. 
* चञ्चू [p= 382] : f. a beak, bill Vop.  iv, 31 [L=70822]
* चञ्चूक [p= 382] : m. = °ञ्चु-पत्त्र Bhpr.  [L=70825] ; m. pl. N. of a people (south-west of मध्य-देश) VarBṛS.  xiv, 18. [L=70825.1]

`110.` षडस्र ― षडश्र
No change. A wrong reading, according to MW.
![image](https://cloud.githubusercontent.com/assets/14730665/10946510/64883ee6-8301-11e5-9969-3ef340e5b66f.png)
MW: षड्-अश्र [p= 1109] : (Cat. ) mfn. hexagonal (w.r. -अस्र &c ) [L=225117] 

`111. ` संधनाजित् → संधनजित् 
Typographical error in the PWG printed text.
There is no धना; आजित् is unexemplified.  √जि is frequently used with धन.
![image](https://cloud.githubusercontent.com/assets/14730665/10946519/70bbf7f2-8301-11e5-836e-ac76349c7092.png)
MW: 
 सं-धन-जित् [p= 1144] : mfn. (= धनसं-जित्) winning booty together, accumulating booty by conquest AV.  [L=231582]
* जित् a [p= 420] : mfn. ifc. (Pāṇ.  3-2, 61) winning, acquiring cf. गो- and स्वर्-जित्, स्वर्ग- &c [L=79195]; (…)
* जि 1 [p= 420] : (…) to win or acquire (by conquest or in gambling) (…)
* धन [p= 508] : n. the prize of a contest or the contest itself (lit. a running match, race, or the thing raced for ; हितं धा*नम्, a proposed prize or contest ; धनं- √जि, to win the prize or the fight).
* धन-जित् [p= 508] : mfn. winning a prize or booty, victorious, wealth-acquiring RV.  AV.  VS.  [L=99285].
* धनंजय  (…) N. of अर्जुन MBh.  Hariv.  
* आ- √जि 2 [p= 133] : √ जि (p. -जयत् ; impf. 3. du. आ*जयताम्) to conquer, win RV.  ii, 27, 15 AitBr.  TāṇḍyaBr.  : Desid. p. -जिगीषमाण, trying or desiring to win RV.  i, 163, 7. [L=23128]
आजि-तुर् [p= 133] : mfn. victorious in battles RV.  viii, 53, 6. [L=23119]

`112.` समुद्ररसन ― समुद्ररशन
No change. Variant form.
PWG: समुद्ररसन [L=105923] [p= 7-0729]	 adj.  (f. आ) meerumgürtet: die Erde  Ragh. 15, 83. Varâh. Bṛh. S. 43, 32. f.  आ die Erde  H. 938, Schol.
MW: सम्-उद्र-रशन [p= 1167] : mf(आ)n. (**also written -रस्°**) sea-girdled (said of the earth) Hariv.  Ragh.  VarBṛS.  [L=235294]

**Comment by gasyoun** [comment]
I'm afraid documenting in such detail takes more time than needed. Guess half would be 2 more than needed, @zaaf2 You are too good!

**Comment by zaaf2** [comment]
`113.` सांकुची ― सांकुचि
No change. PWG gives the f. 
PWG: सांकुची [L=108029] [p= 7-0896] **f.**  = संकोचमत्स्य  Çabdar. im Çkdr.  शां° und शंकोच° gedr.
MW: सांकुचि [p= 1198] : m**f(°ची)**. (perhaps fr. सं-कुच, but cf. शङ्कुचि) a partic. aquatic animal Bhpr.  [L=241201]

`114.` सारमीति ― सारमिति
Factual error. The ī does not seem justified (But it is better to get a second opinion).
 
![image](https://cloud.githubusercontent.com/assets/14730665/11021858/de3434aa-862d-11e5-9619-7c1e21877858.png)

MW: सार-मिति [p= 1208] : m. " measure of all truth ", N. of the वेद L.  [L=242908]
In MW मिति comes under √मि. ― °ति is a primary suffix forming f. action nouns.
मिति 2 [p= 816] : f. (for 1. » [p= 815,3]) measuring, measure, weight. VarBṛS.  ṠārṅgS.  [L=164144]; f. accurate knowledge, evidence MāṇḍUp.  [L=164145]
मि 1 [p= 815] : (cf. √3. मा and मी) cl.5. P. A1. (Dhātup.  xxvii, 4) मिनोति, मिनुते (...), to fix or fasten in the earth, set up, found, build, construct RV.  AV.  ṠBr.  ṠrS.   ; to mete out, measure VarBṛS.; (…)
PW: मि — 1) in den Boden einsenken , befestigen ; gründen , aufrichten ; errichten , bauen ; construiren  Çulbas.1,41.  — 2) messen. — 3) ermessen , erkennen , wahrnehmen. (...)
[Cf. मी 1 (…) to lessen, diminish, destroy (A. and Pass. to perish, disappear, die) RV.  AV.  Br.  Up.  BhP. ― मी 2 [p= 818] : » मन्यु-मी. ― मी 3 [p= 818] : cl.1.10. P. मयति or माययति, to go, move Dhātup.  xxxiv, 18  ; to understand]
MW: सार 2 (…) mn. the substance or essence or marrow or cream or heart or essential part of anything, best part, quintessence; (…) mn. the real meaning, main point MW.

According to PWG and PW the meaning attributed to this word is the result of a misunderstanding, explained at Hemachandra’s [Abhidhana Chintamani (1964 ed.)]( http://dli.serc.iisc.ernet.in:8080/handle/2015/430244), 248, but I could not find the passage. If I am not mistaken the etymology quoted by PWG सारं यथार्थं मीयते ज्ञायते ऽनेन could be translated as: “The essence [सारम् i.e. the real thing] is truly measured [and] known through this [Veda]”.

**Comment by zaaf2** [comment]
`115.` सिद्धान्तलक्षणाक्रोड ― सिद्धान्तलक्षणक्रोड
Insufficient elements to reach a conclusion. (Cf. #130 case `46.`  लक्षणवादरहस्य ― लक्षणावादरहस्य)
 
MW: सिद्धा*न्त-लक्षण-क्रोड [p= 1216] : m. N. of wk. [L=244606]
MW:
`` लक्षण [p= 892] : mfn. indicating, expressing indirectly Vedântas.  [L=180381] (…); n. (ifc. f(आ).) a mark, sign, symbol, token, characteristic, attribute, quality (…); n. a lucky mark, favourable sign (…); n. accurate description, definition, illustration (…)``
`` लक्षणा b [p= 892] : f. aiming at, aim, object, view Hariv.  [L=180434]; f. indication, elliptical expression, use of a word for another word with a cognate meaning (as of " head " for " intellect "), indirect or figurative sense of a word (…)``

**Comment by zaaf2** [comment]
`116.` अजिनपत्री ← अजीनपत्री
Print error in SKD.  
 
There is no अजीन. 
MW: 
अजिन n. the hairy skin of an antelope, especially a black antelope (which serves the religious student for a couch seat, covering &c )
पत्त्र a [p= 581] : n. (and m. Ṡāk.  ; ifc. f(आ and ई). )(sometimes spelt पत्र) the wing of a bird, pinion, feather VS.  ṠBr.  &c [L=114848]

The word is out of Devanagari order in SKD:
![image](https://cloud.githubusercontent.com/assets/14730665/11028315/211aad30-869c-11e5-9216-b666a93f3cba.png)

**Comment by zaaf2** [comment]
@funderburkjim Since the cases from `116.` to `182` are about “One dictionary in first word and one dictionary in second word”, one has to decide whether they should be worked here or directly from the lists in which the other dictionaries are the first. For example case `142.` (PWG मधुकरि x MW मधुकारी):  will @gasyoun  deal with it as he works the MW list? Has he dealt with it already?

**Comment by drdhaval2785** [comment]
Treat the first dictionary only.
Ignore the second dictionary. It would be the first in its own place.
This is how the HTMLs were generated.

e.g. PWG maDukari - MW maDukArI
Concentrate on PWG only.

Those who intend to cover MW e.g. @gasyoun would handle it in MW, where it would be the first dictionary.

NOTE - Till date we are concentrating only on 'Highest probability' ones only. If @zaaf2 ventures into the second slot of 'Medium probability' it would be great. Sooner or later, we would have to deal them. But in my opinion, it should wait till we exhaust 'Highest probability' of all dictionaries. Then we take up the 'Medium' of all.

**Comment by gasyoun** [comment]
@drdhaval2785 what you tell does not makes sense. It made sense a year ago, if there would be only 1 person working and even than partly. I wanted to comment in detail, but let me do it later than never. If working with PWG @zaaf2 finds a MW error and ignores it - it does not makes sense. The very way he works is documenting everything and reinventing the wheel does not sounds great. When working quickly, 5 times quicker than I and 10 times quicker than @zaaf2 (because he is too good!) - I agree, ignore everything and run. But we are slower, much slower. So benefiting each other does not hurt at all.

**Comment by drdhaval2785** [comment]
@gasyoun 
If you intend to take up the matter in one go,
the current format of Dictionarywise errors would not be productive.
http://drdhaval2785.github.io/o_vs_O/output3/composite1.html (highest)
http://drdhaval2785.github.io/o_vs_O/output3/composite2.html (medium)
http://drdhaval2785.github.io/o_vs_O/output3/composite3.html (lowest)

They are composite files.
Linking and decoration would take some time.

This would ensure that we are going one by one, ignoring the dictionary to be corrected.

**Comment by drdhaval2785** [comment]
This would also reduce the burden, and make sure we are not handling the same word again and again in different dictionaries.

**Comment by gasyoun** [comment]
Good work. 3800 high, 1100 medium, 14000 low - low is far too big. Give me longer words first. No need to have them ordered alphabetically.

**Comment by gasyoun** [comment]
5	73888	citraSAkApUpaBakzyavikArakriyA <-citraSAkapUpaBakzyavikArakriyA
PW, PWG print error.

In PW print text चित्रशाकापूपभक्षविकारक्रिया is used instead of the wrong  चित्रशाकपूपभक्ष्यविकारक्रिया.

![citrasakapupabakzyavikarakriya](https://cloud.githubusercontent.com/assets/80761/11103849/266efe44-88d6-11e5-9188-29f385bd688b.PNG)

![citrasakapupabakzyavikarakriya2](https://cloud.githubusercontent.com/assets/80761/11103869/66a2eea8-88d6-11e5-9b37-6c24c39a3ca5.PNG)

**Comment by zaaf2** [comment]
5 73888 citraSAkApUpaBakzyavikArakriyA ― citraSAkapUpaBakzyavikArakriyA

No change. Alternative forms.

PWG & PW give an alternative form, as is clear from the entry’s text. 
 
![image](https://cloud.githubusercontent.com/assets/14730665/11113021/cb0161c4-88f7-11e5-9e94-8c6525ecdd99.png)

PWG:
![image](https://cloud.githubusercontent.com/assets/14730665/11113024/d0b9cf34-88f7-11e5-9c5b-7064f37051e2.png)

PW:
![image](https://cloud.githubusercontent.com/assets/14730665/11113141/05315c90-88f9-11e5-9282-d5a279660242.png)

MW:
* भक्ष [p= 742] : m. drinking or eating, drink or (in later language) food RV.  &c &c (often ifc., with f(आ)., having anything for food or beverage, eating, drinking, living upon) [L=147535]
* (H3) भक्ष्य [p= 742] : mfn. to be eaten, eatable, fit for food (…); n. anything eaten, food  (…)
* शाक 2 [p= 1061] : n. (…) a potherb, vegetable, greens GṛṠrS.  Mn.  MBh.  &c [L=214666]
* पूप [p= 641] : m. a cake, a sort of bread MBh.  R.  &c (cf. अपूप).
* अपूप [p= 56] : m. (cf. पूप), cake of flour, meal, &c RV.  &c

**Comment by zaaf2** [comment]
I consider my mission accomplished. Now it's up to @funderburkjim to review and install changes.

**Comment by gasyoun** [comment]
Let there be Jim.

**Comment by funderburkjim** [comment]
Re '107. शक्राग्नी ― शक्राग्नि'   

This is interesting when one contemplates using the PWG lexicon as a source for generating declension tables.   For such a purpose, the given headword form 'SakrAgnI'  is NOT the stem, but rather the short-i form 'SakrAgni'.   

This phenomenon of dual-form as the citation form was encountered in MW.  There, we (Peter and Chandrashekar mostly) developed a list of such forms, and used that list in deriving the 'lexical grammar' for nominal forms. [See DualPlural.txt](https://github.com/funderburkjim/MWlexnorm/blob/master/step0/DualPlural.txt).

**Comment by funderburkjim** [comment]
@zaaf2  re '116. अजिनपत्री ← अजीनपत्री  Print error in SKD.'   

There IS an ajIna in PD:
अजीन¦ (a-jīna) adj. not subject to old age or decay अजिनमिति चर्म 
अजीनमिति ज्यानिहीनम् TattvBi. 21. 8; Bhām. 355. 9 (on ii. 1. 14)
 
This was discovered from [hwnorm1](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/hwnorm/hwnorm1.php).

Thus, I would demur, and be disinclined to changed SKD.

**Comment by funderburkjim** [comment]
Here are the harvested changes:
```
103. रराठ्य -> रराट्य : typo
104. राजशूक -> राजशुक : print error
105. वाङ्घ् -> वाङ्क्ष् : typo
111. संधनाजित् -> संधनजित् : print error
114. सारमीति -> सारमिति : print error
```
@zaaf2  might check the list and be sure I've not made mistakes.

Will now go about installation.

**Comment by funderburkjim** [comment]
Corrections installed.  Can revise if @zaaf2  finds mistakes in processing.
Also closing issue.
