### ISSUE TITLE
'o vs O' corrections, BEN

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#140]
This issue examines the 'high probability entries' in http://drdhaval2785.github.io/o_vs_O/output2/BEN.html. 
In toto 24 entries, which would be dealt with in single issue

**Comment by drdhaval2785** [comment]
615	apanama -> apagama

It is illegible.
But the preceding entry is 'apakvatA' and succeeding entry is 'apagarjita'.
And the explanation has `apa-gam + a, m. 1. Going
away, `

![capture](https://cloud.githubusercontent.com/assets/5755132/10988876/7bc4f4c6-8466-11e5-88b3-3d17994d789e.png)

**Comment by drdhaval2785** [comment]
779	aBimada ->	aBimarda

Illegible repha.

![Uploading capture.png…]()

**Comment by drdhaval2785** [comment]
2031	uttamaRa ->	uttamarRa
Illegible scan

![capture](https://cloud.githubusercontent.com/assets/5755132/10988918/f423de1e-8466-11e5-901d-7482f01526d6.png)

**Comment by drdhaval2785** [comment]
2348	upaSanti	-> upaSAnti
OCR error

![capture](https://cloud.githubusercontent.com/assets/5755132/10988939/198783c2-8467-11e5-8fc8-2b2a7f1d5411.png)

**Comment by drdhaval2785** [comment]
2495	urjaskara	-> Urjaskara
Print Error

It is in 'U' headwords.
See

![capture](https://cloud.githubusercontent.com/assets/5755132/10988956/462a6e62-8467-11e5-8a62-5d844d2e84e8.png)

**Comment by drdhaval2785** [comment]
2499	UrRamaya	UrRAmaya
NO CHANGE

See the entry UrRa - it says that it means wool and UrRA is feminine.
So they are alternative words for the same meaning.
![capture](https://cloud.githubusercontent.com/assets/5755132/10988967/80f6888c-8467-11e5-806d-caa6d1f0be5f.png)

**Comment by drdhaval2785** [comment]
2986	karuRaveditA	karuRAveditA
NO CHANGE

Reasoning the same as above.

![capture](https://cloud.githubusercontent.com/assets/5755132/10988976/a3a77832-8467-11e5-83db-3dafd085b825.png)

**Comment by drdhaval2785** [comment]
3028	karttari	karttarI
NO CHANGE

Alternate words
![capture](https://cloud.githubusercontent.com/assets/5755132/10988993/c4c4fb48-8467-11e5-9d5f-071ed6dd4d69.png)

**Comment by drdhaval2785** [comment]
8989	purIzaDAna	purIzADAna
Not Sure.

BEN
![capture](https://cloud.githubusercontent.com/assets/5755132/10989011/027a4920-8468-11e5-8995-1160872cc562.png)

MW
![capture](https://cloud.githubusercontent.com/assets/5755132/10989016/10ce68c6-8468-11e5-8c2a-8e3e8dbe168e.png)

Maybe @zaaf2 would have to see in the referred texts and help us in this matter. He is too good when it comes to checking in the sources.

**Comment by drdhaval2785** [comment]
11144	mAYjizwika ->	mAYjizWika
OCR Error

![capture](https://cloud.githubusercontent.com/assets/5755132/10989037/44a6b504-8468-11e5-91e3-8a2190ceed52.png)

**Comment by drdhaval2785** [comment]
11283	mAsuri	mAsurI
Not Sure.

Only BEN gives mAsuri.
All other dicts have mAsurI for 'beard'.
As it is feminine, I am inclined towards the correction. But @zaaf2 would have to review this.

![capture](https://cloud.githubusercontent.com/assets/5755132/10989060/96048318-8468-11e5-92e7-18aab185f855.png)

**Comment by drdhaval2785** [comment]
12442	limpaka	-> limpAka
Print Error

BEN is the only dict giving limpaka for lime tree. All others give limpAka for lime tree.

The English version besides gives 'A'. 
![capture](https://cloud.githubusercontent.com/assets/5755132/10989093/16716818-8469-11e5-8db0-50cd99a843db.png)

**Comment by drdhaval2785** [comment]
14104	vEragika ->	vErAgika
OCR Error

![capture](https://cloud.githubusercontent.com/assets/5755132/10989112/4119d802-8469-11e5-83bf-f48c68522d8a.png)

**Comment by drdhaval2785** [comment]
14324	vratIna	-> vrAtIna
Lexicographer Error

He has taken the word as vratIna, whereas the justified usage is only vrAtIna.

MW has the following entry
![capture](https://cloud.githubusercontent.com/assets/5755132/10989245/ef841992-846a-11e5-8f82-7a1093991281.png)

When I checked AS with [kAzikAvRtti](http://sanskritdocuments.org/learning_tools/ashtadhyayi/vyakhya/5/5.2.21.htm)
It shows
![capture](https://cloud.githubusercontent.com/assets/5755132/10989261/181aa600-846b-11e5-9c40-dd165225cad6.png)

**Comment by drdhaval2785** [comment]
15776	saMbaDana ->	sambADana
OCR Error

![capture](https://cloud.githubusercontent.com/assets/5755132/10989282/63199a80-846b-11e5-8a0f-b5c97e8f2a13.png)

**Comment by drdhaval2785** [comment]
17196	hfdayaviD	hfdayAviD
NO CHANGE

hfdaya+viD and hfdaya+A+viD both justifiable grammatically with 'A' upasarga.

The scan has hfdayaviD undoubtably. So let's keep both

**Comment by drdhaval2785** [comment]
4718	Gil -> GiRR
OCR Error

![capture](https://cloud.githubusercontent.com/assets/5755132/10989326/e2f2c448-846b-11e5-9ea4-3543ef5c9cae.png)

**Comment by drdhaval2785** [comment]
7078	Dfka	-> Dfk
OCR Error

![capture](https://cloud.githubusercontent.com/assets/5755132/10989339/2041c7a4-846c-11e5-9e30-4417703c15d9.png)

**Comment by drdhaval2785** [comment]
6849	drORAyAna	-> drORAyani
Poor print quality.

![capture](https://cloud.githubusercontent.com/assets/5755132/10989351/52868402-846c-11e5-883d-b9a230c89c54.png)

**Comment by drdhaval2785** [comment]
10810	macarCikA	-> macarcikA
Lexicographer error

AP has
![capture](https://cloud.githubusercontent.com/assets/5755132/10989433/2f42c1a8-846d-11e5-9eed-f614cdeb405c.png)

When I searched Siddhantakaumudi for this quote, I landed [here](http://sanskritdocuments.org/learning_tools/ashtadhyayi/vyakhya/2/2.1.65.htm)
![capture](https://cloud.githubusercontent.com/assets/5755132/10989442/52f451b6-846d-11e5-9933-7b5c5d9268ca.png)

**Comment by drdhaval2785** [comment]
14662	SAstravant	Sastravant
NO CHANGE

SAstra and Sastra both are valid words.

**Comment by drdhaval2785** [comment]
This ends the correction submission for 24 high probability words from BEN.

Time for @zaaf2 to fill in the blanks and @funderburkjim to install.

The choice of BEN was a bit random (trying to handle smaller ones).

**Comment by zaaf2** [comment]
re. `8989.` purIzaDAna → purIzADAna
Typographical error in BEN. The upper part of the `a` in question was not reproduced by an error in the printing process. Probably by the same cause the macron sign is missing.  The component parts confirm the form purIzADAna:
MW:
पुरीष (…) n. feces, excrement (…)
आ-धान [p= 138] : n. putting near or upon, depositing, placing (…); n. the place in which anything is deposited or rests ṠBr.  [L=24112]

**Comment by gasyoun** [comment]
@zaaf2 the Sanskrit bookkeeper :8ball:

**Comment by zaaf2** [comment]
11283 mAsuri → mAsurI 
Factual error.
PWG: मासुरी [L=60288] [p= 5-0760] f.  Bart  H. 583.
The source quoted is 
 
![image](https://cloud.githubusercontent.com/assets/14730665/10999136/19caadd4-8479-11e5-8792-1e080abcf48b.png)

The index to this [work (1964 ed.)]( http://dli.serc.iisc.ernet.in:8080/handle/2015/430244) confirms the form मासुरी (PDF pag. 491):
![image](https://cloud.githubusercontent.com/assets/14730665/10999194/76a82e6e-8479-11e5-847b-3a3cbfc1dfc3.png)

**Comment by zaaf2** [comment]
re. `8989.` purIzaDAna ― purIzADAna

I am not so sure any more.  The Devanagari in BEN has ă. The component parts could be:
पुरीष (…) n. feces, excrement (…)
धान [p= 514] : mfn. containing, holding (cf. उद-) [L=100750] ; n. receptacle, case, seat (cf. अग्नि-, क्षुर-, रज्जु- &c ; °नम् अक्तोस् prob. = womb or bosom of the night RV.  iii, 7, 6) [L=100751].
No change. Insufficient elements to reach a conclusion.

**Comment by zaaf2** [comment]
re. `8989.` purIzaDAna → purIzADAna
Factual error in BEN. 
Now I am sure. The source quoted, the [Yājñavalkya Smṛti]( http://dli.serc.iisc.ernet.in:8080/handle/2015/408048) 3.94, confirms the reading  purIzADAna (PDF pag. 897):
![image](https://cloud.githubusercontent.com/assets/14730665/11000311/bd0dc692-847f-11e5-9e8c-651c07b76a8c.png)

**Comment by zaaf2** [comment]
@gasyoun :smile:

**Comment by gasyoun** [comment]
@zaaf2 you're just too good.

**Comment by zaaf2** [comment]
@drdhaval2785 I have reviewed the other cases and I agree with your conclusions.

**Comment by gasyoun** [comment]
@drdhaval2785, smaller ones:
* http://drdhaval2785.github.io/o_vs_O/output2/MD.html - 17
* http://drdhaval2785.github.io/o_vs_O/output2/STC.html - 70

**Comment by funderburkjim** [comment]
These corrections now installed at Cologne for Benfey.

**Comment by funderburkjim** [comment]
@drdhaval2785   I used the Suggestion at #154 and based my code on your prototype at @157.

I made a few changes.  Here's a good way for you to follow along:
**step1** Make a local version of the Cologne environment .
* in /c/xampp/htdocs/cologne,  rename 'ben' directory, to something else, if such a 'ben' directory exists.
* make a GitBash script named ben_init.sh as follows, and run it:
```
mkdir ben
cd ben
echo "downloading benweb1.zip  ..."
curl -o benweb1.zip http://s3.amazonaws.com/sanskrit-lexicon/web1/benweb1.zip
unzip benweb1.zip
echo "downloading ben_pywork.zip ..."
curl -o ben_pywork.zip http://s3.amazonaws.com/sanskrit-lexicon/blobs/ben_pywork.zip
unzip ben_pywork.zip
echo "downloading ben_orig.zip ..."
curl -o ben_orig.zip http://s3.amazonaws.com/sanskrit-lexicon/blobs/ben_orig.zip
unzip ben_orig.zip
echo "You need to add a folder with sqlite3.exe to the 'path' variable"
echo "of the system environment variables"
echo "This is required to run, pywork/redo_xml.sh"
```

**step2** in the ben/pywork/correctionwork/issue-140 directory:
* readme.txt shows all the steps I took.  Pay special attention to the steps 1 and 2.  Your system
   won't be set up to follow along all the subsequent steps (Note that these steps have already
   been done, but you can redo them without harm. the redo_xml.sh script assumes you have
   added sqlite to your PATH environment variable as described in a [comment](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/143#issuecomment-154753765) to #143.
* readme-dhaval.txt   I made some comments showing how I adapted your code.

**Comment by gasyoun** [comment]
In 2016 I should spend time exploring GitBash, so we have a backup of Dhaval as well.

**Comment by funderburkjim** [comment]
@gasyoun  The more people who know how things work, the merrier!
