### ISSUE TITLE
Links gone bad - MW abbrev

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#141]
http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/sqlite/mwauth_deva.html#record_Gan2ar_

When I clicked on preface pages links, it gave 404 errors.

**Comment by gasyoun** [comment]
Did not find a link.

**Comment by funderburkjim** [comment]
@drdhaval2785  When I click on above link, it works fine.

![image](https://cloud.githubusercontent.com/assets/6393033/11017202/e300e74e-8565-11e5-8f10-db8d13336c4b.png)


Don't understand problem.

**Comment by drdhaval2785** [comment]
The problem is not in the link to ganaratnamahodadhi. Once the abbrv list
opens up, there is a description that they are in preface page number blah
blah. Blah blah is hyperlinked, but gives 404 error.

Exact text is
"
This information is based primarily on the lists presented on pages xxxiii
and xxxiv of the preface to the dictionary.
"

**Comment by gasyoun** [comment]
http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/sqlite/mw010005.jpg is not working, now I got it.

**Comment by funderburkjim** [comment]
Problem now solved.  

Note: You may need to reload the [link](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/sqlite/mwauth_deva.html#record_Gan2ar_)  so browser won't use cached version.
