### ISSUE TITLE
Misclosed brackets in pw.xml

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#145]
https://github.com/sanskrit-lexicon/PWK/issues/12 needs a mention here too as it is a correction in XML.

**Comment by funderburkjim** [comment]
A batch of about 310 corrections to literary sources was installed. See https://github.com/sanskrit-lexicon/PWK/issues/12 for further comments.

I think this takes care of all the misclosed brackets in pw.xml, so am closing this issue.
