### ISSUE TITLE
PW abbreviations

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#147]
Current status -
https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/pw_dhaval has created the following output file
https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/pw_dhaval/abbrvwork/sortedcrefs.txt

It needs to be manually checked and corrected.
There are many errors and inconsistencies found.

Right now there is no prescribed format for submitting corrections to the `<ls>` tags.

@funderburkjim may fecilitate us by creating some utility and guide us in which file should we make the changes and how?

**Comment by drdhaval2785** [comment]
Issue 2 - The file is not readable by humans.
```
BA7LR
BA7PAR
BA7RG4AN
BA7T2J
BA7TAR
BA7UAR
BAGH
BAHDH
BAHT2T2
```
Too many artificial numbers there. 
Jim may like to give us file in some format which all of us can understand.

**Comment by gasyoun** [comment]
All I can say the list needs to be:
1) ordered in .XLS for ease of sorting
2) unicode, let's write a Jim-converter, I'll help
3) include chapter reference at least for stats, but actually I myself have used it to locate the Russian translation of a needed passage based on the German reference, so I would not cut off those numbers totally anyway.
My January PW abbreviation research:

Spr.  (II) 2255 -> Spr.  (II) 	2255
R.  GORR.  IV, 526. -> R.  GORR.  	IV, 526. 

>Yourn.  of the Am.  Or.  S.  7, 43. < -> Journ.
>Yourn.  of the Am.  Or.  S.  7, 44. <
>Yourn.  of the Am.  Or.  S.  7, 45, 3 v.  u. <
>Yourn.  of the Am.  Or.  S.  7, 5, Śl.  9. <
>Yourn.  of the Am.  Or.  S.  7, 7, Śl.  19.  23. <
>YONES in As.  Res.  II, 159.  fgg. <

>YĀJŃ.  1, 342. <
>YAJŃ.  1, 342< -> YĀJŃ. 
>YĀJŃ.  1, 343. <

Four different ways for same person
>WEST. <
>WESTER GAARD und BOPP. < -> WESTERGAARD
>WESTERG.  in DHĀTUP.  21, 22. <
>WESTERGAARD). <

**Comment by funderburkjim** [comment]
Re 'The file is not readable by humans.'

The coding is the Anglicized-Sanskrit type  (AS).  

You could make it readable by humans by converting it to IAST (roman).

This could be done by using transcoder.py.  [Here](https://gist.github.com/funderburkjim/0419bbfec48565847080) is a sample program.

The sample is converting a file with lines like
```
1. अपराःणक -> अपराह्णक : typo
```
to a file with lines like
```
1. aparAHRaka -> aparAhRaka : typo
```

In your case, you might convert a file with lines like:
```
BA7RG4AN
```
to a file with lines like
```
BA7RG4AN Bârǵan
NOTE 1: Bârǵan is the way that the PW display shows this.  In the pw/web/webtc/disp.php, 
the code first lower cases BA7RG4AN  to ba7rg4an, then upcases the first letter to Ba7rg4an,
then applies the as_roman transcoding, to end up with Bârǵan .
NOTE 2: I suggest that you keep track of the original coding, at least for now.  The reason is that
I think it *might* be needed later, when disp.php is revised to make use of the abbreviation expansions.
```

You can get the transcoder.py module from the [sanskrit-transcoding](https://github.com/funderburkjim/sanskrit-transcoding) repository.

You will be transcoding from 'as' (the PW variant) to 'roman' (IAST).  
This will require the 'as_roman.xml' file in pw/web/utilities/transcoder/.

@drdhaval2785  You've asked me to look at several other things you've discovered.  
My aim is to get to those requests tomorrow.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Conversion to IAST successful.
Would upload soon.

**Comment by gasyoun** [comment]
@drdhaval2785 eagerly waiting.

**Comment by drdhaval2785** [comment]
Right now trying to preserve the L numbers and key1 and key2 along with the literary resources so that they can be linked to the images and dictionary displays like 'o_vs_O' output2 folder displays.
That would help us process the error submissions.

**Comment by drdhaval2785** [comment]
@gasyoun 
How do you find http://drdhaval2785.github.io/pw/abbrv/display.html ?
Any suggestions or feedback?

![capture](https://cloud.githubusercontent.com/assets/5755132/11058678/6f247fbe-87ba-11e5-8f3b-930f46fce07f.png)

SrNo. Lno. IAST AS Key1 Key2 count

The first links to webpage.
The second links to PDF page.

**Comment by funderburkjim** [comment]
Moved https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/pw_dhaval  to 
https://github.com/sanskrit-lexicon/PWK/tree/master/pw_ls/pw_dhaval.

**Comment by drdhaval2785** [comment]
Shifted to other repository.
Closing the issue.
Correction submission is in separate thread.
