### ISSUE TITLE
'o vs O' corrections, MD

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#148]
I examine here the high probability words from http://drdhaval2785.github.io/o_vs_O/output2/MD.html.
Will tackle in one go.

**Comment by drdhaval2785** [comment]
4451	utsukaya	utsukAya
No change

Causative verb form

**Comment by drdhaval2785** [comment]
4973	uhya ->	Uhya
Lexicographer error.

uhya is grammatically unjustifiable.
वाह ऊठ्‌
http://sanskritdocuments.org/learning_tools/sarvanisutrani/6.4.132.htm

**Comment by drdhaval2785** [comment]
7040	gus	Gus
NO CHANGE

Compound part
गुस् [L=7040] [p= 085-2]
गुस् g-us, V. 3 pl. aor. √ gâ, go.

**Comment by drdhaval2785** [comment]
8953	tve	tvE
NO CHANGE

Different words
first vedic tvam, second a nipAta

**Comment by drdhaval2785** [comment]
11149	parakfta	parAkfta
NO CHANGE

**Comment by drdhaval2785** [comment]
11339	parzi	pArzI
NO CHANGE

A verb form
![capture](https://cloud.githubusercontent.com/assets/5755132/11020201/fcb91796-863d-11e5-899b-b9569f04fdd3.png)

**Comment by drdhaval2785** [comment]
14533	mokzaya	mokzAya
NO CHANGE

Different convention for verbs in curAdi gaRa

**Comment by drdhaval2785** [comment]
16024	varDaya	varDAya
NO CHANGE

Different convention for verbs in curAdi

**Comment by drdhaval2785** [comment]
18118	Se	SE
NO CHANGE

A suffix
![capture](https://cloud.githubusercontent.com/assets/5755132/11020208/3d25ee76-863e-11e5-829f-a542e8ca9dae.png)

**Comment by drdhaval2785** [comment]
18532	saMgawa	saMGawa
NO CHANGE

Different word.
![capture](https://cloud.githubusercontent.com/assets/5755132/11020210/639c57f2-863e-11e5-94a2-7190b55332c2.png)

**Comment by drdhaval2785** [comment]
4151	inDi	indi
NO CHANGE

Verb root
![capture](https://cloud.githubusercontent.com/assets/5755132/11020211/80252606-863e-11e5-8892-68e9f3ec8c83.png)

**Comment by drdhaval2785** [comment]
10728	niSvAsita	niSvasita
NO CHANGE

Both forms justifiable grammatically

**Comment by drdhaval2785** [comment]
20725	parAyatI	parAyati
NO CHANGE

![capture](https://cloud.githubusercontent.com/assets/5755132/11020218/bea8bb86-863e-11e5-890d-021708535bd8.png)

It is in addenda corrigenda

**Comment by drdhaval2785** [comment]
11841	pUraya	puraya
NO CHANGE

Different convention for curAdi verbs

**Comment by drdhaval2785** [comment]
13151	BAtvakzAs ->	BAtvakzas
Print Error

All other dicts have BAtvakzas.
Even the MD English reading has BAtvakzas.
![capture](https://cloud.githubusercontent.com/assets/5755132/11020235/07128d3e-863f-11e5-8cf6-4f22effe338f.png)

**Comment by drdhaval2785** [comment]
14566	mOjAvata ->	mOjavata
Lexicographer error

See MW
![capture](https://cloud.githubusercontent.com/assets/5755132/11020267/9c474eda-863f-11e5-80fe-46d0987fb6b5.png)

Searching the source led me to 

http://www.sacred-texts.com/hin/rvsan/rv10034.htm

परावेपा मा बर्हतो मादयन्ति परवातेजा इरिणे वर्व्र्तानाः |
सोमस्येव मौजवतस्य भक्षो विभीदको जाग्र्विर्मह्यमछान || 

http://www.sacred-texts.com/hin/rvsan/rv10034.htm says मौजवत

**Comment by drdhaval2785** [comment]
This ends the small dictionary correction submissions

**Comment by gasyoun** [comment]
Thanks for the small, but quick catch. :neckbeard:

**Comment by zaaf2** [comment]
4451 utsukaya utsukAya
A denominative (or nominal) verb, from उत्सुक (mfn. restless, uneasy, unquiet, anxious). According to MacDonell (A Sanskrit Grammar for Students, 175), a final -अ is often lengthened before the denominative suffix °य, but sometimes become ई. MW quotes a Pāṇini rule in which the denominative example given is a denominative verb with ā: `भृशाय [p= 766] : Nom. A1. °यते, to become powerful or strong or vehement.`, from: `भृश [p= 765] : mfn. (…) strong, vehement, mighty, powerful`.  All this indicates that MW is probably correct, but without further proofs a change is not justified.


7040 gus Gus
OCR error in GRA and in STC: घुस् → घुष्

![image](https://cloud.githubusercontent.com/assets/14730665/11040589/e42643f8-86eb-11e5-921b-0400500b3587.png)

![image](https://cloud.githubusercontent.com/assets/14730665/11040594/e7ffb306-86eb-11e5-86d1-24e075900b48.png)

I reviewed the other cases and agree with @drdhaval2785's conclusions.

**Comment by zaaf2** [comment]
Confirming 13151 BAtvakzAs -> BAtvakzas
[RV i, 143, 3]( http://www.sanskritweb.net/rigveda/rv01-137.pdf):
![image](https://cloud.githubusercontent.com/assets/14730665/11040879/481c285e-86ed-11e5-8cd5-10baa9db2b90.png)

**Comment by gasyoun** [comment]
@drdhaval2785 The out of sorting order pecularities - can we catch them? Or there are 5-6 sorting variations and to fine tune the algorythm would take longer than the fruits it could bring?

**Comment by funderburkjim** [comment]
@zaaf2   I added the Gus -> Guz corrections for GRA, STC via the Correction Form.  They will get installed in due course, but not immediately.

**Comment by funderburkjim** [comment]
Installation done (3 errors).

[corrections_nochange.txt] (https://gist.github.com/funderburkjim/31056c8e340d8c9cbc12)  updated.
Note: Following discussion at #153 ?, format changed slightly. The issue number (148 in this case) is inserted as the 2nd field, for example:
```
md:148:utsukaya:utsukAya:Causative verb form
```

Comment:  With the improvements to generate, and the detailed commenting of the process, this installation step is now definitely improved.  Thanks for suggestions and code.

**Comment by drdhaval2785** [comment]
Great.
It has a lot of information indeed.
Time to close the issue.
