### ISSUE TITLE
'o vs O' corrections, STC part 1

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#149]
http://drdhaval2785.github.io/o_vs_O/output2/STC.html high probability words examined.
As there are 70 words there, I propose to take up them in two batches of 35 words.

**Comment by drdhaval2785** [comment]
2119	antaS	antas
No change

Compound forms of 'antar'.

**Comment by drdhaval2785** [comment]
2802	aBikaNkz	-> aBikANkz
Ocr error

![capture](https://cloud.githubusercontent.com/assets/5755132/11020283/46f70d84-8640-11e5-87e8-715e0b12f193.png)

**Comment by drdhaval2785** [comment]
2879	aBitf	-> aBitF
ocr error

![capture](https://cloud.githubusercontent.com/assets/5755132/11020289/63757ef0-8640-11e5-849d-de5e2d6d7dbf.png)

**Comment by drdhaval2785** [comment]
4915	AkaNkz ->	AkANkz
print error

![capture](https://cloud.githubusercontent.com/assets/5755132/11020295/8fc8fbda-8640-11e5-9f37-3cfeff0a8d9f.png)

**Comment by drdhaval2785** [comment]
5729	ASyA	AsyA
no change

Different verb convention
![capture](https://cloud.githubusercontent.com/assets/5755132/11020297/b3a0024c-8640-11e5-80ab-f4b25a1c53a4.png)

**Comment by drdhaval2785** [comment]
5861	AhuH	AhUH
no change

Valid verb form

**Comment by drdhaval2785** [comment]
6024	ucCaS	ucCAs
no change

Different words
![capture](https://cloud.githubusercontent.com/assets/5755132/11020302/13ecfa56-8641-11e5-9e66-95e875c4e655.png)

Not seen such word before, but seems correct.

**Comment by drdhaval2785** [comment]
6024	ucCaS	ucCAs
no change

Difficult scan.
![capture](https://cloud.githubusercontent.com/assets/5755132/11020308/4b811038-8641-11e5-84d8-0251766557d4.png)

**Comment by drdhaval2785** [comment]
8253	ke	kE
no change

Valid form.

**Comment by drdhaval2785** [comment]
9057	caYcarika -> caYcarIka
Print error
Maybe lexicographer error also

VCP says that suffix is 'Ikan'. So no scope for 'ika'.
![capture](https://cloud.githubusercontent.com/assets/5755132/11020348/0447afe0-8643-11e5-82c2-a1385518b73e.png)

This फर्फरीकादि search led me to उणादिसूत्रs.
Siddhantakaumudi's उणादि reads
![capture](https://cloud.githubusercontent.com/assets/5755132/11020359/70ded03e-8643-11e5-8690-b43c39d1e6d7.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11020361/823a96e2-8643-11e5-8532-90c2a8a54194.png)

**Comment by drdhaval2785** [comment]
9263	cirayati	cirAyati
no change

valid word

**Comment by drdhaval2785** [comment]
9464	jatukarRIputra	jAtUkarRIputra
no change

A search for Malatimadhava referred by PWG led me [here](https://books.google.co.in/books?id=MrdFAQAAIAAJ&q=%E0%A4%9C%E0%A4%A4%E0%A5%81%E0%A4%95%E0%A4%B0%E0%A5%8D%E0%A4%A3%E0%A5%80&dq=%E0%A4%9C%E0%A4%A4%E0%A5%81%E0%A4%95%E0%A4%B0%E0%A5%8D%E0%A4%A3%E0%A5%80&hl=en&sa=X&ved=0CBwQ6AEwAGoVChMI762A1-yAyQIVyweOCh2UHwsT).
![capture](https://cloud.githubusercontent.com/assets/5755132/11020378/4dfa6eba-8644-11e5-904a-429c840529b8.png)

**Comment by drdhaval2785** [comment]
9716	jyezWya	jyEzWya
Not sure

Further examination needed.

**Comment by drdhaval2785** [comment]
9764	wAtkAra	WAtkAra
no change

Different words

**Comment by drdhaval2785** [comment]
9824	tatya	tAtya
no change

order says that this is a proper word.

**Comment by drdhaval2785** [comment]
9870	tapasvi	tapasvI
no change

compound iic

**Comment by drdhaval2785** [comment]
10999	dyavidyavi	dyavidyavI
not sure

Insufficient material to reach conclusion.

VCP refers to निरुक्तम्‌.
I don't have niruktam. Maybe @zaaf2 may shed some light on it. 
![capture](https://cloud.githubusercontent.com/assets/5755132/11020481/358f7094-8646-11e5-8fb2-960853beaa43.png)

**Comment by drdhaval2785** [comment]
11149	DarziRi	DarziRI
no change

![capture](https://cloud.githubusercontent.com/assets/5755132/11020496/67e801fa-8646-11e5-9849-ec1e589616a3.png)

**Comment by drdhaval2785** [comment]
11220	Dunvant	DUnvant
no change

Lexicographer intended them to be alternatives maybe.

![capture](https://cloud.githubusercontent.com/assets/5755132/11020502/8a717972-8646-11e5-9d59-fa60bb76f61a.png)

**Comment by drdhaval2785** [comment]
11841	nirAkaNkza	-> nirAkANkza
print error
lexicographer error

There is general confusion in this dictionary regarding 'kANkza'. At least 3 such occurrences already noted.

**Comment by drdhaval2785** [comment]
12817	paRAyati	parAyati
no change

different words

**Comment by drdhaval2785** [comment]
12965	parikzI	pArikzi
no change

different words

**Comment by drdhaval2785** [comment]
14469	pratipraS	pratiprAS
not sure.

Maybe `pratipraSn` is what the lexicographer may have in mind.
google translate says that the meaning is 'ask something to somebody'.

Some speaker of the dictionary language may help

**Comment by drdhaval2785** [comment]
15072	prapiq ->	prapIq
print error

See the description prapIqita
![capture](https://cloud.githubusercontent.com/assets/5755132/11020535/7ded75ce-8647-11e5-82b0-37e86f2cc17b.png)

**Comment by drdhaval2785** [comment]
15373	praS	pras
no change

Different words

**Comment by drdhaval2785** [comment]
15887	balluka	-> Balluka

Meaning translation has
![capture](https://cloud.githubusercontent.com/assets/5755132/11020776/b5183dbe-8650-11e5-89ec-eab471f488e1.png)

**Comment by drdhaval2785** [comment]
17997	valmi ->	vallI
print error

![capture](https://cloud.githubusercontent.com/assets/5755132/11020791/67a37a98-8651-11e5-9267-11ba5bf1f6b6.png)

Author intended it to be 'valli' as an alternative of 'vallI'.

**Comment by drdhaval2785** [comment]
18893	vihARa ->	vibARa
smudged print

![capture](https://cloud.githubusercontent.com/assets/5755132/11020793/a2a65368-8651-11e5-8a1a-4bdb2b4bece2.png)

**Comment by drdhaval2785** [comment]
21285	sanadIgirikanana	-> sanadIgirikAnana
print error

kAnana is proper word for forest, not kanana.
![capture](https://cloud.githubusercontent.com/assets/5755132/11020798/c94e2298-8651-11e5-92ec-de9952a77f5d.png)

**Comment by drdhaval2785** [comment]
22223	saMpraRud	sampraruD
no change

False positive

**Comment by drdhaval2785** [comment]
22266	saMpradru	samprAdru
no change

samprAdru is found in MW. MW also has sampradru too.

Both grammatically valid.

**Comment by drdhaval2785** [comment]
22326	saMprasad	samprasAD
no change

Different words.
Both grammatically valid

**Comment by drdhaval2785** [comment]
22796	sAnaTya ->	sAnATya
print error

MW has 
![capture](https://cloud.githubusercontent.com/assets/5755132/11020827/a79609a8-8652-11e5-99a5-0d65a5bfaa0f.png)

Thus it is derived from sanATa. Therefore, there is no rule for converting 'nA' to 'na'.

sAnaTya is grammatically not viable.

**Comment by drdhaval2785** [comment]
23321	sunita ->	sunIta

Digital version has
![capture](https://cloud.githubusercontent.com/assets/5755132/11020835/f3af74f0-8652-11e5-9111-05fb3efc3c83.png)

Whereas the scan has
![capture](https://cloud.githubusercontent.com/assets/5755132/11020837/08cc33aa-8653-11e5-9d8f-8b0026b93804.png)

**Comment by drdhaval2785** [comment]
This ends submission of 35 corrections in part 1.

**Comment by zaaf2** [comment]
After reviewing, I disagree only in this case:
 17997 valmi vallI
I am not sure it is a print error. The author records a wrong reading, which may well be valmi. The Devanagari order seems to confirm this.
![image](https://cloud.githubusercontent.com/assets/14730665/11071162/01dbb360-87be-11e5-914e-de6e6cdb0057.png)

Some observations about the other cases:

5729 ASyA AsyA
Different words (not different verb convention).
ā-ÇYĀ- moy. se dessécher ; °çyāna- desséché, séché ; solidifié.

आस्या a [p= 159] : f. sitting Suṡr.  [L=27872]
आस्या b [p= 162] : f. » √2. आस्. [L=28240]
आ- √श्यै [p= 158] : A1. -श्यायते, to become dry, dry up, shrink in drying Ragh.
आ-श्यान [p= 158] : mfn. dried up, shrunk in drying Ragh.  Kum.  [L=27614]

9057 caYcarika -> caYcarIka
I think it is a lexicographical error. The author probably conceived the ending as the suffix -ika, with the redoubled root चर्
Cf. MW:
चञ्चरिन् [p= 382] : m. (fr. Intens. √चर्) a bee Udbh.  [L=70773]
चञ्चरी [p= 382] : f. (fr. Intens. √चर्) a bee Udbh.  [L=70773.1]
― चञ्चरीक [p= 382] : m. id. [i.e. = चञ्चरी] Bālar.  v, 30 Prasannar.  Dhūrtan.  &c [L=70774]

9263 cirayati cirAyati
Although MW has चिराय (denominative verb), AP90 confirms @drdhaval2785's  conclusion:
AP90:
![image](https://cloud.githubusercontent.com/assets/14730665/11071106/d79e1fde-87bd-11e5-9100-761c26cb397d.png)
 
MW: चिराय b [p= 399] : Nom. P. A1. (p. °यमाण) id. MBh.  &c [L=74332]

9716 jyezWya jyEzWya
An alternative form? Some words formed with the secondary suffix are °य don’t have vṛddhi-strengthening (Whitney, Sanskrit Grammar, 1211). In a Google search I found many instances of ज्येष्ठ्य, but I didn’t check if their sources are authoritative.
STC: jyeṣṭhya- nt. aînesse.
MW: ज्येष्ठता [p= 427] : f. precedence, seniority, primogeniture Mn.  MBh.  iii, 14461 Hariv.  7164. [L=80583]
― ज्यैष्ठ्य [p= 427] : n. = ज्येष्ठता RV.  VS.  &c [L=80637]
PWG: ज्यैष्ठ्य [L=27977] [p= 3-0159]: (von ज्येष्ठ)  n.  principatus, Vorrang, erste Stelle, Obergewalt; Erstgeburtsrecht.

9764 wAtkAra WAtkAra
The same word. Variant forms?
STC:
ṭāt-kāra- m. = ṭaṃ°.
ṭaṃ° iic. onom. °kāra- m. °kṛta- nt. °kāra-rava- m. déclic, boum ! patatras ! bruit, cri.
MW:
ठात्-कार [p= 430] : m. = टां-क्° Bālar.  iii. [L=81318] 
टां-कार [p= 429] : m. = टं-क्° Bālar.  i, 46 and 49 Rājat.  v, 422. [L=81231]
टं-कार [p= 429] : m. (onomat. ; cf. टां-क्°) howling, howl, cry, sound, clang, twang Kād.  BhP.  iii, 17, 9 Uttarar.  Rājat.  v, 417 Sāh.  [L=81199]; m. notoriety L.  [L=81200]; m. surprise L.  [L=81201]

10999 dyavidyavi dyavidyavI
dyavi-dyavi is correct. Different words.
dyavi-dyavi adv. tous les jours, chaque jour.
It is confirmed by MW: 
`द्यु a [p= 478] : m. (rarely n.) day (esp. in pl. and in such forms as दिवा), by day (cf. s.v.) [L=92231.1]; m. द्यवि-द्यवि, daily, every day [L=92231.2]`
 (द्यवि is the locative sg. of द्यु)
AP90: द्यविद्यवी [L=15748] [p= 0583-b] f. A day.

11220 Dunvant DUnvant
Whitney Roots confirms that धु- is an acceptable alternative form.
![image](https://cloud.githubusercontent.com/assets/14730665/11071092/c762bbd4-87bd-11e5-9530-a6edba9cb56e.png)

14469 pratipraS pratiprAS
Lexicographer error (?). The STC author considered प्रश् to be the correct form of the root प्रछ् 
STC: प्रतिप्रश् prati-PRAÇ- demander qqch. à qq'un (2 acc.).
![image](https://cloud.githubusercontent.com/assets/14730665/11071085/bc5fa792-87bd-11e5-9426-597a12d45723.png)
 
![image](https://cloud.githubusercontent.com/assets/14730665/11071088/bff71f34-87bd-11e5-8fef-50b1e163b4fc.png)

  

MW: प्रति- √प्रछ् [p= 667] : P. -पृच्छति, to ask, question, inquire of (2 acc.)


15373 praS pras
For प्रश्, see observation above (case 14469)

15887 balluka -> Balluka
A lexicographer error.

**Comment by funderburkjim** [comment]
These are instances where I made some interpretation.  @drdhaval2785  and @zaaf2  should
check.

* re `4915 AkaNkz -> AkANkz` - changed to OCR error
* re '11149 DarziRi DarziRI'  - changed to print error.  Feminine form of Darzin has long 'I' ending.  IAST form in STC also shows the long I.
* re  `11220 Dunvant DUnvant` - agree no change. MW also has Dunvat.
* `14469 pratipraS pratiprAS` no change.  STC uses 'praS' for 'praC'
* `17997 valmi vallI` no change. Author cites a wrong reading
* `23321 sunita -> sunIta` typo

**Comment by gasyoun** [comment]
@parjanya do you agree?

**Comment by funderburkjim** [comment]
Will install along with #150 .

**Comment by funderburkjim** [comment]
Corrections installed.  Also [corrections_nochange.txt](stc:150:svas:svAs:
stc:150:ADam:Adam:
stc:150:AstF:Astf:alternate spellings
stc:150:IzuH:izuH:different words. IzuH is inflected verb form of iz
stc:150:upAnud:upanud:different words
stc:150:upasTi:upasti:different words. Usual word is upasTa
stc:150:UhuH:uhUH:valid form of 'vAh'
stc:150:kzIrAyati:kzIrayati:
stc:150:CIwa:ciwa:
stc:150:dfzwIviza:dfzwiviza:alternate forms, acc. to STC.
stc:150:DUnayati:Dunayati:different denominative verbs
stc:150:nAnAndf:nanandf:alternate spellings
stc:150:nirmATa:nirmaTa:Different words, same etymology (< √मथ्).
stc:150:nizWIv:nizWiv:verb conventions
stc:150:parikzI:parikzi:verb conventions
stc:150:paristF:paristf:alternate spellings
stc:150:prakzI:prakzi:verb conventions
stc:150:praDam:pradam:Different verbs.
stc:150:BuzuRqI:BuzuRqi:Both are wrong reading for BuSuRqi (PW)
stc:150:vidAy:viday:Both valid words.
stc:150:vistF:vistf:stF - stf are alternate verbs.
stc:150:saMkzI:saMkzi:verb conventions.
stc:150:samAstF:samAstf:Verb conventions.
stc:150:samunnAsa:samunnasa:Both words seem valid.
stc:150:saMpF:sampf:different verbs
stc:150:saMpraruD:sampraRud:False positive.
stc:150:saMpraTita:sampratIta:False positive.
stc:150:saMmUrC:sammurC:Both forms grammatically possible.
stc:150:sopAra:sopara:alternate spellings
) updated.

**Comment by zaaf2** [comment]
@funderburkjim re '11149 DarziRi DarziRI'

After the change we have:

STC: dharṣiṇī- -ī- f. femme impudente, impudique.

This makes no sense, for it only repeats the same form of the headword, whereas the printed text clearly refers to alternate forms. Whether this is correct or not is another question; perhaps it is a lexicographer’s mistake, a confusion with the alternate forms धर्षणी and धर्षणि `f. a wanton or unchaste woman, a harlot` (MW). 
Observe that the STC always puts a hyphen after the headword’s last vowel, so that the second *-ī-* here refers to the last vowel of an alternate form, not to the first *i* of dharṣiṇī. There is no dharṣīṇī (nor *m.* dharṣīn). 
The same notation we find, for example, under: 
* STC: patnī- f. (-i-) épouse (du maître de maison, du sacrificateur). 
* Cf. MW: पत्नि [p= 582] : for पत्नी » above. [L=115103]

To make the STC more useful, I propose that both searches for DarziRI and DarziRi lead to the STC entry for DarziRi.

**Comment by funderburkjim** [comment]
@zaaf2   I thought that 'DarziRi' was  a print error, since this is the locative singular of Darzin.  Unless
there isjustification for believing that 'DarziRi' can be a variant feminine stem (nom. sing.).

Note that MW has Darz**a**RI and Darz**a**Ri  as feminines of DarzaRa, and with the same meaning as our STC word.  But Darz**a**Ri doesn't justify Darz**i**Ri, does it?

![image](https://cloud.githubusercontent.com/assets/6393033/11355650/98e4652a-9224-11e5-8a64-1dd9889e8575.png)

**Comment by funderburkjim** [comment]
I think this issue can be closed.

@zaaf2  I guess you still think that DarziRi  should be left as headword?

**Comment by zaaf2** [comment]
@funderburkjim I somehow missed your posting on 'DarziRi' seven days ago.  
I am sure 'DarziRi' is a lexicographer mistake, but to correct it simply by changing 'DarziRi' to 'DarziRI' makes the entry inconsistent: `dharṣiṇī- -ī- f. femme impudente, impudique`. One might ask what does `-ī-` mean here. Better to eliminated it: `dharṣiṇī f. femme impudente, impudique`.

**Comment by funderburkjim** [comment]
@zaaf2   Installed your suggestion re removing `-ī-`, which is redundant after the change to `dharṣiṇī `.
