### ISSUE TITLE
svArmODna v/s svAmOrDna

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#15]
Jim -
Re: 28 svArmODna -> svAmOrDna
Did NOT change.
(a) The text appears to have the 'r' over the 'm', not over the 'Dn'
(b) By alphabetical ordering in PW (using list display), we see
svArdra , svArmODna , svAlakzaRa
So, 'svArm...' is correctly placed.

@drdhaval2785 :
Explanation to 28
Please look at the image once again.
I can't read the explanation because of language barrier.
But I can read a sanskrit word -mOrDna at the end of the explanation.
Maybe you should reconsider your view.
The digitization is proper as per print.
But svArmODna is not possible according to grammar.
mOrDna can be derived from mUrDan. So svArmODna is the only legitimate choice.

@funderburkjim :
I agree that -mOrDna is at the end of the explanation.
I don't read German either, but using Google Translate can get an idea of the sense.
verdorben == spoiled (Incidentally, this seems completely unrelated to mUrDan!)
Vielleicht *mOrDna zu lesen == Perhaps *mOrDna to read.
I also see in the scan at the headword, svArmODna, and the alphabetical fact is present.
So, it seems the author is spelling the headword as given : svArmODna; If we had the reference Kath.18,12 that the author had, then we might see this spelling.
However, with the 'Perhaps to read' statement the author is , in effect, agreeing with your analysis of the underlying Sanskrit and saying that maybe it should have been svAmOrDna.
So, I'm still not convinced that the headword should be changed.

**Comment by gasyoun** [comment]
@funderburkjim something like `<corrupt>`.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/130#issuecomment-149190453 and https://github.com/sanskrit-lexicon/CORRECTIONS/issues/133 Deals with the same issue.
So, we can close this long standing issue.
