### ISSUE TITLE
'o vs O' corrections, STC part 2

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#150]
#149 continued

**Comment by drdhaval2785** [comment]
24260	svas	svAs
no change

svas from
अस्ति स्वः स्मः

**Comment by drdhaval2785** [comment]
5187	ADam	Adam
no change

Meaning be inflated, being full (gtranslate)
fits with ADam

**Comment by drdhaval2785** [comment]
5815	AstF	Astf
no change

AP says that both are alternate
![capture](https://cloud.githubusercontent.com/assets/5755132/11021043/1553315c-865b-11e5-9bde-97b949836c7e.png)

**Comment by drdhaval2785** [comment]
5987	IzuH	-> izuH
Not sure, but looks print error.
maybe izuH.

STC itself says that it is some form of 'iz'
![capture](https://cloud.githubusercontent.com/assets/5755132/11021055/8aa92376-865b-11e5-9d1e-c6516159c648.png)

**Comment by drdhaval2785** [comment]
6124	utkUrdAna ->	utkUrdana
ocr error

print smudge
![capture](https://cloud.githubusercontent.com/assets/5755132/11021074/f17c4e20-865b-11e5-9aac-17f552492ed4.png)

**Comment by drdhaval2785** [comment]
7122	upAnud	upanud
no change

both valid forms

**Comment by drdhaval2785** [comment]
7056	upasTi	upasti
no change

genitals. 
Usual word is upasTa, but upasTi may also be somehow allowed.
Ordering says that the expected reading is 'upasTi' and not 'upasTa'
![capture](https://cloud.githubusercontent.com/assets/5755132/11021076/65b05502-865c-11e5-9c93-bd8744dae14e.png)

**Comment by drdhaval2785** [comment]
7301	UhuH	uhUH
no change

valid form of 'vAh'

**Comment by drdhaval2785** [comment]
8205	kUsmARqa ->	kUSmARqa
ocr error

STC has
![capture](https://cloud.githubusercontent.com/assets/5755132/11021099/356a3236-865d-11e5-822d-150af7797bcd.png)

MW has the following
![capture](https://cloud.githubusercontent.com/assets/5755132/11021098/26037b7c-865d-11e5-9bc7-a1b05dfce10d.png)

**Comment by drdhaval2785** [comment]
8511	kzIrAyati	kzIrayati
no change

**Comment by drdhaval2785** [comment]
9418	CIwa	ciwa
no change

False positive

**Comment by drdhaval2785** [comment]
10905	dfzwIviza	-> dfzwiviza
ocr error

![capture](https://cloud.githubusercontent.com/assets/5755132/11021106/8f500118-865d-11e5-9403-6867ab4a9e45.png)

**Comment by drdhaval2785** [comment]
11228	DUnayati	Dunayati
no change

Seems correct.
Not sure. Help @zaaf2 .

![capture](https://cloud.githubusercontent.com/assets/5755132/11021110/c35498b6-865d-11e5-913a-68ef6d227393.png)

**Comment by drdhaval2785** [comment]
11493	nAnAndf	nanandf
no change

See STC itself
![capture](https://cloud.githubusercontent.com/assets/5755132/11021112/e3d33476-865d-11e5-95cb-22f922a1ebae.png)

**Comment by drdhaval2785** [comment]
12067	nirmATa	nirmaTa
not sure

Grammatical derivation has to be looked into.

MW has one nearby entry 'nirmATin'. So I guess 'nirmATa' may be defensible grammatically.

![capture](https://cloud.githubusercontent.com/assets/5755132/11021121/289bd392-865e-11e5-9684-8237556aad3e.png)

**Comment by gasyoun** [comment]
I still think https://github.com/sanskrit-lexicon/CORRECTIONS/issues/136 p.4. would make the productivity higher, see my sample:

![dhavala](https://cloud.githubusercontent.com/assets/80761/11021215/c4a27c54-864b-11e5-8abb-390261585082.PNG)

To check 4 letter words does not make much sense. Agree, Dhaval?

**Comment by drdhaval2785** [comment]
@gasyoun I still think that it is too much of headache for a minor productivity improvement.

**Comment by drdhaval2785** [comment]
12431	nizWIv	nizWiv
no change

verb conventions

**Comment by drdhaval2785** [comment]
12965	parikzI	parikzi
no change

verb conventions

**Comment by drdhaval2785** [comment]
13418	paristF	paristf
no change

as already discussed earlier. AP gives both stF and stf as valid verbs

**Comment by drdhaval2785** [comment]
14136	prakzI	prakzi
no change

verb conventions

**Comment by drdhaval2785** [comment]
15022	praDam	pradam
no change

Different verbs.

**Comment by drdhaval2785** [comment]
15022	praDam	pradAm
no change

Different verbs.

**Comment by drdhaval2785** [comment]
16265	BuzuRqI	BuzuRqi
no change

PW clarifies the situation.
![capture](https://cloud.githubusercontent.com/assets/5755132/11032104/1251799c-86ff-11e5-9801-d13a9d90c4c6.png)

Both are wrong reading for BuSuRqi.

**Comment by drdhaval2785** [comment]
18561	vidAy	viday
no change

Both valid words.

**Comment by drdhaval2785** [comment]
19316	vistF	vistf
no change

stF - stf are alternate verbs.

**Comment by drdhaval2785** [comment]
20517	SOnaHSePa	-> SOnaHSepa
Print error
Also lexicographer error

Because he gives the same reading in explanation also.
![capture](https://cloud.githubusercontent.com/assets/5755132/11032179/ae5abd9e-86ff-11e5-929c-6412931d67fa.png)

There is no entry by the name SunaHSepha in the dictionary.
There is only SunaHSepa.
![capture](https://cloud.githubusercontent.com/assets/5755132/11032170/9edd77e4-86ff-11e5-9d36-c60c4337d865.png)

**Comment by drdhaval2785** [comment]
21064	saMkzI	saMkzi
no change

verb conventions.

**Comment by drdhaval2785** [comment]
21892	samAstF	samAstf
no change

Verb conventions.

**Comment by drdhaval2785** [comment]
22046	samunnAsa	samunnasa
no change

Both words seem valid.
But it requires second opinion of @zaaf2 .

**Comment by drdhaval2785** [comment]
22194	saMpF	sampf
no change

![capture](https://cloud.githubusercontent.com/assets/5755132/11033094/a606bfd8-8706-11e5-9a57-039a941e72f0.png)

There exists a verb पॄ
http://sanskrit.uohyd.ac.in/scl/dhaatupaatha/files-6-9-2014/mA735.html

**Comment by drdhaval2785** [comment]
22303	saMpraruD	sampraRud
no change

False positive.

**Comment by drdhaval2785** [comment]
22257	saMpraTita	sampratIta
no change

False positive.

**Comment by drdhaval2785** [comment]
22427	saMmUrC	sammurC
no change

Both forms grammatically possible.
The first with 'tugAgama' of छे च applied.
The second without 'tugAgama'.
http://sanskritdocuments.org/learning_tools/ashtadhyayi/vyakhya/6/6.1.73.htm

**Comment by drdhaval2785** [comment]
23888	sopAra	sopara
no change

The first is an alternate for sUrpAraka.

PW lists sUrpAraka and refers to it as alternate form of SUrpAraka

The google translation says that the town SUrpAraka is now known as 'sopAra'.

![ca](https://cloud.githubusercontent.com/assets/5755132/11034476/de611558-8711-11e5-9d9f-03ca64265140.png)

Therefore, the STC word sopAra is justified.

**Comment by drdhaval2785** [comment]
24183	syUmaraSmI	-> syUmaraSmi
print error

Seems like there is some mark above 'i' and not 'I'.
![capture](https://cloud.githubusercontent.com/assets/5755132/11034596/c8ee6c2e-8712-11e5-950e-9262bbd02b59.png)

PWG referred to Rigveda 1.112.16
![capture](https://cloud.githubusercontent.com/assets/5755132/11034698/8aafbf98-8713-11e5-9907-1d6833a159a2.png)

The Rig is 
```
याभिर्नरा शयवे याभिरत्रये याभिः पुरा मनवे गातुमीषथुः ।
याभिः शारीराजतं स्यूमरश्मये ताभिरू षु ऊतिभिरश्विना गतम् ॥१६॥
```

स्यूमरश्मये seems probable only in स्यूमरश्मि and not in स्यूमरश्मी.

**Comment by drdhaval2785** [comment]
This ends the correction submission for STC highest probability.
Time for @funderburkjim to install.

**Comment by gasyoun** [comment]
24183 syUmaraSmI -> syUmaraSmi
Some dirt is there.

**Comment by drdhaval2785** [comment]
119017 @ &PAST
NO CHANGE
<hr/>

**Comment by zaaf2** [comment]
5987 IzuH -> izuH
Different words.
IzuH is correct:
MW: इष् 1 [p= 168] : (…) pf. 3. pl. ईषुस् RV.

**Comment by zaaf2** [comment]
Re. 7122 upAnud upanud
Different words.

PWG. नुद् [L=40628] [p= 4-0301: (…) — उपा dass.: ततः शेषानुपानुदत् । इषुजालेन महता  Mbh. 7, 1771.  नाद्य शोकमुपानुदे von sich entfernen, sich befreien von 268. zertrümmern, zerspalten.
* OBS: the entries of verbal roots in PWG has many subentries containing the various verbs derived with preffixes. I think it is idispensable be make such prefix-root-verbs searchables headwords, as in all the other dictionaries.

MW72:
![image](https://cloud.githubusercontent.com/assets/14730665/11125520/3ead23aa-8949-11e5-89e1-574e3381c33d.png)


There seems to be a **print error in MW**: is the text missing?
 
![image](https://cloud.githubusercontent.com/assets/14730665/11125526/4492d166-8949-11e5-819d-69fb9d1bae3b.png)

**Comment by zaaf2** [comment]
Re. 11228 DUnayati Dunayati
Different denominative verbs. Both confirmed by MW.

STC:  धूनयति dhūnayati dén. secouer, agiter. 
MW: धूनय [p= 517] : Nom. P. °यति, to shake, agitate Pāṇ.  7-3, 37 Va1rtt. 1 Pat.  [L=101510]
धून [p= 517] : mfn. (Pāṇ.  8-2, 44) shaken, agitated [L=101506]
√धू cl.5 P. A1. धूनोति, °नुते  (…) to shake, agitate 

AP90 धुनयति  Den. P. 1 To sound, roar. — 2 To flow.
धुनय [p= 517] : Nom. P. °यति, to roar, flow noisily RV.  [L=101397]

**Comment by zaaf2** [comment]
Re. 12067 nirmATa nirmaTa
Different words, same etymology (< √मथ्). 

nirmATa is grammatically correct.

STC: 
निर्माथ nir-mātha- m. destruction, ruine.

MW:
माथ [p= 808] : m. ( √ मथ्) churning, stirring W.  [L=162461] m. hurting, killing, destruction Ṡatr.  [L=162462]
निर्-°मथ [p= 556] : m. rubbing [L=109756]
निर्मथ् to grind (fire) out of (wood), to produce (fire) by rubbing (…); to grind down, crush, destroy.

**Comment by zaaf2** [comment]
22046 samunnAsa samunnasa
समुन्नास is grammatically defensible. 

STC: 
समुन्नास  sam-unnāsa- a. au nez proéminent.

MW: 
सम्-उन्नस [p= 1168] : mfn. having a prominent nose
नासा f. the nose (either du. e.g. AV.  v, 23, 3, or sg. Mn.  MBh.  &c ; **ifc.** f(आ). MBh.  R.  &c ) [L=106225]
नस [p= 532] : m. (ifc.) the nose 
नस् 3 [p= 532] : or नास् f. (the strong stem occurs only in du. नासा RV.  ii, 39, 6, the weak stem only in नसा, नसि, नसोस् [cf. Pāṇ.  6-1, 63] and in comp.) the nose

**Comment by gasyoun** [comment]
@zaaf2 , as per indispensable be make such prefix-root-verbs searchables headword in PWG - give a sample, please.

**Comment by zaaf2** [comment]
(Please read “idispensable to make”  instead of “idispensable be make”).

For example: a search in PWG for अतिनुद्, अपनुद्, व्यपनुद्, अभिनुद्, अवनुद्, पर्यवनुद्, अपानुद्, व्यपानुद्, उपानुद्,  उपनुद्, निस्नुद्, अभिनिस्नुद्, परानुद्, परिनुद्, प्रनुद्, अतिप्रनुद्, अनुप्रनुद्, संप्रनुद्, प्रतिनुद्, विनुद्,  अभिविनुद्, सम्नुद्, उपसम्नुद् yields no result, but they are all there, under the verbal root नुद्. These words are searchable independently in MW:
अति- √नुद् [p= 14] : to drive by AV.  [L=3049]
अप- √नुद् [p= 49] : to remove RV.  &c [L=9310];
(…)
वि- √नुद् a [p= 972] : P. A1. -नुदति, °ते, to drive away or asunder, scare away, dispel, remove
etc.

**Comment by zaaf2** [comment]
Re. 24183 syUmaraSmI -> syUmaraSmi
A very thorough, “zaafian” documentation! Thanks. :relaxed:

Here ends the review.

**Comment by gasyoun** [comment]
@funderburkjim how hard is that @zaaf2's request? Seems like a bomb. What can I do to help you?

**Comment by funderburkjim** [comment]
@gasyoun  I'm not sure which 'zaaf2 request' you mean.

**Comment by funderburkjim** [comment]
* `10905 dfzwIviza -> dfzwiviza typo'  Disagree. It is no change.  the first form is given by STC as an alternate to the second form: 
![image](https://cloud.githubusercontent.com/assets/6393033/11286802/23fed44e-8ee5-11e5-9866-42635449c560.png)

*

**Comment by funderburkjim** [comment]
re 'There seems to be a print error in MW: is the text missing?' for upa-nud.

A guess:  Monier had the entry 'upanunna' and inserted the upa-nud entry so that a reader would 
know that upanunna was derived from upa-nud;  but he had nothing else to say about the prefixed
verb upa-nud,  Thus, it probably is not a print error ('bug') but an add 'feature.'

**Comment by gasyoun** [comment]
Indeed, might be treated as feature, @parjanya agree?

**Comment by funderburkjim** [comment]
Corrections installed.  Also [corrections_nochange.txt](https://gist.github.com/funderburkjim/31056c8e340d8c9cbc12) updated.

**Comment by funderburkjim** [comment]
@drdhaval2785   I had to modify the generate.py for use here.

The reason is that there is no 'key1' field in stc.txt.  There is only a pseudo-key2 field in stc.txt, and, to make matters more complicated, that pseudo-key2 field is coded in AS, and with odd capitalization.

Another side-effect is that the actual corrections had to be made to that AS form of key2.

You'll see the details in stc/pywork/correctionwork/issue-149.  The environment for stc at Cologne has been revised at s3.

I'm working on scripts to update the environment at s3 for a given dictionary whenever something in that dictionary's environment changes.

**Comment by gasyoun** [comment]
"pseudo-key2 field is coded in AS, and with odd capitalization" seems like a thriller. What is odd about it? Should we make a table of what encoding is where in which file? Without this comment I would be unaware why we have pseudo-key2 - even know I hardly understand. Understanding is not needed. But a table would not hurt.

**Comment by funderburkjim** [comment]
The capitalization oddity is that in STC the author capitalizes the root, at least in prefixed verbs (see images above for examples).

By 'pseudo-key2'  I was meaning that, in stc.txt there are no distinctly coded key1 and key2.   Whereas in pw.txt, pwg.txt there are.   I haven't made a table showing which dictionaries are which in this dimension, though it might possibly have been noted in the x-meta.txt files for the various dictionaries.

**Comment by gasyoun** [comment]
Capitalization of the root is a CSS issue. All we need to have is a root markup. We do not have to have it on content level, only display level. "I haven't made a table showing which dictionaries are which in this dimension" sure would be interesting. Just x-meta.txt would not do.
