### ISSUE TITLE
'o vs O' corrections, ACC (part 1)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#152]
Based on http://drdhaval2785.github.io/o_vs_O/output3/composite1a.html

1	`27287`	samitsamAropaRaprAtarOpasanaprayoga	samitsamAropaRaprAtarOpAsanaprayoga	समित्समारोपणप्रातरौपसनप्रयोग	समित्समारोपणप्रातरौपासनप्रयोग	ACC	MW,PW
Fixed here https://github.com/sanskrit-lexicon/CORRECTIONS/issues/138#issuecomment-155920571

ACC:
![samitsamaroparaprataropasanaprayoga](https://cloud.githubusercontent.com/assets/80761/11102842/f3850ae2-88cf-11e5-9cdd-6f85a502ce68.PNG)

MW: samit--samāropaṇa-prātar-aupāsana-prayoga
PW:
![samitsamaroparaprataropasanaprayoga2](https://cloud.githubusercontent.com/assets/80761/11102847/f7708e24-88cf-11e5-913f-b080b34c6338.PNG)

**Comment by gasyoun** [comment]
4	31852	uddeSyaviDeyaboDasTAlIyavicAra	uddeSyaviDeyaboDasTalIyavicAra

ACC:
![uddesyavideyabodastaliyavicara](https://cloud.githubusercontent.com/assets/80761/11103757/76add674-88d5-11e5-98b0-34fe9c1cba4b.PNG)

PW:
![uddesyavideyabodastaliyavicara2](https://cloud.githubusercontent.com/assets/80761/11103759/79f20f94-88d5-11e5-999f-bfea8abe9ec5.PNG)

MW: uddeśya-vidheya-bodha-sthalīya-vicāra

**Comment by funderburkjim** [comment]
The only two items mentioned have been corrected in ACC, as Gasyoun noted.
Thus, there seems to be nothing that I need to do with this issue.
So, I am closing it.

Feel free to reopen if I'm missing something.
