### ISSUE TITLE
MW abbreviations wrongly rendered

### ISSUE THREAD

**Issue by zaaf2** [sanskrit-lexicon/CORRECTIONS#158]
Abbreviations of repeated words inside subentries in MW wrongly rendered in the digital edition.

I detected this error in the entry भरतवर्ष :
`भरत-वर्ष [p= 747] : n. " country of भरत-वर्ष ", a N. of India (= भारत-व्°) L.  [L=148758]`
This makes no sense. 
The problem starts with भरतज्ञ [L=148745] and is repeated in the following subentries: 
* भरत-ज्ञ [p= 747] : mfn. " knowing the science of भरत-वर्ष ", conversant with dramatic writings and rules Ṡiṡ.  [L=148745]
 
![image](https://cloud.githubusercontent.com/assets/14730665/11168248/4a21970c-8b65-11e5-9a67-ddea2606ac52.png)

(Of course Bhº refers to the headword भरत (and here especially to `an ancient मुनि supposed author of a manual of the dramatic art called नाट्य-शास्त्र or भरत-शास्त्र`), and not to “Bharata-varsha” in the previous subentry).

The error is repeated in:
* भरत-त्व [p= 747] : n. the name of भरत-वर्ष MBh.  [L=148746]
* भरत-पुत्र [p= 747] : (Ratnâv.  Bālar. ) (L. ) m. " son of भरत-वर्ष ", an actor, mime. [L=148750]
* भरत-पुत्रक [p= 747] : (L. ) m. " son of भरत-वर्ष ", an actor, mime. [L=148751]
* भरत-प्रसू [p= 747] : f. " mother of भरत-वर्ष " N. of कैकेयी (wife of दशरथ) L.  [L=148753]
* भरत-र्षभ [p= 747] : (°त-ऋ°) m. the best or a prince (lit. " bull ") of the भरत-वर्ष MBh.  [L=148757]
* भरत-वाक्य [p= 747] : n. " speech of भरत-वर्ष " N. of the last verse or verses of a play (preceded almost always by the words तथापीदम् अस्तु भरत-वाक्यम्) [L=148759]
* भरत-शार्दूल [p= 747] : m. the noblest (lit. " tiger ") of the भरत-वर्ष MBh.  [L=148761]
* भरत-शास्त्र [p= 747] : n. भरत-वर्ष's manual (of the dramatic art = णात्य-श्°) Cat.  [L=148762]
* भरत-श्रेष्ठ [p= 747] : m. the best of the भरत-वर्ष ib. [L=148764]
* भरत-सत्तम [p= 747] : m. the best of the भरत-वर्ष ib. [L=148765]
* भरताग्रज [p= 747] : m. " elder brother of भरत-वर्ष ", N. of राम Vop.  [L=148769]
* भरतावास [p= 747] : m. " abode of भरत-वर्ष ", N. of PadmaP.  iv. [L=148771]
* भरताश्रम [p= 747] : m. " hermitage of भरत-वर्ष " N. of a hermitage Cat.  [L=148772]

In all these cases भरत-वर्ष should be changed to भरत or भरतs.

It is perhaps advisable to figure out a way to check if there are other such cases.

**Comment by gasyoun** [comment]
Even if there are such, and I'm sure there are, only an eye can catch that. Do we have a markup for parts of words that we think we read correct based on a degree sign? Or they are treated as every other word and all clues are gone, @funderburkjim ?

**Comment by funderburkjim** [comment]
These corrections now installed.

**Comment by funderburkjim** [comment]
Such cases ARE identifiable in the markup of mw.xml, by the `<abE>` tag.

As an example, here is the record of mw.xml for varzajYa:
```
<H3><h><hc3>110</hc3><key1>BaratajYa</key1><hc1>3</hc1><key2>Barat/a--jYa</key2></h>
<body> 
 <lex>mfn.</lex> <c><quote>_knowing_the_science_of_
<abE>Bh</abE><as0>Bharata-varsha</as0><as1><s>Barata-varza</s></as1>_
</quote>_,_conversant_with_dramatic_writings_and_rules</c> <ls>S3is3.</ls> 
</body><tail><MW>094676</MW> <pc>747,3</pc> <L>148745</L></tail></H3>
```

```
grep '<abE>' monier.xml > temp1
wc -l temp1
```

A grep shows there are 13132 records with an `<abE>` tag.

I'm sure that some of these have erroneous expansions, as with Bharata-varsha.  

The general rule of expansion is, as @zaaf2 suspected, to use the nearest previously un-abbreviated word that matches the abbreviation.

**Comment by gasyoun** [comment]
Could you upload the list for a possible reviewer in the future? Every grep should end as a .txt file - such is my opinion. Thanks for the answer.
