### ISSUE TITLE
Greetings, Thomas

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#159]
@thomasincambodia is Thomas Malten.  As probably most of you know, Thomas and his [staff in India](http://www.sanskrit-lexicon.uni-koeln.de/images/Aurorachana_Staff_2006(1).jpg) produced the original digitizations of Sanskrit Dictionaries at Cologne.  This work began in the mid 1990s with the digitization of the Monier-Williams dictionary.  His early and continued espousal of  the idea of *open data* has been crucial to the very possibility of our work on those dictionaries in this GitHub repository started by Marcis.

Thanks, Thomas, and welcome.

**Comment by funderburkjim** [comment]
@thomasincambodia   We'll try not to bombard you with questions until you get used to the format  of working on Github.  

The first thing to learn is how to make a comment to an issue (what I am typing now is such a comment).

Basically, you just open up the issue in a browser  (for this issue, the url is https://github.com/sanskrit-lexicon/CORRECTIONS/issues/159),

you go to the bottom of the page and start typing in the open text input area.  When you're done, you can click 'Preview' to see how it will look (this is optional).  Then, when you've finished with the comment, just click the green 'Comment' button, and the issue comment will be posted.

Why don't you give it a try?

P.S. There are lot's of tricks to making various effects in the comments.  You'll pick these up as time goes by.

**Comment by drdhaval2785** [comment]
@thomasincambodia Welcome.
Looking forward to interact with you.

**Comment by gasyoun** [comment]
@thomasincambodia it's been 10 years at least since 
our last interaction. Hope I can make all good again.
