### ISSUE TITLE
eleven odd members of AP90

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#162]
#43 point 1 is being examined.
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/43#issuecomment-65781239 to be precise.
Proposed hypothesis says `Option 1 - Treat them as M when occuring in between a word (other than the cases where the first member of compound ends with m). e.g. caMcalaM:AP90`

I would study the abberrations thereto.
The method is very crude as of now.
Will evolve as it goes on.

AP90 usually gives 'M[Consonantl]' pattern.
Only two entries in it have 'm[Consonant] pattern.

Abberrations by regex are 
```
akampana:AP90
akARqa:AP90
akiYcana:AP90
akuRWa:AP90
akrAnta:AP90
akzAntiH:AP90
aKaRqa:AP90
aniNgya:AP90
dfnPUH:AP90
dfnBUH:AP90
nitambin:AP90
```
I will examine them one by one.

1 akampana->akaMpana
Print error or should we say that conventional abberration.

![capture](https://cloud.githubusercontent.com/assets/5755132/11316573/60ea78ec-9032-11e5-81e9-c7b5b9d5571d.png)

and 
2 nitambin->nitaMbin
Digitization error
![capture](https://cloud.githubusercontent.com/assets/5755132/11316580/db964e0e-9032-11e5-8d01-d67655f54ec7.png)

**Comment by gasyoun** [comment]
@funderburkjim I guess they are ready to be slaugthered.

**Comment by drdhaval2785** [comment]
3 akARqa -> akAMqa
Convention error

See the description also. It uses kAMqa.
![capture](https://cloud.githubusercontent.com/assets/5755132/11316606/18e0c02c-9034-11e5-9180-84b0a97d8f55.png)

**Comment by drdhaval2785** [comment]
4 akiYcana->akiMcana
Convention error

See the description as well as the next entry
![capture](https://cloud.githubusercontent.com/assets/5755132/11316628/be883802-9034-11e5-9f58-0b6656719461.png)

**Comment by drdhaval2785** [comment]
5 akuRWa->akuMWa
Convention error

See the description as well as the next entry
![capture](https://cloud.githubusercontent.com/assets/5755132/11316643/3757ffba-9035-11e5-82bf-202980f50ed2.png)

**Comment by drdhaval2785** [comment]
6 akrAnta->akrAMta
Convention error

![capture](https://cloud.githubusercontent.com/assets/5755132/11316652/7242928e-9035-11e5-8219-741c60c057d7.png)

'krAnta' is not a headword in AP90. It is 'krAMta' - See [this](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/web/webtc/indexcaller.php?key=krAMta&input=slp1&output=SktDevaUnicode).
So its negation also should have 'akrAMta'

**Comment by drdhaval2785** [comment]
7 akzAntiH->akzAMtiH
Convention error
![capture](https://cloud.githubusercontent.com/assets/5755132/11316656/b1252bce-9035-11e5-8605-f8314590d81b.png)

'kzAMtiH' is the headword. See [this](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/web/webtc/indexcaller.php?key=kzAMtiH&input=slp1&output=SktDevaUnicode)
So negation also has 'M'

**Comment by drdhaval2785** [comment]
8 aniNgya->aniMgya
Convention error

I am not too sure, because never seen the word before.

**Comment by drdhaval2785** [comment]
9 dfnPUH
10 dfnBUH
NO CHANGE

Because the entry reads it as alternative.
There is a separate grammatical sUtra for these words also.


![capture](https://cloud.githubusercontent.com/assets/5755132/11316668/8c073c6e-9036-11e5-87bf-084f4e774c61.png)

**Comment by drdhaval2785** [comment]
11 aKaRqa->aKaMqa
Convention error

See the description iteslf.
![capture](https://cloud.githubusercontent.com/assets/5755132/11316677/f4f7e5ca-9036-11e5-89f2-e2efbad6ac6e.png)

**Comment by drdhaval2785** [comment]
This ends conventional correction submission for AP90.

Time for @funderburkjim to install.

**Comment by gasyoun** [comment]
conventional correction submission - needs a new tag? `c`?

**Comment by funderburkjim** [comment]
@drdhaval2785   for `AP90 usually gives 'M[vowel]' pattern.` I think you meant
`AP90 usually gives 'M[consonant]' pattern.`

In at least a few cases (akARqa, akampana) the related words use "M"  kAMqaH, kaMpana.  This supports your conventional correction suspicion.   

I'll just manually mark 'conventional correction' as the *note* and classify as print errors.
Will do this tomorrow.

**Comment by drdhaval2785** [comment]
@funderburkjim Yes I meant M[Consonant].

It needs an abbreviation as this is just a start.

A subset of print error.

**Comment by funderburkjim** [comment]
Another point justifying these changes is that Apte specifically mentions this convention in the 
[preface](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/ap90pref.html#preface).

  "As in the English-Sanskrit Dictionary, I have
here throughout used the anusvâra instead of the nasals, "

So, I imagine Apte would be pleased by these changes.

It was a nice piece of detective work to find that Apte was inconsistent in so few cases.

**Comment by drdhaval2785** [comment]
@gasyoun 
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/162#issuecomment-158590327 subsequent to this I have corrected our format at https://github.com/sanskrit-lexicon/CORRECTIONS/issues/154#issue-116719290.
`c` is the tag in `notes` for our convention error friends.

**Comment by drdhaval2785** [comment]
@funderburkjim 
So Apte justifies our changes.
God bless him.

**Comment by gasyoun** [comment]
`c` is the tag in `notes` for our convention errors, got it @drdhaval2785 And what about `no idea` cases which I have 20 by now? I document the screenshots in these cases, best I can do.

**Comment by funderburkjim** [comment]
Corrections and nochanges installed.
