### ISSUE TITLE
anusvAra convention violations in AP90

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#163]
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/43#issuecomment-65781239 option 1 examined here.

AP90 has '[M][NYRnm]' pattern only in two types of cases.
1. 'saM' / 'sAM' prefixes e.g. saMmuKa
 and
2. 'Mmanya' suffixes e.g. idaMmanya.

Right now I have used the following logic
```
re.search('M[NYRnm]',word) and not re.search('s[aA]M[NYRnm]',word) and not 
re.search('Mmanya',word)
```

And got the list of 10 words which are to be examined.

```
aviBAvaMnIya:AP90
idaMmaya:AP90
iraMmada:AP90
kusuMmaH:AP90
jaMnmaM:AP90
drAGimaMn:AP90
purAMRa:AP90
BfjjaMna:AP90
lokapfMRa:AP90
vArAMniDiH:AP90
```

**Comment by drdhaval2785** [comment]
1 aviBAvaMnIya->aviBAvanIya
typo

![capture](https://cloud.githubusercontent.com/assets/5755132/11316718/8acab0b8-9038-11e5-9b85-be60c4205885.png)

**Comment by drdhaval2785** [comment]
2 idaMmaya
NO CHANGE

![capture](https://cloud.githubusercontent.com/assets/5755132/11316720/c1a00d4a-9038-11e5-9411-b0f675e079f8.png)

**Comment by drdhaval2785** [comment]
3 iraMmada
NO CHANGE
![capture](https://cloud.githubusercontent.com/assets/5755132/11316723/e81deffa-9038-11e5-81dc-f74c049f5ca8.png)

**Comment by drdhaval2785** [comment]
4 kusuMmaH->kusuMBaH
typo

![capture](https://cloud.githubusercontent.com/assets/5755132/11316728/0af76f7e-9039-11e5-8873-cd3e5ff7afde.png)

**Comment by drdhaval2785** [comment]
5 jaMnmaM->janmaM
print error
![capture](https://cloud.githubusercontent.com/assets/5755132/11316736/468f99b2-9039-11e5-8b94-450f36ab7ede.png)

**Comment by drdhaval2785** [comment]
6 drAGimaMn->drAGiman
OCR error

unclear print
![capture](https://cloud.githubusercontent.com/assets/5755132/11316741/7638fc80-9039-11e5-887f-deb6f62e30f1.png)

**Comment by drdhaval2785** [comment]
7 purAMRa->purARa
typo

![capture](https://cloud.githubusercontent.com/assets/5755132/11316749/acf865c6-9039-11e5-898c-b833c5967aef.png)

**Comment by drdhaval2785** [comment]
8 BfjjaMna->Bfjjana
typo

Print smudge
![capture](https://cloud.githubusercontent.com/assets/5755132/11316753/d4ec7478-9039-11e5-8ac4-92f26d02d0b3.png)

**Comment by drdhaval2785** [comment]
9 lokapfMRa->lokaMpfRa
print error

M misplaced.
See the description

![capture](https://cloud.githubusercontent.com/assets/5755132/11316757/1afda1f8-903a-11e5-838b-e2e4dc51d8e6.png)

**Comment by drdhaval2785** [comment]
10 vArAMniDiH
NO CHANGE

A rare compound
![capture](https://cloud.githubusercontent.com/assets/5755132/11316764/6bfdc632-903a-11e5-8064-11b8b8bce2e2.png)

**Comment by drdhaval2785** [comment]
This completes the correction submission

**Comment by gasyoun** [comment]
Come, o @funderburkjim, feed the pythons :walking:

**Comment by funderburkjim** [comment]
gave pythons a snack.
changes installed.

**Comment by gasyoun** [comment]
Give them more. Feed them the tiger.
