### ISSUE TITLE
hwnorm1 Corrections in PWG, Part 1

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#164]
* aDihastyaM n. -> aDihastya n. (OCR error, print smudge?)
![adihastyam](https://cloud.githubusercontent.com/assets/80761/11320207/05c1c266-90a2-11e5-9976-062197e35714.PNG)

* pravaraM -> pravara (OCR error, print smudge)
![pravaram](https://cloud.githubusercontent.com/assets/80761/11320218/6c1f3746-90a2-11e5-9199-9dd8133d4d92.PNG)
pravaraṁ [L=121099] [p= 7-1776] 	1 
— 4)  f.  ī  Pat. a. a. O.4,24,a.b. 
— Vgl. prāvara.

Print smudge? Seems so. As it come from "Verbesserungen" that means that there should be a `pravaraṁ` entry in main body of dictionary, but there is none. Tertium non datur, this is a false word, no `ṁ`.

* BArikaM -> BArika (OCR error, print smudge)
![barika](https://cloud.githubusercontent.com/assets/80761/11320248/82e63c94-90a3-11e5-88b3-bc3e19fb56ee.PNG)

Print smudge? Seems so. As it come from "Verbesserungen" that means that there should be a `BArikaM` entry in main body of dictionary, but there is none. Tertium non datur, this is a false word, no `ṁ`.

**Comment by funderburkjim** [comment]
In preparing to install these, I wanted to find the PWG convention for headwords ending in 'am' or 'aM'.  

From pwghw2.txt, there are 15 headwords ending in 'aM' and 893 ending in 'am'.  

From examining a small sample,  it appears that non-verb 'am' ending headwords are generally
adverbs.  

Neuter nouns in 'a' are presented as ending in 'a' (like vana).

However, there are some errors like the following:

प्रतिश्लोकम् [p= 4-0979] : (1. प्र° + श्लोक)  adj.  bei jedem Çloka  Bhâg. P. 1, 5, 11.  [L=48625]
[p= 5-1621] :  Bhâg. P. 12, 12, 51.  [L=79236]

This is a print error, and should be 'adv' (adverb).  (MW pratiSlokam = at every Sloka), which I think is same sense as German `bei jedem Çloka`.

And an 'aM' case of likely error is:
यौथ्यं [p= 6-0202] :  adj.  von यूथ gaṇa संकाशादि zu  P. 4, 2, 80.  [L=82610]
Here, comparing MW, probably headword should be yOTya  (not sure whether 'M' is print smudge
typo or print error)

@drdhaval2785  Maybe you should generate, for PWG at least, a list of headwords ending in
'am' or 'aM' and which show 'adj.'   -  that would catch these two, and perhaps some others.

**Comment by gasyoun** [comment]
at every Sloka = bei jedem Çloka
The adj. list in addition to f. list seems to be a nice idea, quick to implement.

**Comment by funderburkjim** [comment]
Three corrections installed:
```
pwg:aDihastyaM:aDihastya:t:print smudge
pwg:pravaraM:pravara:t:print smudge
pwg:BArikaM:BArika:t:print smudge
```
