### ISSUE TITLE
hwnorm1 Option 1.3 wrong (PWG,PWK)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#165]
I started reading https://github.com/sanskrit-lexicon/hwnorm1 - it's a gift Dhaval has done such a research, hope @funderburkjim agrees. I will try to make best use of it. But I have an objection to Option 1.3, that deals with "Use M at the end of a word to denote neuter gender. e.g. aMSukaM" and states "Dictionaries - SKD,AP90,BHS,WIL,PW,PWG,VCP". "SKD,AP90,BHS,WIL,VCP" - "Indian" dictionaries truly use it, but PW,PWG does not. At least not for that purpose and only a few cases (in comparison SKD has 7.5k cases). It's @drdhaval2785  mistake, but such that lead to correction of several mistakes at https://github.com/sanskrit-lexicon/CORRECTIONS/issues/164

18 cases from PWG (markup manually added):
* uccAM adv.
* kisaM ved.
* BaganarAyaM m.  N. pr.
* mahadbilaM n. quotes SKD
* mahEraRqaM m. quotes SKD
* aBiniDanaM N.
* AniDanaM N.
* pAriBAzikaM n. quotes SKD
* putrIkaraRamImAMsAM f. [OCR error]
* yOTyaM adj.
* vfttikAraM m. Verfasser eines Commentars
* vyutkramaM m.
* sutfzRaM (?) N. pr.
* sTUlanAsaM m. 
* hrasvagaveDukAM f. [OCR error]
* aDihastyaM n.
* pravaraM [OCR error]
* BArikaM [OCR error]

17 cases from PWK (markup manually added):
* atideSyaM Adj.
* aByaNgaM m. 
* alaktaM m.
* AgAmikaM Adj.
* ekAdaSakapAlaM Adj.
* etaddevatyaM Adj. 
* krandaM m. 
* grahItavyaM Adj. 
* cetavyaM Adj. 
* CandasyaM Adj.
* jaGanyaM Adj.
* janitavyaM Adj.
* jyotizyaM Adj. 
* tAmravaRaM Adj.  
* pratyanIkaBAvaM m. 
* mahAdamBaM Adj.
* SitivAraM Adj.

So for PWG, PWK instead of the definition "Use M at the end of a word to denote neuter gender" we could say "Use M at the end of a word mainly to denote Adjectiv".

"Note - Some dictionaries seem to follow two conventions in options 3.1 and 3.2. It will need a closer look." - is there a way to see some stats to decide?
Not sure what is the difference between Option 3.1 and Option 3.3, please add 2-3 examples. As per "Uses inflected form with 'A' at end (e.g. kartA)" - waiting for some hint.

**Comment by drdhaval2785** [comment]
Not PW and PWG shifted from option 1.3 to 1.4

Readme updated.

Thanks for testing the hypothesis.

**Comment by gasyoun** [comment]
Can't see the shift to Option 1.4 in readme. For "Use M at the end of a word (not to denote neuter gender, but to denote avyayas mostly) where 'm' is supposed to be. e.g. anukAmaM, anudiSaM etc." I still see only `Dictionaries - YAT`.
