### ISSUE TITLE
aFem Manual Processing, Part 2 (PWK, SCH, AP90)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#166]
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/160 continued.

_PWK_

* agrAhyanAmaka

![agrahyanamaka](https://cloud.githubusercontent.com/assets/80761/11320420/c09bdc74-90a8-11e5-871c-d905004c466e.PNG)
Lexicographer error?

* kalApaKaYja

![kalapakayja](https://cloud.githubusercontent.com/assets/80761/11320437/fa709336-90a8-11e5-8fbe-716afa83f5c5.PNG)
Lexicographer error?

* kikviSa

![kikvisa](https://cloud.githubusercontent.com/assets/80761/11326039/5f03255e-916f-11e5-99de-e0294dba114e.PNG)

* tElaspanda

![telaspanda](https://cloud.githubusercontent.com/assets/80761/11326057/7230b87a-9170-11e5-883b-9ca2bccaa6cd.PNG)

* digdEvata

![digdevata](https://cloud.githubusercontent.com/assets/80761/11326064/9e551e6e-9170-11e5-91f5-5ac8c39b6d72.PNG)

* Denuzyita

![denuzyita](https://cloud.githubusercontent.com/assets/80761/11326077/ca088dd4-9170-11e5-804a-8795950e574d.PNG)

* paricintaka
![paricintaka](https://cloud.githubusercontent.com/assets/80761/11326097/197e9c1e-9171-11e5-930b-bcdcaa8d099b.PNG)

* bAhyatva
![bahyatva](https://cloud.githubusercontent.com/assets/80761/11326105/3a58adc6-9171-11e5-971e-23fcb736ceb7.PNG)

* sAcIsUtra

![sacisutra](https://cloud.githubusercontent.com/assets/80761/11339187/6177428a-9209-11e5-9287-3341977b6caa.PNG)

*  sāraṅgahāra f.  eines Art Jogin.

![sarangahara](https://cloud.githubusercontent.com/assets/80761/11339363/3b095704-920a-11e5-9f53-7913c38f46fc.PNG)

* *śarkāra [L=110769] [p= 6213-1] 	 f.  ī
Everything fine. f. is related to śarkārī, not śarkāra. It would be good to be able to generate śarkārī for search purposes.
![sarkara](https://cloud.githubusercontent.com/assets/80761/11339067/b36b4a42-9208-11e5-880c-ca2a21421f65.PNG)

**Comment by gasyoun** [comment]
garBopanizAwa -> garBopanizAd (OCR error)
![garbopanizawa](https://cloud.githubusercontent.com/assets/80761/11326046/b3c33660-916f-11e5-8495-2325ad673778.PNG)

**Comment by gasyoun** [comment]
* raktādhāra [L=91823] [p= 5157-1] 	 f.  Haut -> m.  Haut (OCR error)
![raktadara](https://cloud.githubusercontent.com/assets/80761/11334194/838c4fac-91e4-11e5-9388-f64385dd6c4f.PNG)

**Comment by gasyoun** [comment]
* laganīya [L=95418] [p= 5212-1] 	 f. -> n.

![laganiya](https://cloud.githubusercontent.com/assets/80761/11338902/ccc291cc-9207-11e5-83c0-f884f8552455.PNG)

**Comment by gasyoun** [comment]
* *vṛkṣamārjāra [L=106300] [p= 6147-3] 	 f.  -> m.
![vfkzamarjara](https://cloud.githubusercontent.com/assets/80761/11338992/429be588-9208-11e5-81b8-ba3a6942f62f.PNG)

**Comment by gasyoun** [comment]
* vedavidya  -> vedavidyA  (OCR error)
![vedavidya](https://cloud.githubusercontent.com/assets/80761/11339034/7e993072-9208-11e5-89cc-46620d753fe4.PNG)

**Comment by gasyoun** [comment]
* samIkriya -> samIkriyA (OCR error)
![samikriya](https://cloud.githubusercontent.com/assets/80761/11339131/0dec2428-9209-11e5-9e88-9e391dd07815.PNG)

**Comment by gasyoun** [comment]
This why we need to test not only `-a`. There seems to be many cases, some of which are legal. (!) f. = legal f., @drdhaval2785 

![interesting-f](https://cloud.githubusercontent.com/assets/80761/11339373/487535a2-920a-11e5-84b9-a93ede23c3b9.PNG)

**Comment by gasyoun** [comment]
* suralAsika -> suralAsikaA (print error)

PWK says to compare [=Vgl.] it with -lāsikā, not with -lāsika, so suralāsika with hrasva is a lexicographer or print error.
*suralāsika [L=127533] [p= 7162-2] 	 f.  Föte. Vgl. svaralāsikā.

![suralasika](https://cloud.githubusercontent.com/assets/80761/11339606/6556d1b6-920b-11e5-9aaf-ec0d8de001f3.PNG)

**Comment by gasyoun** [comment]
* svarapaYcASata -> svarapaYcASat (OCR error)

![svarapaycasata](https://cloud.githubusercontent.com/assets/80761/11339748/ff387da2-920b-11e5-83ac-29cadbddd998.PNG)

**Comment by gasyoun** [comment]
* *hayaśāla [L=133549] [p= 7254-2] 	 f.  , Pferdestall.  -> *hayaśālā f. Pferdestall.  (OCR error)

![hayasala](https://cloud.githubusercontent.com/assets/80761/11340020/3287c450-920d-11e5-996a-b8fe7a055903.PNG)

This ends PWK cases.

**Comment by gasyoun** [comment]
_SCH_

* Kubjottara -> KubjottarA (OCR error)
`<key1>kubjottarA</key1><key2>Kubjottara</key2>`

![kubj](https://cloud.githubusercontent.com/assets/80761/11342641/6d659230-9219-11e5-8ea6-91357ff197b9.PNG)

**Comment by gasyoun** [comment]
_AP90_

* abhisaṁpada -> abhisaṁpad (OCR error) 
![abisampada](https://cloud.githubusercontent.com/assets/80761/11342787/1303286a-921a-11e5-8f2c-7eac48e4193f.PNG)

**Comment by gasyoun** [comment]
Ready for @zaaf2 validation.

**Comment by zaaf2** [comment]
agrAhyanAmaka f. → agrAhyanAmaka Adj. 
Lexicographer error
MW: 
* नामक 1 [p= 536] : mf(इका)n. ifc. = नामन्, name Hariv.  Kāv.  &c (cf. अङ्घ्रि., कृत- &c ) [L=105822]
* कृत-नामक [p= 302] : mfn. named Hariv.  3436.

**Comment by zaaf2** [comment]
kalApaKaYja f. → kalApaKaYja m. 
Print error.

MW:

लापखञ्ज [p= 261] : m. a particular disease (said to be St. Vitus's dance ; v.l. कलायखञ्ज) Bhpr. [L=45861.56]
कलायखञ्ज [p= 261] : m. = कलाप-खञ्ज q.v., ṠārṅgS. [L=45919]
PWK:

कलायखञ्ज [L=25496] [p= 2034-2] m. angeblich Veitstanz Çârñg.sam̄h.1,7,70. कलाप° Bhâvapr.4,156,fg.

-----

kikviSa f.  → kikviSa m.
Print error
MW: 
* किक्विश [p= 282] : v.l. for किक्किश. [L=50195]
* [p= 282] : m. a kind of worm (pernicious to the hair, nails, and teeth) Suṡr.  [L=50191]
PWK: 
* किक्किश [L=27765] [p= 2064-1], ( किक्विश gedr.) und किक्किस ( Ḱaraka.4,8 )  m.  ein best. Wurm.  [Page2.064-2]

-----

tElaspanda f. → tElaspandA f.
Print error.

MW:
* तैल-स्पन्दा [p= 455] : f. Cucurbita Pepo Npr.  [L=87091]; f. Clitoria ternatea ib. [L=87092]; f. काकोली ib. [L=87093]

PWG:
तैलस्पन्दा [L=30593] [p= 3-0399], (तैल + स्पन्द)  f.  N. verschiedener Pflanzen: — 1) = श्वेतगोकर्णी. 
— 2) = काकोली. — 3) Cucurbita Pepo  Nigh. Pr.

----


digdEvata f. → digdEvata n.
Print error

PWG:
दिग्दैवत [L=32830] [p= 3-0610], (2. दिश् + दै°)  n.  = दिग्देवता  Mbh. 7, 7293.
MW:
* दिग्-दैवत [p= 480] : n. = -देवता MBh.  vii, 7293. [L=92541]

----

Denuzyita f. → Denuzyita Adj.
Print error.
* धेनुष्यित [L=37035] [p= 3-0994], (von धेनुष्या) adj.  wohl derjenige, der die Milch seiner Kuh nicht benutzen darf, weil er sie einem Andern schon verpfändet hat, gaṇa तारकादि zu  P. 5, 2, 36.
MW:
* धेनु°ष्यित [p= 520] : mfn. one who has pledged the milk of his cows (?) g. तारका*दि. [L=102056]

----

paricintaka f. → paricintaka Adj.
Print error

PWG: 
* परिचिन्तक [L=42753] [p= 4-0521], (von चिन्त् mit परि) nom. ag. der über Etwas (gen.) nachsinnt, nachgedacht hat: परस्य  Bhâg. P. 3, 32, 8.  भूतानाम्  Mbh. 11, 160.  धर्मार्थ 12, 3476.

MW:
* परि-चिन्तक [p= 594] : mfn. reflecting about, meditating on (gen. or comp.) MBh.  BhP.  [L=117418]

----

bAhyatva f. → bAhyatva n.
Print error.

PWG:
* बाह्यत्व [L=52655] [p= 5-0084] n.  = बाह्यता। वेद°  Madhus. in Ind. St. 1, 13, 25.

MW:
* बाह्य-त्व [p= 731] : n. the state of being outside, exclusion, deviation or divergence from (abl.) Hariv.  Rājat.  &c [L=145076]

----

sAcIsUtra f. → sAcIsUtra n.
Print error

MW:
* साची-सूत्र [p= 1199] : n. frenum praeputii Gal.  [L=241336]
* सूत्र [p= 1241] : n. (…) a thread, yarn, string, line, cord, wire AV.  &c [L=251185]

----

sāraṅgahāra f. → sāraṅgahāra m.
Print error

MW:
* सारङ्ग-हार [p= 1208] : m. a kind of योगिन् W.  [L=242982]
* हार (…) m. taking away, removal ib. [L=260810]

----

suralAsika -> suralAsikaA (print error)

You mean: suralAsika -> suralAsikA (print error)

Confirmation: 
MW:
* सुर-लासिका [p= 1234] : f. a flute (cf. स्वर-ल्°) L.  [L=249414]

----

This ends the PWK review.

**Comment by zaaf2** [comment]
I reviewed the other cases. Nothing to add.

**Comment by gasyoun** [comment]
@zaaf2 thanks, @funderburkjim your turn.

**Comment by funderburkjim** [comment]
Re sch aDoguqA:   

I am uncertain about why this is in the aFem list.  Here is the sch.txt record:
```
.{#aDoguqA#}100{#adhogud2a1#}¦ f. Argyreia speciosa , Caraka 1 , 1. [Schµ1867] €2

```
and here is the sch.xml record:
```
<H1><h><key1>aDoguqA</key1><key2>adhogud2a1</key2></h><body>f. Argyreia speciosa , 
Caraka 1 , 1. [Schµ1867] €2</body><tail><L>1841</L><pc>025-2</pc></tail></H1>
```
and here is the html display 
```
adhoguḍā [L=1841] [p= 025-2]	f. Argyreia speciosa , Caraka 1 , 1. 2
```

Everything looks right to me.  

It is odd that in sch.txt, the 'key2' field is present AND is in the AS coding.  But, that coding is
proper  (the ending 'a1' means dIrGa 'a' or slp1 'A').

I will mark  this as a no-change,

**Comment by funderburkjim** [comment]
pw corrections installed. Normalized form:
```
pw:agrAhyanAmaka:agrAhyanAmaka:p:l  f.->Adj.
pw:kalApaKaYja:kalApaKaYja:p:l  f.->m.
pw:kikviSa:kikviSa:p:l  f.->m.
pw:tElaspanda:tElaspandA:p: 
pw:digdEvata:digdEvata:p:l f.->n.
pw:Denuzyita:Denuzyita:p: f.->Adj.
pw:paricintaka:paricintaka:p:l f.->Adj.
pw:bAhyatva:bAhyatva:p: f.->n.
pw:sAcIsUtra:sAcIsUtra:p: f.->n.
pw:sAraNgahAra:sAraNgahAra:p: f.->m.
pw:SarkAra:SarkAra:n: good to generate SarkArI for search purposes
pw:garBopanizAwa:garBopanizad:t:
pw:jIvapura:jIvapurA:t:
pw:bfhatkaTa:bfhatkaTA:t:
pw:maNgalagIta:maNgalagIta:t: f.->n.
pw:raktADAra:raktADAra:t: f. -> m. 
pw:laganIya:laganIya:t: f.  ein best. Metrum. ->n. <impers.> {%sich anzuh&auml;ngen an%} (<Loc.>)
pw:vfkzamArjAra:vfkzamArjAra:t: f. -> m.
pw:vedavidya:vedavidyA:t:
pw:samIkriya:samIkriyA:t:
pw:suralAsika:suralAsikA:p:
pw:svarapaYcASata:svarapaYcASat:t:
pw:hayaSAla:hayaSAlA:t:
```

**Comment by funderburkjim** [comment]
SCH corrections installed.
```
sch:kubjottarA:kubjottarA:t: key2 Kubjottara -> kubjottara1
sch:aDoguqA:aDoguqA:n:
```

**Comment by funderburkjim** [comment]
Re ap90 `SuBa -> SuB `   There are two forms of this, one a root and one a noun.  In both cases
the text is written without the 'a', and the digitization is wrong in having that 'a'.  So both corrected as typos.

**Comment by funderburkjim** [comment]
ap90 corrections installed:
```
ap90:aBisaMpada:aBisaMpad:t:
ap90:tarada:tarad:t:
ap90:parizada:parizad:t:
ap90:SuBa:SuB:t:  two headwords
```

**Comment by funderburkjim** [comment]
All corrections installed.

**Comment by funderburkjim** [comment]
I'm using a 'playbook' ('cheat sheet', whatever) to do the various update steps.  For your reading 
enjoyment, here is that instruction sheet for ap90:
```

;Corrections to AP90
; Ref https://github.com/sanskrit-lexicon/CORRECTIONS/issues/166
This is in directory pywork/correctionwork/issue-166/.

Input file is change.txt
step 1. Generate ap90upd.txt, ap90upd.tsv, and ap90nochange.txt
sh prepareupd.sh ap90 gasyoun 166

step 1a. Make manual adjustments to ap90upd.txt:
 cp ap90upd.txt ap90upd_edit.txt  # corrections in a copy
  NOTE SuBa had two forms, so had to modify by 
  hand from ap90.txt

step 2. Install corrections using ap90upd_edit.txt
 - By examination of pywork/update.sh, the last line is
python updateByLine.py ../orig/ap902.txt manualByLine02.txt ../orig/ap90.txt 

 - So, we append ap90upd_edit.txt to the end of file manualByLine02.txt
   in pywork,
   cp manualByLine02.txt prev_manualByLine02.txt
   cat prev_manualByLine02.txt correctionwork/issue-166/ap90upd_edit.txt > manualByLine02.txt
 - Then, in pywork directory, issue that last command of update.sh, as shown
   above

 - Then, create the headwords file, ap90hw2.txt
sh redo_hw.sh
 - Then, recreate (a) ap90.xml, (b) ../web/sqlite/ap90.sqlite
sh redo_xml.sh

The rest of the steps update downloads and documentation
step3.  
  web/webtc directory:
  edit web/webtc/download.html, and change as-of-date at bottom of file
  remake downloads:
    cd to downloads directory
    sh redo_all.sh
 
step4a: copy ap90upd.tsv to php/correction_response/
 cd ../pywork
 From pywork directory:
cp correctionwork/issue-166/ap90upd.tsv ../../../../php/correction_response/

step4b: cd ../../../../php/correction_response/
step4c: append ap90upd.tsv to end of cfr.tsv
 cp cfr.tsv cfr-prev.tsv
 cat cfr-prev.tsv ap90upd.tsv > cfr.tsv
 
step5a.  On local machine, open Github application, then open local
 CORRECTIONS repository in Explorer
step5b. Open GitBash terminal,
 cd Documents/GitHub/CORRECTIONS/
 sh redo_cfr.sh
step5c. rm ap90upd.tsv # in php/correction_response/ directory at Cologne.


step6a. edit history.txt, and write note of the changes
step6b. update dictionaries/AP90/ap90_printchange.txt using cfr.tsv
    This done by reformatting the 'print error' records of ap90upd.txt
    NOTE: Not required this step, no print errors.

step6c. update corrections_nochange.txt from ap90nochange.txt
   NOTE: Not required for this step, no nochange cases

step7.  prepare new sanhw1.txt and sanhw2.txt
step7a. On Cologne server, change to scans/awork/sanhw1
  (Assuming still in php/correction_response):
  cd ../../scans/awork/sanhw1/
  sh redo_update.sh
step7b. In local CORRECTIONS repository,
  sh redo_sanhw12.sh

step8. sync with GitHub
step8a. Create commit
step8b. 'Sync'


step9. Make 'installation complete' note in #166.

```

Note that sanhw1 recreation is now part of the process.
