### ISSUE TITLE
Webpage and PDF from L number

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#168]
@funderburkjim 
Would it be possible to link the webpage and PDF from L number of a particular dictionary rather than 'key1'?

I am asking it because after we correct the wrong entries, we won't be able to see the webpage / PDF as it stood at that time.

If we have links based on L number - it would be a bit long lasting.

And yet better - First choice to 'key1' - If it fails - Second chance to L number.

**Comment by gasyoun** [comment]
I guess additional coding required, a database.

**Comment by funderburkjim** [comment]
It is probably possible to do this in the context of the 'sample' displays, where all dictionaries are
handled 'together'.   Part of how this might work is to have a separate access method, which would
take a dictionary code and L-number as parameters, and then would find the corresponding 'key1'.

Then, one could make variants of basic-02 and list-02 and servedpdf that would make use of this separate access method.

So, yes it seems possible.

**Comment by drdhaval2785** [comment]
Right now there are three parameters i guess.

1. Dictionary code
2. Dictionary display year
3. Key 1.

I propose we have 4 parameters.
4. L number

L number should be optional. If the key1 is not found (which would happen
in case we correct an entry), L number fetches the current key1 and
displays.

**Comment by drdhaval2785** [comment]
Now that we know L-numbers change and change substantially, let us close this issue. Not reliable.

**Comment by funderburkjim** [comment]
It is a goal to make the L-numbers non-volatile.   My current idea on this is to embed  the L-number 
within the xxx.txt files, as was recently done with sch.txt.   The main question I haven't  decided on is
whether to also embed the page number within xxx.txt also.   In other words,  provide some uniformity of structure to all the xxx.txt files, so all of them would have a 'header' section with
* key1
* key2
* L
* page-col

If all the xxx.txt files followed this format, then this would make the processing of them (to xxx.xml,
for instance) more uniform.

**Comment by gasyoun** [comment]
> whether to also embed the page number within xxx.txt also.

It's always easier to delete after than to add.
