### ISSUE TITLE
aFem Manual Processing, Part 3 (AP, BOP, BEN, BUR, CAE)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#169]
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/166 continued.

_AP_

* samita [L=33932] -> samit [L=33932] (OCR error, print smudge)

![samita](https://cloud.githubusercontent.com/assets/80761/11343073/6c6a9572-921b-11e5-9dfb-577f1996051a.PNG)
Both are possible

samit:AP90,BEN,BUR,CAE,CCS,MD,MW,MW72,PUI,PW,PWG,SCH,SHS,SKD,STC,VCP,WIL,YAT
samita:AP,AP90,BUR,CAE,CCS,MD,MW,MW72,PUI,PW,PWG,STC

**Comment by gasyoun** [comment]
_BOP_

* paNkta

![pankta](https://cloud.githubusercontent.com/assets/80761/11343161/be574e70-921b-11e5-87fc-5120850cca0c.PNG)
Print error?

**Comment by gasyoun** [comment]
_BEN_

* Una
<key1>Una</key1><key2>Una</key2></h><body><i>u10na</i> (probably for <i>van + na</i> from <lb/><i>van</i> = Goth. van, vans: cf. O.H.G. we10n- <lb/>ag, few, perhaps <g></g> etc.), adj., f. <i>na.</i>

No idea

![una](https://cloud.githubusercontent.com/assets/80761/11343253/36ce984a-921c-11e5-8fb1-2a1923977fbd.PNG)

**Comment by gasyoun** [comment]
_BUR_

* śivīratha -> śivīrathā (OCR error)
çivi1ratha</i> f. palanquin.

![sivirata](https://cloud.githubusercontent.com/assets/80761/11344497/b2d27d5c-9222-11e5-9d0a-02833e72a742.PNG)

**Comment by gasyoun** [comment]
_CAE_

* abhra  -> abhrī
abhra [L=2509] 	abhra ·f. shovel, spade. 

![abra](https://cloud.githubusercontent.com/assets/80761/11345965/4bc2115a-922b-11e5-8bf1-7a40578da978.PNG)

**Comment by gasyoun** [comment]
*  juṭaka ·f. ­ tuft, bunch. -> juṭaka ·n. ­ tuft, bunch. (OCR error, two variants)

![jutaka](https://cloud.githubusercontent.com/assets/80761/11346471/e6474892-922d-11e5-9680-a64cec239103.PNG)

**Comment by gasyoun** [comment]
* makṣika ·f. ­ -> makṣika m. ­ (OCR error, article splitting)

![makshika](https://cloud.githubusercontent.com/assets/80761/11347252/9e77a1b6-9231-11e5-868b-879040f05009.PNG)

**Comment by gasyoun** [comment]
* śvetāśvataropaniṣada ·f. T. of an Upanishad. 

![svetasvataropanizada](https://cloud.githubusercontent.com/assets/80761/11347990/eafa9860-9234-11e5-9d09-da787ac423e0.PNG)

**Comment by gasyoun** [comment]
This ends CAE.

GRA, CCS, PWG
PWK, SCH, AP90
AP, BOP, BEN, BUR, CAE

@zaaf2 is welcome.

**Comment by zaaf2** [comment]
paNkta → paNkti
OCR error

![image](https://cloud.githubusercontent.com/assets/14730665/11359487/566953a4-925b-11e5-9431-48aaae8eb040.png)

MW:
* पङ्क्ति [p= 574] : f. (also °क्ती mc. and in comp.) (fr. पञ्चन्) a row or set or collection of five, the number 5 AV.  Br.  &c [L=113369]	

----

Una (…) adj., f. na  → Una (…) adj., f. nâ
OCR error. Poor print.

![image](https://cloud.githubusercontent.com/assets/14730665/11359563/f6e46efe-925b-11e5-95bc-45d5cbf557f6.png)

MW:
* ऊन [p= 221] : mfn. (…)

----

caritra (…) adj. f. tra →  caritra (…) adj. f. trâ
OCR error (poor print quality)

![image](https://cloud.githubusercontent.com/assets/14730665/11359538/c00f2ce8-925b-11e5-8b1b-494e1f128f98.png)

----

śivīratha f. →  śivīratha m.
Print/Lexicographer error.

![image](https://cloud.githubusercontent.com/assets/14730665/11359492/6234a616-925b-11e5-876f-c92e482f3984.png)

MW:
* शिवी-रथ [p= 1076] : » शिबी-रथ, p.1072. [L=217968]
* शिबी-रथ [p= 1072] : m. a palanquin, litter L.
* रथ 1 [p= 865] : m. ( √4. ऋ) " goer ", a chariot, car (…)


----
kīṭaja f. →  kīṭajā f.
Print error.

MW:
* कीट-जा : f. an animal dye of red colour, lac L.
* कीट-ज [p= 284] : n. " coming from insects ", silk Mn.  xi, 168 MBh.  ii, 1847 [L=50717]
Cf. Le Grand Robert:
* cochenille 1. Insecte hémiptère (Homoptères; Coccidés) dont une espèce (cochenille du nopal) fournit une teinture rouge écarlate. ― 2. ** La teinture elle-même.**

----
somadhāra f. → somadhārā f. (?)
If the word is feminine, than somadhārā is the correct form. Compounds ending in -dhāră are masculine. 
Sky can be m. (Ved.) or f. (classic Skr.):
MW: दिव् and द्यु (…) m. (rarely f.) in Ved., f. in later Skr. heaven, the sky


----

xweḍa f. → xweḍA f.
Print error.

MW:
*  क्ष्वेडा : f. " the roaring of a lion " or " battle-cry " L.

----

yamasādana f. → yamasādana n.
Print error.

MW:
* यम-सादन [p= 846] : n. = -सदन q.v. AV.  TĀr.  &c [L=170501]
* सादन n. (= सदन) a seat, house, dwelling, place, home

----

kakuda ·f. → kakuda n. (m.).
Print error.

![image](https://cloud.githubusercontent.com/assets/14730665/11359496/71c4dbf0-925b-11e5-9216-3e759e27f4d7.png)
(The difference is in the accent).

MW:
* ककुद [p= 241] : mn. a peak, summit (…)
(I could find no ककुदा)

----

“keneṣitopaniṣada or kenopaniṣada ·f.”  → “keneṣitopaniṣad or kenopaniṣad ·f” (perhaps: “keneṣitopaniṣada n. or kenopaniṣad ·f.”)  
Print error / OCR error

![image](https://cloud.githubusercontent.com/assets/14730665/11359581/2257ae98-925c-11e5-9516-ccfd5faadba3.png)

MW:
* केने*षितो*पनिषद् [p= 309] : f. N. of an Up.  (beginning with the word केने*षितम्).
* केनो*पनिषद् [p= 309] : f. id. (beginning with केन). [L=55738]
* उप-निषद् 2 [p= 201] : f. (…)
* उप-निषद [p= 201] : n. = उप-निषद्2 above (esp. occurring ifc.) [L=34982]

----

“पूजक पूजक ·f. ­ worshipper (gen. or — °)”.  → “पूजक, पूजिका ·f. ­ worshipper (gen. or — °)”. [better: →“पूजक m., पूजिका ·f. ­ worshipper (gen. or — °)”
OCR error

![image](https://cloud.githubusercontent.com/assets/14730665/11359504/7e097484-925b-11e5-96cc-d02d347005d8.png)
 
MW:
* पूजक [p= 641] : mf(इका)n. honouring, respecting, worshipping, a worshipper (with gen. or ifc.) Mn.  MBh.  &c [L=127378]


----

pratyavekṣaṇa f.  → pratyavekṣaṇa n.
Print error.

MW:
* प्रत्य्-°अवे*क्षण [p= 676] : n. looking after, care, attention Kām.  Kull.  [L=134132]
* प्रत्य्-°अवे*क्षणा : f. (with Buddhists) one of the 5 kinds of knowledge Dharmas.  94.

----

prayuja f. → prayuj f.
Print/OCR error (poor print quality?)
 
![image](https://cloud.githubusercontent.com/assets/14730665/11359511/8a882818-925b-11e5-8ec4-03163a174096.png)

MW: 
* प्र-युज् b [p= 688] : f. (prob.) a team RV.  [L=136293]

----

śūraputra f. → śūraputrā f.
Lexicographer error.

MW:
* शूर-पुत्रा [p= 1086] : (शूर-) f. " having a heroic son ", the mother of a hero (applied to अदिति) ib. [L=220303]

----

MW:
śvetāśvataropaniṣada f. → śvetāśvataropaniṣad f. (or: śvetāśvataropaniṣada n.).
Print error.

MW:
* श्वेताश्वतरोपनिषद् [p= 1107] : f. N. of an उपनिषद् IW.  43 &c ( °षत्-प्रकाशिका f. °षद्दीपिका f. N. of Comms.) [L=224834]
* उप-निषद् 2 [p= 201] : f. (…)
* उप-निषद [p= 201] : n. = उप-निषद्2 above (esp. occurring ifc.) [L=34982]

----
sīmājñāna ·f. →sīmājñāna ·n.
Print error.

MW:
* अ-ज्ञान [p= 10] : n. non-cognizance; n. ignorance (…)

----

somejya ·f. → somejyā ·f.
Print error.

MW:
* सोमे*ज्या [p= 1251] : f. a सोम sacrifice ṠrS.  [L=253165]
* इज्या : f. a sacrifice, making offerings to the gods or manes Pāṇ.  3-3, 98 KātyṠr.  MBh.  Bhag.  Suṡr.  Ragh.  &c [L=28668]

----

Here ends the review.

**Comment by funderburkjim** [comment]
Re: somadhāra f. → somadhārā f.  Agree.(print error)
Ref MW:  सोम-धारा [p= 1250] : f. the milky way L.  [L=252817]
f. the sky, heaven W.  [L=252818]

**Comment by funderburkjim** [comment]
Re: `kakuda ·f. → kakuda n.`  I think it is 'kakud' f. (a typo - the virama is hard to read).

Ref MW:  ककुद् [p= 241] : f. a peak or summit (Lat. cacumen) [L=41418

**Comment by funderburkjim** [comment]
re `kṛkāṭa ·f. ­ the -> kṛkāṭa n.`  No, it is kfkAwI  (typo)  

Confirmed by MW:
कृकाट [p= 304] : n. the joint of the neck AV.  ix, 7, 1 [L=54720]
(H1B) कृकाटी : f. id. VarBṛS.  li, 9. [L=54721]

**Comment by funderburkjim** [comment]
re `add navamallikā (lost now)`   It is there as headword, no need to add.

**Comment by funderburkjim** [comment]
re cae:
```
:cae:pAduka:pAduka:t: f. -> (nothing - it is adjective)
:cae:pUjaka:pUjaka:t: f. -> (nothing - it is adjective)
:cae:pratyavekzaRa:pratyavekzaRa:t: f. -> (nothing - it is n.)
```

In cae dictionary, the printed text has many entries where there are multiple headword, separated by commas and where a single gender is shown, which seems to be based on the last word in the list.
The comments, based on reference to MW, suggest that the first word is probably an adjective in the first two cases and a neuter noun in the last case.

This paucity of gender-marking seems like an inherent weakness in the cae dictionary.

In the digitization of cae, @thomasincambodia seems to have listed all the words, as separate headwords and
copied the gender (f. in these cases) to all. 

I think we should, in these and similar cases, simply leave the gender un-marked (clearly f. is wrong), rather than infer a gender.

**Comment by funderburkjim** [comment]
re: `hastadhāraṇa ·f. = hastagraha; also help, assistance.`  
Comparing to MW, this could be either
   hastaDAraRA f. or hastaDAraRa n.

H3) हस्त-धारण [p= 1295] : n. holding by the hand, supporting, helping L.  [L=262193]
n. warding off a blow MW.  [L=262194]
n. stopping a blow with the hand ib. [L=262195]
(H3B) हस्त-धारणा : f. supporting, helping MBh.  [L=262196]
f. taking to wife, marrying Hariv.  Naish.  [L=262197]

I'll choose to change the gender, hastaDAraRa n.

**Comment by funderburkjim** [comment]
Ready to install.  Here are the normalized forms being used:
ap:samita:samit:t: first one (L=33932) 'War'
;----------------
bop:paNkta:paNkti:t:
;----------------
ben:Una:Una:t:  f. na -> f. na10 (poor print)
ben:Uzara:Uzara:t: f. ra -> f. ra10 (print smudge)
ben:kftya:kftya:n:false positive, as there is f. ya10. inside the article
ben:caritra:caritra:t: f. tra -> f. tra10 (poor print)
;----------------
; ejf:  Do the one from odile also
bur:SivIraTa:SivIraTa:p: f. -> m.
bur:kIwaja:kIwajA:p:
bur:somaDAra:somaDArA:p: ref. MW 
bur:kzveqa:kzveqA:p:  in text xweḍa f. ->xweḍā f. 
bur:dARqA:dARqA:p: in dARqAjinika f. -> a.
bur:yamasAdana:yamasAdana:P: f. -> n.
;----------------
cae:aBra:aBri:t:
cae:ucCrita:ucCriti:t:  2nd homonym
cae:kakuda:kakud:t: 1st homonym
cae:kfkAwa:kfkAwI:t:
cae:kenezitopanizada:kenezitopanizada:p: kenezitopanizada n. or kenezitopanizad f. Added 'n.'
cae:cakoranetra:cakoranetra:n:  
cae:juwaka:juwaka:t: f.->n.
cae:navamAlika:navamAlikA:t:
cae:pAduka:pAduka:t: f. -> (nothing - probable adjective)
cae:pUjaka:pUjaka:t: f. -> (nothing - probable adjective)
cae:pratyavekzaRa:pratyavekzaRa:t: f. -> (nothing - probable neuter)
cae:prayuja:prayuj:p: poor print quality
cae:makzika:makzika:t: f.->m.
cae:madanaleKa:madanaleKa:t: f. -> m.
cae:manaHSila:manaHSila:t: f. -> m. n.
cae:manIzita:manIzitA:t:
cae:mAnuza:mAnuza:n: false positive
cae:likza:likza:t: f.->s.
cae:leSya:leSya:t: f. -> (nothing - probable adjective)
cae:vITika:vITika:t: f.->s.
cae:SalAka:SalAka:t: f.->m.
cae:SUraputra:SUraputrA:p:  Confer MW
cae:SvetASvataropanizada:SvetASvataropanizad:t:
cae:saMrakzaka:saMrakzaka:t:f. -> (nothing - probable m. )
cae:saMjYa:saMjYa:n: multiple headwords, complicated to straighten out
cae:sImAjYAna:sImAjYAna:p: f.->n.
cae:somejya:somejyA:p:
cae:hastaDAraRa:hastaDAraRa:p:f.->n.
cae:hiraRyamaya:hiraRyamaya:n: false positive
```

**Comment by funderburkjim** [comment]
One interesting note about BUR is that many compounds appear as 'subheadwords' , and are NOT currently included in the 'official' headword list as represented in the burhw2.txt file.

**Comment by funderburkjim** [comment]
Corrections for all dictionaries now installed.

Remember, revisions are possible.  This was a complicated batch, and I may have made a wrong choice or some other mistake.

Optimistically, I'll go ahead and close issue.

**Comment by gasyoun** [comment]
'kakud' f. indeed.
