### ISSUE TITLE
aFem Manual Processing, Part 4 (GRA, MW)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#170]
_GRA_

* ásita, fem. ásiknī
* çîtaka, f. çītikā 

false positives

**Comment by gasyoun** [comment]
_MW_

* ati--katha [p= 12,2] [L=2569] -> ati--kathā [p= 12,2] [L=2569] (OCR error, article splitting)

![thora](https://cloud.githubusercontent.com/assets/80761/11348354/2cddf054-9237-11e5-8880-01e7276c4987.PNG)

**Comment by gasyoun** [comment]
* abhi-marṣa [p= 67,3] [L=12103.51] -> abhi-marṣā (OCR error, article splitting)

![abhi](https://cloud.githubusercontent.com/assets/80761/11380045/d32ae318-9304-11e5-8ca4-a454ced5a039.PNG)

**Comment by gasyoun** [comment]
* avara--kaṅka -> avara--kaṅkā (print error)

![avara](https://cloud.githubusercontent.com/assets/80761/11380283/2ac6c50a-9306-11e5-9f5b-4ce500b9496d.PNG)

**Comment by gasyoun** [comment]
* ikṣu--śalaka -> ikṣu--śalākā/ (OCR error)

![ikshu](https://cloud.githubusercontent.com/assets/80761/11410133/1b5e7dd0-93d6-11e5-91e0-e5174ef06325.PNG)

**Comment by gasyoun** [comment]
* upala [p= 205,3] [L=35620] -> upalā (OCR error, article splitting)
upala [p= 205,3] [L=35621] -> upalā (OCR error, article splitting)

![upala](https://cloud.githubusercontent.com/assets/80761/11430403/32d10f0c-9497-11e5-9c96-f28e0954c4ae.PNG)

**Comment by gasyoun** [comment]
* karkaśa--cchada -> karkaśa--cchadā (OCR error, article splitting)

![karkasha](https://cloud.githubusercontent.com/assets/80761/11443932/7aeda82c-9532-11e5-936d-df02d265f36b.PNG)

**Comment by gasyoun** [comment]
* kilikila [L=50616] -> kilikilā (OCR error, article splitting)

![kilikila](https://cloud.githubusercontent.com/assets/80761/11445306/29bc7ad2-953c-11e5-9bbe-66644ea01b41.PNG)

**Comment by gasyoun** [comment]
* kftArTata -> kftArTatA (OCR error, article splitting)

![krita](https://cloud.githubusercontent.com/assets/80761/11446635/c88c90da-954a-11e5-8838-0f8c40c3ef3d.PNG)

**Comment by gasyoun** [comment]
* gandhá--phala [L=63084] -> gandhá--phalā
-> f., the plant Priyaṃgu

* gandhá--phala [L=6308?] -> gandhá--phalī
f. = -mohinī L.  -> f., the plant Priyaṃgu  = -mohinī L.  

![gandha](https://cloud.githubusercontent.com/assets/80761/11448532/41792556-956b-11e5-8427-760ab057dcf1.PNG)

**Comment by gasyoun** [comment]
* gandhá--mūla [L=63124] -> gandhá--mūlā
the Olibanum tree

* gandhá--mūla [L=63124] -> gandhá--mūlī
the Olibanum tree

![mula](https://cloud.githubusercontent.com/assets/80761/11454483/98666364-963e-11e5-8029-d08ed388a39d.PNG)

**Comment by gasyoun** [comment]
* girí--sutá [L=65248] -> girí--sutā

![suta](https://cloud.githubusercontent.com/assets/80761/11454527/bb2cd300-963f-11e5-84bd-9c61606e76ff.PNG)

**Comment by gasyoun** [comment]
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/174 MW continued.

**Comment by funderburkjim** [comment]
@zaaf2   Were you going to review this one and #174 ?  If so, I'll wait for your review.  Otherwise, I'll go ahead and start the installation.

**Comment by funderburkjim** [comment]
I'm going ahead and preparing installation.

Re ā-kāṅkṣa [p= 126,3] [L=22087] -> ā-kāṅkṣā (OCR error)
Also has different meaning than "f. (in Gr.) need of supplying a word or period for the completion of the sense Sāh. &c ". So 2 mistakes, once OCR, another lost text in OCR.

I don't see 2nd mistake regarding 'lost text'.

**Comment by funderburkjim** [comment]
Re `kācchaka [L=47336.3] -> kācchakā (OCR error, article splitting)`
 
This is a difficult one .  It is possible that that last form 
`a kind of fragrant earth (cf. काक्षी) L.  [L=47336.3]`

should **only** imply the form kAcCI  (which is present as L=47336.1).
Since the printed text shows `(I) f. a kind of fragrant earth`,  I would guess that, if this entry
applies to a feminine form of kAcCaka, then that feminine form would end in long I, not long A,

So I am for now entering the change as
```
mw:kAcCaka,47336.3:kAcCakI:t: Possibly the only feminine form is kAcCI ?
``
but wonder if the 47336.3 record should be deleted.

**Comment by funderburkjim** [comment]
re `gandhá--phala [L=6308?] -> gandhá--phalī (OCR error, article splitting)'  Used L=63084.

This is only error under ganDaPala that I see.

**Comment by funderburkjim** [comment]
Re mw:garBADAna,64117:garBADAna:t: f.->n.

This referential text `cf. RTL.  p.353 `  could be merged into the prior record, and 64117 deleted,
as @gasyoun  suggests.

However, it is easier just to change 'f' gender to inherited 'n.', so I'm taking this route.

**Comment by funderburkjim** [comment]
Re `gava,64340.2`  
Change to gavI

![image](https://cloud.githubusercontent.com/assets/6393033/11577198/0814a01e-99ea-11e5-9e09-b5855be4f35b.png)

**Comment by funderburkjim** [comment]
@gasyoun @drdhaval2785   Good to identify these 'article splitting' errors!

**Comment by funderburkjim** [comment]
Here are the normalized corrections:
```
mw:atikaTa,2569:atikaTA:t: error, article splitting
mw:atiCattraka,2620:atiCattrakA:t: error, article splitting
mw:abADa,10973:abADA:t: error, article splitting
mw:aBimarSa,12103.1:aBimarSA:t: mfn. -> f(A)
mw:aBizavaRa,12615:aBizavaRIs:t: Add to Dual Plural
mw:aByuddfzwa,13578:aByuddfzwA:t: error, article splitting
mw:avarakaNka:avarakaNkA:p: f. name of city should end in A
mw:AkANkza,22087:AkANkzA:t: error, article splitting
mw:ikzuSalaka:ikzuSalAkA:t:
mw:itikaTa,28751:itikaTA:t:error, article splitting
mw:upala,35620:upalA:t:error, article splitting
mw:upala,35621:upalA:t:error, article splitting
mw:usra,37912:usrA:t: could be considered print error?
mw:usra,37913:usrA:t:
mw:usra,37914:usrA:t:
mw:usra,37915:usrA:t:
mw:eraka,40134:erakA:t:error, article splitting
mw:Opala,41091:OpalA:t:error, article splitting
mw:karkaSacCada,44739:karkaSacCadA:t:error, article splitting
mw:kAcCaka,47336.3:kAcCakI:t: Possibly the only feminine form is kAcCI ?
mw:kARqapuzpa,47525:kARqapuzpA:t:error, article splitting
mw:kilikila,50616:kilikilA:t:error, article splitting
mw:kUrma,54067:kUrmI:t:error, article splitting
mw:kftArTata:kftArTatA:t:
mw:kowa,56436:kowA:t:error, article splitting
mw:kzIraSukla,59765:kzIraSuklA:t:error, article splitting
mw:ganDaPala,63084:ganDaPalI:t:error, article splitting
mw:ganDamUla,63124:ganDamUlA:t:error, article splitting
mw:garBADAna,64117:garBADAna:t: f.->n.(inherited)
mw:gava,64340.2:gavI:t:error, article splitting
mw:girisuta,65248:girisutA:t:error, article splitting
mw:gumPana,65975:gumPanA:t:error, article splitting
mw:gfhagolaka,66544:gfhagolikA:t:error, article splitting
```

**Comment by funderburkjim** [comment]
Note that in most cases, where an L-number was required to identify the record to change,  that L number was added to the 'old' (2nd) field.

For the 'generate.py' used here,  this 2nd field was allowed the optional form `key1,L`.  

If the L-number is not needed, as in avarakaNka example above, then this second field
has the prior form `key1`.

This form could be written:
```
dictcode:lnum[,currenthw]:correcthw:errorcode:note
```:
Since I've already written the small modification to this issue-170 generate.py,  I guess I prefer 
this form to that suggested at #154.

**Comment by drdhaval2785** [comment]
@funderburkjim Agree to your suggested form.
And share your small-modified generate.py for world to see.

**Comment by zaaf2** [comment]
@funderburkjim  Sorry I missed the notification to intervene in this issue.

Re `kācchaka [L=47336.3] -> kācchakā (OCR error, article splitting)`
I vote that the 47336.3 record (f. काच्छक) should be deleted.

---

Re `garbhā* dhāna [L=64117] f. cf. RTL. p.353 -> kill entry`
I agree with @gasyoun . This should not appear as an entry. It is just a source reference. In this case, f. is an abbreviation for ‘[and the] following [page]’, or something like that. When there is more than one page, it is written ff.
![image](https://cloud.githubusercontent.com/assets/14730665/11583566/0a87bb92-9a3a-11e5-8b27-43dd8301a983.png)
 
---

I agree (belatedly) with the other changes proposed.

**Comment by gasyoun** [comment]
@zaaf2 thanks for the verification. It's badly needed. Still hope your PW checking will go on, eagerly waiting for it to go no. Good luck to all three of us in hunt for mistakes. Sampada seems to be out of the game, @funderburkjim ?

**Comment by funderburkjim** [comment]
@zaaf2 or @drdhaval2785 

This change 'mw:aBizavaRa,12615:aBizavaRIs:t: Add to Dual Plural'   
requires that I add an entry to the [DualPlural.txt]() file of MWlexnorm.

The reason is that the new headword is not the usual 'stem form' of MW headwords, but is an
inflected form (f1p  feminine-case1 (Nominative)-plural)  of some unspecified stem. 

My question for you is, what is that stem?  

Perhaps the stem would be aBizavaRI  , although the inflected form suggests that the declension
paradigm would be like that for 'DI'  rather than like that for 'nadI'.
If so, the DualPlural entry would be:
```
aBizavaRIs:aBizavaRI:12615:aBizavaRIs:f1p
```

Is this right?

**Comment by funderburkjim** [comment]
Peter answered question re stem.  Namely that it is `aBizavaRI`.  

He further added that the declension is like nadI, BUT explained why the nominative plural shows
as 'Is'  rather than the usual 'yaH'  (nadyaH) that most grammar tables show:

```
The stem is aBizavaRI f. and it declines like nadI.  Vedic in general permits the homorganic long vowel in the nominative plural (as in the accusative plural).
```
