### ISSUE TITLE
Convention 1.2 violations

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#171]
While examininig the convention 1.2 in the hwnorm1 repository

The following results were obtained which contain potential suspect words.
[txt](https://github.com/sanskrit-lexicon/hwnorm1/blob/master/proberrors/12violation.txt) and [html](http://sanskrit-lexicon.github.io/hwnorm1/proberrors/12violation.txt.html)

HTML file to be downloaded locally. It has links to webpage and PDF of the word in that dictionary.

Total of 65 entries to examine

```
aQaMQolayat:SCH
aMBikANkzA:CAE
araMDuza:AP
arkaMparRa:SHS
arjunaMcCavi:SHS
AMBu:CAE
utkaMpitA:SCH
OqupiMka:AP
kacawatapagajaqaMdaba:PW
kalakaRWiMkA:CAE
kavirAjavasuMGara:PW
keSapaMkti:SHS
guMkvaRa:MW
GarmiMta:CAE
caMdanIyA:AP
cUcuMka:CAE
jagaJaMpaRa:SCH
jaMpatI:PW
jaMpatI:PWG
jamBaMjamBam:MW
jAMDita:MW
jAyaMpatI:PW
jitaMte:PW
JaMkAtin:CCS
JaMJA:MD
tarupaMkti:SHS
tarupaMkti:WIL
tAwaMkati:SCH
devavadDaMki:SHS
dvaMda:MW
dvaMda:PW
dvaMda:PWG
dvaMdaBUta:PW
pakzaMbfhat:SCH
pacaMbacA:PW
paYcajitaMte:MW
paYcajitaMte:PW
pAzaMqatA:CCS
pratibiMba:CCS
pratibiMbita:CCS
BaMBaH:AP
BIMti:CAE
BeMpura:PWG
BrAMtar:CCS
mAMkis:CCS
mimaMkzA:AP
mruMca:WIL
vAMgguRa:PWG
visPuliMga:WIL
SilaMDira:PWG
SiliMDra:PW
SItIMBAva:PW
SraMB:CAE
SrOtAMqabilA:MW
sAmagAnAMCandas:MW
sArvaMBOmam:AP
sumuRqIMka:PW
suMbrahman:CCS
suSlizwamaMDi:PW
sfMjayAH:AP
strISUdrAdInAMdevArcanavicAra:MW
svaDIMti:PWG
havirAhuMti:CAE
huMBA:AP
hEMqimba:PWG
```

**Comment by drdhaval2785** [comment]
```
sch:aQaMQolayat:aQaMQolayat:n:Questionable form marked by dictionary itself. Leave it as it is.
cae:aMBikANkzA:aBikANkzA:t:print smudge
ap:araMDuza:araMDuza:t:Confusion of G and D in Sanskrit. 'Sounding loudly' has more relevance to 'Guz'.
shs:arkaMparRa:arkaMparRa:t:print smudge
shs:arjunaMcCavi:arjunacCavi:t:pring smudge
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11745042/2bb19a5c-a03b-11e5-8e74-36cbbef202b0.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11745054/3e6ba08e-a03b-11e5-8be2-76e7fd0d2244.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11745083/7367955e-a03b-11e5-9cdc-96a11ad25bf5.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11745112/ae3f0f5e-a03b-11e5-9802-2921f91dcf57.png)

**Comment by drdhaval2785** [comment]
```
cae:AMBu:ABu:t:pring smudge
sch:utkaMpitA:utkampitA:t:c
ap:OqupiMka:Oqupika:t:pring smudge
pw:kacawatapagajaqaMdaba:kacawatapagajaqadaba:t:
cae:kalakaRWiMkA:kalakaRWikA:t:print smudge. MW and PW has kalakaRWikA
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11745145/e9db2ab6-a03b-11e5-9e24-a2907508b67e.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11745208/76f3f324-a03c-11e5-8678-06c2aa65ff6c.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11745214/93c7c480-a03c-11e5-9c5d-47678221aab0.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11745235/be93b426-a03c-11e5-9726-e67bfcaecb80.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11745247/e158b75e-a03c-11e5-894a-d8fa0cd426dd.png)

**Comment by drdhaval2785** [comment]
```
pw:kavirAjavasuMGara:kavirAjavasuMDara:t:D and G confusion.
shs:keSapaMkti:keSapaNkti:t:convention error. SHS has paNkti as headword.
mw:guMkvaRa:guMkvaRa:n:It is because 'guM' is a headword and 'kvaRa' is subentry. Not as a conjoint entry.
cae:GarmiMta:GarmiMta:t:print smudge
ap:caMdanIyA:caMdanIyA:t:c
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11745933/5c6b5038-a041-11e5-82cd-94e836870efa.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11747765/0f614018-a04b-11e5-8bd4-0a9affcb22b0.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11747787/264f7506-a04b-11e5-8806-3d4ba92c5ff6.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11747904/c1421398-a04b-11e5-82c5-314963581ffe.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748197/1e9ec3dc-a04d-11e5-813c-e0599c81f423.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748219/3d58d5b0-a04d-11e5-9c05-f6d8d5f48912.png)

**Comment by drdhaval2785** [comment]
```
cae:cUcuMka:cUcuka:t:print smudge
sch:jagaJaMpaRa:jagaJampaRa:t:Convention error. The entry is marked by ? by author.
pw:jaMpatI:jampatI:t:c
pwg:jaMpatI:jampatI:t:c
mw:jamBaMjamBam:jamBaMjamBam:n:Compound word.
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11748293/973a4028-a04d-11e5-9e83-97e62b39be9e.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748417/3132ae04-a04e-11e5-90ec-72b68693b157.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748441/60cc46de-a04e-11e5-93a1-1c881f3bdd10.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748462/70497578-a04e-11e5-9404-d6bc6ecdfa5f.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748492/9ce0ec7e-a04e-11e5-9dd1-2de57765ef4e.png)

**Comment by drdhaval2785** [comment]
```
mw:jAMDita:jAMDita:n:compound
pw:jAyaMpatI:jAyampatI:t:c
pw:jitaMte:jitante:t:c
ccs:JaMkAtin:JaMkArin:t:JaM seems to be a valid thing. Many dictionaries are having this. So keeping it as it is.
md:JaMJA:JaMJA:n:
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11748571/e9bc1aa0-a04e-11e5-9c97-81fc43585a31.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748598/0b73da16-a04f-11e5-97a2-04f2f555cf3d.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748683/6d0b8a08-a04f-11e5-993d-61ccd50bfe28.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748704/8e146bf2-a04f-11e5-9f92-6dcd04451b27.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11748751/d6dc31a8-a04f-11e5-8eda-dd48694addc9.png)

**Comment by drdhaval2785** [comment]
```
shs:tarupaMkti:tarupaNkti:t:c
wil:tarupaMkti:tarupaNkti:t:c
sch:tAwaMkati:tAwaNkati:t:c
shs:devavadDaMki:devavardDaki:t:vardDaki is carpenter.
mw:dvaMda:dvaMda:n:compound
pw:dvaMda:dvaMda:n:compund
pwg:dvaMda:dvaMda:n:compound
```

![capture](https://cloud.githubusercontent.com/assets/5755132/11749802/ccdb3f22-a055-11e5-8134-0413af00c343.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11749837/0f01495a-a056-11e5-94a9-f017813b3ad4.png)

**Comment by drdhaval2785** [comment]
```
sch:pakzaMbfhat:pakzaMbfhat:n:compound. Also the author marked it with '!'
pw:pacaMbacA:pacaMbacA:n:compound
mw:paYcajitaMte:paYcajitaMte:n:compound
pw:paYcajitaMte:paYcajitaMte:n:compound
ccs:pAzaMqatA:pAzaRqatA:t:print has R
ccs:pratibiMba:pratibimba:t:
ccs:pratibiMbita:pratibinbita:t:
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11749991/eb934ec2-a056-11e5-962a-65a2494e5217.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11750063/5fe87770-a057-11e5-8472-0a2bdaee17aa.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11750092/8d83d972-a057-11e5-9fb2-803ce6c93cf0.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11750103/a23503d2-a057-11e5-9a75-30a840e826b3.png)

**Comment by drdhaval2785** [comment]
```
ap:BaMBaH:BaMBaH:n:Seems a valid word
cae:BIMti:BIti:t:print smudge
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11750160/f2004098-a057-11e5-9f93-4fea05a4efe8.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11750178/06d60dae-a058-11e5-9da7-fe64b1e651f0.png)

**Comment by gasyoun** [comment]
Halfway done?

**Comment by drdhaval2785** [comment]
Yes. Will complete this in single issue. Maybe on monday. Only 65 entries
to be checked.

**Comment by funderburkjim** [comment]
@drdhaval2785  These are some places where I think the 'new' cases had typos.  I'll use the 2nd forms as indicated, unless you say otherwise.

Re ap:araMDuza:araM**D**uza:t:Confusion of G and D in Sanskrit.
I think you meant
ap:araMDuza:araM**G**uza:t:Confusion of G and D in Sanskrit.

Re shs:arkaMparRa:arka**M**parRa:t:print smudge.
I think you meant (no M)
shs:arkaMparRa:arkaparRa:t:print smudge

Re cae:GarmiMta:Garmi**M**ta:t:print smudge
I think you meant (no M)
cae:GarmiMta:Garmita:t:print smudge

Re ap:caMdanIyA:ca**M**danIyA:t:c
I think you meant
ap:caMdanIyA:ca**n**danIyA:t:c

Re pw:jitaMte:jita**n**te:n:compound
I think you meant
pw:jitaMte:jita**M**te:n:compound

Re ccs:pratibiMbita:pratibi**n**bita:t:
I think you meant
ccs:pratibiMbita:pratibi**m**bita:t:

**Comment by funderburkjim** [comment]
Not yet ready for installation.

**Comment by gasyoun** [comment]
With bolding even better.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/171#issuecomment-164578939 I agree with all of them.
Made corresponding corrections in the original submissions too.

**Comment by drdhaval2785** [comment]
43 to 45
```
pwg:BeMpura:BeMpura:n:Name of a location. Maybe influenced by local pronounciation.
ccs:BrAMtar:BrAtar:t:Accent mark wrongly read as anusvAra
ccs:mAMkis:mAkis:t:Accent mark wrongly read as anusvAra
```

![capture](https://cloud.githubusercontent.com/assets/5755132/11801671/41f76942-a30e-11e5-8c4b-1ed43a010f14.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11801663/2d5d1d38-a30e-11e5-8dce-fa716ae73573.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11801693/6cf0ebd2-a30e-11e5-8924-178e1a8bd503.png)

**Comment by drdhaval2785** [comment]
46 to 50
```
ap:mimaMkzA:mimaMkzA:n:Not sure. This is a verb derivation. Maybe M is justified.
wil:mruMca:mruMca:n:Dictionary has both mruMca and mruYca in the entry
pwg:vAMgguRa:vAgguRa:t:print smudge
wil:visPuliMga:visPuliNga:t:Convention error. WIL has 'liNga' as headword and not 'liMga'.
pwg:SilaMDira:SilaMDira:n:Dictionary itself says that it is 'wohl fehlerhaft' i.e. 'probably erraneous'.
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11801814/6fd50d46-a30f-11e5-9107-436914bc4232.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11801824/8d43299e-a30f-11e5-83d0-70151828d7e3.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11801860/ce606af4-a30f-11e5-9043-ee465d71840c.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11801845/be8bc3a8-a30f-11e5-8eb0-93f16b7c736c.png)

**Comment by drdhaval2785** [comment]
51 to 55
```
pw:SiliMDra:SiliMDra:n:Compound. 'wohl fehlerhaft'
pw:SItIMBAva:SItIMBAva:n:w
cae:SraMB:SraMB:n:Verb. Both reading in explanation.
mw:SrOtAMqabilA:SrOtAMqabilA:t:
mw:sAmagAnAMCandas:sAmagAnAMCandas:n:Two words
```
![capture](https://cloud.githubusercontent.com/assets/5755132/11801957/b6122f68-a310-11e5-8497-6e4d607dcc3f.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11801977/033ab260-a311-11e5-8611-a20f934c9ad2.png)
![capture](https://cloud.githubusercontent.com/assets/5755132/11801987/39475458-a311-11e5-9fd5-eaa5b9fa3245.png)

**Comment by drdhaval2785** [comment]
56 to 60
```
ap:sArvaMBOmam:sArvaBOmam:t:No anusvAra
pw:sumuRqIMka:sumuRqIka:t:
ccs:suMbrahman:subrahman:n:accent anusvAra confusion
pw:suSlizwamaMDi:suSlizwasaMDi:t:sam has the tendency to generate 'M' all across dictionaries.
ap:sfMjayAH:sfMjayAH:n:Compound
```

![capture](https://cloud.githubusercontent.com/assets/5755132/11802044/e58aba84-a311-11e5-89dc-945375a2ee3d.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/11802361/dd550aaa-a315-11e5-80a5-b9732373a3a0.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/11802371/f18bd544-a315-11e5-988e-d7a96d079863.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/11802379/1efae83a-a316-11e5-8844-0424dd2181c5.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/11802419/7cbd8bc6-a316-11e5-8499-fefc426e921c.png)

**Comment by drdhaval2785** [comment]
61 to 65
```
mw:strISUdrAdInAMdevArcanavicAra:strISUdrAdInAMdevArcanavicAra:n:Two words
pwg:svaDIMti:svaDIMti:t:print smudge
cae:havirAhuMti:havirAhuti:t:print smudge
ap:huMBA:huMBA:n:Compound
pwg:hEMqimba:hEMqimba:t:print smudge
```

![capture](https://cloud.githubusercontent.com/assets/5755132/11802463/fa68b0d2-a316-11e5-9ba3-e7eebd81e0ce.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/11802471/0efb5cd4-a317-11e5-89f0-07de0f824a93.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/11802478/2c9dd758-a317-11e5-9414-ef601f9a7b0b.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/11802492/57bb4a92-a317-11e5-9edb-04f70f72f8a3.png)

![capture](https://cloud.githubusercontent.com/assets/5755132/11802499/72e5043e-a317-11e5-83ee-0c71c1ded1f4.png)

**Comment by drdhaval2785** [comment]
@zaaf2 Please review the corrections.
@funderburkjim - From my side the submission is over. When found OK, you may install the corrections.

The submission in standard format is 
https://github.com/sanskrit-lexicon/hwnorm1/blob/master/proberrors/12submission.txt
If you want to save labor of searching thread and copy pasting.

**Comment by zaaf2** [comment]
Re shs:arjunaMcCavi:arjunacCavi:t:print smudge

Perhaps it is a print/lexicographer error, since the word Devanagari order is correct:

![capture](https://cloud.githubusercontent.com/assets/5755132/11745112/ae3f0f5e-a03b-11e5-9802-2921f91dcf57.png)
Cf. MW, where arjunacCavi comes before arjunatas:
 
![image](https://cloud.githubusercontent.com/assets/14730665/11804119/fff64ec4-a2df-11e5-91cc-e6c0f87a5177.png)

**Comment by zaaf2** [comment]
Re:
```
ap:caMdanIyA:candanIyA:t:c
sch:jagaJaMpaRa:jagaJampaRa:t:Convention error. The entry is marked by ? by author.
pwg:jaMpatI:jampatI:t:c
wil:tarupaMkti:tarupaNkti:t:c
sch:tAwaMkati:tAwaNkati:t:c
wil:visPuliMga:visPuliNga:t:Convention error. WIL has 'liNga' as headword and not 'liMga'.
```

Those are not ‘t’ errors, but a ‘p’ incorrect (alternative?) way to represent the nasal before a dental or a labial. 


---

Re pw:jAyaMpatI:jAyampatI:t:c
The dictionary has jAyaMpatI as `perhaps only an incorrect form for जायापती` (`wohl nur fehlerhaft für जायापती`)

---

Re mw:SrOtAMqabilA:SrOtAMqabilA:t:
You mean: mw:SrOtAMqabilA: SrOtARqabilA:t:

---

Re ap:sArvaMBOmam:sArvaBOmam:t:No anusvAra
Confirmation: [Apte Practical Sanskrit-English Dictionary, revised edition](http://dsalsrv02.uchicago.edu/cgi-bin/philologic/search3advanced?dbname=apte&query=%E0%A4%B8%E0%A4%BE%E0%A4%B0%E0%A5%8D%E0%A4%B5%E0%A4%AD%E0%A5%8C%E0%A4%AE%E0%A4%AE%E0%A5%8D&matchtype=exact&display=utf8)

---

Re pwg:svaDIMti:svaDIMti:t:print smudge
You mean: pwg:svaDIMti:svaDIti:t:print smudge

---

Re pwg:hEMqimba:hEMqimba:t:print smudge
You mean: pwg:hEMqimba:hEqimba:t:print smudge

---

End of review.

**Comment by drdhaval2785** [comment]
@zaaf2 I agree with your proposal.
Now the file https://github.com/sanskrit-lexicon/hwnorm1/blob/master/proberrors/12submission.txt has the file updated per zaaf2's suggestions.
@funderburkjim may please use this file.

**Comment by funderburkjim** [comment]
Used the 12sumbission.txt for changes.
10 dictionaries involved.

All changes installed, 
s3 backups made.

**Comment by zaaf2** [comment]
@drdhaval2785 `M-c-Y-t is the alphabetical order in Devanagari` 

You are right. If M in arjunaMcCavi represents the nasal adapted to the following consonant, it should correspond to Y, and the word would be placed before arjunatas. I wrongly considered M in this case to represent m, which of course comes after t. Thanks.
