### ISSUE TITLE
automate sanhw1.txt and sanhw2.txt regeneration

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#175]
@funderburkjim 
Now that we have arrived at a consensus on how to give entries in a specific format for processing, would it be a bad idea to keep our sanhw1.txt and sanhw2.txt at CORRECTIONS repository automatically updated when we make some changes to the cologne server ?

E.g. Right now the declaration says that the corrections have been made for XYZ dictionaries.
But the sanhw1.txt and sanhw2.txt have not been changed.

some shell script would keep them in sync I guess.

This would also obviate the need of fortnightly publication of rejuvenated sanhw1.txt and sanhw2.txt which I and @gasyoun were asking.

**Comment by gasyoun** [comment]
Indeed, shell above all. Does not seems trickier than implementing one batch of corrections manually.

**Comment by funderburkjim** [comment]
Have added a script on Cologne and one in local CORRECTIONS repository to regenerate sanhw1/2.

redo_update.sh is the one at Cologne:
```
echo "remaking sanhw1.txt..."
python sanhw1.py sanhw1.txt
echo "remaking sanhw2.txt..."
python sanhw2.py sanhw2.txt
echo "remaking sanhw12.zip"
rm sanhw12.zip
zip sanhw12.zip sanhw1.txt sanhw2.txt
echo "sanhw1/redo_update.sh done"
```
It takes a minute or so.

The CORRECTIONS one is [redo_sanhw12.sh](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/redo_sanhw12.sh).

The end result is that the sanhw1.txt and sanhw2.txt files in this CORRECTIONS repository are 
updated.

This will now be part of the correction installation process.

**Comment by drdhaval2785** [comment]
Lovely..

**Comment by gasyoun** [comment]
So even the shell will be launched automatically, without clicking on it by Jim?
