### ISSUE TITLE
Earlier efforts documentation

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#182]
@funderburkjim 
As I can see from https://github.com/sanskrit-lexicon/CORRECTIONS/issues/61, https://github.com/sanskrit-lexicon/CORRECTIONS/issues/63 etc, there was some research done earlier in Wilson (and I am sure for some other dictionaries also).

I am not aware where their working papers are.

I know it would take a lot of your time.
But put them together here. So that we have a complete account of pending works of yore.

**Comment by gasyoun** [comment]
In 20017 :cactus:

**Comment by drdhaval2785** [comment]
Let us close this issue. 
Jim has documented things a lot in the intervening time and we know quite a bit about his pythons now.
