### ISSUE TITLE
Non-Sanskrit alphabets in headwords

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#186]
Code - https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/nonalphabet/nonalph.sh 
Output - https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/nonalphabet/noalph.txt

Logic - Words having non-sanskrit alphabets.
Needs to be examined.

**Comment by drdhaval2785** [comment]
Preliminary examination says 
1. Only PD has a space in key1. It should be killed for uniformity.
2. '|' is always proper. ळ्ह
3. anvA\hartavE\:PD;106264 is the only entry having '\'

**Comment by drdhaval2785** [comment]
Once Jim installs these generic corrections, I will regenerate this list and then someone may work one by one.

**Comment by gasyoun** [comment]
Good catch!

**Comment by gasyoun** [comment]
@funderburkjim simple, yet needed changes. Otherwise Dhaval's list is full of convertion dirt, hardly valuable. Otherwise very interesting and fruitful.

**Comment by funderburkjim** [comment]
Re `1. Only PD has a space in key1. It should be killed for uniformity.`  This was done in #217.

**Comment by funderburkjim** [comment]
Re ` '~S' in PD always stands for 'MS'. `

I agree, *provided* we restrict discussion to headwords. There are three cases:
```
pd:aDaHSAKAcaturTA~Sa:aDaHSAKAcaturTAMSa:t:
pd:aDarmA~Sa:aDarmAMSa:t:
pd:aDarmA~SodBava:aDarmAMSodBava:t:
```
The '~' is an SLP1 nasalization; it is used to represent candra-bindu.  There are 50 cases in the
text of the dictionary of the form ~S. Some of these, at least are of the form V~S and properly code candra-bindu over vowel V; some of these text examples could be wrong codings of VMS, but I didn't examine.

**Comment by gasyoun** [comment]
> I agree, provided we restrict discussion to headwords

Sure.

**Comment by funderburkjim** [comment]
corrections installed.

**Comment by gasyoun** [comment]
It's a mix of `pre` and `sumbission`. @drdhaval2785 would you think it's a good idea to leave it open?
