### ISSUE TITLE
Transcoder issue - |

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#187]
![capture](https://cloud.githubusercontent.com/assets/5755132/11568150/9621be0c-9a10-11e5-90f5-c809a61a6526.png)

Shows ळ्ह्‌
Whereas it should be ळ्ह

**Comment by gasyoun** [comment]
@funderburkjim got the message?

**Comment by funderburkjim** [comment]
@gasyoun  No, I'm so far behind that I had not attended to this.

However, now it is solved  (a change to MWScan/2014/web/utilities/transcoder/slp1_deva.xml).

**Comment by gasyoun** [comment]
Great! But MW Transcoder means that the issue is solved only for MW and only for web. Will the pythons work properly in other places as well?

**Comment by funderburkjim** [comment]
Hard to answer definitively.  Should be solved for MW, and, when I do s3 backup of mw.

Each dictionary is separate, so there could be dictionaries where there is a '|' and where the
slp1_deva.xml for that dictionary needs modification.  You could check the web display for
those dictionaries which have a headword with a '|' that Dhaval recently made
[here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/nonalphabet/noalph.txt).

If there is a problem with them, I can change the slp1_deva.xml that they use.  Probably would be good if you checked this while it's on our minds.
