### ISSUE TITLE
PW 'ls' corrections, part 2

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#194]
These corrections based on https://github.com/sanskrit-lexicon/PWK/issues/18.

This continues work of #146.

**Comment by funderburkjim** [comment]
3015 corrections were generated for PW, and have been installed. Some further details in PWK#18 above.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/PWK/issues/20
Cases 37-60 of those not matching are continued.
Reopening it, so that it is visible.

**Comment by funderburkjim** [comment]
Let's put the corrections relating to PWK#20 into a new corrections issue.
The reason is that in the processing, regenerate.py needs to have a corrections issue number to use.  The number 194 is already used (by the pwk#18 corrections).  So, I'm reclosing this issue, and making another corrections issue corresponding to pwk#20.

**Comment by drdhaval2785** [comment]
Got it.
Thanks.
