### ISSUE TITLE
CCS accent mark and anusvAra confusion

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#201]
Recently while submitting corrections for https://github.com/sanskrit-lexicon/CORRECTIONS/issues/171#issuecomment-164638360
I came across two consecutive errors in CCS where the accent mark was mistaken for anusvAra.
See
```
ccs:BrAMtar:BrAtar:t:Accent mark wrongly read as anusvAra
ccs:mAMkis:mAkis:t:Accent mark wrongly read as anusvAra
```

There are chances that in CCS, other places may also have similar error.
It needs some extraction programmatically. 
So noting it down here, so that we are reminded of that work.

**Comment by gasyoun** [comment]
CCS can have everything. It has more mistakes than words.

**Comment by drdhaval2785** [comment]
Testing HTML
http://sanskrit-lexicon.github.io/CORRECTIONS/dhaval/ccsanusvara/ccsanusvara.html

Code 
https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/dhaval/ccsanusvara

**Comment by funderburkjim** [comment]
The 22 cases have been examined, with these conclusions:
```
ccs:aMsumant:aMSumant:t: 
ccs:anUzivaMs:anUzivaMs:n:
ccs:asaMrva:asarva:t: print smudge
ccs:kAryaMrUpa:kAryarUpa:t: print smudge. CAE has kAryarUpa
ccs:jakzivaMs:jakzivas:n: CCS seems to cite these participles as vaMs
ccs:tasTivaMs:tasTivas:n:
ccs:DuMrya:Durya:t: accent coded as M
ccs:nirMvaSa:nirvaSa:t: print smudge
ccs:BrAMtar:BrAtar:n:  PREVIOUSLY CORRECTED to BrAtar
ccs:maMstu:mastu:t: accent coded as M
ccs:mAMkis:mAkis:n: PREVIOUSLY CORRECTED to MAkis
ccs:vaMSaga:vaMsaga:t:
ccs:vyaMyitavya:vyaMsayitavya:t:
ccs:SiMmyu:Simyu:t:accent coded as M
ccs:saMyana:saMyamana:t:
ccs:saMntya:santya:p: Print has M and n. Since CAE shows 'santya', use 'n'
ccs:sAMmba:sAmba:t:
ccs:sAMmya:sAmya:t:
ccs:suMbrahman:subrahman:n: PREVIOUSLY CORRECTED to subrahman
ccs:sEkataM:sEkata:t:accent coded as M
ccs:soMmarAjan:somarAjan:t:accent coded as M
ccs:sriMma:srima:t:accent coded as M
```

**Comment by funderburkjim** [comment]
These corrections installed.
