### ISSUE TITLE
PWG bigrams verified

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#203]
Based on https://github.com/sanskrit-lexicon/CORRECTIONS/issues/185, an examination of
http://sanskrit-lexicon.github.io/CORRECTIONS/ngram/output/html/allvsPWG_2.html

```
bur:aDyAruQa,472:aDyArUQa:t:uQ +
cae:aro|a,2806:aro|a:n:o|
ap:AjiJAsenya,6667:AjijYAsenya:t:iJ +
pe:kuraNNu,3876:kuraNNu:n:Nu non-Sanskrit +
yat:QuQ,16271:QuQ:n:uQ+
acc:tiNantaSezasaMgraha,9001:tiNantaSezasaMgraha:n:Na+
mw:niguQaka,108089:nigUQaka:t:uQ+
mw:vo|ave,208142:vo|ave:n:o|
ccs:sarvAnavadyANNa,26888:sarvAnavadyANga:t:Na+
```

`|` cases do not touch. Waiting for @funderburkjim to kill them.
![adhya](https://cloud.githubusercontent.com/assets/80761/11854149/06d630fa-a453-11e5-971c-bac354a3b1f5.PNG)
![aji](https://cloud.githubusercontent.com/assets/80761/11854148/06d51210-a453-11e5-8aa9-1dcb99faffc2.PNG)
![gudhaka](https://cloud.githubusercontent.com/assets/80761/11854146/06d34818-a453-11e5-8643-00f7852e5146.PNG)
![sarva](https://cloud.githubusercontent.com/assets/80761/11854147/06d496f0-a453-11e5-9f05-96600943107c.PNG)

**Comment by funderburkjim** [comment]
@drdhaval2785   I am confused about the status of the correction list above.

Are all ready for installation?  Or only some?
   What does
`| cases do not touch. Waiting for @funderburkjim to kill them.` 
mean?

**Comment by gasyoun** [comment]
All are ready, hope @drdhaval2785 can approve.

**Comment by drdhaval2785** [comment]
All are ready. They are ready to be installed.

**Comment by funderburkjim** [comment]
Just realized this list is identical to that in #232.
