### ISSUE TITLE
INM 'sh2' errors

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#204]
This was referenced in #188.
I need to make an alternate standard form to facilitate handling such changes, which occur not in the
headword spelling, but in the spelling occurring in the text.

**Comment by gasyoun** [comment]
Indeed, just about time.

**Comment by funderburkjim** [comment]
Many of these seem to be print errors  (there is a dot under the 'h' of 'sh', and that's why 'sh2' was input by the typists).  Maybe some of them are 'smudges', others are simple misprints.  They don't occur in all instances of a given word, so they are just careless mistakes in the manuscript preparation, rather than lexicographer misunderstanding.

For example, under headword SiKaRqin:
![image](https://cloud.githubusercontent.com/assets/6393033/11883102/a02feeea-a4de-11e5-9512-61ad81667351.png)

**Comment by gasyoun** [comment]
So what about the alternate standard?

**Comment by funderburkjim** [comment]
The case under headword 'soma' is somewhat different, print is blurred.  Here I guess the
spelling might end in 'iH'  (raSmiH):
![image](https://cloud.githubusercontent.com/assets/6393033/11883895/f10af418-a4e3-11e5-9050-054f0debcb7e.png)

**Comment by funderburkjim** [comment]
Here is the 'standard change' file  (with comments showing the occurrences)
; Case 1. rec#=5671
inm:Adikara,166:sh2:sh:p:
;<HI>{@A1dikara@}^2¦ = Vishn2u: XII, 13512 {%(Puru***sh2***am2).%}
;
; Case 2. rec#=27539
inm:Sala,2318:sh2:sh:p:
;<HI>{@Çala@}^2,¦ son of Dhr2tara1***sh2***t2ra. § 182 (Dhr2tara1sht2raputrana1mak.):
;
; Case 3. rec#=28938
inm:SatAnIka,2538:sh2:sh:p:
;<>bhi***sh2***ekap.): VII, {@16,@} 625 ({%Na1kulih2,%} attacks Vr2shasena).-- [Page198-a+ 59]
;
; Case 4. rec#=29409
inm:SiKaRqin,2622:sh2:sh:p:
;<>{@57<g></g>,@} 2236, 2243 {%(Bhi1***sh2***mah2…bha1gah2 kr2tah2 Çºah2);%}
;
; Case 5. rec#=34332
inm:Danurveda,3379:sh2:sh:p:
;<>V, {@158,@} 5352 ({%kr2tsnam2 Dhºm2 catu***sh2***pa1dam ava1ptava1n,%} sc.
;
; Case 6. rec#=41736
inm:gArgya,4054:sh2:sh:p:
;<>VII, {@11<g></g>,@} 397 ({%Va1tsya-Gº-Karu1***sh2***a1n,%} had been vanquished
;
; Case 7. rec#=42674
inm:GozayAtrAparvan,4145:sh2:sh:p:
;<>feared that he might not obtain the permission of {%Dhr2tara1***sh2***t2ra,%}
;
; Case 8. rec#=43554
inm:guruSizyasaMvAda,4307:sh2t:sht2:p:
;<C1>2. wind {%(ma1ruta).%} <C2>skin {%(tvac)…%} <C3>objects of touch {%(spra***sh2***tavya)…%} <C4>Lightning {%(Vidyut).%}
;
; Case 9. rec#=44734
inm:hiraRyagarBa,4508:sh2t:sht2:p:
;<>Vasi***sh2***tha), 11511 (do.).--§ 717{%b%} (Na1ra1yan2i1ya): XII,
;
; Case 10. rec#=49391
inm:jayadraTavaDaparvan,4872:sh2:sh:p:
;<>{%Dhr2sht2adyumna. Dron2a%} slew {%Kshatradharman%} ({%Dhr2***sh2***t2a-
;
; Case 11. rec#=62482
inm:manu,7118:sh2t:sht2:p:
;<>as Yudhi***sh2***thira had by his ra1jasu1ya).--§ 327 (Draupadi1-
;
; Case 12. rec#=64679
inm:mokzaDarmaparvan,7350:sh2n:shn2:p:
;<>the reason of {%Kr2***sh2***na's%} assuming the form of an animal.
;
; Case 13. rec#=67399
inm:nara,7587:sh2t:sht2:p:
;<>caiva Dharmakulodvahau devaçre***sh2***thau);%} {@344,@} 13310
;
; Case 14. rec#=72440
inm:pAtAla,8223:sh2t:sht2:p:
;<>{@142,@} 10927 {%(na***sh2***ta1 vasumati1 kr2tsna1 Pºe caiva majjita1).%}--
;
; Case 15. rec#=73138
inm:piSAca,8337:sh2:sh:p:
;<>{%(ºoraga-Ra1k***sh2***asa1h2).%}--§ 599 (Jayadrathavadhap.): VII, {@146,@}
;
; Case 16. rec#=74248
inm:prakfti,8538:sh2t:sht2:p:
;<>{%(a***sh2***tau),%} 11554 (do.), 12725 ({%sapta,%} i.e. the seven r2shis,
;
; Case 17. rec#=74249
inm:prakfti,8538:sh2t:sht2:p:
;<>Manu is the eighth), 12737 (= do.), 13041 ({%a***sh2***tau,%} i.e. the
;
; Case 18. rec#=79588
inm:fta,9181:sh2:sh:p:
;<HI>{@R2ta(m2)@}¦ = Kr2***sh2***n2a: XII, 1622. [Page602-a+ 58]
;
; Case 19. rec#=83386
inm:sOBavaDopAKyAna,9782:sh2:sh:p:
;<>the {%Saubha,%} who moved at will and slew many of the {%Vr2***sh2***n2is,%}
;
; Case 20. rec#=85065
inm:soma,9973:sh2:ih2:p:  ?
;<>38,900 yojanas; VI, {@12,@} 484 {%(Candrama1h2),%} 485 {%(Çi1taraçm***sh2***)%}].
;
; Case 21. rec#=89164
inm:tIrTayAtrAparvan,10844:sh2:sh:p:
;<>came to them {%Balara1ma, Kr2shn2a, Ça1mba,%} etc., {%Ka1r***sh2***n2i,%} the
;

**Comment by funderburkjim** [comment]
The variation of the 'generate.py' program is in the inm/pywork/correctionwork/issue-204/ folder under the name 'generate_gen.py'.  [Here](https://gist.github.com/funderburkjim/a380e76ef893f3125f47) is the current version, along with the bash script to run it.

The 'standard form' for the input file is illustrated above. 
There are **6** colon-separated fields (compare #154)
1 dictcode
2 key1[,L]   : NOTE In current version of generate_gen.py,  the ',L' *is mandatory*, not optional
3 old =  The string to be changed (NOT a regular expression)
4 new = The corrected string.  The replacement is done by simple string substitution
5 errorcode Same as in #154  (p, t, or n)
6 note  Either a single-letter abbreviation, or a comment.  

The fields  (notable old, new, note) should NOT contain a colon, which is the field separator.

**Comment by funderburkjim** [comment]
These corrections to INM now installed.

**Comment by drdhaval2785** [comment]
I have a tiny reservation.

At some places it seems that '2' was not for 'sh', but for the next letter.

sprash2tavya. It should refer to spfzwavtavya and not spfztavya.

Vasish2tha
Yudhish2thira
Kr2sh2na's
devaçresh2thau
nash2ta1
ash2tau

I feel in this cases either we have to add a '2' after the retroflexes.
Deep within i feel that some programmatic step may have jumbled the '2'
letter. Jim may like to comment.

**Comment by gasyoun** [comment]
"'2' was not for 'sh', but for the next letter." looks like one more miscoding Jim wants to bury.

**Comment by funderburkjim** [comment]
Look at the examples shown above, I think you will find that the 'new' field has been entered correctly, for instance 'asht2au', (case 16) and similarly for the others.  So i did add a '2' after the retroflexes.  

inm:prakfti,8538:sh2t:sht2:p:     The 'sh2t' is the old (wrong) text.  The 'sht2' is the new (correct) text.

Re ' Jim wants to bury.' . Why such a harsh statement?  If I'm burying (hiding) something here, please tell me what.  Such is not my intent.

**Comment by gasyoun** [comment]
I did not want to say bad about. 'sht2' makes sense.

**Comment by drdhaval2785** [comment]
In his poemtic sentences, Marcis chooses wrong words sometimes. All he
wanted to say was, Jim would like to correct it.
