### ISSUE TITLE
PW Crefminusbib corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#212]
Refer to https://github.com/sanskrit-lexicon/PWK/issues/36

**Comment by funderburkjim** [comment]
Am taking a Christmas break. Will get back to this next week.

**Comment by drdhaval2785** [comment]
Me too on vacation from friday till sunday. Merry christmas

**Comment by gasyoun** [comment]
Ho, ho, ho.

**Comment by funderburkjim** [comment]
Here are the way I'm handling these cases.   

1. These cases will be treated as typos.  **These changes have not yet been installed.**
   ```
; PW typos
¯LILA&V@savarRana@savarRana@122491:¯LI7LA7V:t: two errors
¯KR2K4K4H@liKana@liKana@96181:¯MR2K4K4H:t:
¯NR2S¯TA7P. ¯UP.@sasaptadvIpa@sasaptadvIpa@122706:¯NR2S.TA7P.UP.:t:Single reference
¯SIDDH.K. ‹ed.› ¯TA7R.@tasTI@*tasTI@45086:¯SIDDH.K.ed.TA7R.:t:New resource. siddhAntakumudI edited by tArAnAtha.
¯GAN2IT.BHAGAN2.33.¯MADHJAM.@deva@deva/@52136:¯GAN2IT.BHAGAN2.33.MADHJAM.:t:It refers to maDyamADyAya of gaRit...
¯AMR2T. ‹Up.› ¯7.@parvataDAtu@parvataDAtu@64878:¯AMR2T.UP.7.:t:
¯Beitr.z.K.d.ig.¯SPR@unmAdayantI@unmAdayantI@19337:¯Beitr.z.K.d.ig.Spr:t:
¯KAN2D2AK@BUruh@BUruh@80683:¯K4AN2D2AK:t:
¯K4AMPAVA@mahardDika@mahardDika@84096:¯K4AMPAKA:t:
‹N.pr. einer› ¯Zofe.@nipuRikA@nipuRikA@58662:‹N.pr. einer Zofe›.:t:Not a reference
(¯BHüLER, ‹Rep. No. 322)›@SizyahitA@SizyahitA@112852:(¯BÜHLER,Rep.No.322):t:
¯Z4. ‹d.d.m.› ¯G.36,531.@vitatI@vitatI@102394:¯Z4.d.d.m.G.36,531.:t:
¯BHA7APR@AmapAcin@AmapAcin@15151:¯BHA7VAPR:t:

   ```
2. These are additions to pwbib_new (some overlap with above):

   ```
; ¯KUMA7RILA@aBihotavE@aBihotavE@7769:¯KUMA7RILA:n:Not sure  ejf: add to pwbib_new
; SIDDH.K.ed.TA7R. added 
; WHITNEY,@SI@SI@112857:¯WHITNEY,:n:Not sure
   ```
3. These cases are handled as non-typos.  The problem with these cases is that it is hard to
recognize the end of the abbreviation.  The solution you suggested above involves inserting a space.  This would be fine if we were making corrections directly to pw.xml, since it is ok to have
a space within an xml tag: `<ls>blah blah</ls>`.  However, inserting a space does not work in the
coding of pw.txt; for instance in `¯KA7D. II,70,11` the space would be interpreted as the end of the
ls element, and the 'II,70,11' would be left dangling unattached to KA7D.  
   The way I'm handling this situation is to leave pw.txt unchanged in such cases, but to add logic to the clean_special function in abbrv.py so that the Roman numeral 'II' will not be considered part of
the abbreviation.  And, similarly for the other cases.
   This is somewhat awkward, but serves the present purposes of finding matches with pwbib.
    Note the last case (BÜHLER) doesn't involve a space, but is similarly handled.

   ```
; ¯VIKR.S@caturaSra@caturaSra@38606:¯VIKR. S:t: 
; ¯KA7D.I@kIlita@kIlita@28102:¯KA7D. I:t: 
; 46-50
;¯LI7LA7V.S95@dIpaka@dIpaka@50514:¯LI7LA7V. S.95:t: 
;¯KA7D.II,70,11@amBomuc@amBomuc@8636:¯KA7D. II,70,11:t:Space
;¯R2SHIMAN2D2ALASTOTRA105@smar@smar@131651:¯R2SHIMAN2D2ALASTOTRA 105:t:space
; BÜHLER,Rep.No. => BÜHLER,Rep.
   ```

**Comment by funderburkjim** [comment]
Including corrections re these PWK issues:
* https://github.com/sanskrit-lexicon/PWK/issues/27
* [MORE TO COME]

**Comment by funderburkjim** [comment]
Corrections installed.
