### ISSUE TITLE
PD - space inside key1

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#217]
Right now PD is the only dictionary which has 'space' inside key1.
I propose that we kill it for uniformity. Let only key2 have spaces.

**Comment by funderburkjim** [comment]
Agree to remove spaces in key1.

**Comment by gasyoun** [comment]
Let only key2 have spaces, hurray.

**Comment by funderburkjim** [comment]
Modified hw1.py for PD, so that spaces are removed from key1.

They remain in key2.

About 25 cases.  Example, aTapunar

Regenerated everything for PD.

**Comment by gasyoun** [comment]
`aTapunar` can't see a space in the example.

**Comment by funderburkjim** [comment]
@gasyoun  Not to worry.  Here's proof that a space remains in key2: 
```
 grep '<key1>aTapunar</key1>' pd.xml
<H1><h><key1>aTapunar</key1><key2>aTa punar</key2></h><body>.<s>aTa punar</s>¦ 
 (atha punar) <b>i</b> but then <s>kumAra nAhamevaM vaktuM samarTaH. <br/>
aTa punarBarataH prApta iti brUyAm</s> Prati. 4. 4 (11); <b>ii</b> then again
 <s>aTa punaH <br/>prakIrRamalapaNkaH…balavatIBiryantraRABirudvejitaH pratyavAmfSam</s> 
Das4KuC. 47. 4.</body><tail><L>38961</L><pc>2-1329a</pc></tail></H1>
```
Note that for PD, the display has put 'key2' in the body: `<body>.<s>aTa punar</s>`

The highlighted part of this PD display is key2:
![image](https://cloud.githubusercontent.com/assets/6393033/12275941/dfa6d9d2-b940-11e5-92e7-10f2d2e2fa76.png)

**Comment by gasyoun** [comment]
Got it.
