### ISSUE TITLE
additional checks for standard format submissions

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#227]
@funderburkjim,
Currently we are working a lot on 'standard format' submissions.
It is very easy for batch processing.
But its user-unfriendly interface poses some problems.

e.g.
Sometimes I correct a headword, but forget to turn `:n:` -> `:t:`.
Sometimes I don't correct anything, but have `:t:` or `:p:`.

I am sure you do a lot of manual examination.
I am not sure whether you do mechanical examination too.
What I propose is

Highlight the following entries while processing any standard format file.
1. Both the headwords are the same, but the error type is not `n`.
2. Both the headwords are different, but the error type is `n`.

That would help us be sure that nothing fishy passes.
If this is incorporated in the generator program, fine.
If not - please incorporate it.

**Comment by drdhaval2785** [comment]
@funderburkjim and @gasyoun 
I have developed the code for the same.

https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dhaval/tools/submittester.py

# Usage:
python submittester.py filepath submissiontype
where submissiontype is 1 for headword submissions and 2 for literary resources submissions

# Input:
File in standard format
1. dictcode:oldword:newword:errorcode:notes   # Useful for headword correction submissions
or
2. oldword@key1@key2@lnum:newword:errorcode:notes   # Useful for bibliographic / other textual corrections.

# Logic:
Try to find out submissions where 
1. oldword == newword but standardconvention != 'n'
or
2. oldword != newword but standardconvention == 'n'

Currently code prints it on screen, as this is just a testing machine, so that no error gets passed.
Not storing the errors somewhere else as log file.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/PWK/commit/bc51f78750bfea545f79c8cb27fc0a59373a1243
This shows the errors displayed by the present program (which were corrected and uploaded in the file)

**Comment by gasyoun** [comment]
So a validator, great!
