### ISSUE TITLE
Make XMLs default instead of txt

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#228]
Per @gasyoun 's remarks at https://github.com/sanskrit-lexicon/PWK/issues/27#issuecomment-168333734, @funderburkjim hesitantly accepted a very remote but possible possibility of making XMLs default for many dictionaries. 
This issue is to be treated as a reminder of that deep freeze issue.

**Comment by drdhaval2785** [comment]
This is irrelevant now.
.txt are the default now, and for good reasons.

**Comment by gasyoun** [comment]
> .txt are the default now, and for good reasons.

But undocumented on the Downloads page.
