### ISSUE TITLE
2-grams vs PWG, part 1

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#232]
http://sanskrit-lexicon.github.io/CORRECTIONS/ngram/output/html/allvsPWG_2.html examined here.
Total 9 entries to be examined.
Will examine in single issue.

https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/ngram/output/corrections/allvsPWG_2_corrected.txt is the corrected file.

**Comment by drdhaval2785** [comment]
1-9
```
bur:aDyAruQa,472:aDyArUQa:t:uQ is not possible grammatically.
cae:aro|a,2806:arI|a:t:the explanation reads arIQa / arI|a.
ap:AjiJAsenya,6667:AjiYAsenya:t:iJ
pe:kuraNNu,3876:kuraNNu:n:Nu-Non-Sanskrit headword
yat:QuQ,16271:QuQ:n:uQ-verb
acc:tiNantaSezasaMgraha,9001:tiNantaSezasaMgraha:n:Na-grammar word
mw:niguQaka,108089:nigUQaka:t:uQ not possible grammatically
mw:vo|ave,208142:vo|ave:n:o|
ccs:sarvAnavadyANNa,26888:sarvAnavadyANga:t:Na
```

**Comment by drdhaval2785** [comment]
I close the submission in this issue.

**Comment by funderburkjim** [comment]
> bur:aDyAruQa,472:aDyArUQa:t:uQ is not possible grammatically.

Classifying as print error. Agree it should be rUQa.

 Compare this word 
![image](https://cloud.githubusercontent.com/assets/6393033/12469767/a39a55fe-bfbc-11e5-999b-d2e4f987d2d9.png)
with
![image](https://cloud.githubusercontent.com/assets/6393033/12469789/cf11636c-bfbc-11e5-8d52-9c3e68611326.png)

**Comment by funderburkjim** [comment]
> ap:AjiJAsenya,6667:AjiYAsenya:t:iJ

Changing to AjijYAsenya:

compare the Devanagari for this word:
![image](https://cloud.githubusercontent.com/assets/6393033/12469921/f14d6e70-bfbd-11e5-88b5-ce0a881711d0.png)

with that for jijYAsA:
![image](https://cloud.githubusercontent.com/assets/6393033/12469939/22fc17e6-bfbe-11e5-9305-401a787a1a67.png)

**Comment by funderburkjim** [comment]
agree with rest

**Comment by funderburkjim** [comment]
Corrections installed
