### ISSUE TITLE
sammArga is correct

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#238]
A user suggested the following correction.  I think he is wrong, and that sammArga is correct  (it is in MW, PW and a couple of other dictionaries per [hwnorm1](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/hwnorm/hwnorm1.php) ; and saMmArja is not found in any dictionary).

Do others agree that sammArga is correct?
```
Case 15091: 01/07/2016 dict=MW, L= L=237163, hw=sam-mārga, user=theunborn
old = sam-mārga should be sam-mārja
new = The root of the word is specified as "sam- √mṛj" so the word should be sam-mārja 
comment = Typo  (I looked up the MW pdf itself and I clearly see as a typo in the print copy going back years. This is not error due to digitization!)

```

**Comment by funderburkjim** [comment]
In Whitney Roots book, under 'mfj', we see '-mArga AV.'   So, Whitney supports the possibility of sammArga.

This *is* confusing, since the derivation of 'mArga' is different, acc. to Wilson.

**Comment by drdhaval2785** [comment]
mArga is possible to be derived from mfj.
It has a meaning of cleaning up, as intended in the present headword.

See VCP on mArga:
![capture](https://cloud.githubusercontent.com/assets/5755132/12219869/31054eca-b77b-11e5-8f94-0639784d4602.png)

The first line says it can be derived from mfj.
So, treat is as non-issue. It can be closed. Your instinct is right. NO CORRECTION needed.

**Comment by gasyoun** [comment]
Samskrtam instinct.
