### ISSUE TITLE
crefminusbib, the rest of them, part 2

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#242]
These corrections discussed at Discussion in https://github.com/sanskrit-lexicon/PWK/issues/59.

**Comment by funderburkjim** [comment]
CORRECTIONS INSTALLED

**Comment by drdhaval2785** [comment]
Hip hip hurray!

Now the only real work pending in this literary resource treasure hunt is - Extending the bibliography.

Where are @gasyoun and @zaaf2 ?

**Comment by gasyoun** [comment]
Extending the bibliography is beyond my reach for the upcoming months. @zaaf2 is out of the game as well, if I understood him right. Let's leave it as it is, @drdhaval2785 for the time being.
