### ISSUE TITLE
C vs. cC in MW

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#246]
@drdhaval2785 any ideas how to batch correct? @funderburkjim what do you think?
`akzaraCandas`:MW
vs
`akzaracCandas`:CAE,CCS,GST,PD,PW,PWG,VCP

**Comment by drdhaval2785** [comment]
There is no need to correct. They are optional forms. 

Grammar rule 

[aiufA]C -> [aiufA]cC

Rule is - Che tuk

**Comment by gasyoun** [comment]
Is MW consistent in no-sandhi? Can you RegEx it, please?

**Comment by drdhaval2785** [comment]
Nope

**Comment by gasyoun** [comment]
Nope non-RegExable?

**Comment by funderburkjim** [comment]
I tried a regex `[aiufA]c?C` and came up with a list of 1764 matches.  
After removing those with 'cC', 71 remained.
[here] is the full list of 1764, with the 71 marked with '***'

@gasyoun  Enjoy!

**Comment by gasyoun** [comment]
@funderburkjim perfect, thanks!

**Comment by funderburkjim** [comment]
This seems to require no correction installation, so relabeling and closing.
