### ISSUE TITLE
MW corrections re MWderivations

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#248]
Working with the [MWderivations](https://github.com/funderburkjim/MWderivations) repository uncovered a few definite headword errors, several headword internal MW spelling  inconsistencies, and several likely markup problems.

**Comment by funderburkjim** [comment]
Here are the definite headword errors:
```
mw:gUDatayA,66346.1:gUQatayA:t:
mw:vrikAmlikA,204150:vfkAmlikA:t: vrika not a Sanskrit word, but vfka is a word
mw:mezaSriNga,168090:mezaSfNga:p: SriNga not a Sanskrit word, but SfNga is a word
mw:mezaSriNga,168091:mezaSfNga:p:
mw:mezaSriNgI,168092:mezaSfNgI:p:
mw:GritAhuta,70054:GftAhuta:t:
mw:saMgItadarpana,228584.12:saMgItadarpaRa:p: cf. PWG, ACC
mw:vIraSEvapUrARa,203788.2:purARa:t:
mw:mUrKaBuya,165773:mUrKaBUya:t:
mw:muRqitamurDan,165429:muRqitamUrDan:t:
mw:indratUrIya,29007:indraturIya:p: cf. PW
```

**Comment by funderburkjim** [comment]
Here are some inconsistent spellings.  The inconsistency is between a spelling of a headword 'X'
and the spelling X' of that word when used in a compound headword.  My feeling is that the
spelling X' should be changed to X in the compound.
However, I'm not as sure about this, so will wait for the comments of others here before making
these changes.  All of these involve nasals; one spelling uses the homorganic nasal, the other
uses anusvAra.
```
13703	aBramAtaNga	aBra-mAtaNga  mAtaMga  Suggest aBramAtaMga	
21419	asTisanDi 	asTi-sanDi  saMDi  Suggest asTisaMDi 	
29648	izwakAsaMpad	  izwakA-saMpad sampad  Suggest izwakAsampad	  
```

There are a few more similar cases, but not a large number of cases

**Comment by funderburkjim** [comment]
There are likely markup errors of several kinds that should be changed.
I don't propose to change these now, but will wait until more are collected.

Some of these are cases where a word from the supplement was inserted into the body of the text at the wrong place (wrong L-number).  There are quite a few of these (perhaps, several dozen). Here are a couple.
```
790.1	agatyA	a-gatyA	ind H2 -> H2C, L -> 787.1 (so under agati)  Since agatyA is an inflected form (3s) of agati, it should appear under agati, and with H-code having a 'C'.

39924.1	ekEkatra  H3 -> H4 so under ekEka.   ekEkatra is formed from ekEka (by a secondary suffix `tra`.  It should be at the subsidiary 'H4' level under ekEka, like ekEkatara, ekEkavat, and ekEkavftti

```

In another (smaller) category, the markup incorrectly mirrors the hierarchy of words in the text.
The only example thus far noticed is:
```
(H2) उप-कुञ्चिका [p= 195] : f. id. Suṡr.  [L=34101]
f. small Cardamoms L.  [L=34102]
(H2C) उप-कुम्भम् : ind. near the water-jar Kāṡ.  [L=34103] 
     34103 should be H1, since text shows headword 'upakumBa'  in Devanagari.
     In fact, there should probably be a new 34102.1, H1 record spelled as 'upakumBa'and then   
     34103-34103.3 would be H1C.
     Since MW72 shows upakumBa as an adjected (mfn) with meaning 'near', I think this is
     how the new 34102.1 upakumBa should be written  (of course, as a 'printchange')
(H2C) उप-कुम्भेन : ind. near the water-jar Kāṡ.  [L=34103.1]
(H2C) उप-कुम्भे : ind. near the water-jar Kāṡ.  [L=34103.2]
(H2C) उप-कुम्भात् : ind. from the water-jar [L=34103.3]


(H1) उप-कुम्भा [p= 195] : f. Croton Polyandrum Nigh.  [L=34103.4]
   This should be an H1B.
```
 This case is clear enough, and I'll go ahead with theses upakumBa corrections.

**Comment by gasyoun** [comment]
> ri

Wonder if there are more because of MW orthography.

**Comment by funderburkjim** [comment]
Sounds reasonable that 'ri' would sometimes be missed as 'f', either because the typist didn't notice the dot below the 'r' in the MW scan, or because the scan itself was missing the dot.

But there are over 14,000  `<key1>` elements with 'ri',  which is too big a number to examine directly.

**Comment by funderburkjim** [comment]
corrections installed.

**Comment by gasyoun** [comment]
> over 14,000 <key1> elements with 'ri'

If compared with similar words from other dictionaries that have just `f` - @drdhaval2785, what do you think?
