### ISSUE TITLE
MW unknown literary sources

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#250]
This issue arose in regard to [Extending PWK bibliography](https://github.com/sanskrit-lexicon/PWK/issues/56).

I thought it might be helpful to take into account the MW literary sources.

A first step was to make a simpler (non-html) listing of the MW literary sources and their abbreviations.
The program which did this mentioned that 11 of the known literary source abbreviations in MW have not been resolved.  Here they are, with frequencies:
```
3 AdhyR.
1 Du1ta7n3g.
2 GrS3.
5 K.
61 KaushBr.
5 Lokapr.
17 Ratnak.
3 S3ambhMa1h.
741 S3rS.
6 S3r.
2 Sam2g.
```
One of these (GrS3) is a typo, it should be Gr2S (which is known, and is the literary category of
gfhya-sUtra.

`S3r.`  is, based on one instance, due to a variant way of writing `Gr2S3rS.`  (namely as 
`S3r. & Gr2S.`  I'm tempted to change these 6 to the 'standard form'.

`S3rS.`  has many instances, and is no doubt referring to the literary category SrOta-sUtra.
In this case, it seems appropirate to add this entry to the underlying MWauthorities data base.

The others are unknown to me.  Maybe someone in this forum will recognize them, or discover 
that they are typos of some kind.

I've put the headwords where all these occur [here](https://gist.github.com/funderburkjim/434b15fbfe69eb8f6f75).

These are grouped by literary source abbreviation.

**Comment by funderburkjim** [comment]
`Sam2g.` occurs in two words (Suktipawwa, sArikA), which mention musical instruments   This is surely an alternate abbreviation to `Sam2gi1tas.` which is already in MW authorites as the Title saMgIta-sArasaMgraha.

So, one reasonable solution is to make a print change in MW from `Sam2g.` to `Sam2gi1tas.`

**Comment by funderburkjim** [comment]
Regarding `S3r.`.  Upon reflection, a better solution seems to change this to `S3rS.` (count as a print change).

**Comment by funderburkjim** [comment]
I'll pause for comments here before making the changes suggested above for `S3r.`, `Sam2g.` , which are debatable, and for 'GrS3.`, which is clear.

**Comment by gasyoun** [comment]
Have you seen @Shalu411 comments on these 11 unresolved cases earlier, Jim?

**Comment by funderburkjim** [comment]
Not that I recall. Is there a link?

**Comment by gasyoun** [comment]
Jim, https://github.com/sanskrit-lexicon/MWS/issues/15

**Comment by funderburkjim** [comment]
Thanks.  Looks relevant.

**Comment by funderburkjim** [comment]
Corrections to MW and to the MWderivations database have been made.
The main points:
*  `GrS3` was a typo in MW, changed to `Gr2S`
*  `S3rs` was a typo in MW, changed to `S3rS`
*  Several errors in the [linkmwauthorities_init.txt](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwauthorities/linkmwauthorities_init.txt) inhibited matching.
  
* Two additions were made to [mwauthorities_init.txt](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwauthorities/mwauthorities_init.txt):
   ```
k	au	<abbr>K</abbr><expandMW><au>Kielhorn (?)</au></expandMW>
kOzbr	ti	<abbr><slp cap="true">kOz</slp><slp cap="true">br</slp></abbr><expandMW><ti><slp cap="true">kOzItaki</slp><slp cap="true">b</slp></ti></expandMW><expandNorm><ti><slp cap="true">kOzItaki-brAhmaRa</slp></ti></expandNorm>
   ```
  For most cases, the suggestions by Shalu (see link above) agreed with what was already in mwauthorities.  

  For documentation completeness, the next comment shows notes made during the correction process.

The end result is that all the cases are resolved.

**Comment by funderburkjim** [comment]
Here is a link to [working notes](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwauthorities/readme_20150216.txt)

**Comment by gasyoun** [comment]
So the mystery solved thanks to Jim Conan Doyle.

**Comment by gasyoun** [comment]
http://www.sanskrit-lexicon.uni-koeln.de/monier/mwauthorities/mwauth_SLP2HK.html, http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwauthorities/mwauthorities_init.txt - which file contains the latest list of MW sources? @funderburkjim please advice. Adding footnotes to a Preface for a 1854 dictionary to be published in a month in Moscow. 568 sources?

**Comment by funderburkjim** [comment]
The mwauthorities_init.txt  is the latest list of MW sources.

the 'monier/mwauthorities/mwauth_SLP2HK.html' file (and similar files) are OLD  (as is everything
in the 'monier' directory).

However, there are similar files which are currently used by the web displays. for example
http://sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/sqlite/mwauth_hk.html

There is one other file,  linkmwauthorities_init.txt, of note.  This has the correspondence between
abbreviations used in mw.xml  and those used in mwauthorities_init.txt.

These two files (mwauthorities_init.txt and linkmwauthorities_init.txt) are used by a program to create the hmlt files  (mwauth_hk.html, etc.)

**Comment by funderburkjim** [comment]
> 568 sources?

This looks right, as it is the number of data lines in mwauthorities_init.txt.

**Comment by gasyoun** [comment]
http://sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/sqlite/mwauth_hk.html lacks last change date. If it would have one, I would not ask about 568. Now I only lack the number of sources in PWK, PWG is 774.

**Comment by funderburkjim** [comment]
> PWG is 774.

Where do you get this?

**Comment by gasyoun** [comment]
> Where do you get this?

Counted number of lines in one of the .txt files. It was linked from https://github.com/sanskrit-lexicon/PWK/issues/56

**Comment by funderburkjim** [comment]
In that case,  the reference is surely to PWK.   I was thrown off by the use of 'PWG'; nothing in PWK#56 refers to PWG .
