### ISSUE TITLE
PUI headword pluralization

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#251]
There are 1341 headwords (with SLP1 spelling)
* end in 's'  
* occur ONLY in PUI dictionary

A random look at these suggests that they are cases when the English plural affix 's' has been appended to a Sanskrit word. For example, ajAmuKas:
अजामुखस् [p= 1-031] : Ajāmukhas (also Adhomukhas)--a group of piśācas. 
Br. III. 7. 381; Vā. 69. 263, 267. [L=228]

![image](https://cloud.githubusercontent.com/assets/6393033/13189794/a179252a-d727-11e5-8c97-eb938dc17697.png)

I think we should change the headword derivation program for PUI to drop the final 's' for these
cases.  (This is probably program hw1.py).  So in the ajAmuKas example, there would result two 
'ajAmuKa' key1 headwords, the second one being the plural.

There are an additional 136 headwords in PUI that end in 's', but that also occur in one or more other dictionaries.   These will probably need to be examined individually to determine whether,
in PUI, any have the final 's' used as an English pluralization, and therefore need to have that 's' dropped in key1.

**Comment by gasyoun** [comment]
>  change the headword derivation program for PUI to drop the final 's' for these
cases. 

Fully agree.

> There are an additional 136 headwords in PUI that end in 's', but that also occur in one or more other dictionaries

Link to the list, please.

**Comment by funderburkjim** [comment]
[Here](https://gist.github.com/funderburkjim/aae0e0881c48814da42f) is the list of 136.

If anyone works on these, a useful form of the result would be to separate the list into two parts:
* those where, in PUI, the word is used as a plural, and the 's' should be dropped in key1
* the rest, where the 's' should not be dropped in key1 for PUI.

**Comment by funderburkjim** [comment]
The judgment will probably be easy in most cases upon examination of the display of the headword in PUI.

**Comment by gasyoun** [comment]
@funderburkjim could it become linkable, please?

**Comment by funderburkjim** [comment]
What isn't linkable?

**Comment by gasyoun** [comment]
Headwords to dictionaries, an additional HTML.

**Comment by funderburkjim** [comment]
[This](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/PUI/issue-251/possibledisp1.txt) file shows the PUI data for each of the 136 questionable plurals.

The [program](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/PUI/issue-251/possibledisp1.py)  that generated this display might have more general use.  

Essentially, this display saves the time required to look up the PUI Basic display for each of the
headwords in question.   In this case, the data shown for PUI should be adequate to make the
decision as to whether the ending 's' of the headword should be dropped.

**Comment by funderburkjim** [comment]
Examination of the above display makes me think the following among the 136 possible plurals are in fact used in a plural sense, while the remaining are used in a singular sense.
```
009:P:apsaras:AP,AP90,BEN,BOP,BUR,CAE,CCS,GRA,GST,INM,MD,MW,MW72,PE,PUI,PW,PWG,SHS,STC,WIL,YAT
019:P:ABIras:PE,PUI
026:P:udIcyas:PUI,VEI
032:P:fBus:PE,PUI
033:P:fzis:PUI,VEI
037:P:kravyAdas:MW,PUI,PW
040:P:gopas:PUI,VCP
043:P:tuzitas:PE,PUI
044:P:dAkziRAtyas:PE,PUI
047:P:draviRas:CAE,CCS,GRA,MW,MW72,PUI,PW,PWG,VCP
053:P:pARqavas:PE,PUI
057:P:pOlomas:PE,PUI
065:P:BAsas:AP,AP90,CAE,CCS,GRA,MD,MW,MW72,PE,PUI,PW,PWG,SHS,VCP,WIL,YAT
067:P:BUtas:PE,PUI
069:P:Bojas:BEN,GRA,MW,MW72,PUI,PW,PWG
070:P:madrakas:PGN,PUI
072:P:maDus:CAE,CCS,MD,MW,MW72,PUI,PW,PWG
073:P:manus:BEN,CAE,CCS,GRA,MD,MW,MW72,PUI,PW,PWG
074:P:maruts:PE,PUI
079:P:mAgaDas:PE,PUI
081:P:mfgayas:AP,AP90,CAE,CCS,GRA,MD,MW,MW72,PUI,PW,PWG
085:P:rakzas:AP,AP90,BEN,BOP,BUR,CAE,CCS,GRA,INM,MD,MW,MW72,PE,PUI,PW,PWG,SHS,STC,VCP,WIL,YAT
088:P:varas:AP,AP90,BUR,CAE,CCS,GRA,MD,MW,MW72,PUI,PW,PWG
093:P:vAlaKilyas:PE,PUI
095:P?:vidas:MW,MW72,PUI
097:P:viSvadevas:PE,PUI
101:P:vedas:AP,AP90,BEN,CAE,CCS,GRA,MD,MW,MW72,PUI,PW,PWG,SHS,VCP,WIL,YAT
103:P:vEKAnasas:PE,PUI
113:P:sagaras:MW,PUI,PW,PWG
117:P:saptadvIpas:PE,PUI
132:P:svaras:GRA,MW,PUI,PW,PWG
135:P:haris:PUI,PW,PWG
```
I will add these to the list of PUI plurals, and thereby remove the final 's' in key1 in PUI for these.

**Comment by funderburkjim** [comment]
The classification of possible plurals as 'S' (singular, not a plural) and 'P' (plural, drop the 's' in key1') into [this file](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/PUI/issue-251/pui_possible_plurals_edit.txt).

There were a few, marked with a `?` in the file, where it was hard to decide. Here they are:
```
041:S?:Candas:ACC,AP,BEN,BOP,BUR,CAE,CCS,GRA,IEG,INM,MD,MW,MW72,PUI,PW,PWG,SHS,STC,VCP,VEI,WIL,YAT
045:S?:diSas:AP,MW,MW72,PUI,PW,PWG,SHS,WIL,YAT
046:S?:devaSravas:GRA,MW,PE,PUI,PW,PWG,VCP,VEI
095:P?:vidas:MW,MW72,PUI
110:S?:SravaRas:MW,PUI,PW
```

**Comment by funderburkjim** [comment]
The lists of 1341 and 32 have now been used to modify the headwords for PUI.  This was done by
a change to hw2.py program for PUI. Thus, for example, 'vedas' is no longer a PUI headword, but rather 'veda'.

**Comment by funderburkjim** [comment]
The 'PE' (Puranic Encyclopedia) dictionary headwords should be examined in the same was as this issue has examined PUI.  For instances, 'maruts', 'pARqavas' and several other faux-plurals from PUI are listed as PE headwords.

**Comment by funderburkjim** [comment]
Headwords now altered, sanhw1 now revised, etc.

**Comment by drdhaval2785** [comment]
Roughly 824 deletions in sanhw1.txt in toto. Good achievement. :+1:

**Comment by funderburkjim** [comment]
@drdhaval2785   I've been thinking about a point you raised earlier, regarding Tamil words.

As I recall, you had to remove a lot of PGN Tamil words when filtering for patterns in Sanskrit words.

I'd now like to take into account a list of non-Sanskrit words when computing sanhw1/2.  

A good start would be the Tamil words from PGN.  Is there a link to a list of these ?

**Comment by gasyoun** [comment]
> I'd now like to take into account a list of non-Sanskrit words when computing sanhw1/2. 

Hope not filter out, just mark.
