### ISSUE TITLE
Misc. headword corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#259]
Various mis-spellings noticed.  Will keep adding similar to this issue for a while.
```
shs:sTirayovana:sTirayOvana:t:
vcp:sTirayIvana:sTirayOvana:t:
```

**Comment by funderburkjim** [comment]
bhs:aMuYciyaM:amuYciyaM:p: 'M' wrong by alphabetical ordering and by text

![image](https://cloud.githubusercontent.com/assets/6393033/13932484/922cf99c-ef7e-11e5-9774-416de8a8a1a3.png)

**Comment by funderburkjim** [comment]
pe:akftavrana:akftavraRa:t:  

Don't know why this was missed in the n-R study of #252 

shs:akzabDu:akzubDa:p: The Devanagari 'u' is misplaced
![image](https://cloud.githubusercontent.com/assets/6393033/13933822/6d0429ea-ef85-11e5-9f8f-3407d99c6fa7.png)

cae:akzaBa:akzama:p:

![image](https://cloud.githubusercontent.com/assets/6393033/13933955/ffd33b8a-ef85-11e5-9f3e-68b63cf93a28.png)

ccs:daktaka:dattaka:t:
ccs:daktadfzwi:dattadfzwi:t:
ccs:daktavat:dattavat:t:
ccs:daktaSulkA:dattaSulkA:t:
ccs:daktAtaNka:dattAtaNka:t:
ccs:daktvA:dattvA:t:

**Comment by funderburkjim** [comment]
skd:kaNkamuKuH:kaNkamuKaH:p:  The entry text supports the 'muKa' -  like a heron's mouth

**Comment by funderburkjim** [comment]
skd:kiriwI:kirIwI:p:  alphabetical ordering and the text both support kir**I**wI

**Comment by funderburkjim** [comment]
ap90:kzurH:kzuraH:t:

**Comment by funderburkjim** [comment]
acc:diNgAga,9950:diNnAga:t: print hard to read. cf MW, PW,

**Comment by funderburkjim** [comment]
skd:apatTaM,1394:apatyaM:t: alph. order, 'na patati vaṁśo yasmāt'

**Comment by funderburkjim** [comment]
skd:aSvinIkumArO,2865:aSvinIkumArO:n:  Could be nom.m.du. of aSvinIkumAra ?
skd:aSvinO,2868:aSvinO:n:  nom.m.du. of aSvin  'the two charioteers' acc. to MW
skd:ahinakulatA,3132:ahinakulatA:n: ahi-nakula+tA
skd:ahibraDradevatA,3138:ahibraDnadevatA:t:  'Dr' and 'Dn' hard to distinguish in SKD print Devanagari
skd:ahimuk,3141:ahiBuk:p:  nom.s. of ahiBuj.   'm' is misprint
skd:AyurdruvyaM,3665:AyurdravyaM:t:
skd:izWArTodyuktaH,4260:izwArTodyuktaH:p: alph. order, consider 'izW' a misprint
skd:uttamaPalino,4503:uttamaPalinI:t: 'I' and 'o' difficult to distinguish in SKD Devanagari

**Comment by funderburkjim** [comment]
The above skd case will be handled as part of #291.

**Comment by funderburkjim** [comment]
vcp:paYcasidDIzaDika,30173:paYcasidDOzaDika:t: I/O confusion in devanagari

**Comment by funderburkjim** [comment]
ap90:rekaRasr,24273:rekaRas:t:

**Comment by funderburkjim** [comment]
pw;barhirjyotas,75920:barhirjyotis:t:

**Comment by funderburkjim** [comment]
wil:dvisamatriBUjA,20224:dvisamatriBujA:p: triBujA is triangle. So 'BUjA' is misprint
yat:dvisamatriBUjA,19711:dvisamatriBujA:p: triBujA is triangle. So 'BUjA' is misprint; prob. copied from Wilson
pw:kARaBUja,26245:kARaBuja:t:

**Comment by funderburkjim** [comment]
vcp:sarvadryanc,45661:sarvadryaYc:p:  nc/Yc.

@drdhaval2785   Would you check this change. The print is clearly 'nc',  

VCP also has 'asmadryanc' and 'daDyanc',

but adadryaYc, amudryaYc, amumuyaYc, udaYc, kadryAyc, devadryaYc, nyaYc.

No other dictionary shows a word ending in 'anc'.  

SHould all three of the 'anc' ending words in VCP be considered print errors?

**Comment by funderburkjim** [comment]
shs:svargigira,46240:svargigiri:t: final a->i

**Comment by drdhaval2785** [comment]
Regarding aYc->anc suggestion, it is NOT a print error.
The original verb is 'anc' only. Because of anusvArasya yayi parasavarRaH
sUtra of Panini, it gets converted to 'aYc'.

VCP has tendency to show verbs in their dhAtupAWa forms. So it shows anc.
Most other dicts show verb in their final used form, so they have aYc.



-- 
Dr. Dhaval Patel, I.A.S
Collector and District Magistrate, Anand
www.sanskritworld.in

**Comment by gasyoun** [comment]
> VCP has tendency to show verbs in their dhAtupAWa forms.

Valuable comment.

**Comment by funderburkjim** [comment]
cae:hmas,40011:hyas:p:  hm/hy  (yesterday, cf. mw, pw, etc.)
ccs:hmas,29664:hyas:p: hm/hy  (gestern, cf. pw.)

**Comment by funderburkjim** [comment]
mw72:hrad,54452:hrad:n: an older form of hrAd (to sound)

**Comment by funderburkjim** [comment]
@drdhaval2785  Regarding 'anc'.

I see that VCP has verb 'anca'. 

I'll leave the *adjectives* ending in 'anc' as no-change, per your suggestion. 

 However, it seems that VCP is inconsistent regarding the spelling of such adjectives.

**Comment by funderburkjim** [comment]
Am stopping adding words to this list now.  There are 32 items to include, which will be 
installed soon.

**Comment by drdhaval2785** [comment]
@funderburkjim 
When I say that VCP / SKD has tendency to show verbs in dhAtupATha form, I mean 'kavikalpadruma' dhAtupATha of vopadeva.
It has a strange system of 'it' markers (anubandhas).
Their significance is shown in pages 95-100 (Appendix III) of this book.
[Kavi kalpadruma- Vopadeva.pdf](https://github.com/sanskrit-lexicon/CORRECTIONS/files/258492/Kavi.kalpadruma-.Vopadeva.pdf)

When you say that the entry is 'anca', actually the entry is 'ancau' 
See
![capture](https://cloud.githubusercontent.com/assets/5755132/15168779/3745b14e-1752-11e6-88e4-f402fac5f804.png)

**Comment by gasyoun** [comment]
Palsule has said that Vopadeva's roots is a mess and I must agree. Bengalese authot Sanskrit dictionary based on Bengali Dhatupatha - it could not get worse. Too bad no Varanasi or Poona dictionary big enough has never been made.
Good that we deal with not more than 2200 entries of such kind.

**Comment by funderburkjim** [comment]
The image above is from skd for anca.   

Here is image of anca from vcp:

![image](https://cloud.githubusercontent.com/assets/6393033/15191960/fb5a5544-1784-11e6-9378-879dc84f579c.png)

**Comment by funderburkjim** [comment]
Whenever someone does attempt study of the roots from the various dictionaries,  we should keep in
mind Peter Scharf's resource http://sanskritlibrary.org/Sanskrit/Vyakarana/Dhatupatha/mdhvcanidx/disp1/index.php.

I provided some technical computer help with this, and believe it was done with great care.

A good first attempt of correlating Madhaviya with MW was also done by me (through the intermediary of Westergaard, in part).    

Relatedly, I'd like to understand the DAtupAWa that forms the basis of Dhaval 
[SanskritVerb](https://github.com/drdhaval2785/SanskritVerb/) work.  Probably he already has
this DAtupAWa in a well-defined data structure that could be used for comparison work.
Is kavikalpadruma the one you start with, Dhaval?

**Comment by funderburkjim** [comment]
These few corrections are now installed.

I'm closing the issue, but the comments regarding vcp/skd are likely of continued interest.

**Comment by drdhaval2785** [comment]
@funderburkjim 
kavikalpadruma dhAtupATha is not much in vogue in the place of India I belong to.
So I am not proficient in reading that thing.
It will take some time before I can jump into
