### ISSUE TITLE
CCS headword errors

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#261]
At a certain point within the whitelisting work being done as mentioned in #254,  there were about 1000 headwords from CCS which had not been whitelisted.   After preliminary sampling, I decided to study these individually for corrections.  

The work documents are in [this directory](https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/dictionaries/CCS/issue-261).

* [prep1.md](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/CCS/issue-261/prep1.md) contains the working document in markdown format.   There are 1033 case.  For each case there is shown:
  * the suspect headword, in slp1 spelling,  and a link to the corresponding scan page for CCS 
  * a 'standard form' for a correction, to be adjusted as required when the case is examined
  * the text of the entry, slightly reformatted from ccs.txt
* [prep1.org](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/CCS/issue-261/prep1.org)  has the same information, with formatting optimized for viewing in the Emacs editor.
* [prep1_edit.org](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/CCS/issue-261/prep1_edit.org)  started as a copy of prep1.org, but contains corrections through case 209.  This is the document I'm working with and modifying and which will be the basis for installing corrections when all cases have been considered.

The main point is that this list has an extremely low false positive density.  In fact, only 14 of the first 209 cases were non-errors.  So many wrong spellings will be corrected once this list is finished.

The corrections are usually easy to identify.  Almost all of them are typos;  as we have observed elsewhere, the original typist for CCS seems to have been inexperienced in transcribing Devanagari.

If anyone wants to spend some time on these,  be sure to coordinate with me so there won't be duplication of effort.   I plan to do 50-100 per day until all cases are done.

**Comment by gasyoun** [comment]
> The main point is that this list has an extremely low false positive density. In fact, only 14 of the first 209 cases were non-errors. So many wrong spellings will be corrected once this list is finished.

Sounds astonishing.

>  as we have observed elsewhere, the original typist for CCS seems to have been inexperienced in transcribing Devanagari.

Drunk, non-reading, sleepy :+1:

**Comment by funderburkjim** [comment]
Three headwords were found to be missing in the digitization, for varying reasons.
```
; 04/05/2016.  Three headwords missing. 
; missing headword taraRIya
67166 old 
67166 new .{#taraRIya#}¦ zu überschreiten.
;headword 'rajju' is missing in digitization
164274 old 
164274 new .{#ra/jju#}¦ ({#ra/jjU}) {%f.%} Strick, Seil.
; headword wrongly marked, also misspelled
241484 old .{#svrarRadI#}
241484 new .{#svarRadI#}¦

```

The insertion of these corrections will have as a side effect that the L-numbers will be changed for
CCS.   Don't consider this L-number change is significant, but thought it should be mentioned since it is a rare occurrence for any of the dictionaries.

**Comment by funderburkjim** [comment]
All the cases have now been examined.

File [prep1_edit.org](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/CCS/issue-261/prep1_edit.org)   was the working document leading to the changes.   This file is best viewed in Emacs editor; if you look at it online, it is better viewed by clicking the 'raw' button.

There were 1009 corrections, of which 42 were classified as print errors.

42 cases were judged to be 'no change' - mostly Denominative verbs or other verb forms.
