### ISSUE TITLE
CCS headword errors, part2

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#264]
This continues the kind of analysis done in #261.

After taking account of the corrections in #261,  the 'hwnorm1c.txt' file was regenerated (refer [here](https://github.com/sanskrit-lexicon/hwnorm1/tree/master/ejf/hwnorm1c)).
This contains headwords from all the dictionaries, organized so that each line has all the spellings that correspond to a given normalized spelling.  There are currently 386,872 words in hwnorm1c.txt.

Then, from this list, all the words occurring ONLY in CCS dictionary were isolated (681 of these).
Finally, from this list the headwords identifed in the #261 analysis as requiring 'no change' (80 of these) were removed.   The result is a list of 601 headwords of CCS that need to be examined.

That's what this issue deals with.

**Comment by funderburkjim** [comment]
These have now been examined and installed.

There were 550 corrections, of which 21 were print changes; the print changes are added to
[ccs_printchange.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/CCS/ccs_printchange.txt), as usual.

There were 59 no change cases, added to [corrections_nochange.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/corrections_nochange.txt) as usual.

The working files, notably prep1_edit.org, are [here](https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/dictionaries/CCS/issue-264).

**Comment by gasyoun** [comment]
Wow! Have we added all the nochange cases to the corrections_nochange.txt file? Did not we have more than 1.1k of them?

**Comment by funderburkjim** [comment]
@gasyoun   According to the history of corrections_nochange.txt, it was begun on Nov 25, 2015.

As I recall, I had thought to 'back fill' the nochange records marked in various issues before this date,
but neither I nor anyone else has done this completely.  I also recall Dhaval saying he had done some sort of
programmatic generation of earlier nochange records, but again, those have not been incorporated into this file.
