### ISSUE TITLE
CAE corrections based on alphabetical ordering

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#275]
A study was made of the headwords of CAE, based upon an examination of the headwords that are not in the 'standard' alphabetical ordering.   

[To be continued]

**Comment by drdhaval2785** [comment]
Any reason why we are taking up CAE only, and no other dictionary ?
A generic examination would also be a welcome step to decide which dictionaries have such an issue and correct all of them.

**Comment by funderburkjim** [comment]
These corrections have been installed.

The reason I am focusing on CAE is that in recent previous work I've focused on CCS, and CAE and CCS are closely related.   

As to why I chose to use the alphabetical ordering technique, I'm not exactly sure.  Probably, I noticed a few random cases in CAE where an error could be detected by such an examination of ordering, and decided to give it a whirl. 

We have used alphabetical ordering to examine some dictionaries (I see SKD and VCP have been so studied; perhaps others, I'm not sure.) I see an analysis of misorderings of AP was begun, but there were so many cases (3500+) that the analysis was not pursued.

**Comment by funderburkjim** [comment]
I'll probably next apply the analysis method of #264 to CAE.  And also, it will be useful to examine the headwords which occur ONLY in CAE AND CCS, since as mentioned above several cases were found where both dictionaries had the same error (in print or digitization).  But this work will be done after processing the several issues @drdhaval2785  has recently prepared using the N-gram approach, and also have catching up with the 30 or so backlog of Correction-Form pending cases.
