### ISSUE TITLE
Install recent n-gram studies

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#276]
For simplicity of installation, this issue is used to aggregate the correction records from various other recent correction submissions:

#266 , #267, #268, #269, #270, #271, #272, #273, #274

**Comment by funderburkjim** [comment]
These are now installed.

Here are some statistics relating to these nine batches of corrections.  

There were 383 cases in all, spread over 26 dictionaries.

 44 digitization errors, 8 print errors, and 331 no-change cases.

Here is a table that shows, for each dictionary, the total number of corrections (including both 
digitization errors and print errors),  the number of print errors, and the number of typos.
```
acc 2 0 108
ap90 1 0 2
ap   5 1 3
bhs  0 0 33
bop  1 0 0
bur  0 0 14
cae  2 0 1
ccs 1 0 0
gra 0 0 5
inm 2 0 8
krm 1 0 0
mci 0 0 1
md  0 0 1
mw72 2 0 4
mw 5 0 48
pe 3 1 7  (AS)
pui 1 0 11  (AS)
pw 3 0 18
pwg 3 0 4
sch 5 2 32 (key2 is AS)
shs 4 1 1
skd 0 0 4
vcp 4 2 15
vei 2 0 3  (AS)  change to hw2 required to allow hiatus in azAQauttarapArASarya
wil 2 0 2
yat 3 1 6
```

The prepared files of corrections in standard form were helpful in the installation process.

I'll close this issue, as well as the contributing issues 266-274.

**Comment by gasyoun** [comment]
Adorable stats. Perfect work. Clearly done.
