### ISSUE TITLE
User submitted correction in GRA

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#281]
A user recently submitted a correction to GRA (Grassman) dictionary, under headword kakuha.

I can't determine the error, which the user submitted in German:
```
3) erhöhter Theil des Wagens LB fehlt

With Google translation to English: 
elevated part of the carriage LB missing   (LB = line-break, probably)
```

Here is the text of the display of kakuha:
```
kakuha [p= 0309] : kakuhá, a., m., 1) a., hervorragend, erhaben; im RV meist im übertragenen 
Sinne [die Nebenform kakubhá (VS.) führt auf kakúbh zurück]; 2) m. oder a. mit mṙgá (429,4), 
hervorragendes Zugthier am Wagen der Açvinen. 
-ás 1) somiás rásas 779, 8; víṣṇus 288,14. -- 2) 181,5; 427,7; 429, 4; 626,48. 
-ám 1) tvā (índram) 665, 14. 
-âs 2) 184,3. 
-âsas 2) 340,2. 
-ân 1) (marútas) 225,11. [L=2372]
```

and here is the scan:
![image](https://cloud.githubusercontent.com/assets/6393033/14541674/177c61cc-0259-11e6-912f-b96495046d52.png)

Can anyone see what the error might be ?

**Comment by gasyoun** [comment]
I can't. With `fehlt` ones means something is missing.

**Comment by funderburkjim** [comment]
Possibly the same user  (no email provided, but there were several GRA corrections, most valid) also submitted the correction `2) saftig, kräftig`  for headword iza  (L=1773).

In this case, comparing MW  and PW iza,   maybe the user is suggesting an addition to Grassman,
due to an incompleteness in the GRA entry for iza  (i.e., he may be suggesting that the entry is missing an important sense normally associated with iza.)

If this is the case, maybe that's the way to understand the kakuha example,  as a suggested third sense that Grassman is missing.

@gasyoun Could this be what is going on?

Too bad no email was provided.

**Comment by gasyoun** [comment]
`he may be suggesting that the entry is missing an important sense normally associated with iza` - seems so.

**Comment by funderburkjim** [comment]
@gasyoun  Thanks for the confirmation.
