### ISSUE TITLE
Question on User submission

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#282]
A user submitted the following in the correction form under hw=Sanskrit, L = 32212.for dictionary MWE.

It looks sort of like Sanskrit, but I'm not clever enough to get sense out of it.

Since he left an email, maybe there is some response we can provide.

```
Aham adhya dasame dinnansya sambhashana samsruta varga sikskhan antari upavishtatha
```
Any suggestions?

**Comment by drdhaval2785** [comment]
He wants to convey that he is attemnding 10th day of spoken Sanskrit class.

Nothing which needs correction.


-- 
Dr. Dhaval Patel, I.A.S
Collector and District Magistrate, Anand
www.sanskritworld.in

**Comment by gasyoun** [comment]
`samsruta` - Telugu form?

**Comment by funderburkjim** [comment]
@drdhaval2785   Thanks for the interpretation!
