### ISSUE TITLE
BEN Devanagari-IAST comparision.

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#287]
Recently while tracking errors in trigrams, I stumbled upon this entry

mayUsva
![capture](https://cloud.githubusercontent.com/assets/5755132/14585009/534d34be-0480-11e6-98c9-f25e9e4fed74.png)

And print version
![capture](https://cloud.githubusercontent.com/assets/5755132/14585011/674d01a6-0480-11e6-98f8-f59fc0237f78.png)

This shows that the IAST version and Devanagari in BEN is keyed in separately.
This makes it a candidate for comparision of Devanagari v/s IAST, just as was done for PD.

**Comment by funderburkjim** [comment]
@drdhaval2785   

Working documents have been prepared to help us with this good idea.

According to this approach, there are 458 cases where the IAST and Devanagari differ.

Before I begin tackling the cases, I'd like you to do some spot checking of the cases to see if
anything catches your eye as needing revision.  This is because the IAST part of Benfey is often
quite complicated.

Take a look at [this summary](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/BEN/issue-287prep/hwchk_iast1.txt) or 
the similar [emacs working document](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/BEN/issue-287prep/hwchk_iast1.org), which is what I will be working from.

**Comment by drdhaval2785** [comment]
@funderburkjim 
A suggestion

There seems to be errors in both Devanagari and Roman one.
Therefore, our summary should show suggestions for corrections in Devanagari one or Roman one.

The logic could be - 
A. If key1 is found in other dictionaries, suggest change only in key2.
B. If key2 is found in other dictionaries, suggest change only in key1.
C. If neither key1 nor key2 is found in other dictionaries, flag it as the one requiring closer look.

Let me clarify it with examples.

A.
Examination entry -
`0001-b:aMSumanta:338,339:am5çu + mant.:aMSumant`
The sanhw1.txt entries relevant to this entry are
```
aMSumant:CAE,CCS,PW,PWG,STC
aMSumanta:BEN
```
Here aMSumant is found in other dictionaries. Therefore, chances are there that it is correct word. So our key1 should show tentative correction from aMSumanta->aMSumant


B.
Examination entry
```
0011-b:atilubDatA:1165,1167:ati-lubdha + tva10:atilubDatvA
```
Here the sanhw1.txt entry relevant is
```
atilubDatA:BEN
```
There is nothing like atilubDatvA in any dictionary. Therefore, our key2 has some error and should be suggested to be changed to atilubDatA.

C.
Examination entry
```
0002-a:akfta:380,389:a-hr2ita.:ahfta
```
Here `akfta` and `ahfta` both are seen in sanhw1.txt. Therefore, we cannot be sure which is correct and which is wrong. Flag them as needing closer look.

**Comment by gasyoun** [comment]
Good catch! Perfect classification. Linnaean classification.

**Comment by funderburkjim** [comment]
Although as part of the case review process I keep a copy of hwnorm1c.txt open in an emacs window,
it is more efficient to have the checks done ahead of time, as @drdhaval2785  suggests.

The preparation program was so modified, so in the prep1_edit.org file, these lookups are present.
For instance,
```
* TODO Case 0001: aMSumanta [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ben&page=0001-b][page 0001-b]]
;ben:aMSumanta,6:aMSumant:n:
;ben:aMSumanta,6:am5çu + mant.:am5çu + mant.:n:
; aMSumanta:aMSumanta:BEN
; aMSumat:aMSumat:AP,AP90,BOP,BUR,GRA,GST,INM,MD,MW,PD,PUI,SHS,VCP,WIL,YAT;aMSumant:CAE,CCS,PW,PWG,STC
;  <P>{#aMSumanta#}¦ {%am5çu + mant.%} {@I.@} adj., f.
;  <>{%mati10.%} Radiant. {@II.@} m. The sun.

* TODO Case 0002: akfta [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ben&page=0002-a][page 0002-a]]
;ben:akfta,22:ahfta:n:
;ben:akfta,22:a-hr2ita.:a-hr2ita.:n:
; akfta:akfta:AP,AP90,BEN,BUR,CAE,CCS,GRA,GST,MD,MW,MW72,PD,PW,PWG,SCH,SHS,STC,VCP,WIL;akftaM:SKD;akftta:AP,AP90,GRA,MW,MW72,PD
; ahfta:ahfta:MD,MW,PW,STC
;  <P>{#akfta#}¦ {%a-hr2ita.%} {@I.@} adj., f. {%ta10.%} {@1.@} Not
;  <>done. {@2.@} Undone, Man. 8, 117. {@3.@}
;  <>Not cultivated, Man. 10, 114. {@4.@}
;  <>Wavering, MBh. 14, 34. {@II.@} f. {%ta10.%} A
;  <>daughter who is not by a formal de-
;  <>claration, but only mentally, appointed
;  <>to supply an heir for her father, MBh. 9,
;  <>136. {@ -- Comp.@} {%Kr2ita-,%} adj. 1. wrought
;  <>and unwrought. 2. prepared and not
;  <>prepared.

```

**Comment by funderburkjim** [comment]
One of the time-consuming parts of checking the case is to decide whether an error should be classified as a print error or as a digitization error. (p or t).  This decision always involves looking at the scanned image.  

I'm tempted to classify all errors as 't', even if, as in cases such as aMSumanta, the correct classification is (based upon viewing the scanned image) 'p'.   The reason for this would be the expectation that the overall task would be less time consuming if there are many  clear cases such as aMSumanta.   

What do others think of this?

**Comment by Sonnetag** [comment]
I am only working with MW Sanskrit-English Dictionary (1899) because my 
current project heavily rely on.
I check the scanned images often for a number of reasons.

Yes almost all of the errors are digitization errors.  However, there 
are some print errors. I have encountered 2 cases so far, if my memory 
serves me. I have been reporting them as I find them. Unfortunately I 
have not distinguished which error, when I reported. From next time, I 
will mark which error when I report it.  Thank you to you all for your 
hard work.

**Comment by gasyoun** [comment]
> I'm tempted to classify all errors as 't', even if, as in cases such as aMSumanta, the correct classification is (based upon viewing the scanned image) 'p'. The reason for this would be the expectation that the overall task would be less time consuming if there are many clear cases such as aMSumanta, where the correction itself does not require looking at the scanned image, but only the p-t decision.

In the sake of speed I vote for `t`. The `p` list was a good idea to be included as an additional list for reprints. It can be an additional work done later - to check which `t` are `p`. For that I would introduce a new tag - approved or not-approved. So one would not check the older day 't'-s which should mostly be as stated.

**Comment by drdhaval2785** [comment]
I disagree with the proposal of classifying all errors as 't'.
We have put in so much effort to classify the erros as 't' and 'p'.
It is worth the time to continue the effort. Speed may decrease a little bit, but output is worth it.

**Comment by gasyoun** [comment]
Let Jim decide. Dhaval is a rocket engine. For him it might be a matter of seconds. For me and Jim - many, many minutes. So it's all because it's not in our blood.

**Comment by funderburkjim** [comment]
Upon reflection, I think I come down on the side of retaining the p-t distinction as a required part of our systematic correction efforts.  Having lists of 'p' errors for the various dictionaries is a contribution to the scholarship of the Sanskrit lexicons, and thus is worth the occasional extra effort.  At some point, we (or someone) will want to make use of such information in the displays of the dictionaries, along the lines suggested in these issues (such as #128) by @zaaf2 .  We may also want to share such information with other workers, notably those preparing the monumental PD.

**Comment by gasyoun** [comment]
> We may also want to share such information with other workers, notably those preparing the monumental PD.

Exactly. Because in 1800 years they will finish letter `ha`.

**Comment by funderburkjim** [comment]
These corrections now identified and installed. Here are a few stats:
```
433 records written to change-287.txt
IAST-n 6
DEVA-p 47
DEVA-t 71
DEVA-n 3
IAST-p 226
IAST-t 80

306 IAST changes.  Usually, these were cases where an under-dot (for retroflex) or an 
over-circumflex (for long vowels in BEN) were missing.  In a few cases, the IAST was irregular, and
I thought it appropriate to generate print changes to enforce more regularity.  Most IAST changes
were errors in the print.

118 Devanagari errors. The Devanagari is often blurred in the print.

The few (9) no-changes were due to odd characters in the IAST which the comparison algorithm 
didn't handle.

There was 1 additional case where a prefix-form of headword verb 'nand' was erroneously marked 
as a separate headword;  correcting this introduces a change in some L-numbers.
```

The idea of matching the Devanagari and IAST forms to hwnorm1c list of headwords in all 
dictionaries proved to be a good efficiency supplement in this task.

**Comment by gasyoun** [comment]
> matching the Devanagari and IAST forms to hwnorm1c list of headwords in all 
dictionaries proved to be a good efficiency supplement

Guess not for all, but for some gives a lot.
