### ISSUE TITLE
CAE corrections, continue

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#289]
All the headwords of CAE which occur in no other dictionary are examined.  There are 874 of these currently.

**Comment by funderburkjim** [comment]
These cases resulted in
* 326 changes to headwords, of which 78 were classified as print changes
* 545 no change cases.

The corrections have been installed.

Working documents are in [this directory](https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/dictionaries/CAE/issue-289prep).

I'm close to finishing examination of CAE and CCS by the current methods.

The next stage will be to examine the headwords which occur exactly in BOTH dictionaries (but in no other dictionaries).

Most of the CAE no-changes are simple compounds that Cappeller decided to include  as headwords.

One special feature of the CAE dictionary is that there are many headwords for which semantic alternates are provided.  And, it appears that the digitization generally included these alternates as separate headwords.   That is probably a major reason why there are about 10,000 more headwords in the digitization of CAE than in the digitization of CCS, where these alternates were generally not repeated as separate headwords.

**Comment by funderburkjim** [comment]
Incidentally, there are a few no change cases that I marked with a '?'.  These were cases that might need correction.  These are shown below, in the hope that someone else might take a second look.
```
cae:289:ajahakzaRA,401:ajahakzaRA->ajahakzaRA: ? = ajahallakzaRA cf. PW.  Also, stated to be opposite of jahallakzaRA
cae:289:anudGAyya,1436:anudGAyya->anudGAyya: ?
cae:289:AyAsada,4468:AyAsada->AyAsada:  variant AyAsaka, Might be AyAsad ?
cae:289:AhirbunDa,4861:AhirbunDa->AhirbunDa: ? possible print error for buDna. = AhirbuDya
cae:289:IqeRya,5097:IqeRya->IqeRya: = MW Iqenya  (is IqeRya an error?)
cae:289:IriRasTa,5112:IriRasTa->IriRasTa: ?
cae:289:fgyajuz,6228:fgyajuz->fgyajuz: ? = mw fgyajuza, fgyajus
cae:289:ekAdaSaguRa,6485:ekAdaSaguRa->ekAdaSaguRa: Why not 'gaRa' ?
cae:289:kanakAjja,6969:kanakAjja->kanakAjja: ?
cae:289:kAnyakujja,7478:kAnyakujja->kAnyakujja: ?  could be mis-spelling of kAnyakuYja of WIL
cae:289:cikitvaMs,10493:cikitvaMs->cikitvaMs:  = mw cikitvas. Note ccs may also have 'M' ?
cae:289:TUrv,13112:TUrv->TUrv:  verb. = mw Turv.  Is TUrv acceptable?
cae:289:daRqakAla,13189:daRqakAla->daRqakAla:  ?
cae:289:dIdivas,13794:dIdivas->dIdivas: ? may have anusvAra. dIdivaMs
cae:289:pracyotos,20172:pracyotos->pracyotos:  infinitive of pracyu (?)
cae:289:pravahaRabalIvarda,20921:pravahaRabalIvarda->pravahaRabalIvarda: ?
cae:289:mfdBa,25286:mfdBa->mfdBa: ?
cae:289:ramawaka,26606:ramawaka->ramawaka: ?? text has (after rama), 'rawa or *ka'  So alphabetiically wrong. Not sure what is correct
cae:289:rAzwriyasyAla,26986:rAzwriyasyAla->rAzwriyasyAla: ?
cae:289:vicazarRi,29278:vicazarRi->vicazarRi: ?
cae:289:viSezay,30233:viSezay->viSezay:  verb stem?
cae:289:Saktf,31603:Saktf->Saktf:  ?
cae:289:saguqA,34091:saguqA->saguqA: ?
cae:289:sarpaSattra,35821:sarpaSattra->sarpaSattra: ? cannot find Sattra in any dictionary
cae:289:sukradDa,37020:sukradDa->sukradDa:  ?  maybe sukroDa ? kradDa isn't a word
cae:289:svavAn,39101:svavAn->svavAn:  ?   nom. singular of svavat (MW)

```

**Comment by gasyoun** [comment]
> major reason why there are about 10,000 more headwords in the digitization of CAE than in the digitization of CCS, where these alternates were generally not repeated as separate headwords.

Oh, it's getting bad.
