### ISSUE TITLE
skd corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#291]
This issue examines 600 or so headwords of SKD dictionary for possible spelling errors.

The first of these cases were originally entered somewhat randomly in #259;  but since the approach taken seems fruitful on the basis of that preliminary work, the work is being transferred to this separate issue.  The #259 cases will be part of this work.

**Comment by funderburkjim** [comment]
These cases have now been examined, and corrections generated and installed.

597 cases were examined.

518 were classified as print errors (84), typos (109) or no-changes (325), and are shown
in standard form [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/SKD/issue-291prep/change-291.txt).

76 were classified with a '?', meaning that I either couldn't decide the status, or, more likely, there
was no typo error, but I couldn't see how the word might be related to other words.
An extract of the emacs org mode file for these 76 cases is [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/SKD/issue-291prep/prep1_edit_query.org).  
*At some point, either I or someone else needs to examine these*;  some of these I now recognize as
DAtupAWa forms of roots from kavikalpadruma (N. of a metrical collection of roots written by vopa-deva.), and these should be reclassified as 'nochanges'.  However there were some other cases which may indeed be spelling errors, but I couldn't decide one way or the other.


For the no-change cases, most are marked as being 'equal' to words in other dictionaries.  
It seems that skd is rigorous in providing a nominative case form (usually singular, but sometimes
dual or plural) for the headword spelling; so for instance 
`skd:goDuk,11319:goDuk:n: nom.sg. of goduh`.  I tried to indicate the correspond 'MW' form for these.   And also did some correspondences programmatically (not shown here); such as 'pitA' as the nom.sg. form of 'pitf', and several other categories.   As we improve our current 'hwnorm1' multidictionary searches, such correspondences will be useful.

There were also 76

**Comment by funderburkjim** [comment]
There were also three cases where a word was incorrectly marked as a headword, where it was really just part of the entry for the previous headword.   Corrections of these modify the L-number for the skd headwords.

**Comment by gasyoun** [comment]
> 518 were classified as print errors (84)

After reading it I fell off from my dragon. Congratulations!

> did some correspondences programmatically (not shown here); such as 'pitA' as the nom.sg. form of 'pitf'

Rather interesting to know what exactly. Does not matters how :gem:
