### ISSUE TITLE
Install recent 2-gram, 3-gram studies

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#295]
This issue is devoted to the amalgamation of numerous headword spelling correction studies developed by @drdhaval2785.   Here is a listing of those studies, along with the issue numbers

* 2-grams vs MW72 (#241) 53 final entries [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/ngram/output/corrections/allvsMW72_2_corrected.txt)
* all vs VCP 2-grams (#257) 44 final entries [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/ngram/output/corrections/allvsVCP_2_corrected.txt)
* all vs STC 2-grams (#277)  46 final entries [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/ngram/output/corrections/allvsSTC_2_corrected.txt)
* all vs BHS 2-grams (#280) 97 final entries [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/ngram/output/corrections/allvsBHS_2_corrected.txt)
* all vs BEN 2-grams (#283). 32 final entries [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/ngram/output/corrections/allvsBEN_2_corrected.txt)
* all vs MW 3-grams:  part 1 (#284), part 2 (#285), part 3 (#286) , part 4 (#288)
  In #284, Dhaval posted the link to final corrections [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/ngram/output/corrections/allvsMW_3_corrected.txt)
  This final list has 375 items.

The installation of all these  (by my count, 647) entires will now begin.

**Comment by funderburkjim** [comment]
All the corrections now installed.
Here's a summary:
```
     #t   #p   #n
acc  21    1  123
ap90  4    0    1
ap    3    0    0
ben   0    0    0   (5 items had previously been corrected)
bhs   0    0   67
bop   0    0    1   (1 item had previously been corrected)
bur   8    0   49
cae   1    0    0   (8 items had previously been corrected)
ccs   2    0    0   (2 items were previously corrected;
  ccs:yajYoyavIta,19483:yajYoyavIta:n:Yo 
       A previous correction to yajYopavIta had been made, and after
       review yajYopavIta looks right.
gra   0    0    1
gst   1    0    3
inm   2    0   20
   Note: inm:rAmAyaROpAKyAna,8984:rAmAyaRaupAKyAna:t:RO
     The 'O' is due to the original entry being a two-word headword.
     This is neither a 't' or a 'p' error.
     This false 'O' is corrected by a change to hw2.py for INM.
krm   0    0    1
mci   0    0    3
md    0    0    1
mw72  5    0   11
mw    2    0   40
  One change involving mw:kzRU,60596.1:kzRU:n:RU  
  This is not a headword spelling error, but the H-code should be H2, rather 
  than H1B.
  Regarding:
   mw:pallISarawayoHPalAPalavicAra,120295.1:pallISarawa:t:oH
   mw:pallISarawayoHSAnti,120295.2:pallISarawa:t:oH
   I changed these to 'n' (no change).
  They are  multi-word headwords (names
  of works that start with pallISarawa).  cf. ACC
pe    2    1   17
pgn   0    0    4
pui   4    3   43
pw    9    1   30
pwg   7    2   14
sch   1    3   32
shs  11    0    5
     Re: shs:akzabDu,187:akzubDa:t:bDu  . This correction previously made.
skd   0    0    6
   skd:PalAWyA,23781:PalAQyA:t:lAW   changed previously
stc   1    0    1
vcp  10    0   16
vei   0    0    2
wil   7    0    0
yat  13    1    8
    ===  ===  ===
    114   12  499
30 dictionaries.
```

@drdhaval2785   Thanks for all those lovely corrections :smile:

**Comment by drdhaval2785** [comment]
Pleasure is all mine.
It is very interesting to see the details documented so well.
Learning proper logging by watching your analysis.

**Comment by gasyoun** [comment]
> It is very interesting to see the details documented so well.

Yeah, the documenting needs additional research :heavy_multiplication_x:
