### ISSUE TITLE
YAT, bug in the display

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#297]
While reviewing the YAT corrections in #295, I noticed a bug in the display, which probably should be considered a bug in the xml display of YAT.  Another possibility is that it should be considered a display in the markup of yat.xml.

Here's an example.
```
; maraRABiBuKa -> maraRABimuKa # typo # BuK TODO
43847 old <HI>{#maraRA\BiBuKa (KaH-KA-KaM)#}¦ {%a.%} On the
```
Now, here's the display of that record:
```
maraṇābhibhukha [p= 577-b] : a. On the 
point of death, near to death. [L=29137]

Note that (KaH-KA-KaM) is missing from the display.  That's the bug symptom.
```
The display is based on yat.xml, and the relevant xml record is:
```
<H1><h><key1>maraRABiBuKa</key1><key2>maraRA\BiBuKa (KaH-KA-KaM)</key2></h>
<body><i>a.</i> On the <lb/>point of death, near to death.</body>
<tail><L>29137</L><pc>577-b</pc></tail></H1>

Note that (KaH-KA-KaM) is part of key2.
```

We certainly need to get that (KaH-KA-KaM) into the display.

There would be several ways to accomplish this:

*  option 1. Change yat.txt markup:
   ```
   43847 new <HI>{#maraRA\BimuKa#}¦ {#(KaH-KA-KaM)#} {%a.%} On the
   ```

* option 2. Leave yat.txt unchanged, and alter the xml version:
   ```
   <H1><h><key1>maraRABiBuKa</key1><key2>maraRA\BiBuKa</key2></h>
   <body> <s>(KaH-KA-KaM)</s> <i>a.</i> On the <lb/>point of death, near to death.</body>
   <tail><L>29137</L><pc>577-b</pc></tail></H1>
   ```

* option 3.  Leave both yat.txt and yat.xml unchanged, but modify the display program so it shows stuff
     in key2 after the space that is currently present in key2.

My preference at the moment is option 1.  The gender-ending information is not the kind usually thought of as key2 information (it's not accent information, or pada information).

What do others think?

**Comment by drdhaval2785** [comment]
I agree with option 1.
But I have not seen any changes yet in structure of .txt file on mass scale.
If you think it is safe, let us go ahead with it.

**Comment by gasyoun** [comment]
> option 3.

Is bad, so go for 1st. Otherwise, if unsafe, 2nd.

**Comment by funderburkjim** [comment]
This is a different kind of change task than that which starts with a collection of 'standard form corrections.'  However, it turns out that it could be done rather easily, AND safely.  

Preliminary observations:
```
Referring to yathw0.txt, in 44399 of the 45205 lines, there is a space
in the raw headword.
In Emacs, delete lines matching regexp 
^[^:]*:[^: ]* +([^: ]*):
2667 lines remain.
Of these, delete lines containing NO space
1861 lines remain.
These appear to be mostly verbs.
Nonetheless, it appears appropriate to remove a space and everything after
the space to OUTSIDE of the 'key' field.
```

A special program was written to generate update transactions to carry out this idea.
This program is pywork/correctionwork/issue-297/genspecial.py in the Yates directory.

Here is a summary of what that program does.
```
    Read yathw0.txt and yat.txt
    For every line of hw0 that contains a space in key field, generate an update
    of the corresponding line of yat.txt.  The update will move 
    the space and following characters of the key field outside of the
    headword specification of the line.
    Example. 2nd line of yathw0.txt:
    001-a:a (aH):93,93
    corresponding line 93 of yat.txt:
    <HI>{#a (aH)#}¦ 1. {%m.%} A name of Vishnu.
    Generate this update record pair
    93 old <HI>{#a (aH)#}¦ 1. {%m.%} A name of Vishnu.
    93 new <HI>{#a#}¦ {#(aH)#} 1. {%m.%} A name of Vishnu.
```

The program generated 44,399 old/new update transactions.

From this point on, the update process is the same as always.
* Apply these transactions to the previous version of the yates digitization
* regenerate the headwords
  As a check, I compared the new headword list (yathw2.txt) with the previous one, and
  found, as expected, that the two lists are identical.
* regenerate the xml file (yat.xml)
  Now, the stuff after the space is now part of the `<body>` element, rather than part of the `<key2>` element, as desired.

No changes were required in the programs that generate the headwords or that generate the xml.

A small sample of the displays show the originally noticed problem is solved.  For instance, the
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html display now shows:
```
maraṇābhimukha [p= 577-b] : (khaḥ-khā-khaṁ) a. On the 
point of death, near to death. [L=29137]
```
