### ISSUE TITLE
long KRM headwords

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#300]
Following a suggestion made in #294 ,  here is the list of headwords in the digitization of KRM whose
SLP1 spelling has a length of 7 or more characters:
```
page number:headword:line1,line2 of krm.txt
0201:kuwumba:5327,5349
0606:qINvihAyasA:15418,15451
0724:daridrA:18405,18458
0849:palpUla:21696,21702
1318:Scyutir:34544,34561
1356:zwrakza:35599,35600
1370:saNketa:36021,36024
1371:saNgrAma:36025,36037
1376:sUrkzya:36162,36167
1381:skandir:36325,36375
1383:skanBuH:36376,36402
```
Probably in `qINvihAyasA`, vihAyasA  is the meaning, and the headword should be 'qIN', so there
should be correction.
```
krm:qINvihAyasA,651:qIN:t:  vihAyasA  is the meaning
```
None of the others look like candidates for corrections.

@drdhaval2785   Agree?

**Comment by drdhaval2785** [comment]
Agree. Time to close.

**Comment by funderburkjim** [comment]
For convenience, include this AE correction submitted by a user via email:
```
ae:husband,5059:Batf:Bartf:t:
```

**Comment by funderburkjim** [comment]
corrections installed.
