### ISSUE TITLE
allvsSCH_3

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/CORRECTIONS#301]
Namaste
Interesting issues in allvsSCH_3--

acc:काटकोपनिषद्,30371:काठकोपनिषद्:p:काट् Print unclear
Actually that is ठ in the text but due to some erase-effect, it appears as ट. 
![kathaka](https://cloud.githubusercontent.com/assets/6392207/16693109/4911e6ea-4551-11e6-8bf1-3631b0fa3855.PNG)

bhs:ज्ञानलोतु,6692:ज्ञानलोतु:n:ओतु (There is a question mark in the printed book- mentioning a possibility of this word being an error)

Will such information be of any help? (Image attached)

![lotu](https://cloud.githubusercontent.com/assets/6392207/16693114/52559e5e-4551-11e6-85d4-a50a224af053.PNG)

**Comment by Shalu411** [comment]
mw:दिनम्मन्या,92210.1:दिनम्-मन्या:n:म्म (there is a hyphen between the two words in IAST in printed book)

Should we be considering that hyphen and use same in Devanagari as well?
![dinam-manya](https://cloud.githubusercontent.com/assets/6392207/16693488/fcd9ed98-4552-11e6-827c-c4270843e2c5.PNG)

**Comment by drdhaval2785** [comment]
Hyphen is there in key2. Key1 it is ommited. Not to correct.

We nowadays feed the texts with explanations only. Less of images. Only in
difficult cases, post images.

**Comment by Shalu411** [comment]
Sure. Fine. Got it. 

mw:धात्वाकराख्य,100715:धात्वाकराख्य:n:राख्
This case was not found in scan page. Searched keenly thrice. If anyone can locate, would like to check.

**Comment by funderburkjim** [comment]
> mw:धात्वाकराख्य,100715:धात्वाकराख्य:n:राख्

Occurs under धात्वाकर on [page 514](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=514).

You might like to try [this display](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html) since 
* it lets you choose Devanagari for input (as well as output), and
* it has a 'suggestion' feature.
* You can use it for any dictionary.

**Comment by gasyoun** [comment]
> try this display 

Best one out there.

**Comment by gasyoun** [comment]
@funderburkjim 
[L=732] [p= 1-189]	2. Kosa -> Kośa (because of [L=731] [p= 1-189]	1. Kośa)
http://www.sanskrit-lexicon.uni-koeln.de/scans/VEIScan/2014/web/webtc/indexcaller.php

**Comment by funderburkjim** [comment]
@gasyoun   Have submitted correction Form for VEI - kosa -> koSa (slp1)

**Comment by gasyoun** [comment]
@funderburkjim time to close?
