### ISSUE TITLE
dIpikA and friends

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#302]
While investigating the lack of derivation for `muktAvalivyAptivAdadipikA`, several issues arose.

**First**,  `dipikA` is wrong, the first vowel is long: `dIpika`
   There are in fact four occurrences in mw.xml of this error. These are all typos, occurring also in
   `muktAvalIvyAptivAdadipikA`,  `nyAyasidDAntamaYjarIdipikA`, and in body of entry for 
   headword `sAMKyAlaMkAra` as `sAMKya-krama-dipikA`.

**Second**, notice that there are two headwords with almost identical spellings (after correction):
  `muktA-vali-vyAptivAdadIpikA` and `muktA-valI-vyAptivAdadIpikA`.
   This is because MW gives two variants for the parent: `muktA-vali` or `muktA-valI`;  AND, the 
   way these alternates were handled also included making alternates *for all the children*.
   
   Here's the entire list of headwords involved, as currently present in mw.xml:
```
H=H3, L=165202, key1=muktAvali
H=H3B, L=165202.1, key1=muktAvali
H=H4, L=165202.3, key1=muktAvalikiraRa
H=H4, L=165202.31, key1=muktAvaliwIkA
H=H4, L=165202.32, key1=muktAvalidIpikA
H=H4, L=165202.33, key1=muktAvalipadDati
H=H4, L=165202.34, key1=muktAvaliprakASa
H=H4, L=165202.35, key1=muktAvalipraBA
H=H4, L=165202.4, key1=muktAvalImaya
H=H4, L=165202.5, key1=muktAvalivyAKyA
H=H4, L=165202.51, key1=muktAvalivyAptivAdadIpikA

H=H3, L=165203, key1=muktAvalI
H=H3A, L=165203.1, key1=muktAvalI
H=H3A, L=165203.11, key1=muktAvalI
H=H4, L=165203.2, key1=muktAvalIkiraRa
H=H4, L=165203.3, key1=muktAvalIwIkA
H=H4, L=165203.4, key1=muktAvalIdIpikA
H=H4, L=165203.5, key1=muktAvalIpadDati
H=H4, L=165203.6, key1=muktAvalIprakASa
H=H4, L=165203.7, key1=muktAvalIpraBA
H=H4, L=165203.8, key1=muktAvalIvyAKyA
H=H4, L=165203.9, key1=muktAvalIvyAptivAdadIpikA
```

Here is the relevant portion of the scanned image:
![image](https://cloud.githubusercontent.com/assets/6393033/17080539/ed4502cc-5101-11e6-9203-40977afe1dac.png)

**Comment by funderburkjim** [comment]
It seems appropriate to duplicate the H3 and two H3A. 
However, it now seems inappropriate to duplicate the H4s without further thought.

For instance, in the case that started this train of thought, a reference to ACC shows that the 
long-I version of `valI` is the only one mentioned: `muktAvalIvyAptivAdadIpikA`

A further comparison with ACC shows
* none of the short-i `vali` spellings appear in ACC
* The following long-i `valI` spellings appear in ACC
   `muktAvalIkiraRa`, `muktAvalIwIkA`, `muktAvalIpadDati`, `muktAvalIvyAptivAdadIpikA`
* neither spelling of `muktAvalIdIpikA`, `muktAvalIprakASa`, `muktAvalIpraBA`, 
  `muktAvalIvyAKyA` or `muktAvalImaya`  appears in ACC.
* `muktAvalImaya`  is weird because in the digitization, 
    * it appears (a) only in the long-I spelling  (which the scan supports), and
    * that long-spelling is unfortunately listed among the short-i variants.

My inclination is to remove the H4 entries with short-i spellings, since there is no evidence of their use.

Does anyone else have an opinion?

**Comment by funderburkjim** [comment]
Here's an unrelated item.

In MW there is a headword `mukti-kozwaka`, mentioned as a poet.  There is no derivation for
`kozwaka`, although there is a headword `kozWaka`, meaning *store-room*, so `mukti-kozWaka` would be a nice name for a poet.

No other dictionary has `mukti-kozwaka`, or `kozwaka`.  While `kozWaka` is in many dictionaries, and
`mukti-kozWaka` is in ACC, as a poet.

Thus, it seems likely that `mukti-kozwaka` in MW is a print error and should be changed to
`mukti-kozWaka`.  

Agree?

**Comment by drdhaval2785** [comment]
आवलि आवली both are valid words. So no possibility of removing मुक्तावलि.
Both have to be retained.

**Comment by funderburkjim** [comment]
> Both have to be retained.

Agree.  I am suggesting removing only 
```
L = 165202.3 through L=165202.35,  
L=165202.5 and 165202.51
and changing L=165202.4 to L=165203.71

These involve changes only to muktAvalikiraRa through muktAvalivyAptivAdadIpikA
```

**Comment by funderburkjim** [comment]
Unrelated item:
```
mw:muqAKyA,165403:muRqAKyA:t: muq ->muRq
```

**Comment by funderburkjim** [comment]
Unrelated corrections:
```
mw:pratisaMsaMsarga,133343:pratisaMsarga:t:saM erroneously doubled
mw:pratisaMsaMsfzwa,133344:pratisaMsfzwa:t:saM erroneously doubled
mw:pratisaMsaMsfzwaBakta,133345:pratisaMsfzwaBakta:t:saM erroneously doubled
mw:pratisaMsaMskAra,133347:pratisaMskAra:t:saM erroneously doubled
mw:pratisaMsaMskAraRA,133348:pratisaMskAraRA:t:saM erroneously doubled
mw:pratisaMsaMskfta,133349:pratisaMskfta:t:saM erroneously doubled
```

Incidentally, there is one headword with a properly doubled saM prefix:  `saMsaMyu`

**Comment by funderburkjim** [comment]
Another mw correction:
```
mw:praSnasamucaya,137660:praSnasamuccaya:t: ucaya -> uccaya
```

**Comment by gasyoun** [comment]
> Agree. I am suggesting removing only

@drdhaval2785 ?

**Comment by funderburkjim** [comment]
mw correction:
```
mw:virUDaka,199471:virUQaka:t: rUDa -> rUQa
mw:virUDaka,199472:virUQaka:t: rUDa -> rUQa
mw:virUDaka,199473:virUQaka:t: rUDa -> rUQa
mw:virUDaka,199474:virUQaka:t: rUDa -> rUQa
```

**Comment by funderburkjim** [comment]
mw correction:
```
mw:prakIrRakezI,:prakIrRakeSI:t: kezI -> keSI
```

**Comment by funderburkjim** [comment]
These corrections now installed.

That includes the deletions mentioned [above](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/302#issuecomment-234794598)
