### ISSUE TITLE
Misc. corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#303]
```
mw:carahArDa,72278:caraRArDa:t: print smudge
mw:carahArDa,72279:caraRArDa:t: print smudge
```

**Comment by funderburkjim** [comment]
```
mw:cittaDArAbudDisaMku,:cittaDArAbudDisaMku:t:  from supplement; last part was previously part of text, by mistake
```

**Comment by funderburkjim** [comment]
This is a question regarding the word 'roza-vAhaRa' . This word appears in MW and WIL (and also the Wilson surrogates of SHS and YAT).   

It shows up in MW among the compound of `roza` and is translated `being a vehicle of anger`.  Thus,
it appears to be a simple tatpuruza compound.  

The question is why the 2nd part of the compound has the retroflex nasal.  There is no headword
`vAhaRa`, but only `vAhana` (vehicle).  So, it must be that the retroflex nasal in `roza-vAhaRa` is due to
`n-R` sandhi governed by the `r` in `roza` (or maybe by the `z`); but in either case, the 
`n-R` sandhi *crosses the pada boundary` of the compound.

It is my understanding that the `n-R` sandhi does not normally cross a pada boundary in a compound;
although the example of `rAmAyaRa` shows that is sometimes does.

Is there a consistent explanation available for these cases?

**Comment by drdhaval2785** [comment]
रषाभ्यां नो णः समानपदे ८.४.१

This rule mandates n->R when it occurs after r,z in the same पदम्.

अट्कुप्वाङ्नुम्व्यवायेऽपि ८.४.२

This rule says that any combination of
[rz][aAiIuUfFxeoEOhyvrkKgGNpPbBmM]*[n] is fine.

पदम् is defined as सुप्तिङन्तं पदम् i.e. the words ending in case suffices,
verb suffices are called पदम्. In this case, there is no case ending
between first and second word of compound. So n->R change happens.

For counter example see अग्निर्नयति. Here, the r belongs to the first word
which ends with a case suffix.

**Comment by funderburkjim** [comment]
Let me paraphrase your explanation to see if I understand the reasoning as applied to the
compound of 'roza' and 'vAhana'.  

Since there is no case ending between the first word (roza) and
the second word (vAhana) of the compound,the 'r' (or 'z') of 'roza' and the 'n' of 'vAhana' are considered to be in the same padam;  therefore, since the intervening characters between 'z' and 'n'  (namely,
'avAha') are acceptable (i.e., in the set `aAiIuUfFxeoEOhyvrkKgGNpPbBmM`), the 'n' of vAhana changes to 
'R', thereby resulting in the final form of the compound as 'rozavAhaRa'.

@drdhaval2785  Do you confirm the wording of this explanation of the example?

**Comment by funderburkjim** [comment]
```
mw:laGucitrAlaMkara,180835:laGucitrAlaMkAra:p:  laMkara -> laMkAra.  ACC confirms this as name of work.

**Comment by funderburkjim** [comment]
```
mw:vamaSAhva,184303:vaMSAhva:t: vamaS -> vaMSa
```

**Comment by funderburkjim** [comment]
```
mw:vyavavahfta,209232:vyavahfta:t: wrong duplication of prefix ava
; There are two names of works in mw, vyAvahArikatvaKaRqana and vyAvahArikatva-KaRqaRa-sAra.
; ACC confirms the spelling `KaRqana` in both cases. So assume the `KaRqaRa` is a print error.
mw:vyAvahArikatvaKaRqaRasAra,210013.1:vyAvahArikatvaKaRqanasAra:p:

**Comment by funderburkjim** [comment]
```
mw:vrajaBuzaRamiSra,210469:vrajaBUzaRamiSra:t: BuzaRa -> BUzaRa
```

**Comment by funderburkjim** [comment]
```
mw:samApApAdya,234448:samApAdya:t: wrong repetition of Ap
mw:samApApAdya,234449:samApAdya:t: wrong repetition of Ap
```

**Comment by funderburkjim** [comment]
```
mw:sarpirmisra,238084.1:sarpirmiSra:t:  misra->miSra

**Comment by funderburkjim** [comment]
```
mw:sarvalokakrit,238656:sarvalokakft:t: krit -> kft
```

**Comment by funderburkjim** [comment]
```
mw:sAraprakaSikA,242886:sAraprakASikA:t: prakaSikA -> prakASikA
```

**Comment by funderburkjim** [comment]
```
mw:sArakzetramAhatmya,242837:sArakzetramAhAtmya:t:  mAhatmya -> mAhAtmya
mw:sArakzetramAhatmyasArodDAra,242838:sArakzetramAhAtmyasArodDAra:t:  mAhatmya -> mAhAtmya
```

**Comment by funderburkjim** [comment]
```
mw:hiteCA,262925:hitecCA:t: ecA -> ecCA  (icCA)
```

**Comment by drdhaval2785** [comment]
Yes, I agree with the paraphrase.

**Comment by funderburkjim** [comment]
Here is an application of the paraphrase to the compound of 'rAma' and 'nATa'.

Since there is no case ending between the first word (rAma) and
the second word (nATa) of the compound, the 'r'  of 'rAma' and the 'n' of 'nATa' are considered to be in the same padam; therefore, since the intervening characters between 'r' and 'n' (namely,
'Ama') are acceptable (i.e., in the set aAiIuUfFxeoEOhyvrkKgGNpPbBmM), the 'n' of 'nATa' changes to 
'R', thereby resulting in the final form of the compound as 'rAmaRATa'.

@drdhaval2785 Do you agree with this application of the nR rule to the compound of rAma and nATa ?

**Comment by drdhaval2785** [comment]
On deeper analysis, I take back my earlier stand. Even in case of
compounds, the parts of compounds are considered separate padas. So my
earlier reasoning was faulty.

Therefore, it would be rAmanATa and not rAmaRATa.

As regards rozavAhaRa, there is a separate sUtra which justifies णत्व here
i.e. वाहनम् आहितात् ८।४।८
http://sanskritdocuments.org/learning_tools/sarvanisutrani/8.4.8.htm

**Comment by drdhaval2785** [comment]
See 8.4.1 to 8.4.38 for full णत्वप्रकरणम् । There are many rules,
exceptions, negations etc.

**Comment by funderburkjim** [comment]
Thanks for tracking this down, Dhaval.   

Those 8.4.1-38 sutras will probably help explain the spellings seen in several words;  for instance, 

For instance, 8.4.7 explains that  pUrva + ahna becomes pUrvAhRa.

Similarly to the way that people joke "there's an app for that",  I guess we who study Sanskrit can nearly always say "there's a sutra for that!".  It's good that there are people like you who know how to find the apt sutra.

**Comment by gasyoun** [comment]
> "there's an app for that", I guess we who study Sanskrit can nearly always say "there's a sutra for that!". It's good that there are people like you who know how to find the apt sutra.

We are blessed that Dhaval is around.

**Comment by funderburkjim** [comment]
The following is unusual, in that there are two spelling errors in the printing of one word; or so it seems
to me
```
mw:BerItAdaRa,152903:BerItAdaRa:p: tAdaRa -> tAqana.  Confirm work spelling in ACC
```
![image](https://cloud.githubusercontent.com/assets/6393033/17493882/2d8bec8a-5d80-11e6-90a1-40ad2736e589.png)

**Comment by funderburkjim** [comment]
Correction:
```
mw:BOmasAnti,153415:BOmaSAnti:t: sAnti -> SAnti
```

**Comment by funderburkjim** [comment]
Correction, confirmed by WIL, PWG, etc.
```
mw:marmaspriS,:marmaspfS:p: spriS -> spfS
```
![image](https://cloud.githubusercontent.com/assets/6393033/17496691/62911b6a-5d8c-11e6-8de4-99fa14c53f87.png)

**Comment by funderburkjim** [comment]
By usual interpretation of MW, this word `mahAtyaya-tyayika` is ok.  However, PW has
`mahAtyayika`, and I think that should be the way we interpret this word in MW.
In other words, I'm suggesting:
```
mw:mahAtyayatyayika,159686.3:mahAtyayika:p: markup error in MW
```
By markup error, I'm suggesting that `-tyayika` be changed to `°tyayika`, which we would code in 
key2 as `<sr/>tyayika`.

Here is MW scan:
![image](https://cloud.githubusercontent.com/assets/6393033/17497313/3d40260a-5d8f-11e6-8e94-8fee859566cb.png)

![image](https://cloud.githubusercontent.com/assets/6393033/17497364/8b869a24-5d8f-11e6-84b8-fcf19fd21485.png)

Here is PW entry:

 महात्ययिक [L=84365] [p= 5044-2]	 Adj.  mit grosser unmittelbarer Gefahr verbunden  Ḱaraka.6,11. 

@drdhaval2785  Do you agree?

**Comment by drdhaval2785** [comment]
BerItAqana.

Dot shifted from d to n by error.

**Comment by drdhaval2785** [comment]
I agree regarding mahAtyayika.

**Comment by funderburkjim** [comment]
correction:
```
mw:viSvacakradanaviDi,201057:viSvacakradAnaviDi:t: dana -> dAna
```

**Comment by gasyoun** [comment]
`{%pratipakshita:BEN` in `sanhw` file has crept in.

**Comment by funderburkjim** [comment]
> Re: %pratipakshita:BEN in sanhw

There was an error in the corrections under issue#287.  Error now corrected, and sanhw1 regenerated.

**Comment by funderburkjim** [comment]
These corrections now installed.
