### ISSUE TITLE
sattva misspelling in AE

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#304]
A user noticed several cases in AE where 'sattva' was misspelled as 'satva'.  

Further examination leads me to think that most of these are print error.

The user noticed this error under headwords `froth`, `linsey-woolsey` (a new word to me!),
`restore` and `rich`.

A search for `satva` in the ae.txt digitization resulted in several 10s of cases.

Here are the ones corrected so far:
```
; also under DIE
14967 old <>{#niScala, niScezwa, jaqa, nistejas, niHsatva,
14967 new <>{#niScala, niScezwa, jaqa, nistejas, niHsattva,
14985 old <>{#pretasavarRa#}. {@-ness,@} {%s.%} {#dOrbalyaM, niHsatvatA,
14985 new <>{#pretasavarRa#}. {@-ness,@} {%s.%} {#dOrbalyaM, niHsattvatA,
; under DRY
17327 old <>aklinna, vAna#}. {@2@} {#asAra, niHsAra, niHsatva,
17327 new <>aklinna, vAna#}. {@2@} {#asAra, niHsAra, niHsattva,
; under EMPTY
18516 old <>{#virasa, niHsAra, asAra, Palgu, niHsatva;#} ‘e.-
18516 new <>{#virasa, niHsAra, asAra, Palgu, niHsattva;#} ‘e.-
; under FAINT
20982 old <>-Tilabala, niHsatva, vihvala, mlAna, glAna, klAMta,
20982 new <>-Tilabala, niHsattva, vihvala, mlAna, glAna, klAMta,
; under FEEBLE
21595 old <>niHsatva#}. {@-ness,@} {%s.%} {#dOrbalyaM, kzIRatA, alpa-
21595 new <>niHsattva#}. {@-ness,@} {%s.%} {#dOrbalyaM, kzIRatA, alpa-
; under HOLLOW
27910 old <>{@2@} {#asAra, niHsatva, niHsAra, Palgu, SUnya#}. {@3@}
27910 new <>{@2@} {#asAra, niHsattva, niHsAra, Palgu, SUnya#}. {@3@}
; under IMPAIR
29231 old <>-niHsatva#}. -{@ing,@} {%s.%} {#kzayaH, PAsaH, apacayaH,
29231 new <>-niHsattva#}. -{@ing,@} {%s.%} {#kzayaH, PAsaH, apacayaH,
; under Impotent
29527 old <><P>{@Impotent,@} {%a.%} {#nirbala, durbala, aSakta, niHsatva;#}
29527 new <><P>{@Impotent,@} {%a.%} {#nirbala, durbala, aSakta, niHsattva;#}
29531 old <>niHsatvaM#}. {@Impotency,@} {%s.%} {#dOrval{?}, niHsatvaM,
29531 new <>niHsattvaM#}. {@Impotency,@} {%s.%} {#dOrval{?}, niHsattvaM,
; under Jejune
32859 old <>niHsatva#}.
32859 new <>niHsattva#}.
; under Froth (user supplied)
; 23915 <>{%f.%}), {#Penin#}. {@2@} {#asAra, laGu, niHsAra, niH-
23916 old <>-satva, aMtaHSUnya#}.
23916 new <>-sattva, aMtaHSUnya#}.
; under linsey-woolsey (user supplied)
35458 old <>niH-satva; kzudra#}.
35458 new <>niH-sattva; kzudra#}.
; under restore (user supplied)
52514 old <>{#agnivarDana#} ({#nI#} {%f.%}), {#satva-bala-varDana#}. {%-s.%}
52514 new <>{#agnivarDana#} ({#nI#} {%f.%}), {#sattva-bala-varDana#}. {%-s.%}
; under RICH (user supplied)
52961 old <>-ratna,#} &c. {@4@} {#satva-sAra guRa-vat, sPIta,
52961 new <>-ratna,#} &c. {@4@} {#sattva-sAra guRa-vat, sPIta,

```

The reason for introducing this issue is to deal with the rest of the cases.

I'd like to come up with a simple form-based application that would facilitate
crowd-sourcing (or at least providing a basis for sharing the work) of checking the other cases.

**Comment by funderburkjim** [comment]
Noticed 'niHsatvI-kf' under 'empty', a similar error, but not caught by 'satva' search.

**Comment by gasyoun** [comment]
Not a false orthographical convention? Anyway for us it's a typographic error, agree, @drdhaval2785 ?

**Comment by funderburkjim** [comment]
> orthographical convention?

Doubtful, as there are cases where 'sattva' is correctly shown in print, e.g., under 'exist':
![image](https://cloud.githubusercontent.com/assets/6393033/17950784/729e710a-6a2b-11e6-90fa-64a44e39b3d2.png)

**Comment by funderburkjim** [comment]
[Here](http://sanskrit-lexicon.uni-koeln.de/scans/AEScan/2014/pywork/correctionwork/issue-304/update.php) is a program aiming to be a relatively friendly way for others to contribute to
checking the cases.  

The ones in green are one's I've done.  Click one of the words (green or not), and if you know how
to correct, click the appropriate type (no change, print, typo), then 'submit'.

Hope some will give this a try.

Would welcome comments as to whether this is a step in the direction of making it easier for
more to contribute.

**Comment by gasyoun** [comment]
> Would welcome comments as to whether this is a step in the direction of making it easier for
more to contribute.

Let me show it to a person who said he wanted to help, has knowledge, but never helped because of our non-UI.

![knock](https://cloud.githubusercontent.com/assets/80761/17971910/6b730b42-6ae5-11e6-849b-b245aae07064.PNG)

**Comment by drdhaval2785** [comment]
Seems fine as UI.
A link to PDF page is missing.
Otherwise how will one know whether it is print error or typo?

**Comment by funderburkjim** [comment]
> A link to PDF page is missing.

Actually, there is a page link within the record display (e.g., p=148 in the image above); this link is active, so  following that link is the way to determine if a print error.

**Comment by drdhaval2785** [comment]
Yes.

I missed it. Can we make it more obvious ?

**Comment by gasyoun** [comment]
> Can we make it more obvious ?

Like RED in CSS.

**Comment by funderburkjim** [comment]
All the cases have been examined.
There were 9 corrections made.
Sampada helped me finish these.

Also a typo under 'rescue', changing `paritrayaDvaM` to `paritrAyaDvaM`  

(`pari` + root `trE`, 2d pl. imperative (`low`), atmanepada. Confirmed by MW and SanskritVerb generated forms).

**Comment by funderburkjim** [comment]
Thanks for formatting comments (re scan link).

I'll take account of this when adapting this form to another situation.

**Comment by gasyoun** [comment]
`Sampada helped` - thanks to @sanskritisampada
