### ISSUE TITLE
SKD, probable error in 4 m. nouns ending in A

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#305]
A user submitted a correction for SKD  where the headword `kleSA` ,m. should be changed to
`kleSaH`.  This case turns out to be a typo.

A search for similar headwords ending in 'A' and marked as masculine led to the following 4 items, 
which I think need correction as indicated. But I would like a second opinion before making the changes.
- [gaRqUzA](http://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/webtc/indexcaller.php?key=gaRqUzA)
  `<HI>gaRqUzA, puM, (gaRqUza + wAp .) gaRqUzaH . iti   ### <HI>gaRqUzaH ?`
- [BadravallikA](http://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/webtc/indexcaller.php?key=BadravallikA) 
  `<HI>BadravallikA, puM, (BadrA vallikA .) gopavallI .  ### strI ?`
- [SElavalkalA](http://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/webtc/indexcaller.php?key=SElavalkalA) 
  `<HI>SElavalkalA, puM, (SElaM SilA valkalaM yasyAH ..) ### strI ?`
- [hemnA](http://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/webtc/indexcaller.php?key=hemnA) `<HI>hemnA, puM, buDagrahaH . yaTA, --  ### strI ?`

These would all be print errors.

**Comment by drdhaval2785** [comment]
> gaRqUzA <HI>gaRqUzA, puM, (gaRqUza + wAp .) gaRqUzaH . iti ###
<HI>gaRqUzaH ?

No change. Doesn't seem plausible, because the bracket says that feminine
suffix 'wAp' i.e. 'A' is added. There is a separate entry of gaRqUzaH.
Bettervto change the oresent to 'strI'.

> BadravallikA <HI>BadravallikA, puM, (BadrA vallikA .) gopavallI . ###
strI ?

Change.

> SElavalkalA <HI>SElavalkalA, puM, (SElaM SilA valkalaM yasyAH ..) ###
strI ?

Change.

> hemnA <HI>hemnA, puM, buDagrahaH . yaTA, -- ### strI ?
>

No change. It is name of mercury. Musculine for sure. There is a verse in
jyotish which records this name. Musculine.

**Comment by funderburkjim** [comment]
Re hemnA:   Could it be that the spelling of headword should be 'hemnaH' ? 

MW has 
```
(H1) हेम्न [p= 1305] : m. (Gk. *῾ερμῆς) the planet Mercury VarBṛS.  [L=264351]
(H1B) हेम्ना : f. id. (?) L.  [L=264352]
```

If the spelling of headword were `hemnA` and masculine, I wouldn't know how to decline.

**Comment by gasyoun** [comment]
`hemnA and masculine` seems an impossible combination.

**Comment by gasyoun** [comment]
@rblinderman any idea?

**Comment by gasyoun** [comment]
> So the correct form should be masc. हेम्नः

Great catch.

**Comment by funderburkjim** [comment]
`hemnA`now changed to `hemno` in quote, and 'cendra' changed to 'cendu'.
Other corrections about previously made.
