### ISSUE TITLE
Apte English-Sanskrit Correction Form, sample batch

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#306]
This issue deals with corrections to Sanskrit words appearing within the entries of the Apte English-Sanskrit dictionary.

Please take a look at the [issue-306-demo](http://www.sanskrit-lexicon.uni-koeln.de/scans/AEScan/2014/pywork/correctionwork/issue-306-demo/update.php) program, which is a
form for such corrections.  Read the instructions and give it a try.  It's ok to play around with it, since it is a demo.

I am soliciting your comments on the user-interface.  As with other recent similar forms, I'm trying to get forms that make it easier for others to contribute.

Once such comments have run their course, I'll describe the techniques that I'm using to arrive at candidate lists of likely misspelled words.

**Comment by gasyoun** [comment]
![ui](https://cloud.githubusercontent.com/assets/80761/18928649/b03817d2-85c9-11e6-93ac-35cf12be471e.PNG)

So I found one mistake! The UI is kinda UNIX :) But it's sure enough for me. Why only 6 possible cases?

**Comment by funderburkjim** [comment]
@gasyoun  Thanks for taking a look.

>The UI is kinda UNIX

Not quite sure what this means; I can tell it is slightly negative, but in a friendly way.  I was aiming at
practicality and efficiency.   

> Why only 6 possible cases?

This is just a demo.  Sampada will be helping me with more cases.  I'll describe the case-selection
methods soon.

**Comment by funderburkjim** [comment]
The documention mentioned above has been written in the ApteES repository, in [this issue](https://github.com/sanskrit-lexicon/ApteES/issues/6)

**Comment by funderburkjim** [comment]
The corrections using 2-grams have now been finished.  In all, 150+ corrections made.
They are listed [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/AE/issue-306/corrections.txt).

**Comment by funderburkjim** [comment]
There was one case where Sampada and I could not decide for sure. 

Here are details, under AE headword `chink`.
```
chink [p= 056] : Chink, s. CidraM, raMDraM. 2 kvaRitaM, rAvaH. -v. i. 
sPud 6 P, vidF pass. 2 SiMj 1, 2 A; kvaR 
1 P, svan 1 P. 3 >>>>CidrapUr <<<<10. -y, a. aneka- 
-raMDra, bahuvivara. 
```
The original digitization of `CidrapUr` was `CIdraM pUi`.

 But the sense of this (i.e., translation) is unclear
in relation to headword 'chink';  based on the preceding 'kvaR' and 'svan', I would expect the
sense of `CidrapUr` (if that is what the spelling should be) to be something related to sound,  but
'pUr' means 'to fill'  (AP, AP90.).  

Here is the scan:

![image](https://cloud.githubusercontent.com/assets/6393033/19783068/73a95eec-9c5e-11e6-8022-8983058bb9d2.png)


What do others think?

**Comment by gasyoun** [comment]
> pUr

For sure.
