### ISSUE TITLE
Headword missing from descriptions

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#311]
While working on something else ('nR' issue in PW preverb), I stumbled upon this interesting piece of data.
This is not current VCP database, but some old version of VCP converted to mobile stardict file long time ago.
In that headword was missing from the description part. Some programmatic way is possible at least for Indian dictionaries where headword (any inflected form thereof) is missing from description. Not sure about the productivity of this method. Just thought to document.

प्रनण्ड (Current version has correct प्रगण्ड)

पु० गडि--वदनैकदेशे अच् प्रकृष्टो गण्डः अवयवः
प्रा० स० । १ कूर्परोपरिकक्षपर्य्यन्तभागे अमरः । दुर्गप्रा-
कारभित्तौ २ शूराणां निवेशनस्थाने च स्त्री गौरा०
ङीष् । “सञ्चारो यत्र लोकानां दूरादेववबुध्यते ।
प्रगण्डी सा च विज्ञेया बहिःप्राकारसंज्ञिता । प्रणिधि-
स्तत्र यत्नेन कर्त्तव्यो भूतिमिच्छता । स एवाकाशरक्षीति
ह्युच्यते शस्त्रकोविदैः” भा० टी० धृतवाक्यम् । “प्रगण्डीः
कारयेत् सम्यगाकाशजननीस्तथा” भा० शा० ६९ अ० ।
“प्रगण्डीर्दुर्गप्राकारभित्तौ शूराणासुपवेशनस्थानानि ।
आकाशजननीस्तत्रैवैककक्षायां भित्तौ तत्रत्यानां रक्षण-
भूतायां बाह्यार्थदर्शनार्थानि क्षुद्रछिद्राणि यद्द्वारा आ-
ग्नेयास्त्रगुलिकाः प्रक्षिप्यन्ते” नीलकण्ठः ।

**Comment by gasyoun** [comment]
> In that headword was missing from the description part.

Should we worry about was mispogrammed?

**Comment by drdhaval2785** [comment]
Leave it. Now we regenerate from cologne data. Non issue now
