### ISSUE TITLE
bur.txt v/w

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#312]
Both are seen in Burnouf.
Non consistent.

<P>{%agnivallabha%} n. {%(vallabha)%} re4sine.
.{#ajihva#}¦ {%ajihwa%} m. {%(jihwa1)%} grenouille, m a11 m. la
be10te sans langue.

**Comment by drdhaval2785** [comment]
Also uses x in AS for 'kz'.

**Comment by gasyoun** [comment]
> Non consistent.

Let's kill 'em, Jim.

**Comment by drdhaval2785** [comment]
After IAST conversions this issue is closable. If any new error is found, it can be tracked in separate issue.
