### ISSUE TITLE
hradroga

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#315]
A user submitted a correction under AP90 for 'hradroga'.

The correction was to change the spelling to 'hfdroga'.

This would be a print error if we change it since the word is clearly among 'hra' words in AP90:

![image](https://cloud.githubusercontent.com/assets/6393033/19424557/1072aca2-93f8-11e6-8866-bdc67bbda87e.png)

The only other dictionary to have this spelling is SHS, who also has `hfdroga` spelling
```
ह्रद्रोग [p= 838-b] : m. (-गः) The sign Aquarius of the zodiac: see हृद्रोग. The word is of Greek origin. [L=47250]
```

AP90 does not have 'hfdroga'

Many other dictionaries have 'hfdroga' : CAE,CCS,GRA,MD,MW,PW,PWG,SHS,VCP,WIL,YAT;hfdrogaH:SKD

So hfdroga is clearly preferred.

Should we change AP90 ?  My intuition is NOT to change.  

Also, I think we should NOT change SHS.

What do others think?

**Comment by drdhaval2785** [comment]
hfd is used for heart
hradaH is used for pond.

Aquarius is more related to water than heart. So no change

**Comment by gasyoun** [comment]
> Aquarius is more related to water than heart

You made my day :sagittarius:

**Comment by funderburkjim** [comment]
Thanks!  Will leave AP90 no change.
