### ISSUE TITLE
SOS message

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#316]
Someone in Indology mailing list sent this message.
This is rare time when I am seeing MW service down.
@funderburkjim may need to fix it fast.
```
Dear Colleagues,

Since yesterday the online version of Monier-Williams’ Sanskrit-English dictionary at http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/indexcaller.php does not work any more (at least for me). Whatever word I search, the result is “not found,” although the input is correct. Does anybody else experience the same problem?

Many thanks for your reply,

Philipp Maas
```

**Comment by fxru** [comment]
I can verify this for all interfaces of the current interface of mw (B, L, and A). The List interface gives an HTTP 500 error message.

<img width="1140" alt="mw_agni_500" src="https://cloud.githubusercontent.com/assets/1352294/19512435/33441e8c-95ec-11e6-981e-34c7f10334fe.png">

Other dictionaries I tested as well as legacy versions of mw are not affected.

**Comment by fxru** [comment]
p.s. the mobile interface of still works as well.

**Comment by gasyoun** [comment]
> I can verify this for three interfaces of the current mw (B, L, and A). The List interface gives an HTTP 500 error message.

Works for me. Testing 24 h/ day.

**Comment by fxru** [comment]
The interface itself works, but access to the database seems to be broken. Search in mw interface _A_ for ‘agni’:
<img width="1137" alt="mw_agni_a" src="https://cloud.githubusercontent.com/assets/1352294/19515934/e5a00084-95f9-11e6-8c4f-fda3d292fc7d.png">

The initial query works, but the content of the results are not displayed.

**Comment by Sonnetag** [comment]
Dear Jim and others,
I sent the same message to Jim last night. The M-W Old Display (2008) 
and the Inflected Form Lookup, which is linked to the 2008 Old Display 
still work. But 2014 New Display does not bring up any definitions when 
I type keywords. I heavily reply on the Inflected Form Lookup and M-W 
Sanskrit-English Dictionary for my project.

Would you please keep the 2008 Old Display and the Inflected Form Lookup 
on the Web as well as M-W New Display (2014).
Thank you,
Youngsinn Sohn

**Comment by funderburkjim** [comment]
Mea culpa.

I did an update to MW for some Correction Form submissions a couple of days ago.  There are lots
of steps, and one of them seemed to have failed.

I think I know which step failed.  When the sqlite file is updated, there can be a problem when there is someone using the file at the precise time the file is being updated.   Usually I do things in the middle of the night (for Cologne), and there is no such contention.   But apparently this time there was such a 
problem.

I've redone the step and things look back to normal now.

**Comment by gasyoun** [comment]
>When the sqlite file is updated, there can be a problem when there is someone using the file at the precise time the file is being updated. Usually I do things in the middle of the night (for Cologne), and there is no such contention. But apparently this time there was such a 
problem.

Yeah, you have written about it before. So for such case I would shut down the scripts before, so no one can use them at the same time.
