### ISSUE TITLE
Apte English-Sanskrit Corrections, based on odd 3-grams

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#318]
This continues the search for corrections of Sanskrit words within the text of Apte Englis-Sanskrit dictionary.  In #306 , correction candidates were drawn from a list of 150 words whose spelling contained odd 2-grams.

In this issue, the approach uses odd 3-grams.  There are 781 such cases identified, and listed in
[this file](https://github.com/sanskrit-lexicon/ApteES/blob/master/ae_saninvert/invert2_notfound3_ngram3prob.txt).

It is expected that there will be more false positives in this batch; in fact, some tests to remove
of false positives was added to the program logic (for instance, don't count and ending XEH as odd
provided that Xa is found  - the EH is instr. pl. ending of nouns ending in 'a').  These tests reduced the
original list from 959 to the present 781 case.

As with #306, Sampada will be doing most of the examination and corrections of these cases.

**Comment by gasyoun** [comment]
>  some tests to remove
of false positives was added to the program logic (for instance, don't count and ending XEH as odd
provided that Xa is found - the EH is instr. pl. ending of nouns ending in 'a')

Smart one.

> As with #306, Sampada will be doing most of the examination and corrections of these cases.

Let there be joy to Sampada!

**Comment by funderburkjim** [comment]
Currently, the highlighted word below is spelled `nizprAtebaDaM`,  but this spelling doesn't make any sense to me.  Does anyone know what the spelling should be, so that we get a meaning of 'despotic' ?
![image](https://cloud.githubusercontent.com/assets/6393033/20365183/f8bd187a-ac13-11e6-9541-098a939254aa.png)

**Comment by gasyoun** [comment]
You forgot to added the mantra @drdhaval2785 :jack_o_lantern:

**Comment by funderburkjim** [comment]
Never mind. 
I think it is 'nizpratibaMDa'  (meaning unopposed)

**Comment by drdhaval2785** [comment]
> Never mind.
> I think it is 'nizpratibaMDa' (meaning unopposed)

Bingo.

**Comment by funderburkjim** [comment]
There are several cases in AE like this:   नाहं यन्त्रितोस्मि    (I am not bound [by ...]).  

I understand the last word to be application of visarga sandhi to यन्त्रितः अस्मि.  

However, the application of visarga sandhi in such a case (e.g. by Antoine I, Section 15) would have an avagraha:  यन्त्रितोऽस्मि .

Is the absence of avagraha in Apte supported by some optional sandhi rule, or should it be thought of as an error?

**Comment by SergeA** [comment]
> Is the absence of avagraha in Apte supported by some optional sandhi rule, or should it be thought of as an error?

Avagraha is not a sandhi-element. It is written only for the comfortable reading.
यन्त्रितोस्मि = यन्त्रितोऽस्मि, it's just different style of writing words.
If in general it is written in this book in such cases, then better to correct this one. But there are books that do not use avagrahas at all.

**Comment by funderburkjim** [comment]
AE may be varying in use of avagraha.  

Here's a case where no avagraha was used, involving diphthong sandhi:

![image](https://cloud.githubusercontent.com/assets/6393033/21210948/3bddcea2-c24d-11e6-8d72-2315574e11f8.png)

I parse this as पृष्ठे अभिलिखेत् दत्वा   and expected (by Antoine again) पृष्ठेऽभिलिखेत्  .

However, there are at least a few cases of avagraha. e.g., under 'add',
![image](https://cloud.githubusercontent.com/assets/6393033/21211056/2b4bf892-c24e-11e6-8b33-d277fa24a49b.png)

By one filter of our digitization, there are 65 cases of avagraha.   

No filter comes to mind that would catch cases where an avagraha was omitted.

Knowing that the presence or absence of avagraha is a writing convention -- that's good to know.

**Comment by funderburkjim** [comment]
What class 2P root might mean 'die', and fit the unreadable Devanagari?

![image](https://cloud.githubusercontent.com/assets/6393033/21211511/27482726-c252-11e6-826d-f9b10adcf39f.png)

**Comment by SergeA** [comment]
> What class 2P root might mean 'die', and fit the unreadable Devanagari?

प्र-इ

**Comment by drdhaval2785** [comment]
>
> Knowing that the presence or absence of avagraha is a writing convention
> -- that's good to know.
>
>
You would be thrilled to know that spacing is also a writing convention.
The style of introducing spaces is mostly just as modern as printing
technology in Devanagari.
Old manuscripts have no spaces at all.

**Comment by funderburkjim** [comment]
> thrilled 

Definitely :)  The ancients  gave little attention to such notions  as 'user friendly' in their written UI.

**Comment by funderburkjim** [comment]
> प्र-इ   

Yep, that must be it.

**Comment by funderburkjim** [comment]
Can anyone fill in this garbled print?  

HW = set   ( [Link to the page](http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ae&page=419) )

Excerpt from page identifying the problem area:

![image](https://cloud.githubusercontent.com/assets/6393033/21367431/1852b3fc-c6cc-11e6-92ec-b38e9a10bac2.png)

**Comment by SergeA** [comment]
yadi maṇis trapuṇi pratibadhyate
(from Pañcatantra 1.1)

**Comment by funderburkjim** [comment]
Do you have a link to Pañcatantra ref?

**Comment by SergeA** [comment]
https://archive.org/stream/Panca_Tantra_M_R_Kale/panca-tantra.%20M.%20R.%20Kale%20%28MPd%20scan%29#page/n11/mode/2up
p.14, verse 75

**Comment by funderburkjim** [comment]
@SergeA   Thanks. Got it.

**Comment by funderburkjim** [comment]
What is this mystery word?   It looks like 'sIgan' सीगन्  but I can't find such a word.

This is under headword 'league' in AE. [Page 254](http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ae&page=254)

Could it be sargin  (with print missing the 'r') ?   (I can't find this either, but saMsargin is next).

**Comment by SergeA** [comment]
> What is this mystery word? It looks like 'sIgan' सीगन् but I can't find such a word.

I think it is संगिन् ' uniting ' with lost anusvara.

> Could it be sargin (with print missing the 'r') ?

It will not give the required meaning. The words संसर्गः ' mixture or union ' & सर्गः '  discharging ' are not synonymous, so सर्गिन् will not be equal to संसर्गिन्.

**Comment by funderburkjim** [comment]
संगिन्  makes sense. Will use that, as print error for missing anusvara.

**Comment by funderburkjim** [comment]
Another mystery word, under headword 'option' in AE:

![image](https://cloud.githubusercontent.com/assets/6393033/21584550/ff0f4a4c-d079-11e6-847a-43d55652382b.png)

The mystery part is हृक्रोर् .

**Comment by drdhaval2785** [comment]
A Paninian rule

http://avg-sanskrit.org/sutras/1-4-53.html

**Comment by drdhaval2785** [comment]
Genitive dual of compound 'hfkf' composed of two verbs hf and kf.

**Comment by funderburkjim** [comment]
> Genitive dual ...

Thanks, @drdhaval2785  - I guess Apte thought everyone would surely recognize this as a Paninian sutra!

**Comment by funderburkjim** [comment]
Sampada and I have now finished all the cases.   There ended up being about 800 cases.  Along with
some additional corrections I added along the way, roughly 1500 corrections have been made in AE spellings. The vast majority of these were classified as typos.

I'm sure that there are still many more errors in the digitization. And the question now is how to proceed. 
  
I'm thinking that we need to essentially proofread all the text (probably most of the headwords involved in those 800 cases don't need complete proofreading). There are 11,000 headwords, and 500 pages.

One way to approach this might be to make a wiki, which would have a page for each page of the text.
Then, one could have the scanned image and a page of the wiki as work ingredients for proofreading one page.  Programs should allow me to compare pages after editing to generate corrections.

There could be versions of the pages for Sanskrit representation (maybe just SLP1 and Devanagari would be enough versions - the printed text uses Devanagari for Sanskrit).

The wiki itself could provide revision information.

Does anyone have thoughts on whether this wiki idea seems worth pursuing?

Are there better approaches?

I think it is desirable to have a relatively clean version of AE.

I'll wait for some feedback before charging off.

**Comment by drdhaval2785** [comment]
My experience is that majority of typos in ngrams were of such nature that they will easily miss out in human inspection. Would it be of some help to read some textbooks on text cleaning? Like ngrams proved a major boon. There may be similar methods already existent and we didnt know them. Let us be sure we exhausted low hanging fruits first.

I remember you doing some work on headwords available in only one dict. My logic would be

1. Pass such singular entries from logic of hwnorm1 and whatever fails is our next suspect lot.
