### ISSUE TITLE
MW72 corrections to text Sanskrit Italics

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#320]
By a process similar to that of #318 for the AE dictionary,  potential errors in the spelling of Roman Italic Sanskrit in MW72 have been developed.

This issue is devoted to those.

The potential corrections are examined by an interactive program.  Here is the url for the
first sample batch of 5 cases [batch 00](http://www.sanskrit-lexicon.uni-koeln.de/scans/MW72Scan/2014/pywork/correctionwork/issue-320/00/update.php).

**Comment by funderburkjim** [comment]
Batch 00 has been completed.

[Batch 01](http://www.sanskrit-lexicon.uni-koeln.de/scans/MW72Scan/2014/pywork/correctionwork/issue-320/01/update.php) and
[Batch 02](http://www.sanskrit-lexicon.uni-koeln.de/scans/MW72Scan/2014/pywork/correctionwork/issue-320/02/update.php) have
been prepared are are ready to be analyzed.

I intend to work on these a bit at a time; maybe others can do some also 😃 .

These are all based on unusual 2-grams.

When these are finished, there will be a much larger (approx. 500) collection of 3-grams to examine.

**Comment by drdhaval2785** [comment]
Life seems so simpler now with a UI. Now non technical people can also
contribute better.

**Comment by gasyoun** [comment]
> Now non technical people can also
contribute better.

If only we could get the green blurb here. I spent most time searching the word on page.

**Comment by funderburkjim** [comment]
The green blurb is there!

![image](https://cloud.githubusercontent.com/assets/6393033/20507404/79f7f37a-b028-11e6-8e30-adab5ea9bf1b.png)

Click as shown, and you get  the same as with Greek in mw72 - a green blob near the line in question.

If you use Chrome, you will probably need one refresh. for the green highlighted section to show.
The magnification is already large enough, in my experience.

**Comment by gasyoun** [comment]
> The green blurb is there!

Ah, so I had to click on the line link, not the page link, got it! Now what is great!

![van](https://cloud.githubusercontent.com/assets/80761/20510142/3f3abc98-b07f-11e6-9983-b8f340a448a5.PNG)

> If you use Chrome, you will probably need one refresh. for the green highlighted section to show.

None needed, it works like a charm, thanks!

> The magnification is already large enough, in my experience.

Yes!

**Comment by funderburkjim** [comment]
@gasyoun Thanks for the feedback!

**Comment by funderburkjim** [comment]
One detail regarding a few cases of non-sanskrit words.  In mw72.txt there is a new markup tag
'<nsi>` (Non-Sanskrit Italic) which is used to distinguish italicized words which are not Sanskrit words.
Here's How I marked one such case in batch 02 
![image](https://cloud.githubusercontent.com/assets/6393033/20547758/5ec544ee-b0ec-11e6-9539-e7788290b2f5.png)

Thanks to the user who already went through batch 02!

**Comment by funderburkjim** [comment]
> Yudhisṭhira-  

This is misspelled (a typo), as the retroflex `sh` goes with the retroflex `ṭh`.   I've adjusted such cases in batch 02 to make the correction 's' -> 'sh'.

**Comment by funderburkjim** [comment]
All the 2-gram cases (batch 00, 01, 02) are not completed. Ready to install.

**Comment by drdhaval2785** [comment]
By not you mean now ?

**Comment by funderburkjim** [comment]
'now' - right.

Corrections for batches 00,01,02 now installed.  2-gram analysis finished.

**Comment by gasyoun** [comment]
> 2-gram analysis finished.

Give us more!
