### ISSUE TITLE
AP90, preparing for identifying text spelling errors

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#327]
There are several infrastructure improvement steps which seem warranted for AP90 dictionary, before beginning analysis of the spelling of the words within the text of entries (as opposed to headwords).

* In the extant digitization of this text, the lines of the digitization correspond to lines of the printed text - a good thing when comparing digitization to printed text.
* Sanskrit words appear both in Devanagari and also in **two** IAST variants.

Some of the changes proposed are non-controversial, and some are controversial to some degree.

**Comment by funderburkjim** [comment]
## Non-controversial changes to Devanagari

It is convenient for analysis to be able to identify *within a line* the text that is marked as Devanagari.

However, the text as currently digitized is not closed within lines for the Devanagari markup.

Here's an example from the digitization (Devanagari text is coded in SLP1 transliteration).

The markup in the digitization uses `{#` to open a Devanagari segment, and `#}` to close a segment.

```
<>gonal. ({@{#--jaH#}@}) a pentagon; cf. {#paMcako-     Devanagari snippet is opened
<>Ra#}. {@{#--BUtaM#}@} the five elements; {#pfTvI, a-   but closed in next line.  
                                                                       Another snippet also opened in one line
<>p, tejas, vAyu#} and {#AkASa#}. {@{#--makAraM#}@}    and closed in another
```

So this would be easier to work with coded as follows, where all snippets are closed within lines of the digitization: 
```
<>gonal. ({@{#--jaH#}@}) a pentagon; cf. {#paMcako-#}
<>{#Ra#}. {@{#--BUtaM#}@} the five elements; {#pfTvI, a-#}
<>{#p, tejas, vAyu#} and {#AkASa#}. {@{#--makAraM#}@}
```

This seems uncontroversial.

A similar phenomenon exists for italic text snippets, whose markup should be similarly closed.

A slight variant of the Devanagari closure issue is exemplified here:
```
<>letter is {@{#ma;#}@} see {@{#paMcatattva#}@} (2). {@{#--mahApA-
<>takaM#}@} the five great sins; see {@{#mahApAtaka#}. {#[Page0657-c+ 57]
<>--mahAyajYAH#}@} ({%m.%} pl.) the five daily
```
In this example, the `{@...@}` markup is used to indicate **BOLD** text in the print.  This markup 
occurs for non-Sanskrit as well as Sanskrit.  

The non-controversial recoding would look like:
```
<>letter is {@{#ma;#}@} see {@{#paMcatattva#}@} (2). {@{#--mahApA-#}@}
<>{@{#takaM#}@} the five great sins; see {@{#mahApAtaka#}@}. [Page0657-c+ 57]
`<>{@{#--mahAyajYAH#}@} ({%m.%} pl.) the five daily
``

**Comment by funderburkjim** [comment]
## Slightly controversial recoding of bold-Devanagari

As far as I can tell, there is no significance to the fact that the text shows some Devanagari as bold and some as perhaps not bold.

Thus, I think the Bold-Devanagari markup in the digitization should be dropped, as it adds confusion without significance. With this, the last example above would be recoded as:
```
<>letter is {#ma;#} see {#paMcatattva#} (2). {#--mahApA-#}
<>{#takaM#} the five great sins; see {#mahApAtaka#}. [Page0657-c+ 57]
<>{#--mahAyajYAH#} ({%m.%} pl.) the five daily
````

The seems only slightly controversial to me.

**Comment by funderburkjim** [comment]
## The two types if IAST in AP90:

![image](https://cloud.githubusercontent.com/assets/6393033/21447017/031d56e6-c89c-11e6-9e36-eb20e5ef69e4.png)

The first type of 'IAST' appearing in AP90 uses diacritics  (the circumflex, dot under, etc) on Latin alphabet to indicate certain details of the Sanskrit alphabet. 

The second type of IAST uses italicization of letters instead of diacritics.

**Comment by funderburkjim** [comment]
## Uncontroversial recoding of type-1 IAST

In the digitization ap90.txt,  the type-1 IAST instances of the printed text are currently coded using what Thomas calls the 'Anglicized Sanskrit' (AS) coding.  Instead of decorating a letter with a diacritic,  the letter is decorated with a number. This shown in the example above 'Ya10dava' and 'Kr2ishn2a'.  The 'a10' means
'a with circumflex', and the 'r2' means 'r with underdot', and 'n2' means 'n with underdot'.

The uncontroversial recoding of this AS coding would use Unicode diacritics in place of letter-number:
```
<>N. of a Yâdava, a friend and uncle
<>of Kṛishṇa. [It was he who induced
```

**Comment by funderburkjim** [comment]
# Slightly controversial recoding of type-1 IAST

For some reason, the ap90 text uses the circumflex over vowels to indicate a long vowel.  

In current IAST convention, a macron would be used instead.

The controversional recoding would use the current IAST conventions.  So our example would look like:
```
<>N. of a Yādava, a friend and uncle
<>of Kṛishṇa. [It was he who induced
```

There is another detail.  In numerous cases,  the text presents a grave accent over a vowel. For instance, the digitization shows 896 cases of a grave accent over the vowel 'a'.  And the print definitely does look this like a-grave:
![image](https://cloud.githubusercontent.com/assets/6393033/21447181/fac74288-c89e-11e6-8955-ea119a1ac559.png)

In this case (and probably in all cases), the 'a-grave' represents a long vowel 'a', in this case the title mālatīmādhava .

The controversial proposal would also change this to a-macron.  So, both a-circumflex and a-grave would be changed to the same a-macron.

Carrying out this process is controversial because the digitization would then not distinguish the two kinds of a-diacritics that the text shows.

**Comment by funderburkjim** [comment]
## Controversial recoding of type-2 IAST.

There appears to be no method to the madness of the text's use of  italicization instead of diacritics.  As we see in the example, dear कृष्ण appears in both disguises.

However, I do think that the italicization is internally consistent - e.g. an italic-n always represents the retroflex nasal Sanskrit letter.  I do not yet have a complete cross-reference of these italicized diacritics.

 The proposal is that the italicized diacritics be discarded in the digitization in favor of the current IAST standard diacritics.

This is controversial, because, if both type-1 and type-2 IAST are converted, then the digitization would lose the distinction between the two forms appearing in the print edition.

**Comment by gasyoun** [comment]
> Thus, I think the Bold-Devanagari markup in the digitization should be dropped, as it adds confusion without significance. 

Makes sense.

> The second type of IAST uses italicization of letters instead of diacritics.

Macdonnel and Mueller Oxford style. That's something we should get rid off in the digitization as least as an option, because it's undreadable.

> Thomas calls the 'Anglicized Sanskrit' (AS) coding. Instead of decorating a letter with a diacritic, the letter is decorated with a number. This shown in the example above 'Ya10dava' and 'Kr2ishn2a'. The 'a10' means
'a with circumflex', and the 'r2' means 'r with underdot', and 'n2' means 'n with underdot'.

The problem is not all can be unicoded, something will still remain semi-unicode as far as I remember similar experiments with PW, PWK.

> The controversional recoding would use the current IAST conventions.

Fully agree. When documented we should not be afraid of the move.

> So, both a-circumflex and a-grave would be changed to the same a-macron.

Makes sense. There is no metadata that is lost, I guess. It's just that the book was printed with legs, not arms.

>  I do not yet have a complete cross-reference of these italicized diacritics.

I can make one.

> The proposal is that the italicized diacritics be discarded in the digitization in favor of the current IAST standard diacritics.

Yes!

> This is controversial, because, if both type-1 and type-2 IAST are converted to current standard IAST, then the digitization would lose the distinction between the two forms appearing in the print edition.

Let's add a meta tag to the type-2. So nothing is lost forever.

**Comment by funderburkjim** [comment]
Further study on the two types of IAST.   [This gist](https://gist.github.com/funderburkjim/71a79de7e14d87eecb7d7e4bdf281505) has two files that
tell much of the story.

## asitalic_roman1.xml  
 This is a transcoding file that shows one way of unambiguously converting *most* of the cases to
  a partially non-standard IAST.  By accepting some non-standard aspects of the IAST, we can get
  all but about 200 of the cases converted fully to IAST, and in such a way that the conversion is
  'invertible'.  Invertible means that we can convert back to the original coding and get what we 
   started with.

   The main non-standard aspects involve the vowels:
   Those that are coded as a10, etc are converted to circumflex diacritics; similarly for a11, etc. to grave accents, and a4, etc. to acute accents.
   Now, the Italic vowels can be converted to macron diacritics without being confused with the
   circumflex vowels, grave and acute accents.

   The AS cerebral constants  (d2, n2, r2, t2) are converted to 'dot-under' diacritics;  the only non-standard detail here is that that the vocalic 'r' is now coded as `ṛi` - the current standard IAST doesn't
have that 'i'.

  The very frequent italic palatal sibilant only appears in the italic coding, so we can convert
  `{%S%}` unambiguously to `Ś`.

The remaining bunch of italic consonants cannot be coded unambiguously.  The italic `d,t`  are
definitely coding the retroflex consonants;  Similarly, the italic `r` is coding the vocalic `r`.

The italic `n`  is a special case.  At first I thought it was only used to represent the cerebral nasal,
`ṇ`, but no, it is also used to represent palatal nasal at least (see 'a{%n%}jn{%a%} 1 Sa{%n%}jnā saRjnA`).
Also, the non-italic 'n' is not only used for the dental nasal, but also for the guttural nasal. Ugh!

The italic `c` and `m` are actually appearing in English words.

## gistfile1.txt

This gives ALL the distinct examples, of words with either (or both!) kinds IAST coding.  
The 2nd field is a number, indicating frequency of occurrence. 
The 3rd field indicates the transcoding of the instance, using the asitalic_roman1 transcoding.

The 4th field is conversion of the 3rd field to slp1.  This could provide a basis for further study, with
an eye to looking for spelling problems.

Some of the 'word' instances are abbreviations of works (like {%S%}).  Some are incomplete parts
of words that span lines.

Incidentally, there is a small number of non-Sanskrit words in the file. Some are 
```
burni{%n%}g    {%S%}ee  {%s%}ee
```

## proposal
I propose that we go with this intermediate transcoding of ap90.txt -- in other words, replace all
instances of word1 in the gistfile with word3.

This will improve the vast majority of the 15000 or so cases.   The result will have some warts, as
mentioned above.  We can decide later what to do with the remaining italic-cases.  

## multi-character italic
There are still some intraword multicharacter italic sequences in Sanskrit words.

Using one regex, 169 cases were found. These are in file 'multicharitalic.txt' in the gist above.

These have not been examined, and would remain unhandled by the proposal mentioned above.

**Comment by drdhaval2785** [comment]
Glad to see we are diving into text corrections. Time to move on from
Headwords to texts has come up. I didn't feel it will come so fast.

**Comment by funderburkjim** [comment]
## Revised proposal: Go all the way to modern IAST in AP90

After sleeping on it, I changed my mind on the half-way proposal above.  From the point of view of 
dictionary utility, it will be better to replace the archaic IAST of AP90 with current IAST.

But what about lack of invertibility?  This can be handled by generating a list of of the old/new lines
for each line changed on the basis of the conversion to new IAST.  There are 18056 such lines that
are changed (out of about 200,000 total lines in ap90.txt).   If some future worker decided that this
change to modern IAST was unwarranted, then the change file for these 18056 changes could be
not applied (or the changes could be reapplied, but in reverse order). This hypothetical worker might have to deal with the SUBSEQUENT changes dependent on the new version. This would be tedious, but doable.

Another way to handle this situation would be, as @gasyoun suggested in a comment above, to 
maintain BOTH versions (old and new IAST) in the digitization.  This could be done, but it would
make it harder to use the digitization.  

I'll wait until tomorrow to actually effect this new proposal.  

** If anyone has objections, now is the time to air them.**

When these changes have been made, we can get  to the task of doing n-gram studies of
the Devanagari Sanskrit spelling in ap90.

**Comment by drdhaval2785** [comment]
I disagree with proposal to remove distinction between bold and not bold
Devanagari.

Bold is alternate headwords.
Non bold is explanation or other Devanagari stuff.

This is what I gather from cursory view. If we remove distinction, we loose
the opportunity to extract alternate headwords from AP90.

**Comment by funderburkjim** [comment]
@drdhaval2785 What is an example in support of your observation about alternate headwords?

**Comment by drdhaval2785** [comment]
http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/web/webtc/indexcaller.php?key=paMcan

अंशः, अग्निः etc are bold.

अन्वाहार्यपचन etc are not bold.

My computer is undergoing updates. So I will not able to see the ap90.txt
file for two hours. But I guess that there will be some difference based on
which the visual display is showing bold and non-bold.

On 28 Dec 2016 8:43 a.m., "funderburkjim" <notifications@github.com> wrote:

@drdhaval2785 <https://github.com/drdhaval2785> What is an example in
support of your observation about alternate headwords?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sanskrit-lexicon/CORRECTIONS/issues/327#issuecomment-269418824>,
or mute the thread

**Comment by funderburkjim** [comment]
Here is the ap90 coding for the beginning of पंचन् 
```
<P>.{#paMcan#}¦ {%num. a.%} (Always pl.; nom.
<>and acc. {#paMca#}) Five. (As the first
<>member of comp. {#paMcan#} drops its final
<>{#n#}). [cf. Gr. {%pente%}] {@--Comp.@} {@{#--aMSaH#}@}
<>the fifth part, a fifth. {@{#--agniH#}@} 1. an
<>a ggregate of five sacred fires; {%i. e.%} [Page0656-b+ 57]
<>({#anvAhAryapacana#} or {#dakziRa, gArhapatya, Ahava-
<>nIya, saBya,#} and {#AvasaTya#}) --2. a house-
<>holder who maintains the five sacred
<>fires; {@{#paMcAgnayo DftavratAH#}@} Ma10l. 1; Ms.  
<>3. 185. --3. five mystic fires suppos-
```

Note that it is not the Bold that specifies the 'subheadword', but the presence of a '--':  `{#--X#}` is the
way to identify sub-compounds.
We would not lose the ability to locate subheadwords if the bold `{@..@}` markup is removed.

Also note the bold in the next to last line --  this is not a subheadword, but a quotation.

I think this is generally the case -- the BOLD markup in our digitization has no definite meaning.

So, there is no loss in meaning by removing the bold.

**Comment by funderburkjim** [comment]
@drdhaval2785  If, after you review cases tomorrow you still feel that we would be losing some meaning
by dropping the bold markup,  it would be possible to do the IAST conversion, but leave the bold markup
present.

I'll wait for your further comment before proceeding.

**Comment by funderburkjim** [comment]
The changes mentioned above have been installed. To review, these changes are:
* Close Devanagari and italic markup on each line of the digitization ap90.txt.
   - Given Dhaval's concerns about possible semantic content in the Bold Sanskrit markup,
      this markup has been retained.
* Change the two types of IAST coding to modern IAST.

The steps of this work are described in this [readme.txt](http://sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/20161228/readme.txt) .

**Comment by drdhaval2785** [comment]
As mentioned by Jim, there is no method to madness that I could find.
Sometimes quotations have {@{# too. It seems that some work on {#-- will be
able to yield alternate headwords. Please go ahead.

**Comment by drdhaval2785** [comment]
Just for record, there are 432 occurrence in my local copy (quite old one) which match `[^@]{#--`
regex. Out of 35000 odd matching `{#--` regex. These are the places where potential headwords may not be marked by bold. This may need further investigation. @funderburkjim may run this on fresh copy and open a new issue for investigation.

**Comment by gasyoun** [comment]
> Invertible means that we can convert back to the original coding and get what we
started with.

That's great.

> Now, the Italic vowels can be converted to macron diacritics without being confused with the
circumflex vowels, grave and acute accents.

We can go for it now?

> vocalic 'r' is now coded as ṛi

For these words to be found I would propose you add to the search engine. That ṛi = ṛ. So no need to touch the text, let it be as close to the original as possible. All I care is about search, so it can be found.

> The very frequent italic palatal sibilant only appears in the italic coding, so we can convert
{%S%} unambiguously to Ś.

No choice left.

> Also, the non-italic 'n' is not only used for the dental nasal, but also for the guttural nasal. Ugh!

This is an issue, invented by MW and followed by many, as I'm aware of. The idea as far as I know is marking etymologically correct sounds, like marking what was there before (on border of upasarga and dhatu, for example).

> We can decide later what to do with the remaining italic-cases, and whether and how to go fully to modern IAST.

Agree. As it is it's dead. 

> Headwords to texts has come up. I didn't feel it will come so fast.

Neither did I - to finish it in 2 years seemed impossible. I think that we have just dropped it on middle road, because the low hanging fruit has been gathered, am I right, Jim? Why I worry is because I guess the number of corrections inside the dictionary is 7-10 bigger than what we had in headwords. Even the single task of German in old orthography in PWG, PWK is a task for months. Why have we started with MW72, Jim? It's rarely used and seldom quoted. MW, AP, PW, PWK - these are the popular ones and I would always stick to them first, what do others think?

> This hypothetical worker might have to deal with the SUBSEQUENT changes dependent on the new version. This would be tedious, but doable.

A hell I would say, but we sure want to mark or extract those lines affected.

> This could be done, but it would
make the digitization uglier and harder to analyze.

No need. All I wanted to say is one more tag, nothing else. No full form words, just additional markup.

> These are the places where potential headwords may not be marked by bold. 

Interesting and promising proposal.

**Comment by funderburkjim** [comment]
> Please go ahead.  (with removing bold-sanskrit)

Because Dhaval's comments were slightly out of sync with my actions,  I had made corrections KEEPING
bold Sanskrit.   However, now that I see that Dhaval also has no particular reservations about removing
the bold-Sanskrit,  I am going to redo things so that bold-sanskrit is removed.   After doing some snow-cleaning today, I'll do that.

**Comment by funderburkjim** [comment]
Here is a small [study](https://gist.github.com/funderburkjim/8a832b09b347b157d0f866521bb9e736) of bold and non-bold Sanskrit in ap90 digitization.  

The version used was ap902.txt; this is the version before the changes described above.

In broad summary, the text marked as Sanskrit Devanagari in ap90 can be decomposed into several
categories:
* non-bold
  * headwords   32000
  * preceded by a blank: 8000
  * preceded by some non-blank  13000
  *  subheadwords 400+  (boldsanstudy.txt provides instances)  This is the group mentioned in a comment [above](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/327#issuecomment-269572439)
* bold
  * subheadwords 35000
  * other  30000

**Comment by funderburkjim** [comment]
ap90.txt has been regenerated again.  

This time,  the bold-sanskrit markup is removed.  Hurray!  

Everything else as before.  In particular, standard IAST replaces both AS-IAST and italic-IAST.

**Comment by gasyoun** [comment]
> We really need someone proficient in German to focus on these.

For the German words, but there is plenty of Sanskrit and (hint!) hyperlink issues, like the linking to Rigveda that would seem to be an easy task (compared to linking to other texts and outdated editions).

> standard IAST replaces both AS-IAST and italic-IAST

Hurray! Long live Jim!
