### ISSUE TITLE
AP90 Sanskrit text corrections based on 2-gram, 3-gram

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#329]
This is the work space for developing corrections to the Devanagari Sanskrit text appearing in the digitization of  the ap90 dictionary.

The correction candidates are derived from odd 2-character or 3-character sequences in the spelling of the text.

**Comment by funderburkjim** [comment]
## urls for the UI for 2-grams

There are about 75 cases developed by the 2-gram approach.

The UI may be used in either SLP1 mode or Devanagari mode.

### URLS for SLP1 mode:

[batch 200](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-329/200/update.php)  [batch 201](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-329/201/update.php)  [batch 202](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-329/202/update.php)  [batch 203](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-329/203/update.php)  


### URLS for Devanagari mode

[batch 200](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-329/200/update.php?input=deva)  [batch 201](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-329/201/update.php?input=deva)  [batch 202](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-329/202/update.php?input=deva)  [batch 203](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-329/203/update.php?input=deva)

**Comment by funderburkjim** [comment]
## Progress Table for 2-gram Batches

Batch | case1-case2 | User | Date Begin | Date End | Installed
----- | ----------- | ---- | ---------- | -------- | ---------
200 | 1-5 | @funderburkjim|  12/30/2016| 12/30/2016 |
201 | 6-25 | | | |
202 | 26-50 | | | |
203 | 51-76 | | | |

**Comment by drdhaval2785** [comment]
Batch 201 done except SvaSura one.

**Comment by funderburkjim** [comment]
## Extra preliminary step for 3-grams

The number of initial cases for 3-grams is 1250.  While we could do all these via the UI,  it seems best
to do some weeding out of cases first.   The reason is that there are many of the instances involve Sanskrit phrases with inflected forms, and with external sandhi.  While we do not have software to parse such text into component word stems,  we can often parse these and determine on that basis whether the parsed result is probably Sanskrit.  

As a first step, I've done this on the initial list and come up with 366 of the 1250 cases as probably acceptable; the likely False Positive 3-gram errors are in file [ngram3-exclude-list.txt](https://gist.github.com/funderburkjim/e1e140e60c3d3edd4cca752ef9c7d399).  The file shows on each line the Sanskrit word/phrase , in SLP1 and Devanagari.

It is likely that there are some non-false-positives in this list. It would be good if someone would go through this list and copy/paste into a comment of this issue the ones that look wrong - i.e., ones that we  should check further in the UI.

As a second step, there is a list of other 884 (= 1250 - 366) 3-grams that are not in the exclude list;
this is file ngram3-remain-list.txt in the Gist above.

Someone should look at this list to see if any of these should be added to the exclude list (i.e., cases where the word or phrase looks like correctly spelled Sanskrit).    Any such cases can be copy/pasted to another comment.

In a day or two, when any adjustments to the lists of excluded and remaining 3-grams are finished,  I'll create UI batches for the remaining 3-grams that need attention.

**Comment by funderburkjim** [comment]
@drdhaval2785   Unfortunately, your results for batch 201 got clobbered.

I had this same problem with Sampada working from India.

It seems that sometimes the transmission from your computer back to the Cologne server gets corrupted.  I've never had this happen, nor has @SergeA , but Sampada (who is currently working from India) did have this problem.

I'll introduce the corruption protection measures into the code here.   When this is done, maybe you can resubmit the corrections for batch 201.  

😢

**Comment by funderburkjim** [comment]
The protection measures are now in place,  for batches 201,202,and 203;  and will be included in future UI batches.

The 201 batch cases have been regenerated and are ready to be redone. 😃 

The partial work on batch 202 was not lost by this revision.

Here's how the protection measure works:
* When  you 'Submit' a case, all the data is tranferred back to Cologne server, as a JSON array.
* The length of this new transmitted JSON array is computed
* Also, the previous version of the data is read from Cologne disk as an old JSON array
* The length of this old JSON array is computed.
* If the length of the old JSON array and the new JSON array are the same,  then the
   new JSON array is written to disk at Cologne, and a 'success' response is returned to your
   browser.  Upon receipt of this success response, a 'Case Submitted' message appears in red
   for a few seconds at the bottom of the display.  This means all is ok.  You should wait to see this
   message before proceeding with the next case.
* If the length of the old and new JSON arrays differ, then old data remains on the Cologne server,
   and an 'error' response is returned to your browser.  The browser then presents an alert , indicating
    there was an error.   If this should happen, you should  press 'Submit' again for the case.  Since the
    problem is intermittent, believed to be due to some transient internet transmission error, the second
    Submit should probably work.

* More complex checking could be done, of course, but this level of checking is probably adequate; at
  least that's the experience with Sampada.

**Comment by drdhaval2785** [comment]
Batch 202 done except two. Not legible.

**Comment by drdhaval2785** [comment]
Batch 201 done.

**Comment by drdhaval2785** [comment]
Batch 203 done.

**Comment by SergeA** [comment]
> Batch 202 done except two. Not legible.

I corrected them by my book. The scan is not good. :(

**Comment by SergeA** [comment]
batch 202

> Case 2: hw=अंबष्ठः DONE (जुई is spelled correctly)

non-Sanskrit

> Case 7: hw=अत्र DONE (दव्न → दध्न)

→ दघ्न ; from the root दघ्

> Case 17: hw=शृंखलः DONE (पृषो० is spelled correctly)

in this line अमेन → अनेन

> Case 24: hw=वल्लिः DONE (भुजंगवल्लिवलयस्रङ्तद्धजूटा is spelled correctly)

→ भुजंगवल्लिवलयस्र**ङ्न**द्धजूटा

**Comment by SergeA** [comment]
batch 203

> Case 4: hw=मुहर DONE (मुह्-कित्च → मुह्-किरच्)

wrong headword: मुहर → मुहिर

> Case 9: hw=अर्क DONE (रुई is spelled correctly)

non-Sanskrit

> Case 10: hw=याथार्थ्यं DONE (र्ध्थं → र्थ्यं)

in previous line र्थ्थविदः → र्थ्यविदः

**Comment by funderburkjim** [comment]
@SergeA  Re 202, case 7. 

Although your comment above says 'ghna',  the correction shown in the UI is 'dhna'.   I'm changing UI correction to 'ghna'.

**Comment by funderburkjim** [comment]
Re Scan not good.

Due to the close relationship between ap90 and ap (1957),  we may be able to find ways to compare the two editions as a way to generate corrections.

One small way to make use of this is with the scans.   
For instance, under headword शृङ्खलः (AP) = शृंखलः (AP90), अनेन is clear in the scan for AP, while not clear in scan for AP90:

AP90:
![image](https://cloud.githubusercontent.com/assets/6393033/21579267/3deb6a0e-cf74-11e6-9e39-e07d12b29ccf.png)

AP:
![image](https://cloud.githubusercontent.com/assets/6393033/21579270/62770b44-cf74-11e6-8bff-7c77a790c8de.png)

**Comment by funderburkjim** [comment]
Batch 200, case 4.  ALso, headword saMhatanaM -> saMhananaM. typo.

**Comment by funderburkjim** [comment]
Pulling this comment from Batch 201, case 4 so it won't be lost:

>Spacing issue. It is recurrent issue in AP90. Systematic analysis of words greater than 10 SLP1 letters should be done.

Here was the correction : 
```
22231 old <P>.{#abDiH#}¦ [{#ApaHDIyaMte atra, DA-ki#}] {@1@} The
22231 new <P>.{#abDiH#}¦ [{#ApaH DIyaMte atra, DA-ki#}] {@1@} The
```

Note comparison to AP:
```
.{#abDiH#}¦ [{#ApaH DIyante atra, DA-ki#}]
```

The spacing in AP agrees with the corrected AP90.

**Comment by funderburkjim** [comment]
Here is another comment from Batch 201, case 10:

>known hiatus issues like this need to be systematically handled.

The correction in question:
```
; EuR -> aiuR
125901 old <>{#pratyAhAra#} of the Sūtra {#EuR; ac#}
125901 new <>{#pratyAhAra#} of the Sūtra {#aiuR; ac#}
```

Note:  This was occasioned by the limitation of the original Harvard-Kyoto transliteration.  That transliteration does not distinguish between vowel hiatus and diphthongs.  Thus in conversion to SLP1, which does make this distinction (by using 'E' instead of 'ai' for the diphthong),  this wrong conversion was unavoidable.

I think there are only two cases, the other one being 'au' in HK could be hiatus (= SLP1 'au') or it could be diphthong ( = SLP1 'O').

I'm not clear how to track down other such cases (where 'O' in current SLP1 should be hiatus 'au', or 'E' in current SLP1 should be hiatus 'ai').  For if we search for all instances of 'O' or 'E' in Sanskrit text, there will be mostly False Positives  (nom. dual ending 'O', instr. pl. ending EH - or Es, Er, etc. from sandhi).

**Comment by funderburkjim** [comment]
comment batch 201, case 15 : Written in HK accidentally??

```
95645 new <>points; (see {#azwadiggaja#}); {#digdaMtiSe-#}
95646 old <>{#SAH kakubhazcakAra#} Vikr. 7. 1. {#--grahaRaM#}
```
The question is what are are 'bh' and 'z' and for that matter, the inital 'S' in 'SAH' doing there.  Why weren't they converted to 'B', 'S', and 'z' when HK was converted to SLP1?

To answer this question, we need to look at the original HK form of these two lines (drawn from file ap90_orig_utf8.txt): 
```
<>points; (see {#aSTadiggaja#}); digdaMtize-
<>SAH kakubhazcakAra@}#} Vikr. 7. 1. {#{@--grahaNaM@}#}
```
Here are those two lines after the conversion to SLP1:
```
<>points; (see {#azwadiggaja#}); digdaMtize-
<>SAH kakubhazcakAra#}@} Vikr. 7. 1. {@{#--grahaRaM#}@}
```


Note that there is an error in markup in the HK version:  There is no opening `{#` before `digdaMtize`.
 Back in 2014,  this omission was corrected (refer file manualByLine_slp1.txt):
```
95645 old <>points; (see {#azwadiggaja#}); digdaMtize-
95645 new <>points; (see {#azwadiggaja#}); {@{#digdaMtiSe-
```

This change was likely noticed when making an xml version, since there would have been  non-valid xml before this change.

Note that the correction rightly changed the coding of digdaMtize to SLP1.

**HOWEVER**,  it was NOT noticed that the next line (95646) needed to have it's Sanskrit coding changed from HK to SLP1.

So, That explains the error.  Isn't it nice to be able to track down such things?

**Comment by funderburkjim** [comment]
Batch 201, case 17 comment:

> gt / mt are common misspelling for st, dye to poor print. Systemstically may be examined.

Line in question:
```
50855 old <>{#pAdo dvitIyaScottaraH smftaH . kriyApAdagtftIyaH#}
50855 new <>{#pAdo dvitIyaScottaraH smftaH . kriyApAdastftIyaH#}
```

also gt/st  (since often devanagari 's' and 'm' are mistaken.

Also 'gr','gt','gn' are variously confused:  Example from batch 200, case 1:
```
; agtyAhita -> agnyAhita
41603 old <>ficer; cf. {#agtyAhita#}. --2. a Brāhmaṇa
41603 new <>ficer; cf. {#agnyAhita#}. --2. a Brāhmaṇa
```

**Comment by funderburkjim** [comment]
Batch 202, case 12 comment:

> r and virAma look similar below letters wWqQ.

Correction in question:
```
; nI-zwn -> nI-zwran
109368 old <P>.{#netraM#}¦ [{#nayati nIyate vA anena nI-zwn#}] 1
109368 new <P>.{#netraM#}¦ [{#nayati nIyate vA anena nI-zwran#}] 1
``

AP90: 
![image](https://cloud.githubusercontent.com/assets/6393033/21579714/9c88c7a2-cf8b-11e6-909d-dace450c0093.png)


AP:


![image](https://cloud.githubusercontent.com/assets/6393033/21579710/79aa1740-cf8b-11e6-9671-4371f954a160.png)

**Comment by funderburkjim** [comment]
Batch 202, case 17 Comment:

> pfzo0 is short form for pfzodarAdi.  

As MW says, this refers to Panini 6.3.100.  Acc. to Katre, this is a class of compounds beginning with
pfzodara.   

Question: Where is a list of such compounds ?
(I tried to search on Sanskrit Documents site, but without luck.)

**Comment by funderburkjim** [comment]
Batch 203, case 12 comment:

> H+vowel combination is not usual. Do systematic analysis.

This occurs within a quotation: 
![image](https://cloud.githubusercontent.com/assets/6393033/21579789/60a55d90-cf90-11e6-87c2-6916a46bce27.png)

It appears the same way in AP.  

Perhaps the source (Mk. = ? mfcCakawikA ) has this spelling?

**Comment by funderburkjim** [comment]
Corrections from 2-gram batches now installed.

Does anyone have preliminary revisions to  ngram3-exclude-list.txt or ngram3-remain-list.txt mentioned [above](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/329#issuecomment-269847038) ?

**Comment by SergeA** [comment]
> Batch 203, case 12 comment:
> Perhaps the source (Mk. = ? mfcCakawikA ) has this spelling?

No, it has not. 
Stenzler´s ed. 1847
![screenshot_1](https://cloud.githubusercontent.com/assets/6435011/21579930/9e4b72c6-cfde-11e6-977b-db3f07475c0f.png)
Kale´s ed. 1924
![screenshot_2](https://cloud.githubusercontent.com/assets/6435011/21579951/5718a46c-cfe0-11e6-909f-3c3ea3c2c055.png)
The danda fits here better. The space arise a problem of sandhi.

**Comment by gasyoun** [comment]
> I'm not clear how to track down other such cases (where 'O' in current SLP1 should be hiatus 'au', or 'E' in current SLP1 should be hiatus 'ai')

What if we use a whitelist, like the 190 word MW list?

> SLP1, which does make this distinction (by using 'E' instead of 'ai' for the diphthong), this wrong conversion was unavoidable.

So we should check words from the MW hiatus list in other dictionaries for possible wrongly converted words, Jim?

> Isn't it nice to be able to track down such things?

It's mesmerizing! If I would be Watson I would name you Holmes!
"Excellent! I cried. "Elementary," said he.

> Due to the close relationship between ap90 and ap (1957), we may be able to find ways to compare the two editions as a way to generate corrections.

Interesing to see in how many ways AP quotes and defitions repeat AP90. Was not aware.

> The danda fits here better. The space arise a problem of sandhi.

Let it be Stenzler´s way, thanks @SergeA

**Comment by SergeA** [comment]
> Let it be Stenzler´s way, thanks @SergeA

I don´t think we should make such modifications as inserting omitted dandas. There can be multiple quotations from Mricchakatika etc. with similar ignoring of dandas. Yes, it it not perfect, but when we see the other edition also without danda, we can not say it is Apte´s defect.

**Comment by funderburkjim** [comment]
Dhaval's added space change was made:  `lImAtaHasti  -> lImAtaH asti`

Incidentally, AP has this space.

Versions of this quote  (thanks to @SergeA 's  research) show the power of having links to sources.  

In addition to augmenting access to subheadwords,  developing abilities to link lexicon entries to external source documents would probably be the most value we could add to the digital editions.   

A requisite to this is linkable versions of source documents.  

@SergeA   You showed two nice images of verses from मृच्छकटिका .   Are there links to your two sources?

**Comment by funderburkjim** [comment]
> What if we use a whitelist, like the 190 word MW list?

Sounds worth considering further.

@gasyoun  Could you provide that list ?

**Comment by drdhaval2785** [comment]
@funderburkjim, 
I saw the list of exclusion of ngrams.

One question.
Why don't we compare SKD explanation + headword as basis and compare AP90 to it.
If we use headword data for base and compare AP90 explanation, it would be apple vs oranges comparision.

**Comment by drdhaval2785** [comment]
Majority of our inflected form issue will die out if we do explanation vs explanation comparision.

**Comment by funderburkjim** [comment]
When you said 'SKD' did you mean 'AP'?

i.e., compare AP to AP90 ?

**Comment by drdhaval2785** [comment]
No. I meant SKD. It has all explanations in Sanskrit. So maybe the false
positives may not arise (mainly because of external sandhi).

**Comment by funderburkjim** [comment]
Hmm.   Well, maybe comparison between SKD and AP90 could be useful.  I'll leave that exploration to
you for now.

Meanwhile, I'm exploring comparison between AP and AP90, since they appear to have very similar
Sanskrit snippets.

**Comment by SergeA** [comment]
> @SergeA You showed two nice images of verses from मृच्छकटिका . Are there links to your two sources?

Stenzler
https://books.google.ru/books?id=HzhNAAAAcAAJ&hl=ru&pg=PP5#v=onepage&q&f=false

Kale
http://www.new.dli.ernet.in/handle/2015/326600

aslo other editions
http://www.new.dli.ernet.in/discover?scope=%2F&query=mrichchhakatika&submit=&rpp=10

**Comment by gasyoun** [comment]
@funderburkjim 
https://github.com/sanskrit-lexicon/MWS/blob/master/hiatus-190-entries.txt

**Comment by gasyoun** [comment]
@funderburkjim is this issue closed? Because if not, @rblinderman (http://sas.fas.harvard.edu/people/radha-blinderman) is ready to help. All she needs is an algo how to work and what to verify or cleanup. She is interested in AP, AP90 and SKD, VCP and MW above all. I tried to find a dropped task on suspicious word lists but was not good at finding anything interesting.

**Comment by funderburkjim** [comment]
I think this particular issue can be closed.  We've got VCP alternate headwords as task for Radha to help.

**Comment by gasyoun** [comment]
@funderburkjim ok, do we have proofreading tasks `based on 2-gram, 3-gram` for other dictionaries left undone?

**Comment by funderburkjim** [comment]
> proofreading tasks undone?

None comes to mind.

**Comment by funderburkjim** [comment]
Not saying that.  Rather, there are none that are currently in progress.

**Comment by gasyoun** [comment]
> Rather, there are none that are currently in progress.

Yeah, that's what I'm requesting. Radha is waiting and alternative headwords are great, but I would want to have some simpler task as well, like the 2-grams for a dictionary we have not dealt with.
