### ISSUE TITLE
AP, preparatory normalization of digitization

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#333]
Similarly to what we did to normalize some of the coding conventions of the AP90 digitization (#327), we can do for the AP digitization.

These coding changes can be separated into at least these two cases:
* Replace AS (number-letter) coding of letter-diacritic text with Unicode letters.
  * Unlike AP90, there are no italic-letter codings (We should be thankful for small favors!)
  * We have to choose whether to use modern IAST spelling (notably `Ṛ` or `Ṛi` for the vowel ऋ ).  
     The text has `Ṛi` but modern IAST is `Ṛ`.  There may be a few other such choices.
      * My preference is modern IAST.  But recall that for MW72, we chose to use non-modern IAST
         in order to maintain consistency with the printed text.  Modern IAST would be consistent with
         AP90, and facilitate comparisons to AP90.
* Remove Sanskrit Bold .  
   * With AP90, we decided that text coded as bold Sanskrit was not meaningful.  The issue with AP is 
      similar.  Here are some preliminary statistics. Bold Sanskrit is coded in AP digitization as `{#{@...@}#}`
   * There are about 49000 Bold-Sanskrit text snippets.
   * All but about 2000 of these (4%) have a '-' as the first letter.  These are sub-headwords.
   * By contrast, there are only 11 cases of non-bold Sanskrit text whose first letter is a '-'
   * Random examination of the 2000 cases indicates that many of these are relevant for subheadword
      analysis.
   * Preliminary conclusion:   
     * Remove the bold designation of `{#{@-xxx@}#}`.  The leading '-' has the
      information (subheadword); the Bold designation is duplicative.
     * Keep the bold designation for those 2000.  (but change coding to have the 'bold' outside:
       `{@{#X#}@}`.

**Comment by gasyoun** [comment]
> We should be thankful for small favors!

Small? Huge!

> Modern IAST would be consistent with
AP90, and facilitate comparisons to AP90.

I go for modern. If we will remember what was there before.

> Remove the bold designation of {#{@-xxx@}#}. The leading '-' has the
information (subheadword); the Bold designation is duplicative.

Preliminary agreed.

**Comment by funderburkjim** [comment]
Regarding Bold Sanskrit:
* Changed my mind regarding its elimination -  Leave it for now.  When we get seriously into subheadwords, we may want to replace the bold markup with more expressive markup. For instance,
under headword tArA, we see
```
.-{@Comp.@}
.{#{@-aDipaH@}#}
 etc.
```
More expressive markup might be
```
 <shw key1="tArADipaH">{#-aDipaH#}</shw>
```
where we use sandhi to resolve the headword `tArA` and the sub-headword fragment `aDipaH`.
This resolution step is non-trivial, but can mostly be done by our existing compound-sandhi program.
Whenever we do this subheadword identification, that will be a better time to deal with the bold Sanskrit markup.

However, it does seem appropriate to put the 'bold' markup *outside* of the Sanskrit-Devanagari markup
```
{#{@X@}#}  -> {@{#X#}@}
```
And I'll do that in this preparatory round.

**Comment by funderburkjim** [comment]
In converting the AS to standard IAST unicode, we encounter an issue of inconsistency in the text of AP.
While the usual case (1200+ lines) is to use vocalic 'r' followed by 'i'  (r-dot+i), there are a minority of
cases (200+) where the following 'i' is omitted.

Thus, when we convert to standard IAST  (r-dot with no following 'i'),  this conversion will be non-invertible in those cases (i.e., we would not know whether the original coding had the 'i' or not).

Analysis showed that there are 157 distinct words in the text which have one or the other forms of vocalic r.
Of these  22 words fail to have the following 'i' .  And in terms of instances, 3 literary source abbreviations (R2v, R2s, Br2) account for 90% of the instances.

These are the ones marked with an asterisk `*` in [vocalic_r.txt](https://gist.github.com/funderburkjim/56ff230cb5238018e7e40ae8126f9ab5).   In this file, the AS coding r2 represents r-with-underdot in Unicode.

A close examination of this file will point out several cases where there are errors somewhere (typo or print).  E.g. 
* 'father2'  (the text erroneously shows a dot, possibly a smudge, under the 'r')
* there are several forms of  कृष्ण , some being wrong.

Based on this study, I don't consider the lack of invertibility to be significant, and think it is ok
to go ahead and convert both r2i and r2 to `ṛ`.

**Comment by gasyoun** [comment]
> Based on this study, I don't consider the lack of invertibility to be significant, and think it is ok
to go ahead and convert both r2i and r2 to ṛ.

Agree, well done.

**Comment by funderburkjim** [comment]
Two other features of the current digitization of AP were modified:
* The page break coding `[Pagexxxx]` sometimes (about 1500) occurs in the middle of a digitization line:
   *  blah blah [Pagexxxx] blah2 blah2
   * This makes it imposible to associate such a digitization line with a particular page-col of the text.
   * In such a case, the coding was changed to 3 lines
   ```
     blah blah
     [Pagexxxx]
     blah2 blah2
    ````
  * Similarly, even for lines of the original digitization *ending* with a page break, the break was
     put onto a new line. so
     ```
       blah blah [Pagexxxx]  
        becomes two lines
       blah blah
       [Pagexxxx]
     ```
* Making digitization lines have approximate equal lengths
   In the current digitization, some lines are quite long.  Here is a distribution of line lengths:
    ```
      line length < 50 = 155713
      line length < 60 = 10464
      line length < 70 = 7877
      line length < 80 = 6718
      line length < 90 = 6383
      line length < 100 = 5405
      line length < 110 = 4602
      line length < 120 = 3466
      line length < 130 = 2783
      line length < 140 = 2267
      line length < 150 = 1767
      line length < 200 = 5383
      line length < 300 = 3221
      line length < 400 = 884
      line length < 500 = 331
      line length < 999999 = 467
    ```
  * A simple algorithm was used to break long lines into several shorter lines.  The standard length
     was chosen as 75 characters  (since this is easily viewed as 1 line in text editor), and longer
     lines were broken into approximately this standard length, but maintaining space-define 'words'.
     ````
      line length < 50 = 180338
      line length < 60 = 13804
      line length < 70 = 10756
      line length < 80 = 48838
      line length < 90 = 11377
      line length < 100 = 2258
      line length < 110 = 416
      line length < 120 = 86
      line length < 130 = 19
      line length < 140 = 5
      line length < 150 = 1
     ```
     Probably the reason there are still some longer lines than the standard is the presence of
     very long devanagari 'words'.
    * Adjustments were made to maintain closure of Devanagari/italics markup within the new lines.

**Comment by gasyoun** [comment]
> In the current digitization, some lines are quite long

Well done, as usual. I use Wrap by Windows mode, so that does not bothers me, but 467 very long lines still can hurt.

**Comment by funderburkjim** [comment]
### remove {|...|} markup

There are about 1500 lines with this kind of markup, which in all but one case appears within the italic markup.  In other digitizations, this vertical bar markup indicates the typographical feature of 'wide character spacing'.  Perhaps that is the intent here, but examination of several cases suggests that there is no semantic, and only minor typographical, meaning.  Thus, it seemed reasonable to view this markup as not useful and to remove it from the digitization.

### correct several IAST coding errors
In about 40 lines, there were obvious spelling errors in the IAST,  involving vocalic 'r'.  In several (14) of the cases, these were minor print errors (missing a dot below an r,s, or n).  These corrections have been
made.

### correct several page errors
There were 10 or so cases where the page-break data had a wrong page number.  These have been corrected.

### two markup details 

* €  symbol appears in about 3000 records of the Cologne digitization of AP.   The entries are roots, and the markup appears precented the class-pada information just after the headword. e.g.
`   ``
   .{#aMS#}¦ €10U. {#aMSayati-te#} also {#aMSApayati#} To divide, distribute, share among.
   ```
   Although inelegant, this markup might be of use within a study of the root entries of AP.
* ‡  symbol appears in about 7100 lines. It represents a line-ending '-' within Devanagari text.
   Although the lines of the AP digitization do not aim to correspond to the lines of the text (alas!),
   this symbol might prove useful to know about when doing any analysis of the Sanskrit text with AP.

**Comment by funderburkjim** [comment]
The various preparatory steps for AP are now installed.

**Comment by gasyoun** [comment]
> € symbol appears in about 3000 records of the Cologne digitization of AP. The entries are roots

Hurray. 3068 dhatus, including sopasarga like `niyuj, vinikzip, saMkf`. It's half of MW's 6427 roots.

Last modified: 01/10/2017. So it's not yet online.

> In about 40 lines, there were obvious spelling errors in the IAST, involving vocalic 'r'. In several (14) of the cases, these were minor print errors (missing a dot below an r,s, or n). These corrections have been
made.

[These](url=https://github.com/sanskrit-lexicon/CORRECTIONS/commit/1fc095cd87163f2b3d6321036430368294351dbe) actually could be killed by Dhaval and I'm sure there are a few hundred more out there. @drdhaval2785 please let the Sandhi engine do the proofing work.

**Comment by drdhaval2785** [comment]
Hi Marcis,
I am still in hibernation. May wake up around december 2017.

**Comment by funderburkjim** [comment]
@drdhaval2785   Have missed your inputs.  Did not know you were in hibernation.  Will continue working to improve things.
