### ISSUE TITLE
Corrections to MW for Arabic markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#337]
This is a placeholder issue in this CORRECTIONS repository.

For background information on the Arabic markup changes, see [this](https://github.com/sanskrit-lexicon/Cologne/issues/68) issue in the Cologne repository.

**Comment by funderburkjim** [comment]
With this correction, the venerable monier.xml is being retired.

This means that all updates, starting with this one, will begin with the current version of mw.xml, which
is being renamed mw0.xml.  In other words, mw.xml will still be the final (current) form of the
Monier-Williams digitization, and it will be constructed by one or more steps starting with mw0.xml.

**Comment by funderburkjim** [comment]
These changes now installed.

**Comment by gasyoun** [comment]
> venerable monier.xml is being retired

Hurray! It was 25 years in service. Time to move on. Long live `mw0.xml`!
