### ISSUE TITLE
Accents on 'poet' in Burnouf

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#338]
A recent user correction to the Burnouf dictionary, under headword Adi , was to change the spelling of
the French word for 'poet' from having an umlaut over the 'e' `poëte` to a grave accent (poète).  
The print actually does show the umlaut.  A few other cases suggest that the digitization agrees with
the print.

In examining the digitization for other entries, it was found that there are various diacritics
over that 'e':  27 umlauts,  2 acute accents,  20 grave accents.

Using Google Translate as authority,  the grave accent is the correct spelling.

I think that all the umlauts and acutes should be should (29), and classified as print errors.

**Comment by funderburkjim** [comment]
These changes now installed.

**Comment by gasyoun** [comment]
Umlauts do occur in French as well, like in `naïve, Noël` so when making such lists please do add the list of words to the issue as well. Otherwise well done, as usual.

**Comment by SergeA** [comment]
> Using Google Translate as authority, the grave accent is the correct spelling.

@funderburkjim  You are wrong to use google as authority in the french orthography of the XIX century.

Please see this link.
https://fr.wiktionary.org/wiki/poëte

> Ancienne orthographe de poète jusqu’en 1878. 

The spelling **poëte** was correct until 1878. So, when the Burnouf´s dic was printed in 1866 this spelling was correct. It is not a print error. And I suppose the other cases you´ve mentioned are NOT print errors.

**Comment by funderburkjim** [comment]
@SergeA   

It is interesting to have the historical perspective which you supplied. Thanks.

I wonder why Burnouf uses both the 19th century spelling and the modern spelling with grave accent.

The file that we keep for 'print errors' is actually named 'bur_printchange.txt' -- it is where we note that
we have intentionally changed the spelling that appears in our version of the printed text.  We don't,
in that document, distinguish between 'errors' and 'changes'.  However , based on your insights,  I have
added the comment 'modern spelling' for these changes.   

It is beyond our current technical ability to maintain multiple versions.  For instance, someone with
your erudition might prefer to maintain the conventions of the original authors.  In the case of Burnouf
this might well include maintaining the various spellings as present in the printed edition for 'poet'.  In other cases it might mean to maintain the author's version of IAST.

However, my current view is that we should err on the side of utility.  The person who submitted the correction in spelling for 'poet' is a native French speaker, and she found the older spelling jarring.  So, it still seems appropriate to have made the changes in this case.  Do you agree?

**Comment by funderburkjim** [comment]
Incidentally, here is a link to [the Burnouf printchange file](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/BUR/bur_printchange.txt).  It is in this repository.

The printchange files for other dictionaries are similarly located in this repository.

**Comment by gasyoun** [comment]
> We don't,
in that document, distinguish between 'errors' and 'changes'. 

So we would want to have it as comment, if it's a change (unification, update)?

> my current view is that we should err on the side of utility.

Such is mine as well.

> So, it still seems appropriate to have made the changes in this case. Do you agree?

It's documented, that is what matters. One day we will learn how to show on the word in question what operations have been done with it. And maybe even both words would give up same search results.

**Comment by SergeA** [comment]
> I wonder why Burnouf uses both the 19th century spelling and the modern spelling with grave accent.

I don´t know where and how to check if Burnouf uses both poëte and poète. If so, it is an excuse for unification of the spellings.

> The person who submitted the correction in spelling for 'poet' is a native French speaker, and she found the older spelling jarring. So, it still seems appropriate to have made the changes in this case. Do you agree?

Not agree. :)
Tastes differ. Somebody will find it jarring, another one will find it pretty nice. The orthography changes time to time. Burnouf, Bohtlingk, Monier etc. - all of them have many French, German, English etc. obsolete spellings. I see no logic, nor any benefit, in updating this single "poëte" case. Yes, from the practical point of view the old spellings may cause problems for modern people, and in theory it is desirable to have the modern spellings everywhere. But who is able to handle such a task? And on the other hand, every minor change in the text lessens its exactness.

**Comment by gasyoun** [comment]
> And on the other hand, every minor change in the text lessens its exactness.

So we should have the original text and a ghost text for easy access :1st_place_medal:

**Comment by funderburkjim** [comment]
@SergeA   > Not agree

I thought you might say that!   I'll try to keep your views in mind as similar situations arise.

**Comment by funderburkjim** [comment]
> I don´t know where and how to check if Burnouf uses both poëte and poète. If so, it is an excuse for unification of the spellings.

Here is a listing of the headwords of BUR where one of the *three* spellings of 'poet' occurs'
In this listing: 
* the headwords are spelled with slp1
* e7 means e-umlaut
* e11 means e-grave
* e4 means e-acute

By looking up the word and checking the scan, I think you'll find that all forms appear in the print.

```
L=93, hw=agastya, poe7te
L=154, hw=aNgiras, poe7te
L=289, hw=atiTi, poe7te
L=356, hw=atri, poe7te
L=2151, hw=Adi, poe7te
L=4234, hw=kavi, poe7te
L=4234, hw=kavi, poe7te
L=4236, hw=kavijyezWa, poe7te
L=4238, hw=kavitva, poe7te
L=4510, hw=kAlidAsa, poe11te
L=4530, hw=kAvya, poe7te
L=4760, hw=kutsa, poe7te
L=5207, hw=kOSika, poe11te
L=5849, hw=gAyana, poe11te
L=5991, hw=gftsamada, poe11te
L=10331, hw=noDas, poe7te
L=11467, hw=pracetas, poe7te
L=11579, hw=pratijYA, poe7te
L=12656, hw=Barata, poe11te
L=12656, hw=Barata, poe11te
L=12659, hw=BaradvAja, poe11te
L=12665, hw=Bartf, poe11te
L=12674, hw=Bava, poe11te
L=12680, hw=Bavina, poe7te
L=12726, hw=BAravi, poe11te
L=12787, hw=BUti, poe11te
L=12994, hw=maDu, poe7te
L=13207, hw=mAgaDa, poe4te
L=13208, hw=mAGa, poe7te
L=14017, hw=rasa, poe7te
L=14732, hw=vaptf, poe7te
L=14753, hw=vararuci, poe7te
L=14808, hw=varRa, poe11te
L=14955, hw=vAgAru, poe11te
L=15622, hw=vimada, poe11te
L=15858, hw=viSva, poe11te
L=16528, hw=Sata, poe11te
L=16528, hw=Sata, poe11te
L=17063, hw=SyAva, poe11te
L=17426, hw=satsAra, poe4te
L=18547, hw=sidDa, poe11te
L=18913, hw=sUta, poe11te
```
