### ISSUE TITLE
AE dictionary, convert AS to IAST unicode

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#339]
There are only a very few instances (approx. 60) in the Apte English-Sanskrit dictionary where an IAST type diacritic form appears in the text . The digitization ae.txt heretofore has coded these with the AS (number-letter)  coding.  These few instances have been changed to Unicode, using modern IAST. For instance
`Ra10ma` -> `Rāma`.

**Comment by gasyoun** [comment]
Perfect.
