### ISSUE TITLE
BOP alphabetic misordering corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#343]
1-5
```
bop:aNiGri,87:aNGri:t:
bop:oDa,1704:oGa:t:
bop:kaNkitikA,1757:kaNkatikA:t:
bop:kicaka,2161:kIcaka:t:
bop:kzRadAdara,2543:kzaRadAcara:t:
```

**Comment by drdhaval2785** [comment]
6-10
```
bop:tadfSa,3703:tAdfSa:t:
bop:naqravala,4477:naqvala:t:
bop:pawiwaSa,4839:pawwiSa:t:
bop:pUp,5252:pUy:t:
bop:miSrU,6235:miSr:t:
```

**Comment by drdhaval2785** [comment]
11-15
```
bop:medenI,6369:medinI:t:
bop:yoz,6546:yez:t:
bop:rakzRa,6574:rakzaRa:t:
bop:sakiTa,8159:sakTi:t:
bop:saNGaya,8177:saNkzaya:t:
```

**Comment by drdhaval2785** [comment]
16-17
```
bop:saNGepatas,8179:saNkzepatas:t:
bop:sEha,8580:sEMha:t:Related to siMha.
```

**Comment by drdhaval2785** [comment]
@gasyoun and @funderburkjim 
My first small stint with corrections after hibernation.

BOP alpha-mismatch completed.

**Comment by gasyoun** [comment]
> BOP alpha-mismatch completed.

A good catch I would say, Dr. Dhaval :eagle:

**Comment by funderburkjim** [comment]
@drdhaval2785 Glad you used the 'standard' form for corrections.  Prior programs worked like a charm to facilitate the installation.

A couple of weaks ago, there was a black bear sighting in the woods nearby. Maybe one of your confreres also waking from hibernation :)

**Comment by gasyoun** [comment]
> black bear sighting in the woods

This one is a Himalayan :baby_chick:
