### ISSUE TITLE
ACC correction for commentary - C¤

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#345]
```
<HI>{#aKaRqAnanda muni,#}¦ disciple of Akhan2d2a1nubhu1ti:
<HI1>Tarkabha1sha1praka1çavya1khya1. Taylor 1, 26.
<HI1>Tattvadi1pana Pan5capa1dika1vivaran2a (veda1nta).
<HI1>Vivaran2atattvadi1pana, a C¤: on Sureçvara's Brahma-
<>su1trabha1shyava1rttika.
```

Look at `C¤`. 
Time to kill. Change to `C.` or `Co.` something better.

Checked on the frontend. 
It is shown as it is in digitized version.

**Comment by drdhaval2785** [comment]
राजतरङ्गिणी by Kalhaṇa. Stein 72. 73.
Continuation by Çrīvara, called Jainataran̄giṇī.
Stein 73.
Continuation by Prājyabhaṭṭa, called Rājāvali-
patākā. Stein 73 (inc.).


Look at jEnataraGgiRI ( in slp1).
G in particular.

n with macron above is not suited.

**Comment by drdhaval2785** [comment]
jEnataraNgiRI

**Comment by drdhaval2785** [comment]
This is universal issue. Some 200+ items still having 'n1' in XML and rendered thus in web version. Maybe a convertor issue.

**Comment by gasyoun** [comment]
> n with macron above is not suited.

That's one of the possible orthographical solutions.

> Time to kill.

Agree.

**Comment by funderburkjim** [comment]
> a C¤: on Sureçvara's   

![image](https://cloud.githubusercontent.com/assets/6393033/24628119/305426c0-1884-11e7-9bbd-6ec6e025900a.png)

Here's the author's explanation from one of the prefaces:
![image](https://cloud.githubusercontent.com/assets/6393033/24628561/d42798c2-1884-11e7-9a4f-89f5c8981c4c.png)

To preserve the presence of this (These) special symbols, perhaps an empty xml tag could be used.
e.g. `<symbol n="C."/>`.  But there should also be a default, more useful rendering.  So a better
solution might be `<symbol n="C.">C.</symbol>`  The explanation of the meaning of a symbol
could be part of the xxx-meta description.

Does this sound like a good solution?  Is 'C.' appropriate for this particular case.?

Have we seen  examples of  ![image](https://cloud.githubusercontent.com/assets/6393033/24629049/aa1086ce-1885-11e7-8fa7-ede8940f1939.png)  ?

**Comment by funderburkjim** [comment]
n-macron -> n-dot-above

In most of the recent conversions to IAST,  the principle has been to convert to **modern** IAST, as per this [IAST](https://github.com/sanskrit-lexicon/Cologne/issues/107) article.   

This seems a reasonable principle for increasing utility and uniformity of the digitizations, and will 
guide the ACC conversion to IAST also.

**Comment by funderburkjim** [comment]
> jEnataraGgiRI

I'm not finding that spelling (with 'G') in current acc.txt.

**Comment by gasyoun** [comment]
> Does this sound like a good solution? 

Makes sense.

**Comment by funderburkjim** [comment]
Here are some other forms re 'C' as they appear in digitization:

* C¤:   8673 instances.  The colon-charcter seems to be part of the abbreviation used by the author,
         so it should be also removed in the default rendering
* CC-¤   482 instances, e.g. in hw anumitirahasya; no following 
* CC--¤   3 instance, e.g. under hw aTarvaSiKopanizad  This should be viewed as digitization error for
    CC-¤ 
* CCC-¤  39 The text really does have multiple backward 'C' characters. Example under nyAyasUtra
* CCCC-¤  8
* CCCCC-¤  3   That's the most.

Question: What should be the default rendering for the *multiple* commentaries?

**Comment by funderburkjim** [comment]
Here is Aufrecht's description of his Sanskrit printing system:
![image](https://cloud.githubusercontent.com/assets/6393033/24633134/02614cb4-1895-11e7-8f0d-f19ad2b32f00.png)

The diffierences from modern IAST:
* r-underdot+i -> r-underdot
* r-underdot + i-macron -> r-underdot-macron
* n-macron -> n-overdot
* c-cedilla -> s-acuteaccent
* sh -> s-underdot

This listing does not mention:
* anusvara  (modern m-underdot)
* visarga (modern h-underdot)
* avagraha (modern apostrophe)

**Comment by funderburkjim** [comment]
These are cases where ACC uses a reprensentation not mentioned in the above table
* n-dotabove  1862 cases.  This seems to be used in place of anusvara when preceding 
   (SLP1) sSzh.   I'll convert these to anusvAra.

**Comment by drdhaval2785** [comment]
jEnataraGgiRI

> I'm not finding that spelling (with 'G') in current acc.txt.

I intended to use jEnataraNgiRI. Old HK habit came into play unknowingly.

**Comment by drdhaval2785** [comment]
>Question: What should be the default rendering for the multiple commentaries?

`<symbol n="C.">C.</symbol>` 
`<symbol n="CC.">CC.</symbol>` 
`<symbol n="CCC.">CCC.</symbol>` 
etc ?

**Comment by funderburkjim** [comment]
That seems fine for CC and friends.  Will probably have ACC conversion done tomorrow, not that many
oddities to handle.

**Comment by gasyoun** [comment]
> n-dotabove 1862 cases. This seems to be used in place of anusvara when preceding
(SLP1) sSzh. I'll convert these to anusvAra.

Yes, that's how later author used it as well, including Kochergina's dictionary I showed you.

>  I'll convert these to anusvAra.

The only thing I ask is to mark them as such, converted, or too hard?

**Comment by funderburkjim** [comment]
@gasyoun   You want to add markup to each of the 1862 cases?   Technically, this probably would not be hard, but I am concerned that the end result would be ugly.

**Comment by funderburkjim** [comment]
Here are three cases where I think the r-underdot is an error, but am not sure.
```
1. L=7960, key1=jalpeSvaramAhAtmya, Tiruvaiyāṛ -> Tiruvaiyār
2. L=12541, key1=paYcanadamAhAtmya, Tiruvaiyāṛ -> Tiruvaiyār
3. L=40126, key1=tripadadyotinI, Eṛṛamādhavārya -> Erramādhavārya
```
![image](https://cloud.githubusercontent.com/assets/6393033/24676307/76777658-1950-11e7-98d1-76cad1274d10.png)

![image](https://cloud.githubusercontent.com/assets/6393033/24676356/aafa90a4-1950-11e7-8395-f1b178ac505e.png)

![image](https://cloud.githubusercontent.com/assets/6393033/24676401/d29e6130-1950-11e7-884c-4f143f4afc2f.png)

**Comment by gasyoun** [comment]
> maybe some kind of separate listing would fit your needs?

Makes sense, indeed.

>  I am concerned that the end result would be ugly.

Agree.

>  r-underdot is a print error

@drdhaval2785 it's non-Sanskrit or what?

**Comment by funderburkjim** [comment]
@gasyoun   Re the separate listing for n-dotabove.    Tell me what you would like in the listing.

**Comment by funderburkjim** [comment]
The conversion to IAST in ACC is now complete.  

For future reference:
* [readme](http://www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/pywork/20170403/readme.org)
* Main [transcoder file](http://www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/pywork/20170403/accas_roman.xml)

**Comment by gasyoun** [comment]
> The conversion to IAST in ACC is now complete.

Maybe open a new page, where all the  encodings used nowadays are listed in all dictionaries?

> Tell me what you would like in the listing.

The word in question and headword to which it relates, I guess should be more than enough.

**Comment by drdhaval2785** [comment]
>1. L=7960, key1=jalpeSvaramAhAtmya, Tiruvaiyāṛ -> Tiruvaiyār 2. L=12541, key1=paYcanadamAhAtmya, Tiruvaiyāṛ -> Tiruvaiyār 3. L=40126, key1=tripadadyotinI, Eṛṛamādhavārya -> Erramādhavārya 

Non Sanskrit local names. Can be converted to 'r'.
Not fit for 'f'.

**Comment by funderburkjim** [comment]
@drdhaval2785   Thanks, I thought those might be non-Sanskrit words, but wasn't sure.

P.S. That would be one of the fine points, if a further conversion to SLP1 were to be done.

**Comment by funderburkjim** [comment]
### ndot study
@gasyoun  This [n3study gist](https://gist.github.com/funderburkjim/59d5167d612eb7e589631bc80e5383a4)  shows
the instances in ACC where the author represents a nasal before sibilants and 'h' as `ṅ` (n with dot above).

In these displays, the guttural nasal is represented as n̄ (n-combining-macron).

Note that these nasal representations are not what is used in the current acc.txt digitization;  in the
current acc.txt,  nasal before siilants and 'h' is represented as `ṃ` (anusvara), and guttural nasal is 
represented as `ṅ` , in accordance with modern IAST.

A second note is that in some cases (916 lines) (not represented in these displays), the author  uses 
an anusvAra before sibilants or h:   Examples saṃhitā, Saṃskṛtamañjarī, Saṃśayavāda,  (could not 
find any ṃṣ).

**Comment by funderburkjim** [comment]
I think this issue can be closed.
