### ISSUE TITLE
sch.xml - an abberrant entry

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#360]
In sch.xml, no letter was given a special treatment except 'E'.
See 
```
<H1><h><key1>E</key1><key2>Ai</key2></h><body></body><tail><info seq="9422" n="1"/><L>9300</L><pc>128-1</pc></tail></H1>
<H1><h><key1>E</key1><key2>ai</key2></h><body>Interj. Maitr. S. 4 , 9 , 21. </body><tail><info seq="9423" n="1"/><L>9300.1</L><pc>128-1</pc></tail></H1>
```
![screenshot from 2017-06-21 11-32-27](https://user-images.githubusercontent.com/5755132/27369388-55c4262e-5675-11e7-9b6a-9538eadf454a.png)

This has given rise to problem in stardict generation.
Actually the letter 'E' (9300) is not a headword and included in `<H1>` tag wrongly. No other letter is.
And subsequent to it `E` which is a headword (currently shown as 9300.1) is sent to alternate headword category.
Needs correction.

For proof, see `O` where letter is not given headword status.
```
<H1><h><key1>EhilOkika</key1><key2>aihilaukika</key2></h><body>Adj. = <i>aihalaukika</i> , Hem. Par. 3 , 184. </body><tail><info seq="9462" n="2"/><L>9338</L><pc>128-3</pc></tail></H1>
<H1><h><key1>ogaRa</key1><key2>ogaṇá</key2></h><body>, vgl. Pāli <i>ogaṇa</i> , gewaltig , -x- groß. </body><tail><info seq="9463" n="2"/><L>9339</L><pc>128a-1</pc></tail></H1>
```
![screenshot from 2017-06-21 11-33-00](https://user-images.githubusercontent.com/5755132/27369404-6660e684-5675-11e7-8667-d6a2b66b1968.png)

**Comment by gasyoun** [comment]
> Needs correction.

Hercule Poirot, nothing less.

**Comment by drdhaval2785** [comment]
@funderburkjim,
This is a small error. Kill it so that I can also regenrate this dict too.

**Comment by funderburkjim** [comment]
I will take this opportunity to introduce the 'meta-line' format to SCH.
Then will kill the unneeded line.

**Comment by gasyoun** [comment]
> I will take this opportunity to introduce the 'meta-line' format to SCH.

The grand master's wish is our command.

**Comment by funderburkjim** [comment]
meta-line restructuring finished for sch.txt.

Errroneous record deleted.

xml file ready for stardict retry.

**Comment by drdhaval2785** [comment]
It seems that meta line reconstruction is now very fast. Initial teething
problems with ACC are not that evident now.
May I request for conversion of all dictionaries this way? Then generic
application may be possible partially for important information.

**Comment by gasyoun** [comment]
> May I request for conversion of all dictionaries this way? 

Hmm, we will loose Jim for months, no?

**Comment by funderburkjim** [comment]
Yes, the metaline conversion does seem to go well.  The main bottleneck is IAST conversion.
My approach has been to do consider meta-line conversion  as a 2nd step to be done after IAST
conversion.    The table in [this issue](https://github.com/sanskrit-lexicon/Cologne/issues/110)  aims
to show progress.  

Probably I should focus next on doing the meta-line conversion step for those dictionaries that have
already had IAST conversion, and for SKD, VCP which have no IAST conversion to worry about.
