### ISSUE TITLE
Unknown MW literary reference abbreviation

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#361]
A user noticed that the literary reference mentioned under hw prapatti was not found.
I'm stuck.  Anybody know what it might be, or if it is variant spelling of a known MW literary source?
The abbreviation in question is `Ṡāṇḍ. `
```
(H2) pra-patti [p= 682] : f. pious resignation or devotion, Ṡāṇḍ.  [L=135116]
```
![image](https://user-images.githubusercontent.com/6393033/28148467-da559d10-6754-11e7-8f28-bab332b45f2e.png)

Incidentally, investigation of this led to discovery of typo 'Silana'  (should be SIlana) as the name of work.

**Comment by funderburkjim** [comment]
That typo prapattipariSilana -> prapattipariSIlana was confirmed by ACC, since it is name of a work.

A good exercise would be to cull all the MW headwords identified as 'N. of wk', and try to find them in ACC; this might catch a few other spelling errors.

**Comment by gasyoun** [comment]
> cull all the MW headwords identified as 'N. of wk', and try to find them in ACC

Can you? And I'll take a look as well.

**Comment by funderburkjim** [comment]
### is `Ṡāṇḍ.` an abbreviation of the author SARqilya  ?

This abbreviation occurs 5 times in MW. under headwords
prapatti  (shown above),  prARitva, bAhulyAt, vyutkrama, and sakaraRaka.

The entry for SARqilya:
```
m. N. of various teachers, authors &c (esp. of a muni or sage from whom one of the three principal 
families of the Kanouj or kānyakubja Brahmans is said to be descended ; he is the author of a law-book 
and of the bhakti-sūtra or aphorisms enjoining " love or devotion to God " as one of the three means
 of salvation - a doctrine said to have been formulated in the 12th century ; » bhakti RTL.  63) 
```

**Comment by gasyoun** [comment]
@funderburkjim please ask at https://groups.google.com/forum/#!forum/bvparishat

**Comment by funderburkjim** [comment]
@gasyoun   If you are already a member of this google group, perhaps you could post the question?

**Comment by funderburkjim** [comment]
In response to my query to Peter Scharf:
```
The NCC lists numerous texts by various SARqilyas in vol. 33, pp. 205–208. 
 But I suspect it is the SARqilyasmfti p. 208a that MW referred to.
```

I'm not sure what 'NCC' refers to.

**Comment by gasyoun** [comment]
@funderburkjim I post too many questions there. Let them see that there are 2 white people around, not just me.

> I'm not sure what 'NCC' refers to.

No idea as well.

**Comment by drdhaval2785** [comment]
> I'm not sure what 'NCC' refers to.

New Catalogus Catalogorum.

A follow up work on ACC by University of Madras.

**Comment by gasyoun** [comment]
https://archive.org/details/newcataloguscata029431mbp

**Comment by funderburkjim** [comment]
Installed abbreviation as SARqilyasmfti , per Peter's suggestion.

**Comment by funderburkjim** [comment]
It appears that the NCC (link dated 1937), might be a good candidate for future digitizations.  It seemed that the archive org version linked above might have been only part of the full work.

**Comment by gasyoun** [comment]
> good candidate for future digitizations

Agree and Vedic Index from Luckanow the 2nd best choise. I wrote an email regarding NCC, but did not get a reply, wanted to get in contact with them. The latest volumes of NCC should be digital, but as everything academic in India - rather closed.

**Comment by SergeA** [comment]
> Installed abbreviation as SARqilyasmfti , per Peter's suggestion.

Please add a question mark in such cases. We must not write something by just somebody's suggestion based on naked intuition. A proof is needed always. By the abbr. śāṇḍ. we may only say it points to the author Śāṇḍilya, but the name of the work is not evident.

I checked the śāṇḍ. examples in PWG (as Boehtlingk gives more precise links) and found only one under **bāhula** 
`bāhulyāt meistentheils, gewöhnlich Śāṇḍ. 44.`
And then found this word in Śāṇḍilya's Bhaktisūtra №44.
https://archive.org/stream/ShandilyaBhaktiSutra/shandilya_bhakti_sutras#page/n91/mode/2up
So the abbr. must be changed to
`śāṇḍ. = bhakti-sūtra, by śāṇḍilya`

**Comment by funderburkjim** [comment]
> Please add a question mark in such cases

Excellent idea. Have added '(?)' .   This is the only inferred case in MW, afaik.  The others were developed by digitizing the printed pages of the preface;  this was done (acc. to mwheader.xml) by Susan J. Moore; she did it according to a format developed by Scharf and Hyman.

**Comment by funderburkjim** [comment]
Added expansion in PWG for Śāṇḍ. as you suggest.   
In that case the expansion contains the phrase `[Cologne addition]`, which I think adequately conveys that the expansion is  inferred, rather than  overtly asserted by the text.  A '(?)' could also be used here, in addition to [Cologne addition].

Incidentally, 37 ls references in pwg digitization are marked `<ls>ŚĀṆḌ. `.

**Comment by funderburkjim** [comment]
The pwg ls abbreviations are governed by a Cologne file named pwgbib.txt.   This file is a copy of
a file by the same name in the pwg repository:  [pwgbib.txt](https://github.com/sanskrit-lexicon/PWG/blob/master/pwg_ls1/pwgauth/pwgbib.txt).   You can see the ŚĀṆḌ. example
by searching for c.070 in this file 

![image](https://user-images.githubusercontent.com/6393033/34540988-96ed25be-f0a4-11e7-87f3-43eae13b29e8.png)

Almost all the 'c.xxx' cases need similar expansion.

**Comment by SergeA** [comment]
> Excellent idea. Have added '(?)' .

`403 शाण्डिल्यस्मृति (?)Title[Ṡāṇḍ.]`
The idea was to add "?" not to any additional changes, but to not verified additions - to show it is not confirmed info.
As I showed above through comparison with PWG, this supposed source Śāṇḍilya-smṛti was wrong, and the correct source is Śāṇḍilya-bhakti-sūtra. The sources of MW and B. are closely connected and it is possible to verify MW by B. So I think the LS for MW should be corrected to -
śāṇḍ. = bhakti-sūtra, by śāṇḍilya

Here I confirmed all MW Śāṇḍ. occurences in Bhakti-sūtra.

> This abbreviation occurs 5 times in MW. under headwords

https://sa.wikisource.org/wiki/शाण्डिल्यभक्तिसूत्रम्
**prapatti** (shown above) तद्वत: **प्रपत्ति**शब्दाच्च न ज्ञानमितरप्रपत्तिवत् ॥ ९ ॥, 
**prARitva** **प्राणित्वान्**न विभूतिषु ॥ ५० ॥, 
**bAhulyAt** सम्मानबहुमानप्रीतिविरहेतरविचिकित्सामहिमख्यातितदर्थप्राणस्थानतदीयतासर्वतद् भावा प्रातिकूल्यादीनि च स्मरणेभ्यो **बाहुल्यात्** ॥ ४४ ॥, 
**vyutkrama** **व्युत्क्रमाद**प्ययस्तथा दृष्टम् ॥ ९२ ॥, 
and **sakaraRaka** = not found :(

For the last case again Böhtlingk comes for help with his second dic PWK:
`सकरणक Adj. (f. °णिका) durch ein Organ vermittelt Comm. zu  Śāṇḍ.S.3. Z.5. `
So the word is not in the sūtra text, but in the commentaries. And we can even trace it to the book.
`1053The Aphorisms of SĀṆḌILYA in der Bibl. ind.[ŚĀṆḌ]`
https://books.google.ru/books?id=juY9AAAAcAAJ&hl=ru&pg=PT9#v=onepage&q&f=false
page 3, line 5, exact word-form = सकरणिका

Of course is not wise to check every word. I think the coincidence of 1 word in the exact pointed line of the text is enough to prove the LS identity by text name.

**Comment by gasyoun** [comment]
> Of course it is not wise to check every time every word. I think the coincidence of 1 word in the exact pointed line of the text is enough to prove the LS identity by text name.

Fully agree, otherwise too much time is spent.

**Comment by funderburkjim** [comment]
> (?) not to any additional changes, but to not verified additions.

I think the expanded abbreviation should clearly indicate cases where
we, as editors of the digital edition, have added to the information of the text.  That was my intended interpretation of the '?';  this usage is analogous to the `[Cologne addition]' phrase used in the very large number of additions in PWG.   Probably that 'Cologne addition' phrase is more descriptive, and maybe it should be used in the case of MW

Taking into account the convincing work by @SergeA above, the reference in MW now reads:

![image](https://user-images.githubusercontent.com/6393033/34692783-539c32ca-f48f-11e7-8f49-aca15c5034d1.png)

**Comment by gasyoun** [comment]
> Taking into account the convincing work by @SergeA above, the reference in MW now reads:

It's usually hard to argue with him because he finds the source no matter how hard it might be.

**Comment by SergeA** [comment]
> 'Cologne addition' phrase is more descriptive, and maybe it should be used in the case of MW

Agree.

**Comment by funderburkjim** [comment]
> he finds the source

Of great value in our work.
