### ISSUE TITLE
ACC vs MW corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#363]
Examining the newly generated faultfinder output at https://github.com/drdhaval2785/SanskritSpellCheck/blob/master/AllvsMW/dictwiseerrors3-table.html after a lot of corrections have already been done.

UPDATE
Summarily these are the corrections.
READY to be installed.
```
ACC:uTAnadvAdaSIvratakalpa:utTAnadvAdaSIvratakalpa:t
ACC:OdIcryaprakASegotrapravaroccAraH:OdIcyaprakASegotrapravaroccAraH:t
ACC:gaNgAnandakavondra:gaNgAnandakavIndra:t
ACC:gOtamIgaNgAmAhatmya:gOtamIgaNgAmAhAtmya:t
ACC:vESvatmyarahasya:vESvAtmyarahasya:t
ACC:tkAvAda:ktvAvAda:t
```

Two questions to be answered.
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/363#issuecomment-326789749 and https://github.com/sanskrit-lexicon/CORRECTIONS/issues/363#issuecomment-326790058

**Comment by drdhaval2785** [comment]
```
ACC:uTAnadvAdaSIvratakalpa:utTAnadvAdaSIvratakalpa:t
```
![capture](https://user-images.githubusercontent.com/5755132/30001363-a4958c3e-90a9-11e7-8aa2-0d0dc77f545b.png)

**Comment by drdhaval2785** [comment]
Not actually a correction submission, but a question for @funderburkjim 
Currently the headword is BaNgIBIra,
Should it not be BaNgIBIradIkzita?

![capture](https://user-images.githubusercontent.com/5755132/30001392-42df9f10-90aa-11e7-926a-58fdb9883f96.png)

**Comment by drdhaval2785** [comment]
@zaaf2 may like to see the referred works and decide whether it is 'molha' or 'mohla'.
Either of these two entries is wrong.
See

![capture](https://user-images.githubusercontent.com/5755132/30001420-44a4f862-90ab-11e7-9089-2af9f1436838.png)

and

![capture](https://user-images.githubusercontent.com/5755132/30001423-52d5a846-90ab-11e7-945e-7d4ac4c7b457.png)

**Comment by drdhaval2785** [comment]
ACC:OdIcryaprakASegotrapravaroccAraH:OdIcyaprakASegotrapravaroccAraH:t

crya -> cya

OdIcya is a name of gotra.

![capture](https://user-images.githubusercontent.com/5755132/30001448-44f75570-90ac-11e7-83ee-2deb0266522c.png)

**Comment by drdhaval2785** [comment]
ACC:gaNgAnandakavondra:gaNgAnandakavIndra:t

kavIndra

![capture](https://user-images.githubusercontent.com/5755132/30001456-79341cba-90ac-11e7-9715-4fd31bf902f5.png)

**Comment by drdhaval2785** [comment]
ACC:gOtamIgaNgAmAhatmya:gOtamIgaNgAmAhAtmya:t

mAha -> mAhA

![capture](https://user-images.githubusercontent.com/5755132/30001464-bd12f85c-90ac-11e7-9d23-0f3531aa6a0a.png)

**Comment by drdhaval2785** [comment]
ACC:vESvatmyarahasya:vESvAtmyarahasya:t

vESva->vESvA

**Comment by drdhaval2785** [comment]
ACC:tkAvAda:ktAvAda:t

Wrong orthography.

Looks like this.
![capture](https://user-images.githubusercontent.com/5755132/30001490-94e9adb6-90ad-11e7-86dc-8c3fcd0c0e53.png)

Actually should look like this.
![capture](https://user-images.githubusercontent.com/5755132/30001492-a95f6ca4-90ad-11e7-8d4a-bf8f8ca8791a.png)

**Comment by drdhaval2785** [comment]
This completes ACC corrections based on MW as base.

**Comment by zaaf2** [comment]
I could not find these works. Perhaps मोल्ह and मोह्ल are just alternative forms. We find the same variation in other words. Examples from M-W:

सल्ह [p= 1190] : m. N. of a man (also written सह्ल)
कल्हण [p= 263] : m. (also spelt कह्लण), N. of the author of the राज-तरंगिणी.
बिह्लण [p= 732] : incorrect for बिल्हण. 
सह्ल [p= 1196] : सह्लण » सल्ह्°
बाह्लीक [p= 729,3]	n. = बाल्हिक

**Comment by drdhaval2785** [comment]
Maybe. Then let these two words survive, unless we get some more concrete data.

**Comment by gasyoun** [comment]
@funderburkjim all the series closable?

**Comment by funderburkjim** [comment]
> all the series closable?   

I'm unsure if something is needed from me on this.

**Comment by gasyoun** [comment]
> I'm unsure if something is needed from me on this.

The question remains if it has been implemented. There is no your comment here, which is strange and suspicious.

**Comment by gasyoun** [comment]
@drdhaval2785 so all are installable, but still not installed?
