### ISSUE TITLE
AP90 vs MW corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#365]
READY to install
only one correction.
```
AP90:pazRi:pfzRi:t
```

It is a unique case where the error has entered due to wrong entry of Alternate headword.
![capture](https://user-images.githubusercontent.com/5755132/30001612-4fc60dee-90b0-11e7-9e98-81941e3bc8c1.png)

See the digitization also

![ca](https://user-images.githubusercontent.com/5755132/30001614-634b64b8-90b0-11e7-85f7-f9a8fba6657b.png)

**Comment by funderburkjim** [comment]
The correction here has to be made in file pywork/hwextra/ap90_hwextra.txt.  I have manually made
this correction:
```
<L>19306.01<pc>0719-b<k1>pfzRi<k2>pfzRi<type>alt<LP>19306<k1P>pfSni<ln1>162162<ln2>162175
```

Please EXCLUDE this in  standard correction file.

**Comment by drdhaval2785** [comment]
Excluded from standard correction file.
