### ISSUE TITLE
VCP vs MW corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#376]
```
VCP:UdDvaka:UrdDvaka:p
VCP:UrdDakaca:UrDvakaca:p
VCP:UrdDakaRWa:UrDvakaRWa:p
VCP:UrdDakarmman:UrDvakarmman:p
VCP:UrdDamAna:UrDvamAna:p
```

Alternates have been added erroneously.
One is UrDva and the other is UrdDva.
No `^UrdDa` anywhere.

![capture](https://user-images.githubusercontent.com/5755132/30002196-d426f14c-90c0-11e7-8b42-5741a595c014.png)

**Comment by funderburkjim** [comment]
> VCP:UdDvaka:UrdDvaka:p

This is an error in alternate headword.  Now corrected in vcp_hwextra.txt.   
Will await other corrections before fully installing.
