### ISSUE TITLE
ACC vs PW submissions

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#381]
```
ACC:kfzRAzwampudyApana:kfzRAzwamyudyApana:p
ACC:guRRamandAramaYjarI:guRamandAramaYjarI:t
ACC:jayutuNgodaya:jayatuNgodaya:p
ACC:SAmbavyagfhmasUtra:SAmbavyagfhyasUtra:t
ACC:Agamatatt:AgamatattvavilAsa:t
```
![capture](https://user-images.githubusercontent.com/5755132/30002418-99339c88-90c6-11e7-9fc3-6a77b673816b.png)
![capture](https://user-images.githubusercontent.com/5755132/30002424-c00236ee-90c6-11e7-98f6-962f78dcda16.png)
![capture](https://user-images.githubusercontent.com/5755132/30002429-d8ce19fe-90c6-11e7-8773-1e157d9ddb2b.png)
![capture](https://user-images.githubusercontent.com/5755132/30002452-95e9e45a-90c7-11e7-9a41-86df322d793d.png)

**Comment by drdhaval2785** [comment]
There is one more entry which is Agamatatt
It ends abruptly.
The book is blank at that place.
@zaaf2 may like to read and correlate and find the exact work being referred to.
Then we may add this headword.
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=ACC&key=Agamatatt

![capture](https://user-images.githubusercontent.com/5755132/30002463-e43570a2-90c7-11e7-8551-222e67087592.png)

**Comment by zaaf2** [comment]
आगमतत्त्वविलास (this same work is mentioned in the next line).

**Comment by drdhaval2785** [comment]
Incorporated.

**Comment by gasyoun** [comment]
> आगमतत्त्वविलास (this same work is mentioned in the next line).

Thanks!
