### ISSUE TITLE
'nh' in PUI

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#385]
Barring a single item sEnhlAda (It should also have been sEMhlAda, but I give it grace of convention), all others are wrong words.
There is no grammatical rule which allows this transposition.
There is one phonetic rule which allows such pronounciation, but never in writing.

They need to be corrected from 'nh'->'hn'

	Line 136526: Anhikakrama:PUI
	Line 201243: cidvanhi:PUI
	Line 205243: janhu:PUI
	Line 205244: janhugaRa:PUI
	Line 207460: jAnhavI:PUI
	Line 305929: maDyAnhA:PUI
	Line 340686: vanhi:PUI
	Line 340687: vanhijvAla:PUI
	Line 340688: vanhivAsa:PUI
	Line 340689: vanhivAsinI:PUI
	Line 345141: vAqavavanhi:PUI

**Comment by gasyoun** [comment]
> There is one phonetic rule which allows such pronounciation, but never in writing.

Interesting.

**Comment by drdhaval2785** [comment]
Incorporated in #380 standard file, because it had some of these members.
