### ISSUE TITLE
GST vs VCP corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#400]
```
GST:aparAhla:aparAhRa:t
GST:aparAhlaka:aparAhRaka:t
GST:aparAhlakfta:aparAhRakfta:t
GST:aparAhlatana:aparAhRatana:t
```
![capture](https://user-images.githubusercontent.com/5755132/30004623-835f558a-90f0-11e7-8fa1-ce406410457d.png)

**Comment by funderburkjim** [comment]
> GST:aparAhlakfta:aparARlakfta:t

I think you meant 'hR' rather than 'Rl'
```
GST:aparAhlakfta:aparAhRakfta:t
```
