### ISSUE TITLE
INM vs VCP corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#401]
```
INM:jYAnOttama:jYAnauttama:t
INM:daSalakzaRasamyukta:daSalakzaRasaMyukta:t
INM:lokAnAMkIrtivarDaRaH:lokAnAMkIrtivarDanaH:p
INM:lokaDAtr:lokaDAtf:p
```

hiatus issue
![capture](https://user-images.githubusercontent.com/5755132/30004661-1f6772e6-90f1-11e7-9e3f-85718013e136.png)
![capture](https://user-images.githubusercontent.com/5755132/30004668-4c5581f8-90f1-11e7-914d-cee19c06b4ff.png)
![capture](https://user-images.githubusercontent.com/5755132/30004691-a129efd4-90f1-11e7-9e34-f39e74e51ead.png)
![capture](https://user-images.githubusercontent.com/5755132/30004737-7f452f40-90f2-11e7-907d-e6ca7cc3a026.png)

**Comment by funderburkjim** [comment]
> INM:jYAnOttama:jYAnauttama:t

hiatus 'au' because it's really two words?

**Comment by drdhaval2785** [comment]
Yes.
