### ISSUE TITLE
PUI vs VCP corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#404]
```
PUI:AirAvata:ErAvata:p
PUI:kArtavIryArjuRa:kArtavIryArjuna:t
PUI:tapomUrtI:tapomUrti:t
PUI:gavisTira:gavizWira:p
PUI:SrIpUrtI:SrIpUrti:p
```

Print error
![capture](https://user-images.githubusercontent.com/5755132/30014090-f5c1d914-9167-11e7-86c8-8414b593a6df.png)
The very next entry has correct reading.
![capture](https://user-images.githubusercontent.com/5755132/30014107-07325872-9168-11e7-8901-696cee0dabfb.png)

Print smudge wrongly taken as R.
![capture](https://user-images.githubusercontent.com/5755132/30014226-d6f51252-9168-11e7-9a95-54ab5264e4d0.png)

Print smudge wrongly taken as I. The next item shows that it is I.
![capture](https://user-images.githubusercontent.com/5755132/30014297-25e13b0c-9169-11e7-9806-555d5763167c.png)

Print error. Above and below have 'zW'.
![capture](https://user-images.githubusercontent.com/5755132/30014349-5eda5b64-9169-11e7-960d-8a7ec4e16d6c.png)

**Comment by drdhaval2785** [comment]
Questionable correction.
The macron over is slanting. A smudge. @zaaf2 may look the word referred and decide.
```
PUI:SrIpUrtI:SrIpUrti:p
```
![capture](https://user-images.githubusercontent.com/5755132/30014548-794933ac-916a-11e7-8666-5f0b1968cbb5.png)

**Comment by zaaf2** [comment]
I could not find the work Cintāmaṇi gṛha (the Digital Library of India is currently off air), but I have no doubt Śrīpūrtī is the correct form. It is an adjective tatpurusha compound, here used as a feminine proper noun. पूर्त is the passive participle of पॄ ‘to fill’. The feminine of adjectives ending in -a are either ā (more common) or ī.

> Whether a masc.-neut. stem in a shall form its feminine in ā or in ī is a question to be determined in great part only by actual usage, and not by grammatical rule. (Whitney’s Grammar §332 a).

**Comment by SergeA** [comment]
> I could not find the work Cintāmaṇi gṛha (the Digital Library of India is currently off air), but I have no doubt Śrīpūrtī is the correct form. It is an adjective tatpurusha compound, here used as a feminine proper noun. पूर्त is the passive participle of पॄ ‘to fill’. The feminine of adjectives ending in -a are either ā (more common) or ī.

The forms of p.p.p. usually are used with -ā feminine termination and the idea of -ī termination seems weird to me. Anyhow the referenced source Brahmanda-purana 4-36-26 give for this word short -i:
श्रीपूर्तिश्च महादेवी

![zripurtizca_mahadevi](https://user-images.githubusercontent.com/6435011/30026697-b2d6d518-9186-11e7-8a81-52bddb03a39a.png)

**Comment by funderburkjim** [comment]
### ErAvata  and IAST weakness.

*This is a minor rant -- feel free to ignore :)* 

The IAST as described in [wikipedia](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration),  has a weakness with regard to distinguishing a diphthong from a hiatus.   It uses 'ai' as the dipthong  (SLP1 = E).  So it has no way to write a hiatus 'a-i'.   SImilar problem with 'au'.

Possibly for this reason, some authors appear to augment the standard IAST by putting macrons over either the 'a' or the 'i'.   The interpretation of this usage is problematic (non-standard).  For hiatus with 'a-u' we often see 'a + u-diaresis = u-umlaut)'.

Thus the use above of (A-macron + i) or (A + i-macron) is probably not so much a bug (print error) as an
undocumented feature.

**Comment by funderburkjim** [comment]
> pUrti or pUrtI ?

I vote for short-i pUrti -- it is in MW as a feminine.

**Comment by drdhaval2785** [comment]
I change it to SrIpUrti now.

**Comment by zaaf2** [comment]
I was wrong. I did not consider पूर्ति, with the suffix -ति, which forms feminine words expressing an action. As an example we have a similar formation with भूति (f.). Although the vast majority of proper names ending in भूति are masculine, we have देवभूति (M-W: f. the Ganges of the sky L. ) and महाविभूति (f. the great goddess of welfare, लक्ष्मी).

**Comment by gasyoun** [comment]
> Although the vast majority of proper names ending in भूति are masculin

Jim's MW with grammar data would be an easy way to add more examples of the same kind.

**Comment by funderburkjim** [comment]
The work such as [lexnorm-all.txt](https://github.com/funderburkjim/MWlexnorm/blob/master/step1b/lexnorm-all.txt) may be what Marcis is referring to.  
[lexnorm-all_BUti.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/files/1286089/lexnorm-all_BUti.txt) is an extract of mw words ending in BUti (72 of them), and showing gender information in last column.

**Comment by zaaf2** [comment]
I was referring to the *vast majority* within the universe of names of persons and gods, not of words in general. The list above includes both.
