### ISSUE TITLE
PW vs VCP corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#406]
```
PW:tadAnIdugDa:tadAnIMdugDa:t
PW:prAtIvoDIputra:prAtIboDIputra:t
PW:anuzwupkArmIRa:anuzwupkarmIRa:t
PW:Adityozwi:Adityezwi:t
PW:iwkara:iwcara:t
PW:immAdiBAratyAcarya:immAdiBAratyAcArya:t
PW:kiknisa:kiknasa:t
PW:tfzucyuvas:tfzucyavas:t
PW:vajrodrata:vajrodgata:t
PW:SilpojIvin:SilpopajIvin:t
PW:saMgrAmaBUrDan:saMgrAmamUrDan:t
PW:samaraBUrDan:samaramUrDan:t
```
![capture](https://user-images.githubusercontent.com/5755132/30023899-05f2cbe6-918f-11e7-8a85-5d6a89ddbe26.png)
![capture](https://user-images.githubusercontent.com/5755132/30023932-346dfee6-918f-11e7-9385-0a10d9b86ee4.png)
![capture](https://user-images.githubusercontent.com/5755132/30024005-7ea82a86-918f-11e7-869c-a4e0bf636460.png)
![capture](https://user-images.githubusercontent.com/5755132/30024117-fe248250-918f-11e7-90bf-631f369b6987.png)
This reading is also confirmed by PWG.
![capture](https://user-images.githubusercontent.com/5755132/30024211-597582a8-9190-11e7-86b3-f15a7eaf060a.png)
![capture](https://user-images.githubusercontent.com/5755132/30024267-97331718-9190-11e7-8455-ad0b0570c595.png)
![capture](https://user-images.githubusercontent.com/5755132/30024362-0dc5ecb6-9191-11e7-8988-95ff61d9e392.png)
![capture](https://user-images.githubusercontent.com/5755132/30024442-77d1cdd2-9191-11e7-8fbc-d5d2dfd0d0a8.png)
![capture](https://user-images.githubusercontent.com/5755132/30028914-a2212cb4-91a4-11e7-9e46-aaf7f1da4dc0.png)
![capture](https://user-images.githubusercontent.com/5755132/30029117-754d6d32-91a5-11e7-8bea-c077876b0079.png)
![capture](https://user-images.githubusercontent.com/5755132/30029180-d2d6b83c-91a5-11e7-917d-5fd606822dfb.png)
![capture](https://user-images.githubusercontent.com/5755132/30029210-f4319e7a-91a5-11e7-8a9d-f1c39c0756c3.png)

**Comment by drdhaval2785** [comment]
![capture](https://user-images.githubusercontent.com/5755132/30025507-7ccef99a-9196-11e7-98c1-d59ebfb155a0.png)

I am not sure whether it is vajrodrata or vajrodgata.
My hunch is that it is vajrodgata.
@zaaf2 may like to verify.

**Comment by SergeA** [comment]
> My hunch is that it is vajrodgata.

vajrodgato nāma samādhiḥ
http://www.dsbcproject.org/canon-text/content/42/400

**Comment by drdhaval2785** [comment]
Thanks @SergeA. That helps.
