### ISSUE TITLE
SHS vs VCP corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#408]
```
SHS:pARokaraRa:pARIkaraRa:t
SHS:mEyuna:mETuna:p
SHS:vfDAGAta:vfTAGAta:t
SHS:mfgE:mfgErvvAru:t
SHS:uDmAna:udDmAna:p
SHS:kawiSfNkalA:kawiSfNKalA:t
SHS:girimrallikA:girimallikA:t
SHS:daRqatAmro:daRqatAmrI:t
SHS:dAprayitvA:dApayitvA:t
SHS:DvajotyAna:DvajotTAna:t
SHS:nESreyasika:nEHSreyasika:p
SHS:pApnAn:pApman:t
SHS:puttapOtrIRa:puttrapOtrIRa:p
SHS:maDurAmnaka:maDurAmlaka:t
SHS:apaNkta:apANkta:t
SHS:patryAwa:patnyAwa:t
```

![capture](https://user-images.githubusercontent.com/5755132/30034501-a064d8ec-91bf-11e7-8f84-d30baa4613de.png)

Print error
![capture](https://user-images.githubusercontent.com/5755132/30034619-1db08512-91c0-11e7-98ad-2312959aecae.png)
Print error
![capture](https://user-images.githubusercontent.com/5755132/30034624-2792aac4-91c0-11e7-8565-cf6f2d896880.png)

Wrong end of headword before a bracket.
![capture](https://user-images.githubusercontent.com/5755132/30069122-6dad4510-927d-11e7-8057-deb46ac80441.png)

The explanation reading will convert to udDmAna and not uDmAna.
![capture](https://user-images.githubusercontent.com/5755132/30069196-a821aae2-927d-11e7-8b76-25cd98d3604c.png)

![capture](https://user-images.githubusercontent.com/5755132/30069250-dcf79a88-927d-11e7-88b4-d7dec48d8b8d.png)

![capture](https://user-images.githubusercontent.com/5755132/30069271-ede56794-927d-11e7-8c71-3e00b59a74e4.png)

![capture](https://user-images.githubusercontent.com/5755132/30069548-9c9de6ee-927e-11e7-867e-8a4819e22b42.png)

![capture](https://user-images.githubusercontent.com/5755132/30069554-a37cffd6-927e-11e7-9b74-c6938b62965f.png)

![capture](https://user-images.githubusercontent.com/5755132/30069596-ca574d3c-927e-11e7-9f8f-8a0e817d9734.png)

Print error. Explanation has H. Alphabetic ordering also mandates nEHSreyasika.
![capture](https://user-images.githubusercontent.com/5755132/30070059-ef91dd14-927f-11e7-9ae0-4bc307bbf092.png)

Print error. It is in between two 'puttra'.
![capture](https://user-images.githubusercontent.com/5755132/30070315-b18aaa40-9280-11e7-9de6-659e05dbecb2.png)

amla is sour.
![capture](https://user-images.githubusercontent.com/5755132/30070543-5fee29d6-9281-11e7-85df-b56ca423984e.png)

A is smudged.
![capture](https://user-images.githubusercontent.com/5755132/30070588-8084b62e-9281-11e7-84a3-5288634a811d.png)

patnI is wife. So word for harem here is patnyAwa, corroborated by explanation.
![capture](https://user-images.githubusercontent.com/5755132/30070679-dbee59b6-9281-11e7-9da4-a7b82f15b527.png)

**Comment by drdhaval2785** [comment]
A question for @SergeA or @zaaf2 
The word is pApman / pApmAn or something else?
Ligature is definitely not known to me.
And it is not surely pApnAn (as currently shown in dictionary digitization).
![capture](https://user-images.githubusercontent.com/5755132/30070183-4bde8658-9280-11e7-9027-e7cfac83a684.png)

**Comment by SergeA** [comment]
> The word is pApman / pApmAn or something else?

I think it is
पाप्मन् m. (-प्मा)
pāpman m. (-pmā)
(in the brackets it is given Nom. form)
Badly printed low म or print error with न instead of म.

**Comment by gasyoun** [comment]
> BTW the word puttrapautra shows orthographic inconsistency with double tt and single t of the same root.

As bad as can be...
