### ISSUE TITLE
Std file for dicts vs VCP corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#410]
#395 to #408
```
MW72:anuArabDa:anvArabDa:t
MW72:anuAramBa:anvAramBa:t
MW72:apaej:apej:t
MW72:apAkaeman:apAkarman:t
PUI:AirAvata:ErAvata:p
GRA:aSvesita:aSvezita:t
PWG:AjunAvaka:ArjunAvaka:t
CAE:kenezitopanizada:kenezitopanizad:p
INM:jYAnOttama:jYAnauttama:t
PW:tadAnIdugDa:tadAnIMdugDa:t
PWG:nAqodBava:nIqodBava:p
SHS:pARokaraRa:pARIkaraRa:t
PW:prAtIvoDIputra:prAtIboDIputra:t
SHS:mfgE:mfgErvvAru:t
SHS:mEyuna:mETuna:p
SHS:vfDAGAta:vfTAGAta:t
SCH:vfsIdaRqa:vfzIdaRqa:t
PUI:SrIpUrtI:SrIpUrti:t
SCH:ananravAya:ananvavAya:t
PW:anuzwupkArmIRa:anuzwupkarmIRa:t
CAE:aparAhla:aparAhRa:t
CCS:aparAhla:aparAhRa:t
GST:aparAhla:aparAhRa:t
GST:aparAhlaka:aparAhRaka:t
GST:aparAhlakfta:aparAhRakfta:t
GST:aparAhlatana:aparAhRatana:t
MW72:apicya:apIcya:t
MW72:aBimarDin:aBimardin:t
MW72:aBisaNgf:aBisaNgF:t
PWG:arDumuzwi:arDamuzwi:t
BOP:AkANGA:AkANkzA:t
PW:Adityozwi:Adityezwi:t
PW:iwkara:iwcara:t
PW:immAdiBAratyAcarya:immAdiBAratyAcArya:t
SHS:uDmAna:udDmAna:p
SHS:kawiSfNkalA:kawiSfNKalA:t
CAE:kanakAjja:kanakAbja:t
BOP:kANGA:kANkzA:t
PUI:kArtavIryArjuRa:kArtavIryArjuna:t
PW:kiknisa:kiknasa:t
PUI:gavisTira:gavizWira:p
SHS:girimrallikA:girimallikA:t
CCS:gfhaBArtar:gfhaBartar:t
PUI:tapomUrtI:tapomUrti:t
PW:tfzucyuvas:tfzucyavas:t
PWG:truwyavayaba:truwyavayava:t
SHS:daRqatAmro:daRqatAmrI:t
INM:daSalakzaRasamyukta:daSalakzaRasaMyukta:t
SHS:dAprayitvA:dApayitvA:t
SHS:DvajotyAna:DvajotTAna:t
PWG:nirgOrva:nirgOrava:t
CCS:nirnikti:nirRikti:t
SCH:nfjvAtA:nfjvAlA:t
SHS:nESreyasika:nEHSreyasika:p
SHS:pApnAn:pApman:t
SHS:puttapOtrIRa:puttrapOtrIRa:p
CCS:pralhAda:prahlAda:p
CCS:pralhAdana:prahlAdana:p
CCS:pralhAdin:prahlAdin:p
PWG:prazyarza:pratyarza:p
PWG:BAdvAjI:BArdvAjI:p
MCI:BIsmaparvan:BIzmaparvan:t
SHS:maDurAmnaka:maDurAmlaka:t
SCH:mIDvaMs:mIQvaMs:p
PWG:yOTyaM:yOTya:t
INM:lokAnAMkIrtivarDaRaH:lokAnAMkIrtivarDanaH:p
PWG:lozwAnI:lostAnI:t
PW:vajrodrata:vajrodgata:t
BOP:SiNGa:SiNG:t
PW:SilpojIvin:SilpopajIvin:t
PUI:SrIpUrtI:SrIpUrti:p
MW72:saNgf:saNgF:p
PW:saMgrAmaBUrDan:saMgrAmamUrDan:t
MW72:sanaraqvipa:sanaradvipa:t
PW:samaraBUrDan:samaramUrDan:t
SHS:apaNkta:apANkta:t
PWG:ArDya:ArGya:t
PWG:natsTa:tatsTa:t
SHS:patryAwa:patnyAwa:t
PWG:Batrya:Bavya:t
INM:lokaDAtr:lokaDAtf:p
BOP:kANGin:kANkzin:t
CCS:aparAhla:aparAhRa:t
```

**Comment by drdhaval2785** [comment]
@funderburkjim 
Now I will wait till all corrections till now are incorporated and sanhw1 is regenerated.
Now I feel that the method has been exhausted for low hanging fruits.
The work is tedious for comparision to other dictionaries and less fruitful.

**Comment by gasyoun** [comment]
> Now I feel that the method has been exhausted for low hanging fruits.

1 to many comparisons over? Now many vs many left over, Dhaval?

**Comment by funderburkjim** [comment]
I want to be sure I have all the corrections before starting.

Currently, I am aware of these sources:
* The list in this comment
* The list in #386 
* The list in #394 
* The list in #380 

@drdhaval2785  Do these four lists cover everything that needs to be installed?

**Comment by drdhaval2785** [comment]
Yes. These four lists have all the corrections. Confirmed.

**Comment by funderburkjim** [comment]
> SHS:pARokaraRa:pARIkaraRa:t

I think `pAROkaraRa`  (confirm MW, WIL)
SHS:
```
pARokaraRa¦ 
n. (-RaM) Marriage.
E. pARo with the hand, and karaRa making. [L=24278]    [typo: also pARo -> pARO  (loc. of pARi)
```

**Comment by funderburkjim** [comment]
### Installed

The corrections from the 4 lists are installed.

A few variations from the suggested solutions were made, and noted in comments appearing in this and related issues.

Here's an approximate summary of the changes, orgarnized by dictionary:
```
acc 13
ap   2
bop  4
bur  1
cae  6
ccs  7
gra  2
gst  5
inm  5
mci  2
mw72 13
pd   1
pe   2
pui 22
pw  14
pwg 12
sch  5
shs 18
skd 1
vei 2
wil 3
yat 5
vcp 2
```

**Comment by funderburkjim** [comment]
#### Technical comment on changing headwords in dictionaries converted to *meta-line* form.

Changing a headword spelling in one of the dictionaries converted to the meta-line format requires
a change in *two* lines of the digitization X.txt:
* One change is in the 'meta-line' line
* Another change is in the first line of the entry (the line of the digitization just *after* the 'meta' line.

For example, consider the correction of the ACC dictionary: `ACC:Agamatatt:AgamatattvavilAsa:t`.
Here are the two change transactions for acc.txt.
```
; L=30136: Agamatatt -> AgamatattvavilAsa # typo # 
; ------ FIRST change: to meta-line ------
134093 old <L>30136<pc>1-773,2<k1>Agamatatt<k2>Agamatatt{??}
134093 new <L>30136<pc>1-773,2<k1>AgamatattvavilAsa<k2>AgamatattvavilAsa
; ------ SECOND change: to next line of acc.txt  -----------
134094 old {#Agamatatt{??}#}¦ {??} tantr. by Raghunātha Tarkavāgīśa.
134094 new {#AgamatattvavilAsa#}¦ {??} tantr. by Raghunātha Tarkavāgīśa.
```
This situation was handled by changing the transaction generation program, so it would generate the
two transactions when a dictionary was recognized as in meta-line format.

#### Correcting an error in alternate headword
A third factor is when the error is in the separate list of alternate headwords for a dictionary.
For instance, in VCP, one correction is `VCP:ttri:attri:p`.

Here, there was no change required in the digitization vcp.txt, but rather the error was in vcp_hwextra.txt,
for this alternate spelling of headword 'atri'
```
old:
<L>1091.1<k1>ttri<k2>ttri<type>alt<LP>1091<k1P>atri
new:
<L>1091.1<k1>attri<k2>attri<type>alt<LP>1091<k1P>atri
```

**Comment by funderburkjim** [comment]
I think this and the several related issues can be closed now, but will leave the honors to @drdhaval2785 .
