### ISSUE TITLE
Trial for finding errors in AE headwords

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#411]
Just to document that I tried finding out words not found in pyenchant dictionary and also abnormal trigrams of AE headwords.
The output shows that there is not much to be gained by looking at it.
The headwords are majorly correct.
https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/english has the code and data.

**Comment by gasyoun** [comment]
> The output shows that there is not much to be gained by looking at it.

Spent 20 minutes checking. Lot's of words I do not know, but Google does.

**Comment by drdhaval2785** [comment]
Closing. Not worthwhile to pursue.
