### ISSUE TITLE
MW: SriNg print error for SfNg

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#412]
In three words, a spelling  including `śriNg` was changed to `śṛṅg`.  (ri -> ṛ).

These are all changes to the print, so I'm mentioning here so others may review and alert me if these
corrections are wrong.

#### Case 1
(H1B) a-kṣatā : f. a virgin Yājñ.  [L=546]
f. N. of a plant, karkaṭaśriṅgī or kaṅkaḍaśriṅgī [L=547]
![image](https://user-images.githubusercontent.com/6393033/32637605-d2198b56-c588-11e7-8278-216665b62514.png)

#### Case 2
karkaṭā*hvā : f. gall-nut (cf. śriṅgī above ) Bhpr.  [L=44674]
(the referenced word)
karkaṭa-śṛṅgī : f. gall-nut (an excrescence on Rhus Succedana) Suṡr.  [L=44667]
![image](https://user-images.githubusercontent.com/6393033/32637705-669c36de-c589-11e7-9136-207d08a6b2b9.png)

Note that the referenced word shows print ``śriNga` -- this has previously been changed to `śṛṅga` in the digitization.

#### Case 3
mallikā*rjuna-śriṅga [p= 793] : n. N. of a place Cat.  [L=158987]

![image](https://user-images.githubusercontent.com/6393033/32637779-c776e7d8-c589-11e7-958e-a63178cc4a42.png)

**Comment by SergeA** [comment]
There is only word śṛṅga, so these examples look like print errors with missing underdots.
PW confirms karkaṭa-śṛṅga & mallikārjuna-śṛṅga with ṛ.

**Comment by funderburkjim** [comment]
Thanks for confirm.

Will document as print changes.
