### ISSUE TITLE
Improve MW abbreviation markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#416]
### the problem
In a correction form submission, @gasyoun  noted that some of the standard MW abbreviations do not
have tooltips in the displays.  

Here is the list of [MW abbreviations](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwab/mwab_input.txt).

In order for a tooltip X to display, the digitization must be coded as `<ab>X</ab>`.  

Thus, for any  tooltip abbreviation X , we are searching for places in the digitization where the
markup is missing.

### A search algorithm
For a given X,  we search for a few variations from X in mw.txt.  A specific example helps to explain
the details of the algorithm used in this round of corrections.  Consider the abbreviation 'superl.'

The algorithm looked for instances of ' superl'  (a blank before the initial 's'), and various things after
the final 'l'.  And made changes as indicated.
* ' superl.'   => ` <ab>superl.</ab>`
* ' superl,'  (comma instead of period) => ` <ab>superl.</ab>`
* ' superl '  (period missing, followed by space)  => ` <ab>superl.</ab> `
* ' superl)'  (paren instead of period) =>  ` <ab>superl.</ab>)`

### Programmatic helpers
Two programs were used:
* filter_simple.py   count the occurrences of each of the variations, for each of the abbreviations.
   * The count is useful, because it helps identify instances where the algorithm generates many
      false positives.   For example, consider the abbreviation 'sing.' (singular).  Applying the third
      rule of the algorithm has us searching for ' sing '.  However, 'sing' is a verb in English and appears
      in many entries (like gE, stu, etc.) as part of the definition; we don't want to mark such instances
       as abbreviations.
* make_change_simple.py
  This program generated correction transactions.  This eliminates some of the repetitive work of
  manual searching and changing records of mw.txt.

Because of the issue of false positives, many of the manually generated corrections were examined by
eye;  the hope is that very few erroneous corrections passed this quality control check.

### Results
About 1000 corrections were made.  

These are currently in the dev version of MW, 
such as [simple-search DO](http://198.199.88.166/cologne/apidev/simple-search/v1.0/list-0.2s_DO.html).

For example under headword DarmajYatama (slp1), 
*  Cologne display, unrevised - no tooltip for 'superl'
   ![image](https://user-images.githubusercontent.com/6393033/40254722-81a33e96-5ab2-11e8-8c5c-03a207dd3486.png)
*  DO display, revised -- has tooltip for 'superl'
   ![image](https://user-images.githubusercontent.com/6393033/40254738-95921ac6-5ab2-11e8-9434-7d1d26a53a0a.png)

### Remaining problems?
It is likely that there are some systematic patterns other than those used by the algorithm above, by
which additional abbreviation miscodings can be identified and corrected.  These can be dealt with
as they are noticed.

**Comment by gasyoun** [comment]
> About 1000 corrections were made.

Great batch of digital punctuation errors.

> It is likely that there are some systematic patterns 

Can't think anything more of. Only reading the dictionary will give more.

> 2014/mwaux/mwab/mwab_input.txt

Is this the latest file? It contains bad coding (Ä€., A1di-p., PrÄk.)

What is <UNMARKED>, <INFER/>?

> Rec.	<id>Rec.</id> <disp> ?? </disp> <INFER/> Def? hw=aByAkAram

Means we have no clue what Rec. means and `aByAkAram` contains it as a sample?

**Comment by funderburkjim** [comment]
The bad coding is an artifact of looking at the text file in a browser. The file is utf-8 encoded, but the browser view doesn't know that.  You could download via curl and then view with local editor:
```
curl http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwab/mwab_input.txt -o mwab_input.txt
```

> Rec. Rev.

These appear to be essentially notes of unresolved abbreviations -- they are not in the printed list.
The headword note is a reminder of where this was noted.

If anyone decides what these mean, then the expansion for Rec., Rev. can be added.
