### ISSUE TITLE
STC capitalization of Brâhmane

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#418]
Caujolle made this suggestion in a correction form response:

```
 Moreover i noticed that brâhmane (Brahmin) is here written with a capital. This is wrong, in French there 
should not be a capital on brahmane -brahmane is most commun, brâhmane is of course also correct 
(and generally has my preference)-. In French, only nationality is marked by a capital, that is, a French 
person, un Français; but French language, français. A Christian, un chrétien, etc. So of course, a Brahmin, 
un brahmane. That is a mistake the authors made in this book, without doubt influenced by the Indian 
English which uses a lot of capitals. Myself i liberated myself from this influence quite recently, in the 
beginning i unduly put capitals in my French translations, now they are much better, in a much better 
French.
```
So the argument is that Brâhmane refers to a group of people but not to a nationality; hence, it should
not be capitalized.

There are 229 instances of `Brâhma` in stc.

Should we change?
* Is Caujolle's reasoning right in terms of modern French language conventions?
* If it is right, should we make this print change to STC to bring it into line with such conventions?

@sanskritisampada  What's your opinion here?

Anyone else have enough knowledge of French to comment?

**Comment by Sonnetag** [comment]
All,
I want to reply as a person who is translating Vedic Sanskrit texts into 
English using Monier-Williams Sanskrit English Dictionary.

While Caujolle can choose what words would be translated into French 
with a capital or not following the conventions of French. However, I do 
not believe it is wise to change Dictionary itself. If the 
Sanskrit-French Dictionary is the translation of the Monier-Williams 
original Sanskrit-English Dictionary, I would leave the French words 
with a capital as they are in Monier-Williams.

Sincerely,
Youngsinn

**Comment by funderburkjim** [comment]
### The Burnouf convention

In The Burnouf dictionary  (Burnouf Dictionnaire Sanscrit-Français), of 1866,  `brâhmane` appears uncapitalized.

**Comment by Sonnetag** [comment]
If that is the case, then it is different story.
Youngsinn

**Comment by gasyoun** [comment]
Burnouf argument is a serious one. But 229 print errors do not make sense. It's a matter of convention. I understand that in this case it's a misconvention, but guess would leave it as is.

**Comment by funderburkjim** [comment]
### Huet's convention

In Gerard Huet's [dictionary](http://sanskrit.inria.fr/DICO/1.html#agnihotra),  the spelling is 'brahmane'.
This uses lower-case 'b' , but has the additional difference of no circumflex over the first 'a'.

**Comment by funderburkjim** [comment]
### Rules for Capital letter in French:

@sanskritisampada  recently sent me these rules:


Règle 6 : les noms de fonctions, titres et charges civiles sont toujours en minuscules

Règle 7 : le terme caractérisant une fonction, un titre ou une charge civile prend toujours une majuscule
	Exemples : le ministre de l’Environnement, l’archevêque de Lyon, le Président

Règle 15 : les noms de peuples ou d’habitants prennent toujours une majuscule
	Exemples : les Français, les Canadiens, les Tunisiens, les Celtes, les Berbères, les Blancs, les Noirs, les Juifs (en tant que peuple).

Règle 16 : en revanche on n’utilise pas de majuscule pour les groupes religieux, adeptes d’une doctrine ou d’une idéologie
	Exemples : les musulmans, les chrétiens, les juifs, les communistes, les capitalistes…

(@sanskritisampada -- what is the source?)

Our example of brâhmane seems to fall under rule 16, so non-capitalization would be indicated.

So Stchoupak's Brâhmane seems to vary from current French Grammar;  nonetheless, I think I'll leave
this quirk within the Cologne digitization for now.
