### ISSUE TITLE
Feature request: A way to directly link to every dictionary entry

### ISSUE THREAD

**Issue by vniku** [sanskrit-lexicon/CORRECTIONS#423]
It would be nice if there was some way to directly link to an entry. Ideally, something of the form, https://www.sanskrit-lexicon.uni-koeln.de/MW/144239 (the last one being the entry's ID) would lead to a page which would list the entries 144239 and 144239.1, i.e., the whole of the following

```
(H1)  [p= 727,2]  बाढ   mfn.  (or बाळ्ह) (√ बंह्; cf.  Pān v, 3, 63 ) strong, mighty (only ibc. and in बाळ्हे ind.), loudly, strongly, mightily, RV.   [ID=144239]
--
(H1C)   बाढम्   ind. (or वाढम्)  assuredly, certainly, indeed, really, by all means, so be it, yes  (generally used as a particle of consent, affirmation or confirmation), MBh. ; Kāv. &c.   [ID=144239.1]
```
One would be able to print this too! (That's another feature request, namely, a way to print the entries!)

Update: OR,
A link of the form https://www.sanskrit-lexicon.uni-koeln.de/MW?q=bAQa would lead to a page containing the above. (the last one being the search term in SLP1)

Thanks.

**Comment by gasyoun** [comment]
> But it seems that the links are not working now.

Hmm, that's something new. @vniku please write details in header, `Feature request` is not a detail and CORRECTIONS is not the place, but COLOGNE is for website related issues.

**Comment by vniku** [comment]
I have opened the issue at COLOGNE: https://github.com/sanskrit-lexicon/Cologne/issues/249

**Comment by funderburkjim** [comment]
@drdhaval2785 

servepdf problem solved.  This now works:
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&key=Davala

**Comment by drdhaval2785** [comment]
Thanks Jim.

**Comment by gasyoun** [comment]
Cross-reference: this is tracked as the active issue **sanskrit-lexicon/COLOGNE#249** ("Feature request: A way to link directly to the dictionary entries").

A concrete implementation roadmap is now written up in csl-apidev:

📄 https://github.com/sanskrit-lexicon/csl-apidev/blob/master/doc/cleanurl.md

It proposes a top-level, path-based (no `?q=`) permalink scheme — e.g. `/MW/bAQa`, `/MW/bAQa/2`, `/MW/144239` — all landing on the full listview. Please follow COLOGNE#249 for status and discussion.
