### ISSUE TITLE
STC Ç->Ś and ç->ś

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#430]
Triggered by the suggestion of Caujolle in correction form.
It seems a major change affecting 1146 lines in stc5.txt.

```
Case 24367: 02/20/2019 dict=STC, L= ID=19980, hw=zaka, user=Caujolle
old = ère Çaka (78 de l'ère).
new = ère Śaka (78 de l'ère).
comment = for coherence, the Ç should here be replaced by Ś
```

**Comment by gasyoun** [comment]
> for coherence, the Ç should here be replaced by Ś

As per book?

**Comment by funderburkjim** [comment]
Stchoupak used c-cedilla for palatal sibilant in his version of IAST.   But since  c-cedilla is also used in French words,  it requires extra work to change ç->ś  in Sanskrit words, without introducing mis-spelling of French words.

In other words,  what is needed is a list of all c-cedilla words in Stc,  then a separation of these into Sanskrit and French words, and finally a set of corrections ç->ś  for the Sanskrit words.

The separation into Sanskrit and French words is the labor intensive step.   I've marked this as a bug so
we can revisit.  Sampada may be able to help, since she knows both French and Sanskrit.

**Comment by drdhaval2785** [comment]
Just to help Sampada, the following has been done. (code in pywork/correctionwork/issue-430 folder in Cologne).

words.txt - all words with c-cedilla
sanskrit.txt - words identified as Sanskrit conclusively with manualByLine.txt format
french.txt - words identified by pyenchant package as french conclusively.
doubt.txt - Words which require closer examination whether they need correction or not i.e. neither Sanskrit nor French conclusively.

[doubt.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/files/3366888/doubt.txt)
[french.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/files/3366889/french.txt)
[sanskrit.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/files/3366890/sanskrit.txt)
[words.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/files/3366891/words.txt)

**Comment by drdhaval2785** [comment]
Remaining 11 cases are as follows
```
; FRANÇAIS@}
3 SANSKRIT-FRANÇAIS@} PAR N. STCHOUPAK, L. NITTI ET L. RENOU {%Ouvrage honoré%}
; FRANÇAIST}
8 <H>{TDICTIONNAIRE SANSKRIT-FRANÇAIST}
; intransperçable
16326 {@a-bhedya-@}¦ a. v. à ne pas dénoncer; inséparable <lbinfo n="7"/>; intransperçable.
; çivaïte
21510 {@a-vimukta-@}¦ m. Śiva; n. d'un Tīrtha.  {%°śaiva-%} m. moine çivaïte de
; imperçable
21913 {@a-vedhya-@}¦ a. v. imperçable.
; Çivaïtes
38981 secte particulière de Çivaïtes ; ép. de Śiva ; un des onze Rudra ; {%-ī-%}
; çivaïtes
100388 çivaïtes.
; çivaïte
133869 secte çivaïte.
; Çivaïte
136535 dérivé de Śiva; m. adorateur de Śiva, Çivaïte; nt. bien-être, bonheur.
; Çivaïtes
140178 (chez les Çivaïtes) âme du plus bas degré.
; perçable
157616 <P>{%°bhedya-%} a. v. (perçable avec une aiguille) très dense, massif.
```

Caujolle or Sampada may have a look at them and let us know whether there is any need to change / error in the said lines.

**Comment by drdhaval2785** [comment]
Response from Caujolle regarding doubtful cases is attached herewith
```
FRANÇAIS means French in French

Çivaïte means shaiva in French, so it should be replaced by śaiva or Śaiva, depending on the case

Perçable, imperçable and intransperçable are French words

Paçupati > Paśupati

All cases of Ç. should be replaced by Ś.
```

I am a bit reserved regarding whether to change Çivaïte to śaiva or Śaiva. I vote to keep it as it is. What is your take @funderburkjim and @gasyoun?
Rest resolutions seem fine.

**Comment by drdhaval2785** [comment]
Goth the french word list examined by Caujolle and all are french words. So now the changes are ready to be installed.

**Comment by gasyoun** [comment]
> I am a bit reserved regarding whether to change Çivaïte to śaiva or Śaiva. I vote to keep it as it is. 

I guess she did not meant to change it. Guess she meant `Çivaïte` to `Śivaïte`?

> french word list examined by Caujolle and all are french words. So now the changes are ready to be installed.

Well done, Dhaval. If there is you, there is still hope Cologne will not be doomed.

**Comment by SergeA** [comment]
"Çivaïte" is derived from "Çiva" (शिव). If the spelling "Çiva" is replaced by "Śiva", then  for the sake of consistency "Çivaïte" also needs the same correction. So it will be "śivaïte". (I don't know if here the first letter must be capital or lowercase in French.)
The same is applicable for vishnouïte > viṣṇuïte and other such cases of derived French words.
Perhaps such half-Sanskrit words need a special markup?

**Comment by SergeA** [comment]
> whether to change Çivaïte to śaiva or Śaiva <

Definitely not.

**Comment by drdhaval2785** [comment]
I vote for keeping half-Sanskrit words as they are currently i.e. treat them as French. Only Sanskrit words get converted to Ś from c-cedilla.

**Comment by SergeA** [comment]
In MW we have also such half-Sanskrit words, e.g. **Āraṇyakas** with Sanskrit stem and English ending -s.
BTW, I tried to find in advanced MW "Āraṇyakas" in text, but it gives nothing. Perhaps there is some search/markup conflict here.

**Comment by funderburkjim** [comment]
I vote for Çivaïte -> Śivaïte.

Here are the two instances related to @SergeA's example:

100387:{@bhākta-@}¦ m. adepte de la Bhakti, homme pieux ; pl. sectes vishnouïtes et
100417:<P>{%°purāṇa-%} nt. titre d'un Purāṇa d'inspiration vishnouïte.

Would use viṣṇuïte   (lower-case since vishnouïte is lower).

**Comment by funderburkjim** [comment]
> Āraṇyakas  not found in MW Advanced Search

In the Digitization, Āraṇyakas  appears with markup:
```
<s1 slp1="AraRyaka">Āraṇyaka</s1>s
```
The advanced search uses an extraction (webtc2/query_dump.txt) of the digitization.  The extraction program (webtc2/init_query.py) currently turns `<s1 slp1="AraRyaka">Āraṇyaka</s1>s` into  `āraṇyaka s`.  This is why a substring search for 'Āraṇyaka' will find Āraṇyakas  but a search for the plural form Āraṇyakas  finds no matches.

**Comment by drdhaval2785** [comment]
Installation completed.
