### ISSUE TITLE
MD corrections from faultfinder

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#69]
Only 9 of the headwords from MacDonell's Sanskrit-English dictionary are mentioned
when  (a) selected by faultfinder program as having letter sequences not seen in MW dictionary and 
(b) occuring only in MD dictionary.
```
kxpi:VCV=xpi:MD
apunarvftti:VCCV=arvf:MD
ityE:VCCV=ityE:MD
daDfzvAn:VCCV=fzvA:MD
PeYjaka:VCCV=eYja:MD
bEmbika:VCCV=Embi:MD
riricyAm:VCCV=icyA:MD
SazpIkf:VCCV=azpI:MD
atyuccrita:VCCCV=uccri:MD
```
Of these, the only error found was 

atyuccrita -> atyucCrita
![image](https://cloud.githubusercontent.com/assets/6393033/5787399/ab8815b8-9dca-11e4-94c7-9989964db705.png)

**Comment by gasyoun** [comment]
I've scraped http://dsal.uchicago.edu/dictionaries/macdonell/ and wonder if comparison of both would give same results as SKD and VCH, but I guess it's too much work and too little results in this case. Anyway it seems to be the cleanest file till now.

**Comment by funderburkjim** [comment]
@gasyoun  Can you show a sample of what the scraping looks like? Also, what program did you use for the scraping ?  I like the idea of comparing different digitizations (this has proved useful with Tirupati and Cologne editions of Vacaspatyam).

**Comment by gasyoun** [comment]
Scraping is a folder of .html files that I can turn in an .xls file after. I, actually Anton, my coder, used a paid desktop tool that can scrape every single website around. I like the idea as well, but if I'll provide it now I'll loose you on the headword part, so let me leave it aside for now.
