### ISSUE TITLE
BEN corrections from faultfinder

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#70]
Only 21 of the headwords from Benfey's Sanskrit-English dictionary are mentioned
when (a) selected by faultfinder program as having letter sequences not seen in MW dictionary and 
(b) occuring only in MD dictionary.

This issue examines these 21 cases.

**Comment by funderburkjim** [comment]
1 sPUfja -> sPUrja
![image](https://cloud.githubusercontent.com/assets/6393033/5790142/29e7b024-9e59-11e4-96ec-fcd05c794cac.png)

2 karaBba -> karamba
![image](https://cloud.githubusercontent.com/assets/6393033/5790145/574fdc80-9e59-11e4-8498-7e8799584840.png)

3 gfDru -> gfDnu
![image](https://cloud.githubusercontent.com/assets/6393033/5790149/9073a8ca-9e59-11e4-8a7b-9d8994f77008.png)

4 caramaSErzeka -> caramaSErzika
![image](https://cloud.githubusercontent.com/assets/6393033/5790153/c5f80c70-9e59-11e4-8f89-12a4671c7101.png)

5 tvazwF -> tvazwf
![image](https://cloud.githubusercontent.com/assets/6393033/5790159/fba269b0-9e59-11e4-80d6-969fcc766387.png)

6 DAnuyka -> DAnuzka
![image](https://cloud.githubusercontent.com/assets/6393033/5790164/26d68c60-9e5a-11e4-9b3d-9065b3670fe2.png)

7 nittula -> nicula
![image](https://cloud.githubusercontent.com/assets/6393033/5790168/5f39be74-9e5a-11e4-8f44-7f36cd1ac5ec.png)

8 pUrba -> pUrba NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5790175/85f5e876-9e5a-11e4-8747-d43d94c4a052.png)

9 prayaYyu -> prayajyu
![image](https://cloud.githubusercontent.com/assets/6393033/5790186/c1aee21e-9e5a-11e4-8902-393ba505d19f.png)

10 baRimvaha -> baRigvaha
![image](https://cloud.githubusercontent.com/assets/6393033/5790191/0636bb78-9e5b-11e4-9105-ae531279cb88.png)

**Comment by funderburkjim** [comment]
11 reknas -> rekRas 
[By Sandhi, the 'n' after 'r' becomes 'R', since (in this case) only a vowel and a gutteral intervene.]
![image](https://cloud.githubusercontent.com/assets/6393033/5790222/d560c4ce-9e5c-11e4-8aa1-e665aa18b7af.png)

12 sArpI -> sArpI NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5790225/fd45c43a-9e5c-11e4-8f78-25663d5b5a33.png)

13 syAsla -> syAla
![image](https://cloud.githubusercontent.com/assets/6393033/5790230/376346c4-9e5d-11e4-911f-9b5296895a90.png)

14 aDirjyatA -> aDijyatA
![image](https://cloud.githubusercontent.com/assets/6393033/5790240/6a5f8510-9e5d-11e4-9556-37b3e377ede3.png)

15 ahirbraDra -> ahirbraDna
![image](https://cloud.githubusercontent.com/assets/6393033/5790247/d1e2d750-9e5d-11e4-9f4d-47d21b601170.png)

16 mittra -> mittra  NO CHANGE
17 mittratA -> mittratA NO CHANGE
18 mittravant -> mittravant NO CHANGE
[The author intentionally spells 'mitra' as 'mittra' in these words]
```
mittra, commonly written mitra 
mitra, i. e. mid + tra, I. m. 1. A vedic 
deity, Chr. 298, 25 = Rigv. i. 112, 
25. 2. The sun, Pańch. ii. d. 75. 
II. n. 1. A friend, Râm. 3, 51, 9. 
[etc]
```
19 SOktya -> SOklya
![image](https://cloud.githubusercontent.com/assets/6393033/5790268/6a083ad4-9e5e-11e4-82e4-ea03c2c084dc.png)

20 vArdDrIRasa -> vArdDrIRasa NO CHANGE
[MW vArDrIRasa .   Benfey  doubles D after 'r' to dD]
![image](https://cloud.githubusercontent.com/assets/6393033/5790280/f2983a98-9e5e-11e4-847b-463dd8cdbf04.png)

21 zyE -> zwyE
![image](https://cloud.githubusercontent.com/assets/6393033/5790294/2ed5988e-9e5f-11e4-8b90-c969833dc627.png)

**Comment by funderburkjim** [comment]
These corrections have been made.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Agree with all.

**Comment by gasyoun** [comment]
Wish @drdhaval2785 would approve correction in one dictionary every two weeks.
