### ISSUE TITLE
MW72 corrections from faultfinder, with fuzzy suggestions, Part 1

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#71]
This begins examination of 230 headwords from MW72 (1872 edition of Monier-WIlliams Sanskrit-English) dictionary.  These are chosen from sanhw1.txt as words that:
1. Occur only in mw72
2. Have some letter sequence not found in MW (this via faultfinder3a)

The examination of these cases is aided by producing [suggestion words](https://funderburkjim.github.io/mw72-only-fuzzyalpha.txt)  from sanhw1 that are 'nearly the same' as the questionable word, and, if possible, result in an alphabetical ordering at the position of the headword in the list of all mw72 headwords.

This part1 deals with the first 120 of the 230 cases to be examined.

**Comment by funderburkjim** [comment]
001 anuSAana -> anuSAsana
002 anuSAanIya -> anuSAsanIya
[typo]
![image](https://cloud.githubusercontent.com/assets/6393033/5790917/e33b6ece-9e7e-11e4-8ad4-c769c67d5d47.png)

003 apaastita -> apahastita
![image](https://cloud.githubusercontent.com/assets/6393033/5790921/193486e6-9e7f-11e4-8679-8a0e0472cf96.png)

004 apAeC -> apArC
![image](https://cloud.githubusercontent.com/assets/6393033/5790927/4dfdaf1a-9e7f-11e4-97f1-5e6adb90eeb9.png)

005 aBiah -> aBidah
```
abhi-dah, cl. 1. P. -dahati, -dag- 
dhum, to singe, burn.
```

006 asifdDita -> asidDida NO CHANGE
[in Supplement; asifdDita  confirmed under fdDita in MW]
![image](https://cloud.githubusercontent.com/assets/6393033/5790941/f5a22200-9e7f-11e4-90bf-f64642063287.png)

007 upaF -> upaF NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5790949/21e51ade-9e80-11e4-9674-0fbd84423208.png)

008 tArakia -> tArakin
![image](https://cloud.githubusercontent.com/assets/6393033/5790957/887509d0-9e80-11e4-92f8-1191f2fc1bfd.png)
Note: There is a flaw in the make_xml.py program for mw72, in that some of the information in the
digitization is lost.
```
digitization:
<P>{%Ta1rakia, i1, in2i1, i,%} starry; ({%in2i1%}), f. night.
xml record:
<H1><h><key1>tArakia</key1><key2>tArakia</key2></h><body>starry; (<i>in2i1</i>), f. night.</body><tail><L>20796</L><pc>0371-a</pc></tail></H1>

The part lost is ', i1, in2i1, i,'
```

009 Dortia -> Dorita
![image](https://cloud.githubusercontent.com/assets/6393033/5790996/367e648e-9e83-11e4-867c-65a28b768734.png)

010 BuruaRyu -> BuraRyu
![image](https://cloud.githubusercontent.com/assets/6393033/5791007/915bbc12-9e83-11e4-8a47-6a1a0910062f.png)

**Comment by gasyoun** [comment]
I must confess I'm impressed with the suggestion word algorithm combined with the alphabetical ordering requirement. :gem:

**Comment by funderburkjim** [comment]
011 Buruan ->  Burvan 
![image](https://cloud.githubusercontent.com/assets/6393033/5793848/e6dd7e52-9f21-11e4-9909-3423f18ef2a4.png)

012 muokzayizu ->  mumokzayizu 
![image](https://cloud.githubusercontent.com/assets/6393033/5793853/1b60dad4-9f22-11e4-90f1-91e74107992d.png)

013 yaTaFzi -> yaTafzi
![image](https://cloud.githubusercontent.com/assets/6393033/5793856/4f2ffe58-9f22-11e4-8b86-5db04ff05b94.png)

014 fDila ->  fDila NO CHANGE 
[MW (i.e., MW1899) spells fdDila]
![image](https://cloud.githubusercontent.com/assets/6393033/5793866/a0483d8c-9f22-11e4-8faf-bc1206c83855.png)

015 tfnAvarta -> tfRAvarta
[Print error.  'n' after 'f' becomes 'R', a rule of sandhi]
![image](https://cloud.githubusercontent.com/assets/6393033/5793869/e23cc488-9f22-11e4-9a31-d51e885c2adb.png)

016 yaTaFzi -> yaTafzi, NO CHANGE DUPLICATE: ()

017 vahequka -> vahequka NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5793876/44a2a818-9f23-11e4-8d12-487a13e06584.png)

018 acCE -> acCe
[This is an interesting one.  mw72 shows as acca-i,  PD as acce, MW as accA-i.
  Note MW does not have separate entry 'acce' (By contrast, MW does have 
  'e' as separate entry to which entry 'Ai' refers.)
  So, in this case, Perhaps we should add to MW an 'acce' entry; or else rewrite
  to accA-i entry so it has key1 as acce]
![image](https://cloud.githubusercontent.com/assets/6393033/5793898/ce1b07c4-9f24-11e4-9ad3-ab26e420b329.png)

019 aparADRa -> aparAhRa
![image](https://cloud.githubusercontent.com/assets/6393033/5793904/272886c0-9f25-11e4-8e02-369af12179fe.png)

020 apavakrf -> apavaktf
![image](https://cloud.githubusercontent.com/assets/6393033/5793908/4b4f9020-9f25-11e4-872d-9b77952830b4.png)

**Comment by funderburkjim** [comment]
021 apaSavda -> apaSabda
![image](https://cloud.githubusercontent.com/assets/6393033/5794255/d98e3630-9f33-11e4-9955-27eb5fb00b9b.png)

022 abBicCAyam -> aBicCAyam
![image](https://cloud.githubusercontent.com/assets/6393033/5794256/f92184e8-9f33-11e4-9ed2-2ab990879ae0.png)

023 abBukta -> aBukta
![image](https://cloud.githubusercontent.com/assets/6393033/5794258/20443b4c-9f34-11e4-89e1-c33aafbd1b71.png)

024 aBiniviDwa -> aBinivizwa
![image](https://cloud.githubusercontent.com/assets/6393033/5794263/55697008-9f34-11e4-8c9a-2228a37b0d3f.png)

025 aBisantF ->  aBisantF NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5794273/850167e4-9f34-11e4-97a3-6fa8646a5acd.png)

026 aBIztu ->  aBIzta 
![image](https://cloud.githubusercontent.com/assets/6393033/5794278/ccc85e20-9f34-11e4-98bb-30b4c3386476.png)

027 ayugvARa -> ayugvARa NO CHANGE ?
[mw72 scan clearly 'vARa'.  MW has ayugbARa]
[Not sure why ayun-netra is not separate headword.]
![image](https://cloud.githubusercontent.com/assets/6393033/5794287/5ad2234a-9f35-11e4-82fd-780eb59490e7.png)

028 ayoccizwa -> ayocCizwa
![image](https://cloud.githubusercontent.com/assets/6393033/5794297/af115aac-9f35-11e4-8e00-d53e689785d9.png)

029 araNGuza -> araNGuza NO CHANGE
[mw72 uses homorganic nasal;  there are several like this.]
![image](https://cloud.githubusercontent.com/assets/6393033/5794304/f0ca98dc-9f35-11e4-81a5-461bbc52ceef.png)

030 ANkfti -> ANkfti NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5794318/671109f4-9f36-11e4-9353-6d6ea5f798dc.png)

**Comment by funderburkjim** [comment]
031 AroQri -> AroQf
[print misses two under-dots]
![image](https://cloud.githubusercontent.com/assets/6393033/5794328/afc17ed6-9f36-11e4-8825-a493863efc46.png)

032 upasaNkxp ->  upasaNkxp NO CHANGE
033 upasaNkxpta -> upasaNkxpta NO CHANGE
[Note use of 'n+middle-dot' for slp1 'N' in this dictionary's version of IAST]
![image](https://cloud.githubusercontent.com/assets/6393033/5794340/496134be-9f37-11e4-8645-f2a5e5b18f1b.png)

034 kENkarya -> kENkarya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5794348/7dc7260a-9f37-11e4-8a68-24060fe2765b.png)

035 camniz -> camriz
![image](https://cloud.githubusercontent.com/assets/6393033/5794351/9f824d74-9f37-11e4-8ba9-62831e9543bf.png)

036 tanlIka -> tanlIka NO CHANGE
[can't find in other dictionaries]
![image](https://cloud.githubusercontent.com/assets/6393033/5794365/3a5923fe-9f38-11e4-8c6c-cd5c01958f23.png)

037 tfQvA -> tfQvA NO CHANGE
[Appears with entry for root tfh in MW]
![image](https://cloud.githubusercontent.com/assets/6393033/5794382/9b9d4f64-9f38-11e4-9a0f-6b68ac28dd42.png)

038 dfzkARa ->  dfzkARa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5794388/caeb89fc-9f38-11e4-9644-f06e89809d96.png)

039 nanqi -> nandi
![image](https://cloud.githubusercontent.com/assets/6393033/5794390/f86d4ce4-9f38-11e4-89fd-9b829c1989af.png)
[etc]

040 nAruntuda -> nAruntuda NO CHANGE
[use of homorganic nasal is ok]
![image](https://cloud.githubusercontent.com/assets/6393033/5794396/36d5a0e4-9f39-11e4-9ec8-0ceeb627b203.png)

**Comment by funderburkjim** [comment]
041 nicumyuRa -> nicumpuRa
![image](https://cloud.githubusercontent.com/assets/6393033/5888681/b445ad7e-a3d7-11e4-9c0a-54913b5cb22a.png)

042 nirgF -> nirgF NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888701/1256e2d4-a3d8-11e4-974f-e06f34585a5b.png)

043 nizpF -> nizpF NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888703/4492d226-a3d8-11e4-8ae9-8886f45c015c.png)

044 parimfdnat ->  parimfdnat NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5888711/ab93fd9c-a3d8-11e4-8e00-6f579586fc45.png)

045 parisaNGuz -> parisaNGuz NO CHANGE
046 parisaNGuzwa -> parisaNGuzwa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888728/0ef435f0-a3d9-11e4-8305-5f5b6112b309.png)

047 pAnsin -> pAnsin NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888738/51b9f5c8-a3d9-11e4-9876-85e839670908.png)

048 prASnat ->  prASnat NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888743/817577ec-a3d9-11e4-8f7e-3b250668d848.png)

049 preryamARa ->  preryamARa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888748/d1f6dc06-a3d9-11e4-90fa-58dc9be01821.png)

050 prodgE -> prodgE NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888760/054f1762-a3da-11e4-8531-3089d20acfd0.png)

**Comment by funderburkjim** [comment]
051 marmfjenyu -> marmfjenyu NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888851/367888f8-a3dc-11e4-870d-81b699aa8440.png)

052 mukuRdI -> mukuRwI
![image](https://cloud.githubusercontent.com/assets/6393033/5888859/7a3ca7b8-a3dc-11e4-9a2e-3b543ead7783.png)

053 mUzpAyaRa -> mUzyAyaRa
![image](https://cloud.githubusercontent.com/assets/6393033/5888864/ac1a5c44-a3dc-11e4-82a4-ba01eb754907.png)

054 rUQvA -> rUQvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888873/185e9bfe-a3dd-11e4-9e0a-80bc4d205950.png)

055 lIQvA -> lIQvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888880/414f71f0-a3dd-11e4-9644-2f1289274e02.png)

056 vivfRvAna -> vivfRvAna NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888882/7739705e-a3dd-11e4-9b29-811870b946e1.png)

057 vfRvAna -> vfRvAna NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888891/d4a39378-a3dd-11e4-9759-aa8cfbfa094e.png)

058 vyApnuvAna -> vyApnuvAna NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888896/fac663d2-a3dd-11e4-9f84-14f5f3011315.png)

059 Sirzan -> SIrzan
![image](https://cloud.githubusercontent.com/assets/6393033/5888905/37288fda-a3de-11e4-9542-e4794863cdba.png)

060 Sulvika -> Sulvika NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888924/88dd0d92-a3de-11e4-9b4b-f324cd3a1b57.png)

**Comment by funderburkjim** [comment]
061 SraTnAna -> SraTnAna NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888936/df9c3dd8-a3de-11e4-8884-217e2ba29342.png)

062 saMvfRvAna ->  saMvfRvAna NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5888939/079338d2-a3df-11e4-8d26-3c068c04fbb1.png)

063 saNkF ->  saNkF NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888948/41c8477c-a3df-11e4-89d2-13dca6409c0a.png)

064 saNkxp ->  saNkxp NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888954/80e6a85e-a3df-11e4-98b4-14f000c33aba.png)

065 saNkxpta -> saNkxpta NO CHANGE
066 saNkxpti -> saNkxpti NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5888958/a7a92b10-a3df-11e4-81dc-df102cc272f0.png)

067 saNgE -> saNgE NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888973/f223a724-a3df-11e4-9e1c-412da81bd815.png)

068 saNGuz ->  saNGuz NO CHANGE
069 saNGuzita -> saNGuzita NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5888979/149ccc54-a3e0-11e4-8309-d7a50f83bb21.png)

070 saNGfz -> saNGfz  NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5888990/4e0e8eaa-a3e0-11e4-8a8c-96b7f41491e7.png)

**Comment by funderburkjim** [comment]
071 saNGfzwa -> saNGfzwa NO CHANGE
072 saNGfzyat -> saNGfzyat NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5888995/70e6753c-a3e0-11e4-83f5-3b95def1cd8b.png)

073 saNjagmAna -> saYjagmAna
![image](https://cloud.githubusercontent.com/assets/6393033/5889488/07b2cdfa-a3f8-11e4-8858-46f4ff3212ce.png)

074 saNjuGukzA -> saYjuGukzA
![image](https://cloud.githubusercontent.com/assets/6393033/5889498/8f8cd180-a3f8-11e4-84e1-1cb6925b5dad.png)

075 saNjuGukzu -> saYjuGukzu
![image](https://cloud.githubusercontent.com/assets/6393033/5889501/9faf95a2-a3f8-11e4-964e-9b3dd0c73442.png)

076 saYCAdana -> saYCAdana NO CHANGE
077 saYCAdya -> saYCAdya  NO CHANGE
078 saYCAdyamAna ->  saYCAdyamAna NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889509/2a486518-a3f9-11e4-92a5-c1e9027b386b.png)

079 saYCid -> saYCid NO CHANGE
080 saYCidya -> saYCidya NO CHANGE 
081 saYCidyat -> saYCidyat NO CHANGE 
082 saYCidyamAna ->  saYCidyamAna NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889515/71cb2bdc-a3f9-11e4-9690-6571ad156c5e.png)

**Comment by funderburkjim** [comment]
083 saYjf -> saYjF
![image](https://cloud.githubusercontent.com/assets/6393033/5889518/ac619dd0-a3f9-11e4-85d0-c89569e6b6db.png)

084 saYjfmB ->  saYjfmB NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889525/f3bf2bb6-a3f9-11e4-99a7-d4db9e496f33.png)

085 sanDf ->  sanDf NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889530/20116080-a3fa-11e4-9c1b-1db8ee54e4f7.png)

086 sanDfta -> sanDfta NO CHANGE 
087 sanDfz ->  sanDfz NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889535/50eca9b2-a3fa-11e4-97e4-62bcbe8bf242.png)

088 samuccIya ->  samuccIya NO CHANGE
089 samuccIyamAna -> samuccIyamAnaNO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889539/9ef4ca0e-a3fa-11e4-9291-b29bc7f0a96c.png)

090 samuqga -> samudga 
091 samuqgam ->  samudgam 
![image](https://cloud.githubusercontent.com/assets/6393033/5889543/f02adfee-a3fa-11e4-8441-ad4470076ecb.png)

**Comment by funderburkjim** [comment]
092 samuqgF ->  samudgF
![image](https://cloud.githubusercontent.com/assets/6393033/5889548/4144bab2-a3fb-11e4-970e-5b7e3ff4be2b.png)

093 samuqgE -> samudgE
![image](https://cloud.githubusercontent.com/assets/6393033/5889550/5c6a78a4-a3fb-11e4-8792-5e8568e048bf.png)

094 samuqbanD ->  samudbanD 
![image](https://cloud.githubusercontent.com/assets/6393033/5889555/896cb8bc-a3fb-11e4-9a62-1a3fb6584221.png)

095 samuqbuD -> samudbuD
![image](https://cloud.githubusercontent.com/assets/6393033/5889557/9f942aa8-a3fb-11e4-81e2-a2b4fbf4b41c.png)

096 samuqvas -> samudvas
![image](https://cloud.githubusercontent.com/assets/6393033/5889561/c799088e-a3fb-11e4-8a54-a1cc3d8b7f02.png)

097 samuqvij -> samudvij
![image](https://cloud.githubusercontent.com/assets/6393033/5889563/e875cb32-a3fb-11e4-9970-677670f9b30d.png)

098 samuqvft ->  samudvft 
![image](https://cloud.githubusercontent.com/assets/6393033/5889564/03fcb06e-a3fc-11e4-8fb7-fa120afb0885.png)

099 samuqvfh -> samudvfh 
![image](https://cloud.githubusercontent.com/assets/6393033/5889567/2234ca9e-a3fc-11e4-8bab-11c67fc13a90.png)

100 samnAj -> samrAj
![image](https://cloud.githubusercontent.com/assets/6393033/5889570/41974a1a-a3fc-11e4-96b3-aa633dc542d3.png)

**Comment by funderburkjim** [comment]
101 samprerya -> samprerya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889574/76db91a4-a3fc-11e4-826f-f1a289421e80.png)

102 saraRyU ->  saraRyU NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889576/aeb417c2-a3fc-11e4-93f6-f46f766c9536.png)

103 sANkftya -> sANkftya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889579/d33c5370-a3fc-11e4-970a-260afcb1950f.png)

104 sizvidAna -> sizvidAna NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889582/fb6b6db8-a3fc-11e4-8225-768e4fa4d556.png)

105 snIQvA -> snIQvA NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889584/33fbe28e-a3fd-11e4-82a8-9f03080c9bee.png)

106 adadyraYc -> adadryaYc
![image](https://cloud.githubusercontent.com/assets/6393033/5889675/6c2f2d60-a401-11e4-9e53-6452ef3fe224.png)

107 aDidaRqnetf -> aDidaRqanetf
![image](https://cloud.githubusercontent.com/assets/6393033/5889679/953eaef6-a401-11e4-956e-8c290aa1a14e.png)

108 anusaNgrah ->  anusaNgrah NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889682/c64641a8-a401-11e4-869b-93a7db3a93c8.png)

109 anusaYjvar -> anusaYjvar NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889684/eb0bd174-a401-11e4-84f9-e604e9a43eda.png)

110 apapvrata -> apavrata
![image](https://cloud.githubusercontent.com/assets/6393033/5889692/0e0d5d5a-a402-11e4-999b-c68b5330aa59.png)

**Comment by funderburkjim** [comment]
111 apprakawa -> aprakawa
![image](https://cloud.githubusercontent.com/assets/6393033/5889693/2d69bec8-a402-11e4-859c-1464a308338d.png)

112 apratisaNKya ->  apratisaNKya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889697/615cefa2-a402-11e4-964d-7988f64290c0.png)

113 abzyagni ->  aByagni
![image](https://cloud.githubusercontent.com/assets/6393033/5889701/9b01011c-a402-11e4-8b5d-efedf7856649.png)

114 aBimUrcCita -> aBimUrcCita NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889705/c9396e66-a402-11e4-81d4-f85082336229.png)

115 aBisaMkruD -> aBisaNkruD
[Here, Devanagari and MW's IAST disagree.  The change is consistent with the
 usual convention in MW72 of using the homorganic nasal]
![image](https://cloud.githubusercontent.com/assets/6393033/5889718/5f3b6d9c-a403-11e4-9549-7e630316e4c2.png)

116 aBisaMkruS -> aBisaNkruS
[Similar explanation to previous]
![image](https://cloud.githubusercontent.com/assets/6393033/5889720/7aa36364-a403-11e4-8beb-7b4e22087b88.png)

117 aBisaYjYA ->  aBisaYjYA NO CHANGE
119 aBisaYjvar ->  aBisaYjvar NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889730/02551f00-a404-11e4-8e7e-94d1436f174f.png)

118 aBisaYjYita ->  aBisaYjYita NO CHANGE
[in additions]
![image](https://cloud.githubusercontent.com/assets/6393033/5889736/474cce8c-a404-11e4-8f21-54e33542ca01.png)

120 amvla ->  amvla NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889744/79ac684c-a404-11e4-85a7-cd179e085066.png)

**Comment by drdhaval2785** [comment]
```
018 acCE -> acCe
[This is an interesting one. mw72 shows as acCa-i, PD as acCe, MW as acCA-i.
Note MW does not have separate entry 'acce' (By contrast, MW does have
'e' as separate entry to which entry 'Ai' refers.)
So, in this case, Perhaps we should add to MW an 'acCe' entry; or else rewrite
to acCA-i entry so it has key1 as acCe]
```
Let's keep it acCa-i as it is in the scan

**Comment by drdhaval2785** [comment]
```
027 ayugvARa -> ayugvARa NO CHANGE ?
[mw72 scan clearly 'vARa'. MW has ayugbARa]
[Not sure why ayun-netra is not separate headword.]
```
No change.
ayun-netra is a separate headword.

**Comment by drdhaval2785** [comment]
```
115 and 116
```
I agree with your explanation

**Comment by drdhaval2785** [comment]
@funderburkjim 
Close when you are done with these three feedback.
Rest are OK

**Comment by funderburkjim** [comment]
reverted to hiatus acCai,  changed so ayun-netra is headword.
