### ISSUE TITLE
KCH corrections from faultfinder

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/CORRECTIONS#72]
@funderburkjim can I ask you to help me a file similar to the series published before? I'll do all the checking, it's needed for a new edition of a Sanskrit-Russian dictionary. It's SLP1. Panchavargama conventions might be different than MW, but still.
Documented all the changes from the source .xls file based on web scraping based on printed book.
1) Deleted all acute accent marks `´` (4904)
2) Deleted compositia splitting `-` (7284)
3) change-replaced all `/`
## 4) converted from IAST to SLP1

5) deleted a single case dirt
-  (формы см. ष्ठिव् )
-  (формы см. यु _1_ )
- (формы см. स्था _1_ )
- (X. pr. kaṁpate—I; jut. kam-piṣyate; pf. cakaṁpe; aor. akaṁpiṣṭa )
-  (P. pr. smeṭayati— X; pf. smetayañcakāra; aor. asismiṭat)
-  (caus. от प्रसर् )
  6) what to do with extra words in `()`
- dviḥ(s) + sama
- kṣulla(ka)
- (nu + vai)
- krudhmi(n)
- kārṣi(n)
- kranda(na)
- kramela(ka)
- mārjāra(ka)
- saṁpuṭa(ka)
- kaukṣeya(ka)
- vardhma(n)
- uraṁga(ma)
- kula-deva(tā)
- kula-daiva(tā)
- nāṭita(ka)
  7) remains of roman numerals
- viyuj
  I viyu
  avalup
- adhyāruh
  I adhiruh
  nirvart
- taralā
  I
  tariṇī

8) The draft file for faultfinder is at https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/Kochergina-1987_29007.txt

**Comment by funderburkjim** [comment]
@gasyoun  You'll have to be more specific.  I'm not sure what your objective is   What is the input required, and what is the output your aiming for?

Incidentally, at the moment I think the Kochergina-1987_29007.txt
 file should NOT be part of the CORRECTIONS repository.  I'd like to reserve that repository
for the actual corrections made to dictionaries, and material closely related to corrections  (like the
working documents Sampada uses to generate corrections to missing data, etc.)

**Comment by funderburkjim** [comment]
@gasyoun  You'll have to tell me more if you want me to help in some way.

**Comment by drdhaval2785** [comment]
@gasyoun The ball is in your court

**Comment by gasyoun** [comment]
@funderburkjim - objective is to clean the only big open source Sanskrit-Russian dictionary (29k words only), mainly by comparing to MW, PWG and PWK. There must be at least 200 mistakes, I propose in the headwords.
Input: https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/Kochergina-1987_29007.txt
Output: similar to https://github.com/sanskrit-lexicon/CORRECTIONS/issues/104 or http://drdhaval2785.github.io/o_vs_O/output1/MW.html - one of the used correction methods applied. As per "should NOT be part of the CORRECTIONS repository" - I agree, but as I want to use the same cleaning methods, let it be there for a while.

**Comment by funderburkjim** [comment]
re 'should NOT be part of the CORRECTIONS repository'  --- sounds like I was being needlessly pedantic.  Fine to keep it whereever.

Looking at your input, it seems to be a list of SLP1 spelled headwords.   One easy thing to do would
be for me to write a program to see which spellings appear as key1 in MW, and to kick out the
exceptions.  If you agree this is useful first step, I'll do that.

**Comment by gasyoun** [comment]
I agree. MW was her main source, PWG, PWK, AP90, MD - less.

**Comment by funderburkjim** [comment]
Have completed first pass, comparing to MW.
4622 of the 29007 words NOT  MW headwords.
[kcp-mw.txt](https://gist.github.com/funderburkjim/ef882c6b11eed549d668) adds a Y/N to each word, indicating whether in MW or not.
Some possible reasons for words in the 4622 non-MW category:

* some verbs show guna of SLP1 vowel 'f'. eg 'mar' in kcp is probably 'mf'
     in MW.  avatar in kcp prob. = avatF in MW
* saṁpad  would be sampad in MW
* some nasals are wrong: saNyat in kcp = saMyat in MW
* vikalpavant in kcp = vikalpavat in MW
* some inflected forms in kcp:  enO, ene,... enayA are inflected forms
     of pronoun idam.

**Comment by gasyoun** [comment]
Thanks a lot. Can we write some rules of treating -vant like -vat? This issue is wider, but rules should help to find the real differences, and not just Indian / European standards, or orthography concerned. It's not only KCH vs. MW. Same issue with PWG vs. MW. Can we add some rules, please?

**Comment by funderburkjim** [comment]
I didn't offer to do the whole project for you, only to provide technical assistance.  It's up to you to 
derive useful rules.  Your job is to make my life as easy as possible in this task.  So take some time
thinking through what you need.  Maybe your programmers could help implement your ideas?

**Comment by gasyoun** [comment]
Sounds realistic, let me try. Where can I see the code used for the comparison, so my coders can catch up the work, Jim?

**Comment by funderburkjim** [comment]
I put the python program compare-MW.py in the same Gist as above.  The 'Usage' comments
shows how it is run.

You already have Kochergina-1987_29007.txt.

The other ingredient is a list of MW keys, for which I used a file that you can get by the following
curl command:
```
curl -o extract_keys_b.txt 'http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/mwaux/mwkeys/extract_keys_b.txt'
```

This should get you started.

**Comment by gasyoun** [comment]
Great, before you let me go - can we have a fuzzy comparison of MW vs. KCH?

**Comment by funderburkjim** [comment]
Second phase of analysis of Kochergina headword spelling begun.

The results are three files, in [this gist](https://gist.github.com/funderburkjim/082eff8af4fce9489e175e24572bdab3#file-compare-mw-py)

* compare-MW2.py   extracts the non-matched Kochergina headword records from [kcp-mw.txt](https://gist.github.com/funderburkjim/ef882c6b11eed549d668) , and supplies some rules to get more matches to MW headwords.
* compare-MW2_log.txt   There were 100+ records which had a non-standard form.  The program made plausible adjustments to all but 5 of these, and the nature of these adjustments is mentioned in this log file.  Also the 5 'cannot parse' cases are mentioned.   The line numbers refer to the original Kochergina file.

This log file also shows, at the bottom, statistics regarding solutions
* compare-MW2.txt  This is the result of the comparisons, showing (for all but those 5), the 
  * line number within the original file
  * the spelling within the original file (including the adjustments noted in the log file)
  * the status in terms of matching to MW headwords.
    * If a further spelling adjustment rule was applied to get a match, this alternate spelling is shown
       Currently, the only such extra rule is 'ar'->'f'.

@gasyoun  Let me know if this form is what you had in mind.  I know there are some additional rules, involving nasals, that can be applied once we agree on this form.

**Comment by gasyoun** [comment]
Thanks, Jim. Still I hardly understand are cases like

* vikalpavant in kcp = vikalpavat in MW

Covered now with the rules, like the ones at https://github.com/sanskrit-lexicon/CORRECTIONS/issues/72#issuecomment-150351413 ?

**Comment by funderburkjim** [comment]
Cases like vikalpavant NOT yet handled.  I'm working on additional rules at the moment, and one of those will recognize that `vikalpavant` is the same as mw `vikalpavat`.  

Will post here when revisions to the Gist files are ready.

**Comment by funderburkjim** [comment]
The [Gist files](https://gist.github.com/funderburkjim/082eff8af4fce9489e175e24572bdab3) are now updated.  

The summary from the log file:
```
2153 spellings remain unvalidated
2464 spellings validated
60 validated by method default
379 validated by method ṁ->M
536 validated by method ar->f
204 validated by method M->nasal
711 validated by method N->M
14 validated by method N->M,ar->f
560 validated by method ant$->at

ALSO, 40 records are marked as 'MALFORMED' (letters other than a-zA-Z).
```

So the list of questionable items has been more than cut in half.

**Comment by gasyoun** [comment]
> So the list of questionable items has been more than cut in half. 

Thanks, Jim. I will get back to it as well. I value your help a lot.

The author died and was cremated today, see https://groups.google.com/forum/#!topic/bvparishat/VOZBNUKdFuQ

**Comment by gasyoun** [comment]
> So the list of questionable items has been more than cut in half.

Is there a clean list of output, only MW kind of spelled Kochergina, @funderburkjim ? Please, please, please.

**Comment by Sonnetag** [comment]
Hello,

This is about the broken links in Monier-Williams 1899. As you can see 
the screen shot below, there are links to Whitney and Westergaard 
Dhatupatha. Both links are broken (Page not Found error message). Can 
anyone please restore the links? So we can look them up when necessary.

Thank you, Youngsinn

**Comment by funderburkjim** [comment]
@Sonnetag 

Did you forget to copy the screen shot into a comment?

Is the problem happening for just one headword?  If so, what is the headword?

**Comment by Sonnetag** [comment]
The screen shot below. Type any word in Monier-Williams 1899 and click 
the link to check.

No it is not just one headword. For all headwords, the links to Whitney 
Roots Links and Wetesgaard Dhatupatha are broken.

Youngsinn

**Comment by funderburkjim** [comment]
@Sonnetag   For some reason,  I do not see a screen shot in your comment.

Here's a screen shot of display of 'viS'  And the links seem to work.  Here are two screen shots:
First, the display in MW Advanced Search:

![image](https://user-images.githubusercontent.com/6393033/158868880-3ef529c7-58dc-43f4-ac83-7fcb820d9d1d.png)

Second, result when I click on Whitney roots viS  (slp1) (after I scroll down to 'viS')
![image](https://user-images.githubusercontent.com/6393033/158869249-032e0ff9-339b-4863-a6e0-3bc0b2662ba9.png)

At this stage, I cannot replicate your problem.  More information will be needed.  What kind of
computer are you using? (desktop, laptop, phone? -- Windows, Mac, Linux?)
Which display are you using (advanced search, basic, etc or simple-search?).

And I need to see an image of what appears on your screen when you click the Whitney roots link

**Comment by Sonnetag** [comment]
Sorry if this is a duplicate; just delete it. I sent out the message 
copied below but I do not know where it was sent. So I am sending it to 
the all listed again. Thanks.

Hello,

This is about the broken links in Monier-Williams 1899. As you can see 
the screen shot below, there are links to Whitney and Westergaard 
Dhatupatha. Both links are broken (Page not Found error message). Can 
anyone please restore the links? So we can look them up when necessary.

Thank you, Youngsinn

**Comment by funderburkjim** [comment]
@Sonnetag 
Hi, Youngsinn -
I see your screenshot https://user-images.githubusercontent.com/6393033/158868880-3ef529c7-58dc-43f4-ac83-7fcb820d9d1d.png.
The image shows you are using [advanced search](https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc2/index.php) for mw (1899), have looked up the word 'viS' (slp1).
You have underlined in red the link to Whitney roots, and I understand that (somehow) this link is not working for you.

I just tried the same thing on my desktop computer, and the link works fine.
Here is screen shot of page from Whitney roots that appeared when I clicked the link: 
![image](https://user-images.githubusercontent.com/6393033/195239585-5ca49b5f-464e-42fd-b32c-94f9a636e75f.png)

My desktop is a Windows 11 pc.

Suggestion: If possible, just run your mac as a Mac, and use Safari or Chrome or Firefox, and see what happens.

I don't have a Mac, much less a Mac with Windows 10.  I cannot duplicate your computing environment.

**Comment by Sonnetag** [comment]
Jim,

It is apparent that it has to do with my computer set up. I found that 
when I access MW from 'Inflected form lookup', then the link to Whitney 
roots works! I bought Whitney's hardcopy book and also dowloaded PDF 
file of the book from Archive, so I have what I need.

Thank you,
Youngsinn

**Comment by funderburkjim** [comment]
@Sonnetag   Thanks for feedback. Glad you found a workaround.
Will consider this issue closed now.
