### ISSUE TITLE
MW72 corrections from faultfinder, with fuzzy suggestions, Part 2

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#73]
This part 2 deals with the last 110 of the 230 cases of headwords from MW72.

**Comment by funderburkjim** [comment]
121a arrk -> ark
121 arrka -> arka
![image](https://cloud.githubusercontent.com/assets/6393033/5889777/2cba6f6e-a406-11e4-95a0-f05656f09157.png)

122 asaYjYisattva -> asaYjYisattva NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889779/5ac4a4b0-a406-11e4-925c-e2309a56ef31.png)

123 Adezwri ->  Adezwf 
[print error, r missing underdot]
![image](https://cloud.githubusercontent.com/assets/6393033/5889786/924b3d72-a406-11e4-992a-1dcaa14c3529.png)

124 upasaNkzepa ->  upasaNkzepa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889800/daa83520-a406-11e4-8afa-d54312aa4850.png)

125 upasaNgrah ->  upasaNgrah NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889805/f81e3730-a406-11e4-9135-696143e97c81.png)

126 upasaNgrahaRa -> upasaNgrahaRa NO CHANGE
127 upasaNgrAhya -> upasaNgrAhya  NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889807/0be8368a-a407-11e4-8f48-7b4c045b5962.png)

128 ezwri -> ezwf
[print missing dot under 'r']
![image](https://cloud.githubusercontent.com/assets/6393033/5889809/479bc75a-a407-11e4-8b47-03f7fd9ca7d2.png)

129 kakkvalla ->  kakkvalla NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889812/6d484ce4-a407-11e4-84e1-d4876de887f2.png)

130 kiNkzaRa -> kiNkzaRa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889816/946b2972-a407-11e4-8c26-281236774f4a.png)

**Comment by funderburkjim** [comment]
131 tIkzRizWa ->  tIkzRizWa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889819/c98d64b2-a407-11e4-8287-c622b2d4630b.png)

132 dugDvA ->  dugDvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889821/e6b8c46e-a407-11e4-9c0c-3908ee981df9.png)

133 niHsaNKya ->  niHsaNKya NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889824/274d0990-a408-11e4-9aac-c04b4050fa91.png)

134 niHsaYjYa -> niHsaYjYa NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889826/3d9a6a6c-a408-11e4-9e22-e3002576b669.png)

135 nisaYjYa -> nisaYjYa NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889829/5aa28e78-a408-11e4-9cc2-c3920d58a537.png)

136 nEvasaYjYAsamADi ->nEvasaYjYAsamADi NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889834/99714310-a408-11e4-9b24-59a45bac70c5.png)

137 parisaNkrIq ->  parisaNkrIq NO CHANGE
138 parisaNkrIqat -> parisaNkrIqat NO CHANGE 
139 parisaNkzip ->  parisaNkzip NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889837/fba6c8ac-a408-11e4-950a-5c55355504d4.png)

140 pAzRqaka -> pAzaRqaka
![image](https://cloud.githubusercontent.com/assets/6393033/5889839/2b4d5db4-a409-11e4-9d09-b18835668f34.png)

**Comment by funderburkjim** [comment]
141 pratisaNkrudDa ->  pratisaNkrudDa NO CHANGE
142 pratisaNkruD ->  pratisaNkruD NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889842/66e754ec-a409-11e4-89ab-28b53dc7257d.png)

143 pratisaNgrah ->  pratisaNgrah NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889844/949a9728-a409-11e4-8671-02ffd541ba28.png)

144 pratisaYjYA ->  pratisaYjYA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889845/afbb8724-a409-11e4-895c-3a82759b77c6.png)

145 pradezwri ->  pradezwf 
[print missing dot under 'r']
![image](https://cloud.githubusercontent.com/assets/6393033/5889847/d7efe76c-a409-11e4-94ab-712badd5819e.png)

146 badDvA ->  badDvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889849/1efbcbda-a40a-11e4-9dd2-b1cc27affc72.png)

147 budDvA -> budDvA  NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889852/4455775a-a40a-11e4-9e7a-3e80d3ca1b4e.png)

148 BittvA ->  BittvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889856/652095f0-a40a-11e4-85d2-1759c73cc137.png)

149 mitAkzarAsidDAntasaNgraha -> mitAkzarAsidDAntasaNgraha NO CHANGE
[MW(99) digitization has mitAkzar<b>a</b>-sidDAntasaMgraha - are both 'A' and 'a' correct?]
![image](https://cloud.githubusercontent.com/assets/6393033/5889867/09869e46-a40b-11e4-8289-672bc59e6b16.png)

150 rudDvA ->  rudDvA NO CHANGE 
![image](https://cloud.githubusercontent.com/assets/6393033/5889871/3b18de56-a40b-11e4-871c-3ea9f60e1e24.png)

**Comment by funderburkjim** [comment]
151 lubDvA ->  lubDvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889873/61e1b5b2-a40b-11e4-9f23-0723c52db2cb.png)

152 vittvA -> vittvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889875/84357810-a40b-11e4-8a7c-b13c3af15e4e.png)

153 visaYjYa -> visaYjYa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889877/b15348cc-a40b-11e4-9753-66ab34ff75a4.png)

154 vyUrRvat ->  vyUrRvat NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889878/e238ef3c-a40b-11e4-8b19-ff4c691b26bc.png)

155 SaptvA ->  SaptvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889881/0f84959a-a40c-11e4-857e-69108d95fadb.png)

156 SudDvA -> SudDvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889885/2804ef7a-a40c-11e4-810c-f4894bbf2881.png)

157 SfdDvA ->  SfdDvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889891/53ac4830-a40c-11e4-9255-78355394eb36.png)

158 Sotsyat -> Sotsyat NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889895/79e48b02-a40c-11e4-98d3-7e032b31a797.png)

159 saNkrAmat -> saNkrAmat NO CHANGE
160 saNkrAmita ->  saNkrAmita NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889903/bc5ef18e-a40c-11e4-8a7d-be87a43bafcd.png)

**Comment by funderburkjim** [comment]
161 saNkrI ->  saNkrI NO CHANGE
162 saNkrIq ->  saNkrIq NO CHANGE
163 saNkrIqana ->  saNkrIqana NO CHANGE
 [MW, PWG, SCH, AP90 have 'qana'; SHS, WIL and YAT have 'qaRa']
![image](https://cloud.githubusercontent.com/assets/6393033/5889945/78854a7e-a40e-11e4-9683-8ab477d9e29e.png)

164 saNkrIqamAna -> saNkrIqamAna  NO CHANGE
[SHS, WIL, YAT have 'saNkrIqamARa'; however, they also have krIqamAna;
 so <b>saNkrIqamARa may be an error in SHS, WIL, YAT</b>]
165 saNkrIqita -> saNkrIqita  NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889963/3b9acade-a40f-11e4-9ab1-3914252fbc73.png)

166 saNkruD -> saNkruD NO CHANGE
167 saNkruS ->  saNkruS NO CHANGE
168 saNkroSamAna ->  saNkroSamAna NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889970/ae545eaa-a40f-11e4-9fc5-c62bd6cff7ed.png)

169 saNklid ->  saNklid NO CHANGE
170 saNklinna ->  saNklinna NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889973/d248e1c8-a40f-11e4-9ebc-6d7b23186c52.png)

**Comment by funderburkjim** [comment]
171 saNkliS ->  saNkliS NO CHANGE
172 saNkliSya -> saNkliSya  NO CHANGE
173 saNklizwa -> saNklizwa NO CHANGE
174 saNkleSa -> saNkleSa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889978/204ae43e-a410-11e4-8a83-b1daa6e48c10.png)

175 saNkzi -> saNkzi NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889979/40787de8-a410-11e4-9e64-5aa4404a5ac0.png)

176 saNkzip ->  saNkzip NO CHANGE
177 saNkzipat -> saNkzipat NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889983/74f1cd04-a410-11e4-943e-ff2cdba3abf6.png)

178 saNkzipya -> saNkzipya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889986/8e58d5f8-a410-11e4-99d9-40cf396b8cf9.png)

179 saNkzepaRIya -> saNkzepaRIya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889988/a87695d8-a410-11e4-881b-de54af961547.png)

180 saNkzoBita -> saNkzoBita NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5889994/c58515b4-a410-11e4-9026-0208f30989fb.png)

**Comment by funderburkjim** [comment]
181 saNKyaka ->  saNKyaka NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5892992/8fa593f0-a4a2-11e4-9e95-7212b722a2ce.png)

182 saNgraT ->  saNgraT NO CHANGE
183 saNgraTita -> saNgraTita  NO CHANGE
184 saNgras -> saNgras NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893015/50ea8782-a4a3-11e4-875c-5d3c90311c46.png)

185 saNgrah -> saNgrah NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893020/6289efa0-a4a3-11e4-8bb7-e8e7e647b5a8.png)

186 saNgrahaRIya -> saNgrahaRIya NO CHANGE
187 saNgrahItf -> saNgrahItf NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893025/8930a2c0-a4a3-11e4-9920-76d24d0a992a.png)

188 saNgrAhaka -> saNgrAhaka NO CHANGE
189 saNgrAhita -> saNgrAhita NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893031/b222019c-a4a3-11e4-9f4b-d9cc6b5f40b9.png)

190 saNgrAhya -> saNgrAhya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893032/bf22ccaa-a4a3-11e4-8c39-62b9542e3c6f.png)

**Comment by funderburkjim** [comment]
191 saNGrA -> saNGrA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893040/07542596-a4a4-11e4-8040-584c78231009.png)

192 saYcyu -> saYcyu NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893046/208b5480-a4a4-11e4-8e30-f48bfd26bbae.png)

193 saYjYaka -> saYjYaka NO CHANGE
194 saYjYapat -> saYjYapat NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893073/e7ad0ebe-a4a4-11e4-80d2-e485c99451df.png)

195 saYjYapita -> saYjYapita NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893077/1b1b5e18-a4a5-11e4-8492-6767e4ad8810.png)

196 saYjYAta -> saYjYAta NO CHANGE
197 saYjYAna -> saYjYAna NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893081/31e7ba74-a4a5-11e4-90db-63a41bea806d.png)

198 saYjYApita -> saYjYApita NO CHANGE
199 saYjYApya -> saYjYApya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893074/0be8be90-a4a5-11e4-816b-50ca1422f7f3.png)

200 saYjYin -> saYjYin NO CHANGE

**Comment by funderburkjim** [comment]
201 saYjvar -> saYjvar NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893096/de63dab2-a4a5-11e4-8f94-2c6ea985d2f1.png)

202 saYjval -> saYjval NO CHANGE
203 saYjvalat -> saYjvalat NO CHANGE
204 saYjvAlya -> saYjvAlya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893098/efe13ab4-a4a5-11e4-8671-1b81f9041e01.png)

205 saqvanqva ->  sadvandva
205a saqvasaTa -> sadvasaTa
![image](https://cloud.githubusercontent.com/assets/6393033/5893127/414d80d8-a4a6-11e4-8e1b-9e82d3f08bce.png)

206 santrE ->  santrE NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893131/6c67c260-a4a6-11e4-87ee-e5e07aecf751.png)

207 sandru -> sandru NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893134/91d0ac42-a4a6-11e4-8882-703e1da5f0bd.png)

208 sanDmA -> sanDmA NO CHANGE
209 sanDyE -> sanDyE  NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893142/d1fa486e-a4a6-11e4-80ec-facfc9bfc9a1.png)

210 sannyas -> sannyas NO CHANGE:
![image](https://cloud.githubusercontent.com/assets/6393033/5893153/f84eaf32-a4a6-11e4-8cf8-e49da5e827dd.png)

**Comment by funderburkjim** [comment]
211 samuccyitvA -> samuccayitvA
![image](https://cloud.githubusercontent.com/assets/6393033/5893161/409fee22-a4a7-11e4-816d-d08565708054.png)

212 samuqgranT ->  : samudgranT 
![image](https://cloud.githubusercontent.com/assets/6393033/5893163/7a7996f2-a4a7-11e4-811a-092428cfa835.png)

213 samBriyamARa -> samBriyamARa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893172/def560d4-a4a7-11e4-97ce-be1628250f44.png)

214 sasaYjYa -> sasaYjYa NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893175/1180c3ae-a4a8-11e4-866d-1e54a7bd3d10.png)

215 sANKyAyana -> sANKyAyana NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893184/4278932e-a4a8-11e4-917f-a324014a256c.png)

216 sAdyazkra -> sAdyazkra NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893189/7b9aeb7a-a4a8-11e4-8059-73b0b5bf9fb1.png)

217 sidDvA -> sidDvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893193/a3d365d6-a4a8-11e4-9c2d-2d7565df58a2.png)

218 sisaNgrAmayizu -> sisaNgrAmayizu NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893202/d78fdb3e-a4a8-11e4-9529-091d2a13763e.png)

219 suptvA ->  suptvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893208/01e3be64-a4a9-11e4-992e-b5c1baa17110.png)

220 sfptvA -> sfptvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893215/1a2d7b68-a4a9-11e4-87be-b1d0f815c9a3.png)

**Comment by funderburkjim** [comment]
221 stabDvA -> stabDvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893266/334755cc-a4ab-11e4-87f0-836f215513f3.png)

222 snigDvA -> snigDvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893269/4c61955e-a4ab-11e4-98f9-a466bcb9a7b0.png)

223 saMvastrya -> saMvastrya NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893272/6bd67b66-a4ab-11e4-9867-b595192ef095.png)

224 skanttvA -> skanttvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893275/925838d8-a4ab-11e4-94a5-52f0124e4444.png)

225 syanttvA ->  syanttvA NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893279/b3301274-a4ab-11e4-9941-ed2e67f41380.png)

226 cccU -> cuccU
![image](https://cloud.githubusercontent.com/assets/6393033/5893283/e3e6a2de-a4ab-11e4-81e5-f5e72c63e76f.png)

227 adw -> adw NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5893289/0ff53912-a4ac-11e4-8638-7929717d549b.png)

228 aryj -> aruj
229 aryj -> aruj (DUPLICATE)
![image](https://cloud.githubusercontent.com/assets/6393033/5893299/3576a4c8-a4ac-11e4-9ebe-e1b99f775ee8.png)

230 arrk -> ark
![image](https://cloud.githubusercontent.com/assets/6393033/5893307/82ddcdd6-a4ac-11e4-9d4e-32ab1a8a2afb.png)

**Comment by funderburkjim** [comment]
All of the cases for mw72 now addressed.

The majority (170) of the cases involved no change.  Here's the list of the NO CHANGE cases:
```
006 asifdDita 
007 upaF 
014 fDila 
016 yaTaFzi 
017 vahequka 
025 aBisantF 
027 ayugvARa 
029 araNGuza 
030 ANkfti 
032 upasaNkxp 
033 upasaNkxpta 
034 kENkarya 
036 tanlIka 
037 tfQvA 
038 dfzkARa 
040 nAruntuda 
042 nirgF 
043 nizpF 
044 parimfdnat 
045 parisaNGuz 
046 parisaNGuzwa 
047 pAnsin 
048 prASnat 
049 preryamARa 
050 prodgE 
051 marmfjenyu 
054 rUQvA 
055 lIQvA 
056 vivfRvAna 
057 vfRvAna 
058 vyApnuvAna 
060 Sulvika 
061 SraTnAna 
062 saMvfRvAna 
063 saNkF 
064 saNkxp 
065 saNkxpta 
066 saNkxpti 
067 saNgE 
068 saNGuz 
069 saNGuzita 
070 saNGfz 
071 saNGfzwa 
072 saNGfzyat 
076 saYCAdana 
077 saYCAdya 
078 saYCAdyamAna 
079 saYCid 
080 saYCidya 
081 saYCidyat 
082 saYCidyamAna 
084 saYjfmB 
085 sanDf 
086 sanDfta 
087 sanDfz 
088 samuccIya 
089 samuccIyamAna 
101 samprerya 
102 saraRyU 
103 sANkftya 
104 sizvidAna 
105 snIQvA 
108 anusaNgrah 
109 anusaYjvar 
112 apratisaNKya 
114 aBimUrcCita 
115 aBisaNkrudDa 
116 aBisaNkzip 
117 aBisaYjYA 
118 aBisaYjYita 
119 aBisaYjvar 
120 amvla 
122 asaYjYisattva 
124 upasaNkzepa 
125 upasaNgrah 
126 upasaNgrahaRa 
127 upasaNgrAhya 
129 kakkvalla 
130 kiNkzaRa 
131 tIkzRizWa 
132 dugDvA 
133 niHsaNKya 
134 niHsaYjYa 
135 nisaYjYa 
136 nEvasaYjYAsamADi 
137 parisaNkrIq 
138 parisaNkrIqat 
139 parisaNkzip 
141 pratisaNkrudDa 
142 pratisaNkruD 
143 pratisaNgrah 
144 pratisaYjYA 
146 badDvA 
147 budDvA 
148 BittvA 
149 mitAkzarAsidDAntasaNgraha 
150 rudDvA 
151 lubDvA 
152 vittvA 
153 visaYjYa 
154 vyUrRvat 
155 SaptvA 
156 SudDvA 
157 SfdDvA 
158 Sotsyat 
159 saNkrAmat 
160 saNkrAmita 
161 saNkrI 
162 saNkrIq 
163 saNkrIqana 
164 saNkrIqamAna 
165 saNkrIqita 
166 saNkruD 
167 saNkruS 
168 saNkroSamAna 
169 saNklid 
170 saNklinna 
171 saNkliS 
172 saNkliSya 
173 saNklizwa 
174 saNkleSa 
175 saNkzi 
176 saNkzip 
177 saNkzipat 
178 saNkzipya 
179 saNkzepaRIya 
180 saNkzoBita 
181 saNKyaka 
182 saNgraT 
183 saNgraTita 
184 saNgras 
185 saNgrah 
186 saNgrahaRIya 
187 saNgrahItf 
188 saNgrAhaka 
189 saNgrAhita 
190 saNgrAhya 
191 saNGrA 
192 saYcyu 
193 saYjYaka 
194 saYjYapat 
195 saYjYapita 
196 saYjYAta 
197 saYjYAna 
198 saYjYApita 
199 saYjYApya 
200 saYjYin 
201 saYjvar 
202 saYjval 
203 saYjvalat 
204 saYjvAlya 
206 santrE 
207 sandru 
208 sanDmA 
209 sanDyE 
210 sannyas 
213 samBriyamARa 
214 sasaYjYa 
215 sANKyAyana 
216 sAdyazkra 
217 sidDvA 
218 sisaNgrAmayizu 
219 suptvA 
220 sfptvA 
221 stabDvA 
222 snigDvA 
223 saMvastrya 
224 skanttvA 
225 syanttvA 
227 adw 
```

Many of these are cases where MW72 uses a homorganic nasal rather than an anusvARa.

Another large subcategory consists of verb forms (such as indeclineable past passive participles, and other participles) that do not have separate entries in other dictionaries.

**Comment by gasyoun** [comment]
Do you still believe it should have been done? For me it's still an open questin. 170 false alarms is not a big deal - but to make such amount of screenshots does takes time, at least for me. Will these 170 help in the future as they are added not to a NO CHANGE database? Is there an idea how to make comparisons and life with different standards of homorganic nasal not as harsh?

**Comment by funderburkjim** [comment]
Yes, I think it should have been done, since 60 cases were NOT false alarms.

I could have chosen to mark the homorganic nasal spellings as NO CHANGE, and not clipped the
scans - this would have been faster, as clipping scans does take some time.   If a similar situation arises in another dictionary, I may choose this faster method.

But, we need to get through the issues kicked up by faultfinder for headwords.  Currently it's our best way to identify problems, with alphabetical misorderings being (for most dictionaries) a close second best way.

I'm mentioning the NO CHANGES exactly for the reason you state: to have the data needed for a NO CHANGE database of cases that we've examined, so, in some future phase of checking for headword spellings, we won't need to reconsider the ones in the database.

**Comment by drdhaval2785** [comment]
```
149 mitAkzarAsidDAntasaNgraha -> mitAkzarAsidDAntasaNgraha NO CHANGE
[MW(99) digitization has mitAkzara-sidDAntasaMgraha - are both 'A' and 'a' correct?]
```
It seems that both are correct

**Comment by drdhaval2785** [comment]
```
164 saNkrIqamAna -> saNkrIqamAna NO CHANGE
[SHS, WIL, YAT have 'saNkrIqamARa'; however, they also have krIqamAna;
so saNkrIqamARa may be an error in SHS, WIL, YAT]
```
'na' is better than 'Ra'.

**Comment by drdhaval2785** [comment]
completed cross checking.
