### ISSUE TITLE
gst faultfinder corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#74]
There are only 12 headwords (a) identified by faultfinder as possible errors in comparison with MW,
and (b) appearing only in Goldstucker dictionary (gst).

This issue is devoted to checking these cases.

**Comment by funderburkjim** [comment]
1 abela -> abela  NO CHANGE
[Other dictionaries spell as avela, but, by alph. order, gst's 'abela' was intentional.]
![image](https://cloud.githubusercontent.com/assets/6393033/5927763/fac0159c-a642-11e4-8dd2-411b4d0165fe.png)

2 anekArTasaNgraha -> anekArTasaNgraha NO CHANGE
[use of homorganic nasal. Others spell as anekArTasaMgraha]
anekArTasaNgraha Tatpur. m. (-haH) The title of the second part 
of Hemachandra's vocabulary, containing words with their 
various meanings. E. anekArTa and saMgraha.

3 antaHsaYjYa -> antaHsaYjYa NO CHANGE
[homorganic nasal]
antaHsaYjYa Bahuvr. m. f. n. (-YjYaH-YjYA-YjYam) Sensitive 
(said of plants in general which, according to the native 
theory, from being affected by the quality of darkness or 
sinfulness — tamas — are merely capable of sensation or 
of agreeable and disagreeable feelings, but not of exterior 
manifestations), e. g. tamasA bahurUpeRa cezwitAH karmahetunA . 
antaHsaMjYA Bavantyete suKaduHKasamanvitAH; comp. antaScEtanya. 
E. antar and saMjYA.

4 anvarTasaYjYa -> anvarTasaYjYa NO CHANGE
[homorganic nasal]

5 apaSugGna -> apaSugGna NO CHANGE
[Others dictionaries have paSuGna.  Is there a grammar rule allowing optional 'gG' here?]
![image](https://cloud.githubusercontent.com/assets/6393033/5927900/0f4016f6-a644-11e4-9d43-5eba1f9ac57d.png)

6 apfTaggrahaRa -> apfTaggrahaRa NO CHANGE
[PW has pfTaggrahaRa]
apfTaggrahaRa Tatpur. n. (-Ram) Not taking or perceiving se- 
parately; e. g. in the Nyáya Sútra: tadASrayatvAdapfTaggrahaRam 
‘there is no perception separately (of a web from its 
threads)’, i. e. a web cannot be perceived separately from 
its threads, since it consists thereof. E. a neg. and pfTa- 
ggrahaRa.

7 apramUrcCita -> apramUrcCita NO CHANGE
[BHS has pramUrcCita]
apramUrcCita Tatpur. m. f. n. (-taH-tA-tam) The same as the 
preceding (of which it occurs as an explanation). E. a 
neg. and pramUrcCita.

8 abBratara -> abBratara NO CHANGE
![image](https://cloud.githubusercontent.com/assets/6393033/5928091/013ab60e-a646-11e4-81fe-0b72852450c5.png)

9 abBrita -> abBrita NO CHANGE
abBrita m. f. n. (-taH-tA-tam) See aBrita.

10 abBrIya -> abBrIya NO CHANGE
[Note: The dictionary ends abruptly, before aBrIya]
abBrIya m. f. n. (-yaH-yA-yam) See aBrIya.

11 aBisaNKyatva -> aBisaNKyatva NO CHANGE
[homorganic nasal]

12 abBrya -> abBrya NO CHANGE
abBrya m. f. n. (-bBryaH-bBryA-bBryam) See aBrya.

**Comment by funderburkjim** [comment]
That finishes the list. So all were NO CHANGEs.  Now we know.

**Comment by drdhaval2785** [comment]
```
5 apaSugGna -> apaSugGna NO CHANGE
[Others dictionaries have paSuGna. Is there a grammar rule allowing optional 'gG' here?]
```
अपशुघ्न (अनचि च) -> अपशुघ्घ्न (झलां जश्‌ झशि) -> अपशुग्घ्न.
So there is a rule which allows this.
NO change

**Comment by gasyoun** [comment]
So it must be the cleanest dictionary of them all.
