### ISSUE TITLE
bhs faultfinder corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#75]
There are only 203 headwords (a) identified by faultfinder as possible errors in comparison with MW,
and (b) appearing only in Buddhist Hybrid Sanskrit dictionary (bhs).

This issue is devoted to checking these cases.
.

**Comment by funderburkjim** [comment]
1 acintia -> acintia NO CHANGE
[Perhaps there will be many 'wrong' or 'non-standard' Sanskrit spellings in this dictionary, as here.]
acintia, see acintiya. 

2 gaganapradIpaaBirAmaSrI -> gaganapradIpaaBirAmaSrI NO CHANGE
[Here, the compound is not joined by sandhi]
Gaganapradīpa-abhirāmaś(i)rī (wrongly printed 
as two words), n. of a Buddha: Gv 285.7 (vs). 

3 jyotisUryaganDaoBAsaSrI -> jyotisUryaganDaoBAsaSrI NO CHANGE
(see next), n. of a 
Tathāgata: Thomas ap. Hoernle MR 101 (prob. error 
for next). 
4 jyotisomyaganDaoBAsaSrI -> jyotisomyaganDaoBAsaSrI NO CHANGE
[Note the 'Sanskritized' form given.  Clearly, there are words in this dictionary which
are not 'normal' Sanskrit.  In this search for errors, we should not attempt to change these
odd spellings, but just confirm that they conform to the scan. Early evidence says that the
digitization is conformant with the scan.]
Thomas ap. 
Hoernle MR 102 (twice; from Mahāsaṃnipāta Sūtra; cf. 
prec., which refers to the same); or (Sanskritized) Jyotis- 
saumya-gandhāvabhāsa-śrī, Mmk 7.9, n. of a Tathāgata. 

From here on, I'm not going to make an entry in this issue for cases where I've checked
with the scan and found the digitization to agree with the scan.  This is for efficiency in this
process.  I'll put the list of 'NO CHANGE' headwords for reference after all the 203 cases have
been checked.

055 aBinispIqayati -> aBinizpIqayati
[dot under 's' is faint, but clear in neighboring headwords aBinizpadyate, aBinizpezayati]
![image](https://cloud.githubusercontent.com/assets/6393033/5931043/de9a7600-a665-11e4-8d42-bbe7b5ef9bbd.png)

062 AryamahAsiMhOkkAsita -> AryamahAsiMhaukkAsita
[scan shows a hiatus separated by -:  a-u]
![image](https://cloud.githubusercontent.com/assets/6393033/5931105/d5be717a-a666-11e4-809a-a5c1146025ad.png)

074 upParitvA -> upParitvA  NO CHANGE ?
[scan unclear, could be tva or tvA. Probably NO CHANGE, since 2nd form is also tvA]

081 okramana -> okramaRa
[print here doesn't show dot under n, but does show okramaRa in referenced word avakramaRa]
![image](https://cloud.githubusercontent.com/assets/6393033/5931239/ea4c0fc4-a668-11e4-8d6a-ae77b468339c.png)

100 dfztaSakti -> dfzwaSakti
[print unclear, but among words starting with dfzwa]
![image](https://cloud.githubusercontent.com/assets/6393033/5931318/39e52f2e-a66a-11e4-9296-cfe60130a79e.png)

152 saMdfztika -> saMdfzwika
[print error t->w; confirmed via sAMdfzwika]
![image](https://cloud.githubusercontent.com/assets/6393033/5931693/fbfea55a-a66e-11e4-829e-533e939148e3.png)

187 DarmanayagamBIraSrIcaNdra -> DarmanayagamBIraSrIcandra
[caNdra occurs nowhere else in BHS headwords.  This must be a print smudge]
![image](https://cloud.githubusercontent.com/assets/6393033/5931863/9d3d07a2-a671-11e4-9bff-fb48ad18d329.png)

190 pfcCparipfcCikA -> pfcCaparipfcCikA
[Probably could also be long a: pfcCAparipfcCikA]
![image](https://cloud.githubusercontent.com/assets/6393033/5931898/1edb5ca0-a672-11e4-8a59-408b5433b9a2.png)

203 tayyaTApl -> tayyaTApi
[print smudge]
![image](https://cloud.githubusercontent.com/assets/6393033/5931976/484ff3a6-a673-11e4-9c1a-66ab3eef98db.png)

**Comment by gasyoun** [comment]
Right, "fixing" Buddhist Sanskrit will get us in trouble. So and as there are no BHS dudes around, 
we should trust the book. Only to make sure that the smudges are not counted as diacritics.

**Comment by funderburkjim** [comment]
Here is the NO CHANGE list:
```
001 acintia
002 gaganapradIpaaBirAmaSrI
003 jyotisUryaganDaoBAsaSrI
004 jyotisomyaganDaoBAsaSrI
005 suutTitA
006 ajAtaSatrukOkftyavinodana
007 aYAna
008 avustaM
009 fwiti
010 oDfta
011 osopati
012 osopana
013 kaRqUsika
014 kavaqaCedakam
015 kArzApaRaCedikam
016 gaRqUSika
017 gUToqigalla
018 cUqeSvara
019 trEvEdika
020 dUkUla
021 navutpattika
022 pattraCedaka
023 pariveWeti
024 piTAnita
025 puRyasumerUdgata
026 praCoqayati
027 prativeWApeti
028 pravuccati
029 BaktaCeda
030 BuQuka
031 merUdgataSrI
032 yadBUyEzIya
033 yenEva
034 lavuruka
035 lequ
036 vajraCedikA
037 vAkyaCeda
038 viCidra
039 viCindika
040 viTApita
041 vEBiqiNgI
042 SrURute
043 saMpravutta
044 suSOrya
045 soQOkikA
046 heWA
046 heWA
047 aYYAya
048 anujjuka
049 anuparIndAmi
050 anuprabaDnAti
051 anumajJima
052 apabBAra
053 aparejjukAto
054 appeti
056 avalokitamUrDitA
057 AdIptaSiraScElopama
058 AneYja
059 AbrIQa
060 AmuKIsTita
061 Arwavaka
063 AlikAvendA
064 ujju
065 ujjuka
066 ujJeBaka
067 utKurI
068 utPikA
069 utsoQi
070 udakaplotika
071 unnodana
072 upanibaDnAti
073 uppalaka
074 upParitvA
075 UjYA
076 UdData
077 fjju
078 ettAvat
079 ettiya
080 etto
082 oqqiyAna
083 oqqeti
084 kazmIlita
085 korpara
086 kzunto
087 KuwKuwA
088 grIzmika
089 cagGati
090 cUlla
091 cEloRqUka
092 Caqqeti
093 jfmBIkfta
094 jenta
094 jenta
095 jentI
096 qimPika
097 tattvArTEkadeSAnupraveSa
098 daDyika
099 digvErocanamakuwa
101 dekKiya
102 dOzWulya
103 Danuzketu
104 DuttUraka
105 DurDUraka
106 nErnitya
107 nErmitanErmARika
108 nEzkramyin
109 parikuqyeti
110 parizvedana
111 pariskAra
112 parIndAmi
113 paryavApnoti
114 puRyasumerUdgata
115 pubba
116 puvva
117 pEtfkya
118 pontI
119 pragGarati
120 praccopaka
121 pratijYottaraka
122 praDvopaka
123 pravezye
124 prollIQa
125 bahirzu
126 BUyosya
127 maDyima
128 marwita
129 mahAqimPika
130 mahAsamsfzwa
131 mahIsTAma
132 miRQa
133 miRQaka
134 merUdgataSrI
135 yAvadetto
136 laqqI
137 vaqqIBavati
138 viGuwWa
139 vijYin
140 viSalyIkfta
141 visnapayati
142 verawWiputra
143 vezweti
144 vEcCetuka
145 vERvAwata
146 vErAgyika
147 SeyyA
148 SruGnA
149 zawkikA
150 saMvimawWa
151 saMcagGati
153 samanubaDnAti
154 samantavIryolkAvaBAsameGa
155 samIkaronti
156 samvftaskanDa
157 sarvalokaDAtUdgatamakuwa
158 sAtpOruzya
159 sUtKalin
160 seyyA
161 sostika
162 sOrpArakIya
163 sruGnA
164 heWya
165 hezwe
166 hezwena
167 hezvi
168 hesti
169 aDOrDvadigjYAnAvaBAsa
170 arGyeya
171 ardravalika
172 aSrAdDya
173 AneYjya
174 irzyA
175 utplAva
176 utplAvaka
177 utplAvana
178 utplAvayati
179 utsKalati
180 utstIrya
181 kirttiya
182 kOtsya
183 cAturTya
184 dIrGya
185 dOzprajYa
186 dOzprajYiya
188 nAgnya
189 padmabimbyupaSoBita
191 pratibimbya
192 mUrDnawaka
193 mUrDni
194 varttAlI
195 varttIBavati
196 vartmIya
197 vArttIBavati
198 SlakzRita
199 samADihastyuttaraSrI
200 saMparitakzRoti
201 saMpratakzRoti
202 ssa
```

**Comment by funderburkjim** [comment]
The corrections have been made.
