### ISSUE TITLE
GRA corrections drawn from faultfinder suggestions

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#77]
After the corrections to GRA from alphabetical orderings (issue#76), there are only 40+ headwords unique to the GRA dictionary that are selected by faultfinder3a as having a spelling pattern that doesn't appear among the headwords of MW.  A few of these have already been examined and found to warrant NO CHANGE in issue#76.  36 cases remain, and these will be examined in this issue.

**Comment by funderburkjim** [comment]
001 anupUrvia -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=anupUrvia'>anupUrvia</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0060'>0060</a>
<hr/>

002 ahania -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=ahania'>ahania</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0163'>0163</a>
<hr/>

003 guhia -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=guhia'>guhia</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0404'>0404</a>
<hr/>

004 devadriac -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=devadriac'>devadriac</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0634'>0634</a>
<hr/>

005 dvizeRia -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=dvizeRia'>dvizeRia</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0653'>0653</a>

**Comment by funderburkjim** [comment]
006 pUrviastuti -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=pUrviastuti'>pUrviastuti</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0848'>0848</a>
<hr/>

007 rantia -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=rantia'>rantia</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1145'>1145</a>
<hr/>

008 vAjaganDia -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=vAjaganDia'>vAjaganDia</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1252'>1252</a>
<hr/>

009 vAtAarjanya -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=vAtAarjanya'>vAtAarjanya</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1258'>1258</a>
<hr/>

010 vArkAria -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=vArkAria'>vArkAria</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1261'>1261</a>

**Comment by funderburkjim** [comment]
011 Seyia -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=Seyia'>Seyia</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1412'>1412</a>
<hr/>

012 saMcareRia -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=saMcareRia'>saMcareRia</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1450'>1450</a>
<hr/>

013 hftsuas -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=hftsuas'>hftsuas</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1678'>1678</a>
<hr/>

014 aCokti -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=aCokti'>aCokti</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0018'>0018</a>
<hr/>

015 avaBfWa -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=avaBfWa'>avaBfWa</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0126'>0126</a>

**Comment by funderburkjim** [comment]
016 duCunA -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=duCunA'>duCunA</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0612'>0612</a>
<hr/>

017 duCunAy -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=duCunAy'>duCunAy</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0612'>0612</a>
<hr/>

018 dvesoyut -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=dvesoyut'>dvesoyut</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0653'>0653</a>
<hr/>

019 suCardis -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=suCardis'>suCardis</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1531'>1531</a>
<hr/>

020 aBijnu -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=aBijnu'>aBijnu</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0083'>0083</a>

**Comment by funderburkjim** [comment]
021 avapfgna -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=avapfgna'>avapfgna</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0126'>0126</a>
<hr/>

022 ApfCya -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=ApfCya'>ApfCya</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0180'>0180</a>
<hr/>

023 fRamcaya -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=fRamcaya'>fRamcaya</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0281'>0281</a>
<hr/>

024 kfCra -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=kfCra'>kfCra</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0345'>0345</a>
<hr/>

025 kfCreSrit -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=kfCreSrit'>kfCreSrit</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0346'>0346</a>

**Comment by funderburkjim** [comment]
026 tuCya -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=tuCya'>tuCya</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0538'>0538</a>
<hr/>

027 pozayItnu -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=pozayItnu'>pozayItnu</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0862'>0862</a>
<hr/>

028 BUriSfYga -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=BUriSfYga'>BUriSfYga</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0954'>0954</a>
<hr/>

029 yuDvin -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=yuDvin'>yuDvin</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1121'>1121</a>
<hr/>

030 vAcamIYKaya -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=vAcamIYKaya'>vAcamIYKaya</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1249'>1249</a>

**Comment by funderburkjim** [comment]
031 vftamcaya -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=vftamcaya'>vftamcaya</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1334'>1334</a>
<hr/>

032 SunaSSepa -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=SunaSSepa'>SunaSSepa</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1404'>1404</a>
<hr/>

033 sumadaYSu -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sumadaYSu'>sumadaYSu</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=1545'>1545</a>
<hr/>

034 pArzni -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=pArzni'>pArzni</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0808'>0808</a>
<hr/>

035 kraks -> 
headword <a target='_GRAword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=kraks'>kraks</a> ---  page <a target='_GRApage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/webtc/servepdf.php?page=0353'>0353</a>

**Comment by funderburkjim** [comment]
That finishes the identification of this batch.

Here are the 25 NO CHANGE cases:
```
anupUrvia, ahania, guhia, devadriac, dvizeRia, 
pUrviastuti, rantia, vAjaganDia, vArkAria, Seyia, 
saMcareRia, hftsuas, aCokti, avaBfWa, duCunA, 
duCunAy, suCardis, avapfgna, ApfCya, kfCra, 
kfCreSrit, tuCya, yuDvin, SunaSSepa, sumadaYSu 
```

**Comment by funderburkjim** [comment]
Corrections have been implemented. Closing issue.

**Comment by drdhaval2785** [comment]
```
001 anupUrvia -> NO CHANGE
```
It seems from the entries that GRA has a peculiar way of writing 'ia' instead of 'ya'.
Is it so @funderburkjim .
I have not examined normal entries in GRA

**Comment by funderburkjim** [comment]
Here's the list of 15 headwords (from grahw2.txt) that end in 'ia':
```
0060:anupUrvia:3551,3552
0144:aSvia:9074,9081
0163:ahania:10088,10093
0404:guhia:24285,24308
0462:Candia:27833,27836
0653:dvizeRia:40126,40127
0805:pAjasia:48527,48530
0848:pUrvia:51021,51028
1145:rantia:67799,67802
1252:vAjaganDia:74294,74297
1261:vArkAria:74850,74853
1329:vfjania:79052,79055
1355:veSia:80575,80581
1412:Seyia:84512,84513
1450:saMcareRia:86941,86942
```

**Comment by gasyoun** [comment]
What regex do you use to fetch them from `grahw2.txt`?

**Comment by funderburkjim** [comment]
regex  'ia:'

e.g.  using grep,  grep 'ia:' grahw2.txt > temp

**Comment by gasyoun** [comment]
@funderburkjim you use grep as a command line function?

**Comment by funderburkjim** [comment]
Yes.  grep is a unix search function. 
I have found that there is an excellent program available for Windows OS that provides a terminal which behaves like Unix terminal,  (cd, ls,pwd, grep, sed, ssh, cp, mv are some commands I've used).  This is 
part of a GIt application for Windows, called [GitBash](http://git-scm.com/downloads).
