### ISSUE TITLE
CCS corrections from faultfinder, part 6 (last part)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#89]
This is next batch of cases, 401-450, for CCS headword corrections.  This is the last batch.

**Comment by funderburkjim** [comment]
401 satyasamDa -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=satyasamDa'>satyasamDa</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=469'>469</a>
<hr/>

402 sadasyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sadasyf'>sadasyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=470'>470</a>
<hr/>

403 sadfztikzepam -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sadfztikzepam'>sadfztikzepam</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=470'>470</a>
<hr/>

404 sadnan -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sadnan'>sadnan</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=470'>470</a>
<hr/>

405 samDA -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=samDA'>samDA</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=472'>472</a>

**Comment by funderburkjim** [comment]
406 samniyantar -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=samniyantar'>samniyantar</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=473'>473</a>
<hr/>

407 samniveSa -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=samniveSa'>samniveSa</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=473'>473</a>
<hr/>

408 samnyAsin -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=samnyAsin'>samnyAsin</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=473'>473</a>
<hr/>

409 ssapatnakzayaRa -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=ssapatnakzayaRa'>ssapatnakzayaRa</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=473'>473</a>
<hr/>

410 sapadna -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sapadna'>sapadna</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=473'>473</a>

**Comment by funderburkjim** [comment]
411 saptaacakra -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=saptaacakra'>saptaacakra</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=474'>474</a>
<hr/>

412 samanyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=samanyf'>samanyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=476'>476</a>
<hr/>

413 samApyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=samApyf'>samApyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=477'>477</a>
<hr/>

414 samucCUsita -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=samucCUsita'>samucCUsita</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=479'>479</a>
<hr/>

415 ssamyagvijayin -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=ssamyagvijayin'>ssamyagvijayin</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=482'>482</a>

**Comment by funderburkjim** [comment]
416 sarasyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sarasyf'>sarasyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=483'>483</a>
<hr/>

417 sarpaazwa -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sarpaazwa'>sarpaazwa</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=484'>484</a>
<hr/>

418 saSlGam -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=saSlGam'>saSlGam</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=487'>487</a>
<hr/>

419 sahasyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sahasyf'>sahasyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=489'>489</a>
<hr/>

420 sAdanyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sAdanyf'>sAdanyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=491'>491</a>

**Comment by funderburkjim** [comment]
421 sAaDAna -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sAaDAna'>sAaDAna</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=495'>495</a>
<hr/>

422 sAvtra -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sAvtra'>sAvtra</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=495'>495</a>
<hr/>

423 sudevyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sudevyf'>sudevyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=501'>501</a>
<hr/>

424 suuzpa -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=suuzpa'>suuzpa</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=502'>502</a>
<hr/>

425 suptptTita -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=suptptTita'>suptptTita</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=502'>502</a>

**Comment by funderburkjim** [comment]
426 suBUsti -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=suBUsti'>suBUsti</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=503'>503</a>
<hr/>

427 surakArmfka -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=surakArmfka'>surakArmfka</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=503'>503</a>
<hr/>

428 suragakja -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=suragakja'>suragakja</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=503'>503</a>
<hr/>

429 suraBkandara -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=suraBkandara'>suraBkandara</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=503'>503</a>
<hr/>

430 surraBin -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=surraBin'>surraBin</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=504'>504</a>

**Comment by funderburkjim** [comment]
431 suraa -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=suraa'>suraa</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=504'>504</a>
<hr/>

432 surKa -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=surKa'>surKa</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=504'>504</a>
<hr/>

433 sUnUmant -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=sUnUmant'>sUnUmant</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=507'>507</a>
<hr/>

434 surkzya -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=surkzya'>surkzya</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=507'>507</a>
<hr/>

435 surmyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=surmyf'>surmyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=507'>507</a>

**Comment by funderburkjim** [comment]
436 surypraBa -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=surypraBa'>surypraBa</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=508'>508</a>
<hr/>

437 srotasyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=srotasyf'>srotasyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=520'>520</a>
<hr/>

438 svapnnta -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=svapnnta'>svapnnta</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=522'>522</a>
<hr/>

439 svfraMkfta -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=svfraMkfta'>svfraMkfta</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=522'>522</a>
<hr/>

440 hatnf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=hatnf'>hatnf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=526'>526</a>

**Comment by funderburkjim** [comment]
441 havizyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=havizyf'>havizyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=530'>530</a>
<hr/>

442 hArvf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=hArvf'>hArvf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=531'>531</a>
<hr/>

443 himsA -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=himsA'>himsA</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=532'>532</a>
<hr/>

444 himsaka -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=himsaka'>himsaka</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=532'>532</a>
<hr/>

445 himsra -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=himsra'>himsra</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=532'>532</a>

**Comment by funderburkjim** [comment]
446 hfdayyf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=hfdayyf'>hfdayyf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=535'>535</a>
<hr/>

447 AcAryf -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=AcAryf'>AcAryf</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=538'>538</a>
<hr/>

448 takzans -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=takzans'>takzans</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=540'>540</a>
<hr/>

449 brahmadaRda -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=brahmadaRda'>brahmadaRda</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=541'>541</a>
<hr/>

450 yatsamKyAka -> 
headword <a target='_CCSword' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=yatsamKyAka'>yatsamKyAka</a> ---  page <a target='_CCSpage' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/CCSScan/2014/web/webtc/servepdf.php?page=541'>541</a>

**Comment by sanskritisampada** [comment]
Solved # 401 - # 450.

**Comment by funderburkjim** [comment]
Corrections applied.

This phase of CCS corrections done.

**Comment by gasyoun** [comment]
Hurray!
