### ISSUE TITLE
Missing data in PW - one case open

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#91]
The 39 cases of 'missing data' cases for PW(K) was handled by Sampada in February, 2015.  There is
one 'open' case.  

The 'working paper' for this list is a file in this corrections repository, located 
[here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/PW/missing_0001-0099.txt).
The unresolved case is case 0007, which is shown as:
```
----------------------------------------------------------------------
case 0007: headword=UrDvanayana, page=1257-3 (42931)


(1257-3,42931,UrDvanayana): <orig> : <H1>100{UrDvanayana}1{*UrDvanayana}¦ •m. {%das fabelhafte Thier †C2arabha%} ¯GAT. |<?> PW21118
(1257-3,42931,UrDvanayana): <>     : <H1>100{UrDvanayana}1{*UrDvanayana}¦ •m. {%das fabelhafte Thier †C2arabha%} ¯GAT. |<?> PW21118

ejf: Here the scan is unclear. It may be 'GAL' rather than 'GAT'. Since this
is unclear, I've left it unchanged

(1257-3,42932,UrDvanayana): <>     : 
```
@gasyoun   Maybe you can discover what that last letter of 'GA**T**' really is.

By the way, there appears to be just one case of Russian text in PW in this record from pw.xml:
```
<H1><h><key1>bAhAdura</key1><key2>bAhAdura</key2></h><body><gram n="m">m.</gram> 
<noti>als Beiw. von neuerer Zeit so v.a.</noti> <i>Held</i> |<A></A> |<RUSSISCH></RUSSISCH>). 
PW76882</body><tail><L>76880</L><pc>4223-2</pc></tail></H1>
```
Maybe you can supply the Russian?

Is it likely that there is really no other Russian text in PW(K)?

**Comment by gasyoun** [comment]
`GAL.` not `GAT` stands for an abbreviation.

Single text in PWK seems strange compared to PWG with 50+ cases. But I guess we should not hunt for them, they'll come. It's a matter of time.
```
Russian: <RUSSISCH>богатырь</RUSSISCH>.
```

**Comment by gasyoun** [comment]
@funderburkjim it's closed, I guess. Do it :u6307:

**Comment by drdhaval2785** [comment]
@funderburkjim 
Install what @gasyoun says and close it. We already have 32 cases open. Enough to strain our brains

**Comment by funderburkjim** [comment]
Russian correction installed.

**Comment by funderburkjim** [comment]
Correction to GAL. (missing data case) made.
