### ISSUE TITLE
Missing data in INM

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#92]
There are 89 cases of missing data in the digitization of INM (Index to Names in the Mahabharata, by S. Sorensen).   These are detailed [here](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/INM/missing_0001-0099.txt)

If anyone wants to tackle these, I can supply the fairly simple instructions.  Basically, you have to look at
each case, and, by some means (such as examination of scan or the print version of text), determine what
the missing text should be, and input that and your initials in the line **below** the <b>&lt;orig&gt;</b> line in the file above.  When all the corrections are accounted for, I have a program to process the adjusted file and install the corrections.

A first glance at a couple of examples suggests that this might be hard from our scans alone; so probably reference to a better-printed paper version will be needed -- but this is just a guess.

**Comment by gasyoun** [comment]
I hardly believe that other, printed copies will help. I have none, but still in some cases I understand that what we need to do is decipherment, using some kind of prior knowledge or logic. Slowly I can look at them, to see if I can help at all. Not all cases are hopeless. As you will see in case of `agastya` - it's just some guesswork, but the result is 100% correct. What about the scholar with knowledge of Greek - I see a lot of Greek text. Can we approach him, can we ask for help?

aSlezA
![004](https://cloud.githubusercontent.com/assets/80761/6764010/02100b1e-cfaa-11e4-9ef5-6ebad58a2b83.PNG)

aSvatTAman
![10](https://cloud.githubusercontent.com/assets/80761/6764015/edef86ae-cfaa-11e4-9b86-83f0737529ae.PNG)

agastya
![016](https://cloud.githubusercontent.com/assets/80761/6764035/01cdf916-cfac-11e4-8041-c91fad86e148.PNG)

 [Footnote: *1) Natus erat cum fratre Vasishtho semine Mitri et Varuni, q{??} 
Urvaçīm vidissent, amore incensorum in urceum profluente (Bṛ{??} 
5. 30 ff., see BR.).] 

 [Footnote: *1) Natus erat cum fratre Vasishtho semine Mitri et Varuni, quum nympham
Urvaçīm vidissent, amore incensorum in urceum profluente (Bṛhaddevatā,
5. 30 ff., see BR.).] 

`(Bṛhad-devatā literally means 'a big work dealing with the Vedic deities'.)`

**Comment by funderburkjim** [comment]
@gasyoun   Agree with your solution for Bṛhaddevatā.   What do you need from me to do the rest?

**Comment by gasyoun** [comment]
@funderburkjim we have enough data from you. Nothing more is needed. But as it's "inside" the dictionary and not headword related, let it be there and I'll find a way to get back to it in 2016. Headwords first.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Here is the filled data for the 89 cases listed.
[INM Corrections for unreadable data.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/files/7084254/INM.Corrections.for.unreadable.data.txt)

- Added 4 comment lines (starting with %%).
- Noticed under the HW karRaparvan (case 0053), the small cap. text being typed in all cap.s; is it the same style throughout the work? in PWG the small cap.s were typed with a different marking -- then why was it discontinued? 
- Also noticed several errors in other lines not under the de-marked {??} lines, though did not correct them.

The first and foremost work "to do" for these type of projects is to have/collect good working prints/scans!!
[It's the strategy that we religiously follow for our AB works.]

And finally, if any other CDSL texts are pending for such fillings, I can **sure be of help**.

**Comment by Andhrabharati** [comment]
@drdhaval2785 

As I got all the works from you, handling this piece of work now.

And guess you should be able to put them in resp. works once I give my corrections file.

Found a total of 429 ?? cases in all the works.
![image](https://user-images.githubusercontent.com/75209130/132092686-d1aa44e6-87ad-41fb-8cf4-49498cc1cccf.png)

**Comment by Andhrabharati** [comment]
As a sample, giving the GRA correction here-

![image](https://user-images.githubusercontent.com/75209130/132092862-6f8dba03-a36a-48ea-903e-a7a909466dea.png)

[This would speak about how I work, when I work.]

**Comment by drdhaval2785** [comment]
I shall be able to use your work and get them integrated to Cologne data, provided you don't change markups or line breaks. Otherwise it would entail manual work from my side again.

**Comment by Andhrabharati** [comment]
I do know this!

This is how I am doing-

ae.txt	Line 14:	{%Composition”%} {??}{%c.%} {??}{%c.,%}
		{%Composition”%} {%&c.%} {%&c.,%}	
	Line 39391:	<div n="lb"/>{#????#}
		%%This line is extraneous; to be removed altogether.
	Line 89525:	Purvapithi{??}a,
		Purvapithika, [properly, Pūrvapīṭhikā]
	Line 89572:	-ber of the {??}antra
		ber of the Tantra
	
ap90.txt	Line 86652:	<><ab n="??">S. M.</ab> country. {4} a kind of tree. ({#--रा#})
		<><ab n="South(ern) Marāṭhā (Mahārāshṭra)">S. M.</ab> country. {4} a kind of tree. ({#--रा#})

ben.txt	Line 103:	<div n="lb">Spr{??}ce (Indian Sentences).
		<div n="lb">Sprüce (Indian Sentences).
	Line 150954:	<HI>709, B, 18 ({%mukula%}), Cf. {%hāsta,%} p. 11{??}
		<HI>709, B, 18 ({%mukula%}), Cf. {%hāsta,%} p. 1113.

**Comment by Andhrabharati** [comment]
you may note that my comment lines are starting with %%.

**Comment by drdhaval2785** [comment]
Ok

**Comment by funderburkjim** [comment]
@drdhaval2785   Are you handling the revisions to csl-orig  ?

**Comment by drdhaval2785** [comment]
I do and will handle revisions to csl-orig. Will put a note whenever I handle one, so that we do not step on each other's feet.

**Comment by funderburkjim** [comment]
Sounds good.

I've gotten in the habit of doing a 'git pull' on csl-orig before any 'git add/commit/push', since you've begun doing corrections.  So far, that new habit has avoided problems.  

Also, fyi, when the git pull indicates that
you have changed some dictionary,  then I'm rerunning csl-pywork/v02  redo script both locally and at Cologne site.

**Comment by gasyoun** [comment]
> noticed several errors in other lines not under the de-marked {??} lines, though did not correct them.

Like?

> good working prints

One can't argue with that. But in most cases I have not even seen the original printed book. And the prints them-self are rather low quality with lot of typographical dirt, like the Shabdakalpadruma, for example.

> new habit has avoided problems.

Sounds like we now know how to work together. @Andhrabharati is the gem of 2021. He has done a ton of work in just a few months. I'm afraid we'll be out of work in 10 years from now, if he continues in the same manner.

**Comment by Andhrabharati** [comment]
>  if he continues in the same manner.

it all depends on the other's "proper" understanding and (timely) reactions!

**Comment by Andhrabharati** [comment]
> I'm afraid we'll be out of work in 10 years from now

10 years is too big a time for these things, iff I am allowed to freely work the way I intend to.

**Comment by Andhrabharati** [comment]
Finished this part of work (as informed) from my side.
[Filling the missed places.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/files/7111884/Filling.the.missed.places.txt)

Pl. go through my comment lines which are mostly informative, but a few are for further action ahead.
Esp. look at those at BOR, GRA and KRM.

@drdhaval2785 
after you update the devanagari repo with corrected files, I will initiate another task on them.

**Comment by Andhrabharati** [comment]
> And the prints them-self are rather low quality with lot of typographical dirt, like the Shabdakalpadruma, for example.

@gasyoun, 
have a look at my corrections in SKD, which clearly indicates that there are "better" resources at my disposal!!

**Comment by gasyoun** [comment]
> "better" resources at my disposal

Time to share, so we can upload them to the Cologne site?

**Comment by drdhaval2785** [comment]
@Andhrabharati Your work at https://github.com/sanskrit-lexicon/CORRECTIONS/issues/92#issuecomment-913174476 has been merged into Cologne data via commit https://github.com/sanskrit-lexicon/csl-orig/commit/17ad89c17712e07561f2e037255b09cb05a69776 .

Now only changes in pwg.txt remain to be integrated.

**Comment by drdhaval2785** [comment]
pwg.txt data is also merged in csl-orig repository.

Every other issue which deserved further attention has been put in a separate issue.

Now nothing further remains to be done in this thread.

@Andhrabharati may like to close it once he finds the integration fine.

**Comment by Andhrabharati** [comment]
Probably I should trust you and move ahead; we need to spend time in correcting the points at one effort only, without a scope for checking and rechecking the same point.

As I had mentioned at the beginning days of my teaming here, the policy should be to "do it right, FIRST time, ON time and EVERY time".

**Comment by drdhaval2785** [comment]
I have cursorily checked the diff files visually to ensure that there is no gross error while carrying your changes to csl-orig. Found all OK. You may trust me. 

At the same time, now I now have also developed scripts to 1. Transmit the changes you suggest from your format to csl-devanagari and 2. Transmit changes from csl-devanagari to csl-orig. 

So you may give correction files in the format of https://github.com/sanskrit-lexicon/CORRECTIONS/files/7111884/Filling.the.missed.places.txt and I should be able to integrate it to Cologne data.

**Comment by gasyoun** [comment]
> 1. Transmit the changes you suggest from your format to csl-devanagari and 2. Transmit changes from csl-devanagari to csl-orig.

Where are they?

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-devanagari/blob/main/scripts/carry_changes_to_cslorig.sh

**Comment by Andhrabharati** [comment]
now the ball is in @funderburkjim's court!

one do not know when (and if) he would react on approving them, to go to public from Github to Cologne.

**Comment by drdhaval2785** [comment]
This is a temporary pain. It will go away.
Once @funderburkjim completes the small steps shown at https://github.com/sanskrit-lexicon/COLOGNE/issues/357#issuecomment-906934672, the github and Cologne data would remain in sync for eternity.
Cologne would not remain at max a day behind github, if the cronjob is run daily.

**Comment by Andhrabharati** [comment]
Happy to say that I've seen these corrections duly done at the web display today.
