### ISSUE TITLE
Missing data in VEI (Vedic Index of Names and Subjects)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#93]
Sampada solved the missing data cases for VEI; there are 145 cases.
The working papers are [here](https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/dictionaries/VEI/missing).

One case remains unsolved:
```
case 0003: headword=apacit, page=1-024+ 48 (1182)
(1-024+ 48,1179,apacit): <>     : <F>2) St. Petersburg Dictionary, {%s.v.%}</F> Zimmer,
(1-024+ 48,1180,apacit): <>     : <F>3) {%Altindisches Leben,%} 97. So also
(1-024+ 48,1181,apacit): <>     : <>Ludwig, Translation of the Rigveda,

(1-024+ 48,1182,apacit): <orig> : <>{??} 342, 500.</F> and others to denote an insect
(1-024+ 48,1182,apacit): <ss?>     : <>{??} 342, 500.</F> and others to denote an insect

(1-024+ 48,1183,apacit): <>     : <>whose sting produced swellings, etc. ({%glau%}). But Bloomfield
(1-024+ 48,1184,apacit): <>     : <F>4) {%American Journal of Philology,%} 11,
(1-024+ 48,1185,apacit): <>     : <>320 {%et seq.; Hymns of the Atharvaveda,%}
```
The scans from archive.org are clearer than those at Cologne, and resolved all but that one case -
 it is possible there is nothing missing in that case.

Here are typical links to the scans at archive.orig for VEI:
```
For  page 19 in volume 1:
 https://archive.org/stream/vedicindexofname01macduoft#page/19/mode/1up
For page 7 in volume 2:
 https://archive.org/stream/vedicindexofname02macduoft#page/7/mode/1up
```

**Comment by gasyoun** [comment]
Both scans are good enough. If there was a number, it's an invisible 1 digit.
https://archive.org/stream/vedicindexofname01macduoft#page/24/mode/1up
http://www.sanskrit-lexicon.uni-koeln.de/scans/VEIScan/2014/web/webtc/servepdf.php?page=1-024

**Comment by funderburkjim** [comment]
@gasyoun   Is there sufficient evidence to add the '1' ?

**Comment by gasyoun** [comment]
Sorry, I meant not 1, but any one-digit, there is place only for one. But it was never printed, but still could fit.

**Comment by funderburkjim** [comment]
Sounds like its best to leave out that digit for now.
Let's consider this issue closed.
