### ISSUE TITLE
Missing Data for MWE, includes todo 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/CORRECTIONS#94]
Back in October 2014, Sampada resolved most of the missing data cases for MWE (Monier-Williams English-Sanskrit dictionary).

The working papers have been put [here](https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/dictionaries/MWE/missing) in this repository.

There were 17 cases unresolved. The [missing_todo]() file shows these cases.  Maybe someone else should
take a look, especially if there is available a print edition better than the scans at Cologne.

**Comment by drdhaval2785** [comment]
Missing data is somewhat difficult to read I guess.
If the data can be given in somewhat more readable manner - it would be easier to understand and participate.

**Comment by gasyoun** [comment]
@funderburkjim http://www.sanskrit-lexicon.uni-koeln.de/scans/MWEScan/2013/web/webtc/servepdf.php?page=010 will not help much. http://books.google.ru/books?id=KqD9XJygz4AC&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false seems to be much better. @Shalu411 needed only 2 min to uttaropA{??} -> uttaropāyaḥ. So it will be done in a week.

**Comment by Shalu411** [comment]
Namaste
Happy to be back- 
Here is the next one-
headword=annuity 
 {#vartta{??} >> varttanaṃ

**Comment by Shalu411** [comment]
This part in the code is repeated.. Please delete.
(189,19699,discover): <>     : detect) {#ni{??}#} (c. 10. {#-rUpayati -yituM#}), {#jYA#} (c. 9. {#jAnAti -nIte, jYAtuM#}),

**Comment by Shalu411** [comment]
headword=discover
{#ni{??}#} >> nirūp
![mwdisc](https://cloud.githubusercontent.com/assets/6392207/7137480/97ee7450-e2d7-11e4-9606-37b176f5ac96.JPG)

**Comment by gasyoun** [comment]
@Shalu411 is a bid afraid of SLP1, so I'll do the cleanup after for her. I'll use http://sanskritlibrary.org/transcodeText.html to get SLP1 from her IAST.
I'm not sure in what format Jim needs it, but let the first line be the input, second the output. Let Jim approve.

```
(189,19699,discover): <orig> : detect) {#ni{??}#} (c. 10. {#-rUpayati -yituM#}), {#jYA#} (c. 9. {#jAnAti -nIte, jYAtuM#}),
(189,19699,discover): <>     : detect) {#nirUp#} (c. 10. {#-rUpayati -yituM#}), {#jYA#} (c. 9. {#jAnAti -nIte, jYAtuM#}),
```

**Comment by Shalu411** [comment]
headword=multiplicand,
(520,53500,multiplicand): <orig> : paraRAyA{??}H,#} [Page520-b+ 51]
(520,53500,multiplicand): <>     : pUraRIyANkaH,#} [Page520-b+ 51]

(pūraṇīyāṅkaḥ)

**Comment by Shalu411** [comment]
page=153 (16125)


headword=dad
(153,16125,dad): <orig> : <HI>DAD, DADDY, {%s.%} {#bAlakaBAzAyAM pitfsamAnArTaH SabdaH, mAyA{??}, tAtaH#}.
(153,16125,dad): <>     : <HI>DAD, DADDY, {%s.%} {#bAlakaBAzAyAM pitfsamAnArTaH SabdaH, bAbA, tAtaH#}.

बाबा
It looks so in all three scans I checked, but all unclear. It seems not to be a संस्कृत word.. but taken from Hindi. Cannot exactly say- So its just a guess.

**Comment by Shalu411** [comment]
headword=persuasive
(587,60371,persuasive): <orig> : {#pra{??}yakArI#} &c., {#saMSayaCedakaH#} &c., {#sandehaCedakaH#} &c.
(587,60371,persuasive): <>     : {#pratyayakArI#} &c., {#saMSayaCedakaH#} &c., {#sandehaCedakaH#} &c.

![mwpers](https://cloud.githubusercontent.com/assets/6392207/7139800/d13e8552-e2e5-11e4-96b3-053d3d426bbb.JPG)

**Comment by Shalu411** [comment]
headword=repeat
(677,69560,repeat): <orig> : (c. 10. {#A{??}yati -yituM#}), {#gF#} (c. 9. {#gfRAti, garituM -rItuM#}), {#paWanaM kf#}.-- [Page678-a+ 51]
(677,69560,repeat): <>     : (c. 10. {#zrAvayati -yituM#}), {#gF#} (c. 9. {#gfRAti, garituM -rItuM#}), {#paWanaM kf#}.-- [Page678-a+ 51]

श्रावयति
![mwrep](https://cloud.githubusercontent.com/assets/6392207/7140095/4ceeac62-e2e7-11e4-92e0-9f58eadee2e7.JPG)

**Comment by Shalu411** [comment]
page=707 (72547)
headword=salubrity
(707,72547,salubrity): <orig> : <HI>SALUBRITY, {%s.%} {#ArogyatvaM, ArogyajanakatA, pa{??}yatA, kzemyatA, hitatA#}.
(707,72547,salubrity): <>     : <HI>SALUBRITY, {%s.%} {#ArogyatvaM, ArogyajanakatA, paTyatA, kzemyatA,

पथ्यता
![mwsal](https://cloud.githubusercontent.com/assets/6392207/7140240/dc562146-e2e7-11e4-95cd-9293f6924389.JPG)

**Comment by Shalu411** [comment]
headword=sami
(707,72617,sami): <orig> : <HI>SAMI4, {%s.%} (A thorny tree with a hard wood) {#SaBI, sanI, kA{??}-
(707,72617,sami): <>     : <HI>SAMI4, {%s.%} (A thorny tree with a hard wood) {#SaBI, sanI, kA{??}-

In this article- even this is typo- 
{#SaBI, sanI, >> {#SamI, samI, 
![mwsami](https://cloud.githubusercontent.com/assets/6392207/7140446/de868c8e-e2e8-11e4-8d20-1c891310a9e7.JPG)

**Comment by Shalu411** [comment]
headword=sent
```
(727,74654,sent): <orig> : -tA -taM;#} ‘having sent for,’ {#AnA{??}#}.
(727,74654,sent): <>     : -tA -taM;#} ‘having sent for,’ {#AnAyya}#}.
```
![mwsent](https://cloud.githubusercontent.com/assets/6392207/7140562/96a53a2c-e2e9-11e4-9ccf-11d3983b49d1.JPG)

**Comment by gasyoun** [comment]
Please number the cases if possible. Like `1, 2, 3, 4`. Thanks a lot, Jim will wake up with joy!

**Comment by Shalu411** [comment]
headword=spire
```
(765,78470,spire): <orig> : <HI>SPIRE, {%s.%} (Winding line) {#alakarUpA vyA{??}ttakareKA, AvarttaH#}.--(Steeple,
(765,78470,spire): <>     : <HI>SPIRE, {%s.%} (Winding line) {#alakarUpA vyAvarttakareKA, AvarttaH#}
```

**Comment by Shalu411** [comment]
headword=stained
```
(770,78956,stained): <orig> : <HI>STAINED, {%p. p.%} {#kalaNkitaH -tA -taM, malinitaH#} &c., {#kaluzitaH#} &c., {#{??}laptaH
(770,78956,stained): <>     : <HI>STAINED, {%p. p.%} {#kalaNkitaH -tA -taM, malinitaH#} &c., {#kaluzitaH#} &c., {#liptaH
```
![mwsta](https://cloud.githubusercontent.com/assets/6392207/7141441/3c933e48-e2ef-11e4-91ef-bee7110bed06.JPG)



(770,78957,stained):

**Comment by Shalu411** [comment]
headword=stupid
(781,80105,stupid): <orig> : -DAH -DaH ({??}), matihInaH -nA -naM, budDihInaH#} &c., {#avuDaH -DA -DaM, avu-
(781,80105,stupid): <>     : -DAH -DaH ({s}), matihInaH -nA -naM, budDihInaH#} &c., {#avuDaH -DA -DaM, avu-
![mwstu](https://cloud.githubusercontent.com/assets/6392207/7141598/57839d78-e2f0-11e4-9a80-e6ea8d647513.JPG)

**Comment by Shalu411** [comment]
headword=take
```
(794,81468,take): <orig> : {??}m#} or {#vihf#}.--(Take breath), {%see To%} PAUSE, REST.--(Take
(794,81468,take): <>     : {kram#} or {#vihf#}.--(Take breath), {%see To%} PAUSE, REST.--(Take
```
![mwtake](https://cloud.githubusercontent.com/assets/6392207/7142046/1a66c93a-e2f3-11e4-93d6-b4aee241a8a5.JPG)

**Comment by Shalu411** [comment]
headword=willingly
```
(841,86284,willingly): <orig> : <HI>WILLINGLY, {%adv.%} {#kAmaM, prakAmaM, kAmatas, icCAtas, yaTepsitaM, {??}#} [Page842-a+ 51]
(841,86284,willingly): <>     : <HI>WILLINGLY, {%adv.%} {#kAmaM, prakAmaM, kAmatas, icCAtas, yaTepsitaM, {taTeti}#} [Page842-a+ 51]
```
तथेति

**Comment by Shalu411** [comment]
headword=zealot
```
(849,87050,zealot): <orig> : <HI>ZEALOT, {%s.%} {#atyanuraktaH, ativyagraH, atyAsaktaH, atitIkzRaH#}. {??} [Page849-b+ 51]
(849,87050,zealot): <>     : <HI>ZEALOT, {%s.%} {#atyanuraktaH, ativyagraH, atyAsaktaH, atitIkzRaH#}. {??} [Page849-b+ 51]
```
Nothing is missing here. 
![mwzea](https://cloud.githubusercontent.com/assets/6392207/7142614/8107fc82-e2f7-11e4-92f3-3876456c51dc.JPG)

**Comment by Shalu411** [comment]
Thanks for SLP converter. Its great.

**Comment by gasyoun** [comment]
@Shalu411 all cases covered?
@funderburkjim together we are strong.

**Comment by Shalu411** [comment]
Yes. All cases covered. My side, all done.

**Comment by drdhaval2785** [comment]
@funderburkjim install and close

**Comment by funderburkjim** [comment]
@Shalu411   There's one more to go:

headword = repair
```
case 0007: headword=repair, page=677 (69509)


(677,69509,repair): <orig> : <HI>{%To%} REPAIR, {%v. n.%} (Have recourse, go to) {#A{??}#} (c. 1. {#-ayati -yituM#}), [Page677-b+ 51]
(677,69509,repair): <>     : <HI>{%To%} REPAIR, {%v. n.%} (Have recourse, go to) {#A{??}#} (c. 1. {#-ayati -yituM#}), [Page677-b+ 51]


(677,69510,repair): <>     : {#Sri, ASrayaRaM kf, SaraRArTaM gam#} (c. 1. {#gacCati, gantuM#}) or {#Agam#} or
(677,69511,repair): <>     : {#upagam#} or {#aBigam#} or {#pratigam#} or {#yA#} (c. 2. {#yAti -tuM#}) or {#aBiyA#}
(677,69512,repair): <>     : or {#pratyAyA#} or {#i#} (c. 2. {#eti -tuM#}), {#aByupe#}.

```

**Comment by funderburkjim** [comment]
@Shalu411  A nice surprise  to have all these done!  Will install once 'repair' finished.

@gasyoun Do you know of any small unfinished business that Shalu might tackle now?

**Comment by Shalu411** [comment]
Thank you- Here is the final one. 
One question- Do the cases resolved need numbering? Or will the headword name suffice?
-----------------
headword = repair
```
case 0007: headword=repair, page=677 (69509)

(677,69509,repair): <orig> : <HI>{%To%} REPAIR, {%v. n.%} (Have recourse, go to) {#A{??}#} (c. 1. {#-ayati -yituM#}), [Page677-b+ 51]
(677,69509,repair): <>     : <HI>{%To%} REPAIR, {%v. n.%} (Have recourse, go to) {#Azri#} (c. 1. {#-ayati -yituM#}), [Page677-b+ 51]
```
आश्रि

**Comment by funderburkjim** [comment]
@Shalu411  headword name suffices.   

re Azri v. ASri.   In the Github email notification that was generated when you first provided the answer, there was Azri.  I guess you must have corrected to ASri.   While you were less active, we agreed to have the
Devanagari coded uniformly in SLP1 in the dictionaries.  I realize Marcis and you have discussed this,  and appreciate that you
are willing to learn SLP1, when you are more comfortable with HK.  That 'z(HK)=S(SLP1)' difference is one that I also often trip over.

All these cases now installed, so the issue may be closed.

**Comment by gasyoun** [comment]
Let Jim do the needed.

**Comment by funderburkjim** [comment]
All done.
